(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (>= M A))
   (exec-mem 9920 0 6 6 113 64 0)
   (image-file "B:¥GPC¥DB003.GPC")
   (image-mem 1 3)
   (image-file "B:¥GPC¥DB004.GPC")
   (image-mem 1 3)
   (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
   (exec-mem 912 "C 0 40 0 40 400 1 40 0")
   (exec-mem 912 "A 1")
   (image-file "A:¥GPC¥DB_FRM2.GPC")
   (image-mem 1 0)
   (image-file "B:¥GPC¥DB005C.GPC")
   (image-mem 1 3)
   (exec-mem 912 "GET 0 54 38 23 134")
   (exec-mem 912 "A 0")
   (exec-mem 912 "GET 1 54 38 23 134")
   (exec-mem 912 "A 0,S 0")
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (load-mem "A:¥CLM¥DB004.CLM" 32768)
   (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
   (exec-mem 3744 1 1 80 0 0 0)
   (exec-mem 3744 1 2 80 0 0 0)
   (exec-mem 3744 1 5 15 5 24 13)
   (exec-mem 3744 1 6 27 5 36 13)
   (exec-mem 3744 1 7 23 2 40 3)
   (exec-mem 3744 1 8 3 8 7 12)
   (exec-mem 3744 1 9 37 7 47 14)
   (exec-mem 3744 1 10 52 12 56 15)
   (sound '|| 0)
   (if (</>
        (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
        (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
   (sound '|| 1)
   (text-frame 15 298 74 356)
   (if (</>
        (//
         (? (= 119 #f))
         (text "［コール］悪いな、後片付けなんかさせちゃって・・・。")
         (wait)
         (text-reset 1)
         (text "［シーラ］いいのよ、それより少し疲れたんじゃない？")
         (wait)
         (text-reset 1)
         (text "［コール］俺は大丈夫だが、あの二人も明日仕事があるっていうの　　　　　に元気だよな。")
         (wait)
         (text-reset 1)
         (text "［シーラ］コールも、かなり飲まされてたわね。")
         (wait)
         (text-reset 1)
         (text "［コール］ああ、お陰で今日はぐっすり眠れるよ。")
         (set-reg 119 #t))
        (//
         (text "［シーラ］コール、眠そうね。")
         (wait)
         (text-reset 1)
         (text "［コール］テリーとリンから、あんなに飲まされるとは思わなかっ　　　　　たよ。")
         (wait)
         (text-reset 1)
         (text "［シーラ］あの二人も無茶するからね。"))))
   (wait)
   (text-reset 1)
   (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 105 #t) (= 107 #t) (= 111 #t) (= 112 #t) (= 118 #f))
   (text "［シーラ］コール、旅行の準備はできてるの？")
   (wait)
   (text-reset 1)
   (text "［コール］ああ、バッチリさ。ちゃんとバッグに入ってるよ。パス　　　　　ポートに着替えにカメラに・・・ウノ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］ウノ？")
   (wait)
   (text-reset 1)
   (text "［コール］カードゲームだよ、知らないのか？　面白いんだぞ？")
   (wait)
   (text-reset 1)
   (text "［シーラ］知ってるよ。だけど２人じゃあまり面白くないかもよ。")
   (wait)
   (text-reset 1)
   (text "［コール］したら、誰か他のお客を混ぜればいいよ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］強引ね・・・。")
   (set-reg 118 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 105 #t) (= 107 #t) (= 111 #t) (= 112 #t))
   (text "［コール］バッグの中身はその位かな・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］あっ！")
   (wait)
   (text-reset 1)
   (text "［コール］どうした？")
   (wait)
   (text-reset 1)
   (text "［シーラ］忘れてた・・・カメラのテープ買うの。どうしよう・・")
   (wait)
   (text-reset 1)
   (text "［コール］いいよ、明日空港に行く途中で買えば。")
   (wait)
   (text-reset 1)
   (text "［シーラ］コール、絶対に寝坊するもん。私、ちょっと今から買い　　　　　に行ってくるわ。そこのスーパー２時までよね？")
   (wait)
   (text-reset 1)
   (text "［コール］ああ、そうだけど・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］じゃあ、行ってくる。")
   (wait)
   (text-reset 1)
   (text "［コール］あ、お金・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］いらない、すぐ戻るね。")
   (wait)
   (text-reset 1)
   (text "［コール］気を付けて行けよ。")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB003.GPC")
   (image-mem 1 1)
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (text
    "［コール］まったく、そそっかしいと言うか・・・そういう所は、　　　　　あいつ昔から変わらないよな。だけど、俺の寝坊の計算　　　　　まで入れているとは思わなかったけど・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］キャアアアア！！")
   (wait)
   (text-reset 1)
   (text "［コール］シーラだ、どうしたんだ！？")
   (wait)
   (text-reset 1)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥002.MES"))
 (seg (? (= P 5) (= 100 #f))
   (text
    "［コール］シーラの左手の薬指には俺が買ってあげた婚約指輪が光　　　　　っている。あまり高価な物ではないが、あの時俺に見せ　　　　　たシーラの笑顔は今でも覚えている。")
   (set-reg 100 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 101 #f))
   (text
    "［コール］シーラの奴、心成しかこの数年で意外と雰囲気が変わっ　　　　　たよな。前なんて、ホントにおとなしそうなお嬢さんだ　　　　　ったのに・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］お嬢さんの方が良かった？")
   (wait)
   (text-reset 1)
   (text "［コール］そうだな、やっぱ俺はお嬢さんが・・・ん！？　お前、　　　　　聞いてたな？")
   (wait)
   (text-reset 1)
   (text "［シーラ］どうせ私はオテンバですよーだ！")
   (set-reg 101 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 102 #f))
   (text "［シーラ］リンが私達の事、すごく羨ましがってたわね。彼女も早　　　　　くテリーと結婚すればいいのに・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］え？　あの二人ってデキてたのか？")
   (wait)
   (text-reset 1)
   (text
    "［シーラ］コール知らなかったの？　２年前の事件があった後、精　　　　　神的に参ってたテリーの気晴らしになるだろうって、私　　　　　がリンを紹介したのよ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］それからかな・・・二人が仲良くなったのは。")
   (wait)
   (text-reset 1)
   (text "［コール］・・・全然気がつかなかったな。テリーの奴も俺に一言　　　　　言ってくれればいいのに・・・。")
   (set-reg 102 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 103 #f))
   (text "［シーラ］そんな事より、あんなにガブガブ飲んじゃって・・・、　　　　　明日ちゃんと起きれるの？")
   (wait)
   (text-reset 1)
   (text
    "［コール］大丈夫だよ、明日はシーラとカナダ旅行だもんな。二日　　　　　酔いで飛行機に乗り遅れたなんて、洒落にもならないか　　　　　らな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］ならいいけど・・・。")
   (set-reg 103 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 104 #f))
   (text "［コール］シーラは俺の誕生祝いに、カナダ行きのチケットをプレ　　　　　ゼントしてくれたんだ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］ツアーにしたかったけど、そこまでお金がまわらなかっ　　　　　たの。だから飛行機代だけね。")
   (wait)
   (text-reset 1)
   (text "［コール］十分だよ、ありがとうな。チケットはシーラが持ってた　　　　　よな？")
   (wait)
   (text-reset 1)
   (text "［シーラ］嘘よ・・・コールに渡したわ。")
   (wait)
   (text-reset 1)
   (text "［コール］まじ？　俺が持ってたっけ？")
   (wait)
   (text-reset 1)
   (text "［シーラ］ジャケットに入れてたの見たもん。")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 0 54 38,W 0,O 0")
   (text "［コール］あ、ホントだ・・・。無くすといけないから、シーラが　　　　　持っててくれよ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］うん、判ったわ。")
   (set-reg 104 #t)
   (exec-mem 912 "PUT 1 54 38,W 0,O 1")
   (exec-mem 912 "EXIT")
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 104 #t))
   (text "［シーラ］早く明日にならないかな・・・。なんだか、そう思うと　　　　　ワクワクして眠れそうもないわ。")
   (wait)
   (text-reset 1)
   (text "［コール］睡眠だけはとっておかないとな。観光してるのに、ボケ　　　　　てたら勿体ないからな。")
   (set-reg 105 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 106 #f))
   (text
    "［コール］俺がこのアパートに越してきたのは、あの事件が起きた　　　　　後である。以前の隣街にあったアパートは、あの事件の　　　　　お陰で住む事ができなくなってしまったんだ。")
   (wait)
   (text-reset 1)
   (text
    "［コール］今になって、やっと住民を募集しているらしいが、元々　　　　　治安が悪かったせいか、現在では暴走族が好き放題暴れ　　　　　ているらしいな。")
   (set-reg 106 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 107 #f))
   (text "［コール］このアパートは部屋はとても広いが、建物自体がかなり　　　　　古いため、それだけ家賃も格安なんだ。")
   (wait)
   (text-reset 1)
   (text "［コール］シーラと婚約したため、これから色々とお金を使うだろ　　　　　うから、家賃位でそんなに金をかけられないんだ。")
   (set-reg 107 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text
    "［コール］壁には俺の貼り付けた雑誌の切り抜きが貼ってある。俺　　　　　は気に入った写真や記事があると、こうして壁に貼って　　　　　取っておくんだ。")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 108 #f))
   (text
    "［コール］天井に設置されている大型のエアコンは、この部屋には　　　　　十分すぎる程のパワーをもっている。夏なんて、３分も　　　　　あれば蒸し暑い部屋の気温を一気に落とす事ができる。")
   (set-reg 108 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 109 #f))
   (text
    "［コール］大家に聞いてみたところ、元々この部屋は会社の事務所　　　　　に使っていたらしく、人がたくさん出入りするために、　　　　　これだけの大きなエアコンを設置していたらしい。")
   (wait)
   (text-reset 1)
   (text "［コール］俺としては実にラッキーだよな。")
   (set-reg 109 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "［コール］そろそろ寒くなってきたし、またこいつの世話になるだ　　　　　ろうな。")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 110 #f))
   (text "［コール］電話だな・・・。今はどこからもかかっては来てないし　　　　　どこにもかける必要もない。")
   (set-reg 110 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 111 #f))
   (text
    "［コール］そう、２年前は蘇生薬を作ったってドクから電話があっ　　　　　たんだよな。それが最初であの事件が起きてしまったん　　　　　だ・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］コール、その話はよしましょうよ。死んでしまったクー　　　　　ガーさんに悪いわ。")
   (wait)
   (text-reset 1)
   (text "［コール］ああ、そうだったな。")
   (set-reg 111 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))
   (text "［シーラ］電話がそんなに気になるの？")
   (wait)
   (text-reset 1)
   (text "［コール］いや、なんとなく眺めていただけさ。")
   (wait)
   (text-reset 1))
 (seg (? (= P 9) (= 112 #f))
   (text "［コール］この部屋の出入口にあたるドアだ。鍵がかなり錆付いて　　　　　しまっているから、ブッ叩けばすぐに壊れるだろうな。")
   (wait)
   (text-reset 1)
   (text "［コール］まあ、もし泥棒なんて入っても持っていくような物は、　　　　　まずないけど・・・ね。")
   (wait)
   (text-reset 1)
   (text "［シーラ］そのコンポは？")
   (wait)
   (text-reset 1)
   (text "［コール］ただのラジオ代わりに使っているだけだよ。カセットと　　　　　ＣＤの方は完全に壊れているからね。")
   (wait)
   (text-reset 1)
   (text "［シーラ］コールって、電気製品ってあまり買わないの？")
   (wait)
   (text-reset 1)
   (text "［コール］冷蔵庫とか洗濯機とか、どうしても必要な物以外は滅多　　　　　に買わないな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］車とかは？")
   (wait)
   (text-reset 1)
   (text "［コール］車なんて持ってても、そんな色々と行く所なんてないか　　　　　らなぁ・・・。まぁ、それ以前に免許もないからな。")
   (set-reg 112 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 9) (= 113 #f))
   (text
    "［シーラ］でも、やっぱり鍵は換えておいた方がいいと思うわ。誰　　　　　かが入ってきて、いきなり「ブスッ！」じゃ洒落になら　　　　　ないわよ。")
   (wait)
   (text-reset 1)
   (text "［コール］俺は人に刺されるような恨みを買った覚えはないぞ。")
   (set-reg 113 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 9))
   (text "［コール］ドアの鍵は開いているな。後でシーラが帰ったら閉める　　　　　としよう。")
   (wait)
   (text-reset 1))
 (seg (? (= P 10) (= 114 #f))
   (text
    "［コール］このステレオはラジオしか聞けないんだよな。カセット　　　　　とＣＤが壊れているんだ。早めに修理に出した方がいい　　　　　かもしれないな。")
   (set-reg 114 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 10) (= 115 #f))
   (text "［コール］今はシーラと話しているから、ラジオなんてつけない方　　　　　がいいな。シーラはそういう所が異常に敏感なんだよ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］誰が異常ですって？")
   (set-reg 115 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 10) (= 116 #f))
   (text "［シーラ］コール、ラジオつけて。")
   (wait)
   (text-reset 1)
   (text "［コール］へ？")
   (wait)
   (text-reset 1)
   (text "［シーラ］ラジオよ、何か音楽でも鳴ってないと寂しいでしょ？")
   (wait)
   (text-reset 1)
   (text "［コール］珍しいな・・・これだから女心は判らないよ。")
   (set-reg 116 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 10) (= 117 #f))
   (text "［コール］つけたよ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］ありがと。")
   (wait)
   (text-reset 1)
   (text "［コール］・・・・。" 'br)
   (text "［シーラ］・・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］おい？")
   (wait)
   (text-reset 1)
   (text "［シーラ］ん？")
   (wait)
   (text-reset 1)
   (text "［コール］ハードロックでいいのか？")
   (wait)
   (text-reset 1)
   (text "［シーラ］うん。")
   (wait)
   (text-reset 1)
   (text "［コール］俺はてっきり、ムード音楽でも流すのかと思ってたよ。")
   (set-reg 117 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 10))
   (text "［コール］ラジオからはハードロックがかかっている。こんな時間　　　　　だから、あまりボリュームは上げられないな。")
   (wait)
   (text-reset 1))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))