; Dead of the Brain 2 (PC-98) - 001.MES
; Translated by Geometrizer
; Edited by trentsignia
; -----Scene:-----
; Sheila and Cole hang out after celebrating their engagement with friends Terry and Lynn.
; --Progression:--
; Talk to Sheila after inspecting everything in the room.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (>= M A))
   (exec-mem 9920 0 6 6 113 64 0)
   (image-file "B:¥GPC¥DB003.GPC")
   (image-mem 1 3)
   (image-file "B:¥GPC¥DB004.GPC")
   (image-mem 1 3)
   (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
   (exec-mem 912 "C 0 40 0 40 400 1 40 0")
   (exec-mem 912 "A 1")
   (image-file "A:¥GPC¥DB_FRM2.GPC")
   (image-mem 1 0)
   (image-file "B:¥GPC¥DB005C.GPC")
   (image-mem 1 3)
   (exec-mem 912 "GET 0 54 38 23 134")
   (exec-mem 912 "A 0")
   (exec-mem 912 "GET 1 54 38 23 134")
   (exec-mem 912 "A 0,S 0")
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (load-mem "A:¥CLM¥DB004.CLM" 32768)
   (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)			; Hotspots and buttons defined here...
   (exec-mem 3744 1 1 80 0 0 0)							; 	MOVE button
   (exec-mem 3744 1 2 80 0 0 0)							; 	SYSTEM button
   (exec-mem 3744 1 5 15 5 24 13)						; 	Sheila
   (exec-mem 3744 1 6 27 5 36 13)						; 	Wall
   (exec-mem 3744 1 7 23 2 40 3)						; 	Aircon
   (exec-mem 3744 1 8 3 8 7 12)							; 	Phone
   (exec-mem 3744 1 9 37 7 47 14)						; 	Door
   (exec-mem 3744 1 10 52 12 56 15)						; 	Stereo
   (sound '|| 0)
   (if (</>
        (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
        (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
   (sound '|| 1)
   (text-frame 15 298 74 356)
   (if (</>
        (//
         (? (= 119 #f))								; Lead-in from previous MES script
         (str "Cole: I'm so sorry for making you do all the cleanup.")
         (wait)
         (text-reset 1)
         (str "Sheila: It's all right. You're all worn out, aren't you?")
         (wait)
         (text-reset 1)
         (str "Cole: I'm fine, but those two sure know how to party even" 'br)
         (str "though they have work tomorrow.")
         (wait)
         (text-reset 1)
         (str "Sheila: We sure made you put back the drinks.")
         (wait)
         (text-reset 1)
         (str "Cole: Yeah, and I'll be sleeping like a log because of it.")
         (set-reg 119 #t))
        (//
         (str "Sheila: You look like you're about to fall over.")		; Lead-in from loading game
         (wait)
         (text-reset 1)
         (str "Cole: I never thought Terry and Lynn would make me drink" 'br)
         (str "THAT much.")
         (wait)
         (text-reset 1)
         (str "Sheila: Those two don't know the meaning of moderation."))))
   (wait)
   (text-reset 1)
   (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 105 #t) (= 107 #t) (= 111 #t) (= 112 #t) (= 118 #f))	; Sheila (after inspecting everything) #1
   (str "Sheila: Cole, are you all packed up for the trip?")
   (wait)
   (text-reset 1)
   (str "Cole: Should be fine. Bag's got my passport, change of" 'br)
   (str "clothes, camera...and Uno.")
   (wait)
   (text-reset 1)
   (str "Sheila: Uno?")
   (wait)
   (text-reset 1)
   (str "Cole: You know, the card game. It's fun, isn't it?")
   (wait)
   (text-reset 1)
   (str "Sheila: Yeah, I know Uno, but wouldn't two players be a" 'br)
   (str "drag?")
   (wait)
   (text-reset 1)
   (str "Cole: Well, then you can ask someone else to join in.")
   (wait)
   (text-reset 1)
   (str "Sheila: So pushy...")
   (set-reg 118 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 105 #t) (= 107 #t) (= 111 #t) (= 112 #t))			; Shiela (after inspecting everything) #2
   (str "Cole: Anyway, that's my bag all packed.")
   (wait)
   (text-reset 1)
   (str "Sheila: Oh no!")
   (wait)
   (text-reset 1)
   (str "Cole: What is it?")
   (wait)
   (text-reset 1)
   (str "Sheila: I forgot to buy film for the camera! What am I" 'br)
   (str "going to do...")
   (wait)
   (text-reset 1)
   (str "Cole: It's fine, we'll just pick some up tomorrow on the" 'br)
   (str "way to the airport.")
   (wait)
   (text-reset 1)
   (str "Sheila: Cole, you're the king of oversleepers. I'll go grab" 'br)
   (str "some right now. The supermarket's open until 2am, right?")
   (wait)
   (text-reset 1)
   (str "Cole: Yeah, I think so...")
   (wait)
   (text-reset 1)
   (str "Sheila: Okay, I'm off then!")
   (wait)
   (text-reset 1)
   (str "Cole: Wait, you need cash?")
   (wait)
   (text-reset 1)
   (str "Sheila: I'm good, back soon!")
   (wait)
   (text-reset 1)
   (str "Cole: Take care, all right?")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB003.GPC")
   (image-mem 1 1)
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (str "Cole: She's always been so scatterbrained...just the same" 'br)
   (str "after all these years. She's not wrong about me" 'br)
   (str "oversleeping. Surprised she took that into account.")
   (wait)
   (text-reset 1)
   (str "Sheila: Eeeeek!")
   (wait)
   (text-reset 1)
   (str "Cole: Sheila, what's wrong?")
   (wait)
   (text-reset 1)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥002.MES"))
 (seg (? (= P 5) (= 100 #f))							; Shiela #1
   (str "Cole: The engagement ring sparkles on Sheila's left ring" 'br)
   (str "finger. It's not the priciest, but I still remember the big" 'br)
   (str "smile on her face when I gave it to her.")
   (set-reg 100 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 101 #f))							; Shiela #2
   (str "Cole: Sheila's changed a bit over time. She used to seem" 'br)
   (str "more quiet and reserved.")
   (wait)
   (text-reset 1)
   (str "Sheila: And you're saying I should have stayed that way?")
   (wait)
   (text-reset 1)
   (str "Cole: Well, a little more ladylike would -- hey! You were" 'br)
   (str "listening in, weren't you?")
   (wait)
   (text-reset 1)
   (str "Sheila: After all, I am a tomboy, you know!")
   (set-reg 101 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 102 #f))							; Shiela #3
   (str "Sheila: Lynn seemed jealous about what we've got going. She" 'br)
   (str "should bite the bullet and marry Terry already.")
   (wait)
   (text-reset 1)
   (str "Cole: Wait, those two are a thing!?")
   (wait)
   (text-reset 1)
   (str "Sheila: Cole, you couldn't tell? After the incident two" 'br)
   (str "years ago, Terry was mentally wrecked, so I introduced him" 'br)
   (str "to Lynn. I thought she'd be good for him.")
   (wait)
   (text-reset 1)
   (str "Sheila: I guess back then is when they first clicked.")
   (wait)
   (text-reset 1)
   (str "Cole: Geez, I didn't notice at all. Terry shoulda said" 'br)
   (str "something to me...")
   (set-reg 102 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 103 #f))							; Shiela #4
   (str "Sheila: But seriously, you drank like a fish. Are you gonna" 'br)
   (str "be able to wake up tomorrow?")
   (wait)
   (text-reset 1)
   (str "Cole: It's fine, it's fine. It's our trip to Canada, after" 'br)
   (str "all... a hangover derailing those plans would be a disaster.")
   (wait)
   (text-reset 1)
   (str "Sheila: It sure would.")
   (set-reg 103 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 104 #f))							; Shiela #5
   (str "Cole: Sheila got me a flight to Canada as a birthday" 'br)
   (str "present.")
   (wait)
   (text-reset 1)
   (str "Sheila: I wanted to get us a full tour package, but my" 'br)
   (str "paycheck only goes so far, so it's the flight or nothing.")
   (wait)
   (text-reset 1)
   (str "Cole: That's more than enough! You've got the tickets," 'br)
   (str "right?")
   (wait)
   (text-reset 1)
   (str "Sheila: What are you talking about? I already handed them" 'br)
   (str "to you.")
   (wait)
   (text-reset 1)
   (str "Cole: For real? I've got 'em?")
   (wait)
   (text-reset 1)
   (str "Sheila: I saw you put them in your jacket, genius.")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 0 54 38,W 0,O 0")
   (str "Cole: Oh, right, right. Uh, I don't wanna lose these, so" 'br)
   (str "you should hold on to them for me.")
   (wait)
   (text-reset 1)
   (str "Sheila: Don't mind if I do.")
   (set-reg 104 #t)
   (exec-mem 912 "PUT 1 54 38,W 0,O 1")
   (exec-mem 912 "EXIT")
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 104 #t))							; Shiela #6 (repeat line)
   (str "Sheila: Tomorrow can't come soon enough. I won't be able to" 'br)
   (str "sleep, thinking about it.")
   (wait)
   (text-reset 1)
   (str "Cole: I'd better hit the hay soon. I don't want to be" 'br)
   (str "half-asleep when I'm seeing the sights in the Great White" 'br)
   (str "North.")
   (set-reg 105 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 106 #f))							; Wall #1
   (str "Cole: I moved into this apartment after the incident, which" 'br)
   (str "rendered my last place uninhabitable.")
   (wait)
   (text-reset 1)
   (str "Cole: I hear they're looking for new tenants, but biker" 'br)
   (str "gangs have been raising hell nearby, since this isn't the" 'br)
   (str "safest area.")
   (set-reg 106 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 107 #f))							; Wall #2
   (str "Cole: This apartment has big rooms, but it's real old," 'br)
   (str "hence the cheap rent.")
   (wait)
   (text-reset 1)
   (str "Cole: Since I'm engaged to Sheila, I'll need to save a lot" 'br)
   (str "of cash, so I can't justify paying a bunch for rent.")
   (set-reg 107 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))								; Wall #3 (repeat line)
   (str "Cole: I've got a bunch of magazine clippings on the wall." 'br)
   (str "Whenever I see a photo or article I like, I stick it on the" 'br)
   (str "wall.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 108 #f))							; Aircon #1
   (str "Cole: The air conditioner on the ceiling is super powerful." 'br)
   (str "It can go from balmy to chill in just three minutes.")
   (set-reg 108 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 109 #f))							; Aircon #2
   (str "Cole: When I asked the landlord, he told me this place used" 'br)
   (str "to be an office. The big air conditioner helped out with" 'br)
   (str "everyone coming and going.")
   (wait)
   (text-reset 1)
   (str "Cole: Stroke of luck, I guess.")
   (set-reg 109 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))								; Aircon #3 (repeat line)
   (str "Cole: It's getting cold soon, so I'll need to crank up the" 'br)
   (str "heating on it.")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 110 #f))							; Phone #1
   (str "Cole: My phone. Nobody's calling me now, and I haven't got" 'br)
   (str "anyone to call at the moment.")
   (set-reg 110 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 111 #f))							; Phone #2
   (str "Cole: That's right...two years ago, Doc called me to say he" 'br)
   (str "created a reanimation serum. That's what started the" 'br)
   (str "incident...")
   (wait)
   (text-reset 1)
   (str "Sheila: Cole, let's not go there... Doctor Cooger wouldn't" 'br)
   (str "want us to think about it now, of all times.")
   (wait)
   (text-reset 1)
   (str "Cole: Right, right.")
   (set-reg 111 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))								; Phone #3 (repeat line)
   (str "Sheila: Why do you keep looking at the phone? You expecting" 'br)
   (str "a call?")
   (wait)
   (text-reset 1)
   (str "Cole: Nah, just zoning out.")
   (wait)
   (text-reset 1))
 (seg (? (= P 9) (= 112 #f))							; Door #1
   (str "Cole: Here's the door to my room. The lock's rusted, so one" 'br)
   (str "good hit would bust it open.")
   (wait)
   (text-reset 1)
   (str "Cole: Even if a burglar got in, there's nothing worth" 'br)
   (str "stealing.")
   (wait)
   (text-reset 1)
   (str "Sheila: What about the stereo system?")
   (wait)
   (text-reset 1)
   (str "Cole: It's more like a radio. The cassette deck and CD" 'br)
   (str "player are broken.")
   (wait)
   (text-reset 1)
   (str "Sheila: Cole, you're not much of a gadget guy, are you?")
   (wait)
   (text-reset 1)
   (str "Cole: I only buy the necessities. Like a fridge and washing" 'br)
   (str "machine.")
   (wait)
   (text-reset 1)
   (str "Sheila: How about a car?")
   (wait)
   (text-reset 1)
   (str "Cole: Even if I had a car, I wouldn't have anywhere to go." 'br)
   (str "Not that I've even got a license.")
   (set-reg 112 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 9) (= 113 #f))							; Door #2
   (str "Sheila: I still say you should change your locks. If" 'br)
   (str "someone breaks down your door...")
   (wait)
   (text-reset 1)
   (str "Cole: I haven't made enough enemies for anyone to stab me.")
   (set-reg 113 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 9))								; Door #3 (repeat line)
   (str "Cole: It's unlocked right now. I'll lock it after Sheila" 'br)
   (str "goes home.")
   (wait)
   (text-reset 1))
 (seg (? (= P 10) (= 114 #f))							; Stereo #1
   (str "Cole: Only the radio works on this stereo. The cassette and" 'br)
   (str "CD components are busted. I really should get it fixed.")
   (set-reg 114 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 10) (= 115 #f))							; Stereo #2
   (str "Cole: We're having a conversation, so I don't wanna ruin" 'br)
   (str "the mood by turning on the radio. Sheila's sensitive about" 'br)
   (str "that kind of thing.")
   (wait)
   (text-reset 1)
   (str "Sheila: Who are you calling sensitive?")
   (set-reg 115 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 10) (= 116 #f))							; Stereo #3
   (str "Sheila: Cole, turn on the radio.")
   (wait)
   (text-reset 1)
   (str "Cole: Huh?")
   (wait)
   (text-reset 1)
   (str "Sheila: Without any music, it's a little lonely, isn't it?")
   (wait)
   (text-reset 1)
   (str "Cole: You're something else...this is why I'll never" 'br)
   (str "understand women.")
   (set-reg 116 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 10) (= 117 #f))							; Stereo #4
   (str "Cole: Okay, it's on.")
   (wait)
   (text-reset 1)
   (str "Sheila: Thanks.")
   (wait)
   (text-reset 1)
   (str "Cole: ..." 'br)
   (str "Sheila: ...")
   (wait)
   (text-reset 1)
   (str "Cole: So, uh...")
   (wait)
   (text-reset 1)
   (str "Sheila: Yeah?")
   (wait)
   (text-reset 1)
   (str "Cole: Is hard rock okay?")
   (wait)
   (text-reset 1)
   (str "Sheila: Sure.")
   (wait)
   (text-reset 1)
   (str "Cole: I thought you'd want some mood music.")
   (set-reg 117 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 10))								; Stereo #5 (repeat line)
   (str "Cole: The radio's playing hard rock. It's late, so I can't" 'br)
   (str "really crank it up.")
   (wait)
   (text-reset 1))
 (seg (? (= P 2))								; SYSTEM
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))