; Dead of the Brain 2 (PC-98) - 002.MES
; Translated by Geometrizer
; Edited by trentsignia and JackDBS
; -----Scene:-----
; Sheila and Cole finds Terry and Lynn dead outside their apartment.
; --Progression:--
; After inspecting everything Cole discovers the presence of reanimation serum, leading him to reevaluate the scene. Inspect everything again to progress.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB006.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)			; Hotspots and buttons defined here...
  (exec-mem 3744 1 1 80 0 0 0)							; 	MOVE button
  (exec-mem 3744 1 2 80 0 0 0)							; 	SYSTEM button
  (exec-mem 3744 1 5 49 8 56 13)						; 	Terry
  (exec-mem 3744 1 6 17 12 25 15)						; 	Lynn
  (exec-mem 3744 1 7 12 9 17 11)						; 	Wall
  (exec-mem 3744 1 8 23 8 28 10)						; 	Doorway
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB006.GPC") (image-mem 1 3)
  (if (</>
       (// (? (= 120 #f)) (image-file "B:¥GPC¥DB007.GPC") (image-mem 1 3))))
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC") (image-mem 1 0)
  (image-file "B:¥GPC¥DB009C.GPC") (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (sound '|se | 3)
  (text-frame 15 298 74 356)
  (if (</>
       (//
        (? (= 132 #t))								; Lead-in from loading game (after discovering reanimation serum)
        (str "Cole: Why would there be reanimation serum in a place like" 'br)
        (str "this!?")
        (wait)
        (text-reset 1))
       (//
        (? (= 120 #f))								; Lead-in from previous MES script
        (str "Cole: Lynn... Terry...!")
        (wait)
        (text-reset 1)
        (str "Sheila: Cole...")
        (wait)
        (text-reset 1)
        (str "Cole: Jesus... What happened here!?")
        (wait)
        (text-reset 1)
        (str "Sheila: I don't know... When I came down the stairs...")
        (wait)
        (text-reset 1)
        (str "Cole: Is he...dead?")
        (wait)
        (text-reset 1)
        (str "Sheila: I...I...")
        (wait)
        (text-reset 1)
        (str "Cole: Sheila...")
        (wait)
        (text-reset 1)
        (str "Sheila: Terry and Lynn are both dead?")
        (wait)
        (text-reset 1)
        (str "Cole: They've been beaten so badly...")
        (wait)
        (text-reset 1)
        (str "Sheila: What the hell...")
        (wait)
        (text-reset 1)
        (str "Cole: They both left my room ten minutes ago...did it" 'br)
        (str "happen then?")
        (wait)
        (text-reset 1)
        (str "Sheila: Were...were they being targeted?")
        (wait)
        (text-reset 1)
        (str "Cole: I don't know...but Terry and Lynn wouldn't ever try" 'br)
        (str "to hurt anyone.")
        (wait)
        (text-reset 1)
        (str "Sheila: They really wouldn't...")
        (wait)
        (text-reset 1)
        (str "Cole: Shit... Who could have done this to them?")
        (wait)
        (text-reset 1)
        (str "Sheila: Should we call the police?")
        (wait)
        (text-reset 1)
        (str "Cole: Wait..let me search the area first. If I can find any" 'br)
        (str "kind of clue that might point towards a culprit...")
        (wait)
        (text-reset 1)
        (str "Sheila: It's too dangerous! Leave it to the cops. And if" 'br)
        (str "someone else reports us here, they might think we were" 'br)
        (str "responsible...")
        (wait)
        (text-reset 1)
        (str "Cole: I can't forgive whoever did this to my best friends!" 'br)
        (str "And there's no reason anyone would be here. Nobody would" 'br)
        (str "even notice if you did some vandalism back here...")
        (set-reg 120 #t)
        (wait)
        (text-reset 1)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (image-file "B:¥GPC¥DB006.GPC") (image-mem 1 3)
        (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50))))
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
  (sound '|| 1)
  (loop
   (if (</>
        (//
         (? (= 133 #t) (= 134 #t) (= 135 #t))					; Appended to last action after inspecting everything, post-discovery of reanimation serum
         (str "Cole: Was someone trying to lure me out...?")
         (wait)
         (text-reset 1)
         (str "Sheila: What!?")
         (wait)
         (text-reset 1)
         (str "Cole: Someone killed our friends in front of my apartment," 'br)
         (str "and there are traces of the reanimation serum everywhere.")
         (wait)
         (text-reset 1)
         (str "Sheila: You're trying to find things that aren't there! If" 'br)
         (str "we just called the police, this would all be over...")
         (wait)
         (text-reset 1)
         (str "Cole: Maybe...")
         (wait)
         (text-reset 1)
         (str "Sheila: Cole, you're overanalyzing things!")
         (wait)
         (text-reset 1)
         (str "Cole: ...")
         (wait)
         (text-reset 1)
         (str "Sheila: Cole...")
         (wait)
         (text-reset 1)
         (str "Cole: ...Sheila, I have something to ask you...")
         (wait)
         (text-reset 1)
         (str "Sheila: No, Cole!")
         (wait)
         (text-reset 1)
         (str "Cole: I just can't sit back and pretend like this didn't" 'br)
         (str "happen!")
         (wait)
         (text-reset 1)
         (str "Sheila: But tomorrow was our very first trip...we got" 'br)
         (str "tickets...and you bought me a new bag...")
         (wait)
         (text-reset 1)
         (str "Cole: Sheila, you need to understand. Doc saved me during" 'br)
         (str "the incident two years ago. That's why I'm still here.")
         (wait)
         (text-reset 1)
         (str "Sheila: But...")
         (wait)
         (text-reset 1)
         (str "Cole: If I don't do anything, he would have died for" 'br)
         (str "nothing.")
         (wait)
         (text-reset 1)
         (str "Cole: I don't know who, but someone out there is using" 'br)
         (str "Doc's reanimation serum. I can't just ignore that.")
         (wait)
         (text-reset 1)
         (str "Cole: If I leave things as they are, the damage is only" 'br)
         (str "going to spread. And I'd be letting down Terry and" 'br)
         (str "Lynn...who loved and supported us...")
         (wait)
         (text-reset 1)
         (str "Sheila: ...")
         (wait)
         (text-reset 1)
         (str "Cole: Sheila, please. The gun you had from back then...")
         (wait)
         (text-reset 1)
         (str "Sheila: You don't have to spell it out. I know you better" 'br)
         (str "than anyone, Cole.")
         (wait)
         (text-reset 1)
         (str "Sheila: I'll go get the gun. You wait here.")
         (wait)
         (text-reset 1)
         (str "Cole: I know Sheila wanted me to stop. But I can't back" 'br)
         (str "down after seeing how far things have gone...")
         (wait)
         (text-reset 1)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (image-file "B:¥GPC¥DB008.GPC") (image-mem 1 1)
         (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
         (str "Sheila: It's got three rounds. Don't go around shooting" 'br)
         (str "like a crazy person and get arrested.")
         (wait)
         (text-reset 1)
         (exec-mem 912 "PUT 0 54 38,W 0,O 0")
         (str "Sheila: Here. Take it.")
         (wait)
         (text-reset 1)
         (str "Cole: Thanks. Wait for me, I'll be right back.")
         (wait)
         (text-reset 1)
         (exec-mem 912 "PUT 1 54 38,W 0,O 1")
         (exec-mem 912 "EXIT")
         (sound '|| 2)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (mes-jump "A:¥MES¥003.MES"))
        (//
         (? (= 123 #t) (= 126 #t) (= 129 #t) (= 131 #t) (= 132 #f))		; Appended to last action after inspecting everything
         (str "Sheila: Cole, I've been wondering...what are those weird" 'br)
         (str "spatters on the ground?")
         (wait)
         (text-reset 1)
         (str "Cole: I don't know, moss, maybe? That kind of thing can be" 'br)
         (str "bioluminescent...")
         (wait)
         (text-reset 1)
         (str "Sheila: No, that's not it...")
         (wait)
         (text-reset 1)
         (str "Cole: If it's not moss, what could it be? Let's see.")
         (wait)
         (text-reset 1)
         (str "Sheila: What is it? Does it have a smell?")
         (wait)
         (text-reset 1)
         (str "Cole: Oh my god. This is...")
         (wait)
         (text-reset 1)
         (str "Sheila: What's wrong! You look like you've seen a ghost...")
         (wait)
         (text-reset 1)
         (str "Cole: It's the reanimation serum...")
         (wait)
         (text-reset 1)
         (str "Sheila: No way, you're kidding!")
         (wait)
         (text-reset 1)
         (str "Cole: There's no mistaking it. It smells strong...exactly" 'br)
         (str "the same as the stuff Doc made two years ago. I'll never" 'br)
         (str "forget it.")
         (wait)
         (text-reset 1)
         (str "Sheila: Why!? How could something like that wind up here?")
         (wait)
         (text-reset 1)
         (str "Cole: I don't know... Wait! Could it be...these two...")
         (wait)
         (text-reset 1)
         (str "Sheila: Cole, stop! That's a lie, the incident's all over!" 'br)
         (str "We're the only people left who know about Doctor Cooger's" 'br)
         (str "reanimation serum! Right!?")
         (wait)
         (text-reset 1)
         (str "Cole: That's right...two years ago after I defeated Ghoul," 'br)
         (str "there isn't anyone left who knew about the serum...but how" 'br)
         (str "is this here!?")
         (wait)
         (text-reset 1)
         (str "Sheila: How would I know!?")
         (set-reg 132 #t)							; This flag triggers new "post-discovery" lines for every hotspot in the scene
         (wait)
         (text-reset 1))))
   (exec-mem 3744 3 "P" 32768)
   (text-color 15)
   (seg-call)))
 (seg (? (= P 5) (= 132 #t) (= 133 #f))						; Terry (post-discovery) #1
   (str "Sheila: What are we going to do?")
   (wait)
   (text-reset 1)
   (str "Cole: Let me take a closer look at his head...")
   (wait)
   (text-reset 1)
   (str "Sheila: ...")
   (wait)
   (text-reset 1)
   (str "Cole: So that's how it is...his scalp's been torn off, and" 'br)
   (str "his brain is...")
   (wait)
   (text-reset 1)
   (str "Sheila: What the hell...")
   (set-reg 133 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 132 #t))							; Terry (post-discovery) #2 (repeat line)
   (str "Cole: He took a real hit, so that explains the blood...")
   (wait)
   (text-reset 1)
   (str "Sheila: His scalp's really been...chewed off?")
   (wait)
   (text-reset 1)
   (str "Cole: Yeah...")
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 121 #f))							; Terry #1
   (str "Cole: That's Terry...his eyes still have an expression of" 'br)
   (str "terror. Just what was the last thing he saw...?")
   (wait)
   (text-reset 1)
   (str "Sheila: Terry's eyes are scary...")
   (set-reg 121 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 122 #f))							; Terry #2
   (str "Cole: He bled out. That amount of blood loss would kill" 'br)
   (str "anyone...")
   (wait)
   (text-reset 1)
   (str "Sheila: What are these wounds?")
   (wait)
   (text-reset 1)
   (str "Cole: It looks like his head. He might have been slammed" 'br)
   (str "into the wall...")
   (set-reg 122 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 123 #f))							; Terry #3
   (str "Cole: And the blood still hasn't clotted.")
   (wait)
   (text-reset 1)
   (str "Sheila: It's only been ten minutes since they left the" 'br)
   (str "room...but that IS peculiar.")
   (wait)
   (text-reset 1)
   (str "Cole: What is?")
   (wait)
   (text-reset 1)
   (str "Sheila: If someone were getting attacked like that," 'br)
   (str "wouldn't they have screamed for help?")
   (wait)
   (text-reset 1)
   (str "Cole: Now that you mention it, in a place as quiet as this," 'br)
   (str "we should have heard it.")
   (wait)
   (text-reset 1)
   (str "Sheila: But there was no scream...there was no sound at" 'br)
   (str "all.")
   (wait)
   (text-reset 1)
   (str "Cole: That means the culprit wasn't acting alone.")
   (wait)
   (text-reset 1)
   (str "Sheila: How do you figure?")
   (wait)
   (text-reset 1)
   (str "Cole: If those two got ambushed, one of them would have" 'br)
   (str "screamed, right? If both died without a sound, someone" 'br)
   (str "attacked them at the same time.")
   (set-reg 123 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))								; Terry #4 (repeat line)
   (str "Cole: It looks like the good times we had are just memories" 'br)
   (str "now...")
   (wait)
   (text-reset 1)
   (str "Sheila: ...")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 132 #t) (= 134 #f))						; Lynn (post-discovery) #1
   (str "Cole: Just like I feared. Lynn's head is totally caved in.")
   (wait)
   (text-reset 1)
   (str "Sheila: Why...why would the reanimation serum be here now?")
   (wait)
   (text-reset 1)
   (str "Cole: I don't know...but that means someone aside from us" 'br)
   (str "knows about it.")
   (set-reg 134 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 132 #t))							; Lynn (post-discovery) #2 (repeat line)
   (str "Sheila: Could the culprit be...the undead?")
   (wait)
   (text-reset 1)
   (str "Cole: Probably...you don't see many other people gnawing on" 'br)
   (str "heads.")
   (wait)
   (text-reset 1)
   (str "Sheila: If it was really a...zombie, people on the street" 'br)
   (str "would be freaking out.")
   (wait)
   (text-reset 1)
   (str "Cole: That's true, but it doesn't look like anything's" 'br)
   (str "different from usual. It doesn't look like everyone's on" 'br)
   (str "zombie alert.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 124 #f))							; Lynn #1
   (str "Cole: Lynn lying down over there...she's just a girl..." 'br)
   (str "They should have taken it easier on her, you know?")
   (wait)
   (text-reset 1)
   (str "Sheila: The culprits must have planned on killing them" 'br)
   (str "both. Otherwise they wouldn't have taken it so far...")
   (set-reg 124 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 125 #f))							; Lynn #2
   (str "Sheila: Lynn... you and Terry were doing so well together...")
   (wait)
   (text-reset 1)
   (str "Cole: It's true. I feel so sorry for her...")
   (set-reg 125 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 126 #f))							; Lynn #3
   (str "Cole: There's no signs of a struggle or anything stolen.")
   (wait)
   (text-reset 1)
   (str "Sheila: It isn't possible... If someone attacked Lynn," 'br)
   (str "Terry wouldn't have stood for it. He would have called out" 'br)
   (str "for help.")
   (wait)
   (text-reset 1)
   (str "Cole: That's true. The culprit was deadset on killing them.")
   (set-reg 126 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))								; Lynn #4 (repeat line)
   (str "Cole: But just who could have done such a thing...")
   (wait)
   (text-reset 1)
   (str "Sheila: It's too awful!")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 132 #t) (= 135 #f))						; Wall (post-discovery) #1
   (str "Cole: Sheila, take a look at this wall. There's traces of" 'br)
   (str "the reanimation serum all over it.")
   (wait)
   (text-reset 1)
   (str "Sheila: But why is it there? The serum's supposed to be" 'br)
   (str "administered via injection, isn't it?")
   (wait)
   (text-reset 1)
   (str "Cole: A zombie would explain it. If a reanimated corpse" 'br)
   (str "were shambling around, the serum would be oozing out of" 'br)
   (str "it...right?")
   (set-reg 135 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 132 #t))							; Wall (post-discovery) #2 (repeat line)
   (str "Sheila: But why would a zombie be here?")
   (wait)
   (text-reset 1)
   (str "Cole: ...")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 127 #f))							; Wall #1
   (str "Cole: Anyone using this alley would live here. And who in" 'br)
   (str "their right mind would come into this alley in the middle" 'br)
   (str "of the night?")
   (set-reg 127 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 128 #f))							; Wall #2
   (str "Cole: There's a lot of notices posted on the walls, not" 'br)
   (str "that they'd really get anyone's attention.")
   (set-reg 128 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 129 #f))							; Wall #3
   (str "Cole: The building's shadow makes this place dark even" 'br)
   (str "during the daytime. You can't see anything that's going on" 'br)
   (str "from the street. Nobody would see what went on here.")
   (wait)
   (text-reset 1)
   (str "Cole: Especially at this hour of the night.")
   (set-reg 129 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))								; Wall #4 (repeat line)
   (str "Cole: You can see the bloodstains from those two... It's" 'br)
   (str "gruesome.")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 132 #t))							; Doorway (post-discovery) (repeat line)
   (str "Cole: If a zombie got spotted, everyone would lose their" 'br)
   (str "minds.")
   (wait)
   (text-reset 1)
   (str "Sheila: Right...but I still hear cars passing by, and Main" 'br)
   (str "Street looks the same as always.")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 130 #f))							; Doorway #1
   (str "Cole: Over there's Main Street, but it's so dark here that" 'br)
   (str "nobody would be able to see.")
   (set-reg 130 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 131 #f))							; Doorway #2
   (str "Sheila: The culprit must have fled that way.")
   (wait)
   (text-reset 1)
   (str "Cole: Right. The wall's too high to climb. If they headed" 'br)
   (str "towards Main Street, it might be hard to catch up.")
   (wait)
   (text-reset 1)
   (str "Sheila: Main Street is bustling even at night.")
   (set-reg 131 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))								; Doorway #3 (repeat line)
   (str "Cole: Dammit, why did I move into an apartment like this?")
   (wait)
   (text-reset 1)
   (str "Sheila: Don't blame yourself...or the apartment, Cole.")
   (wait)
   (text-reset 1))
 (seg (? (= P 2))								; SYSTEM
   (exec-mem 6064 2 2)
   (menu1
    25 317  39 317  53 317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))