(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB006.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 49 8 56 13)
  (exec-mem 3744 1 6 17 12 25 15)
  (exec-mem 3744 1 7 12 9 17 11)
  (exec-mem 3744 1 8 23 8 28 10)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB006.GPC")
  (image-mem 1 3)
  (if (</>
       (// (? (= 120 #f)) (image-file "B:¥GPC¥DB007.GPC") (image-mem 1 3))))
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC")
  (image-mem 1 0)
  (image-file "B:¥GPC¥DB009C.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (sound '|se | 3)
  (text-frame 15 298 74 356)
  (if (</>
       (//
        (? (= 132 #t))
        (text "［コール］蘇生薬がどうしてこんな所に・・・。")
        (wait)
        (text-reset 1))
       (//
        (? (= 120 #f))
        (text "［コール］テリー・・・リン・・・。")
        (wait)
        (text-reset 1)
        (text "［シーラ］コール・・・。")
        (wait)
        (text-reset 1)
        (text "［コール］な、何があったんだ！？")
        (wait)
        (text-reset 1)
        (text "［シーラ］判らない・・・私が降りてきた時には・・・。")
        (wait)
        (text-reset 1)
        (text "［コール］死んでる・・・のか？")
        (wait)
        (text-reset 1)
        (text "［シーラ］私・・・私・・・。")
        (wait)
        (text-reset 1)
        (text "［コール］シーラ・・・。")
        (wait)
        (text-reset 1)
        (text "［シーラ］テリーもリンも死んでしまったの？")
        (wait)
        (text-reset 1)
        (text "［コール］ああ、ここまで酷くやられてしまっていてはな・・・。")
        (wait)
        (text-reset 1)
        (text "［シーラ］なんて事・・・。")
        (wait)
        (text-reset 1)
        (text "［コール］二人が俺の部屋から出て行ったのが、１０分位前だから　　　　　・・・多分、その時を狙っていたのかもしれない・・。")
        (wait)
        (text-reset 1)
        (text "［シーラ］・・・二人は狙われていたの？")
        (wait)
        (text-reset 1)
        (text "［コール］判らない・・・。だが少なくとも俺達から見て、テリー　　　　　やリンは人に恨みを買うような人間ではないよ。")
        (wait)
        (text-reset 1)
        (text "［シーラ］そうよね・・・。")
        (wait)
        (text-reset 1)
        (text "［コール］くそっ・・・一体誰が二人をこんな目に・・・。")
        (wait)
        (text-reset 1)
        (text "［シーラ］警察に知らせた方がいいかしら？")
        (wait)
        (text-reset 1)
        (text "［コール］待て、現場を少し調べたい。少しでも犯人の手掛かりに　　　　　なる物が見つかれば・・・。")
        (wait)
        (text-reset 1)
        (text
         "［シーラ］危険よ、警察に任せた方がいいわ。それに、こんな所を　　　　　他の人に見つかったら、それこそこっちが犯人と勘違い　　　　　されてしまうわ。")
        (wait)
        (text-reset 1)
        (text
         "［コール］俺は親友をこんな目に遭わせた奴を許せないんだよ！！　　　　　・・・それに、こんな所に入って来る奴なんて滅多にい　　　　　ないよ。少し位荒らしても気付かれはしないさ。")
        (set-reg 120 #t)
        (wait)
        (text-reset 1)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (image-file "B:¥GPC¥DB006.GPC")
        (image-mem 1 3)
        (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50))))
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
  (sound '|| 1)
  (loop
   (if (</>
        (//
         (? (= 133 #t) (= 134 #t) (= 135 #t))
         (text "［コール］俺を呼び出すための罠か・・・。")
         (wait)
         (text-reset 1)
         (text "［シーラ］え？")
         (wait)
         (text-reset 1)
         (text "［コール］俺の住んでいるこのアパートの前で、友達が死霊に殺ら　　　　　れたんだ。それも、これだけの蘇生薬の跡をつけてな。")
         (wait)
         (text-reset 1)
         (text
          "［シーラ］考え過ぎよ。元々コールが犯人の手掛かりを捜すために　　　　　調べて判った事なのよ？　最初から警察を呼んでいれば　　　　　判らなかった事でしょ？")
         (wait)
         (text-reset 1)
         (text "［コール］まあ・・・ね。")
         (wait)
         (text-reset 1)
         (text "［シーラ］コールの考え過ぎよ。")
         (wait)
         (text-reset 1)
         (text "［コール］・・・・・・・・・。")
         (wait)
         (text-reset 1)
         (text "［シーラ］・・・・・コール・・・。")
         (wait)
         (text-reset 1)
         (text "［コール］・・・シーラ、頼みがあるんだが・・・。")
         (wait)
         (text-reset 1)
         (text "［シーラ］だめっ！")
         (wait)
         (text-reset 1)
         (text "［コール］頼むよ、俺だってじっとしていられないんだ。")
         (wait)
         (text-reset 1)
         (text "［シーラ］だって・・・明日は私達の初めての旅行でしょ？　折角　　　　　チケットも買ったし新しいバッグだって・・・。")
         (wait)
         (text-reset 1)
         (text "［コール］シーラ、判ってくれよ・・・。俺、２年前の事件でドク　　　　　に助けられているんだ。だからこうして生きてられる。")
         (wait)
         (text-reset 1)
         (text "［シーラ］だって・・・。")
         (wait)
         (text-reset 1)
         (text "［コール］俺、このまま何もしないでいたら死んでしまったドクに　　　　　申し訳が立たないよ。")
         (wait)
         (text-reset 1)
         (text
          "［コール］誰だか判らないけど、ドクの研究によって作られた蘇生　　　　　薬を使っている人間が居ると判っている以上は、俺が動　　　　　かない訳にはいかないんだ。")
         (wait)
         (text-reset 1)
         (text
          "［コール］それにこのまま放っておいたところで被害が増える一方　　　　　だし、俺を祝ってくれたテリーとリンにも申し訳が立た　　　　　ないよ・・・。")
         (wait)
         (text-reset 1)
         (text "［シーラ］・・・・・・。")
         (wait)
         (text-reset 1)
         (text "［コール］シーラ、頼むよ。あの時の銃を持ってきてくれないか？")
         (wait)
         (text-reset 1)
         (text "［シーラ］・・・そんなに言わなくたって、私が一番コールの性格　　　　　を知っているつもりよ。")
         (wait)
         (text-reset 1)
         (text "［シーラ］銃を取ってくるわ。待ってて・・・。")
         (wait)
         (text-reset 1)
         (text
          "［コール］あんな事言ってても、シーラには止めて欲しかったんだ　　　　　ろうな。だけど、俺だってここまで見て引き下がる訳に　　　　　はいかないもんな・・・。")
         (wait)
         (text-reset 1)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (image-file "B:¥GPC¥DB008.GPC")
         (image-mem 1 1)
         (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
         (text "［シーラ］弾は３発あるわ。変に撃ったりして警察に捕まらないよ　　　　　うにね。")
         (wait)
         (text-reset 1)
         (exec-mem 912 "PUT 0 54 38,W 0,O 0")
         (text "［シーラ］はい、銃。")
         (wait)
         (text-reset 1)
         (text "［コール］ありがとう、待っててくれ。すぐ戻るよ。")
         (wait)
         (text-reset 1)
         (exec-mem 912 "PUT 1 54 38,W 0,O 1")
         (exec-mem 912 "EXIT")
         (sound '|| 2)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (mes-jump "A:¥MES¥003.MES"))
        (//
         (? (= 123 #t) (= 126 #t) (= 129 #t) (= 131 #t) (= 132 #f))
         (text "［シーラ］コール、さっきから気になっていたんだけど・・地面に　　　　　点々と付着しているのは何？")
         (wait)
         (text-reset 1)
         (text "［コール］たぶん苔か何かだろ？　暗くなると光を出す苔があるっ　　　　　て聞いた事があるぜ。")
         (wait)
         (text-reset 1)
         (text "［シーラ］・・・違う・・・。")
         (wait)
         (text-reset 1)
         (text "［コール］苔じゃないと・・・何だろう？　どれどれ・・・。")
         (wait)
         (text-reset 1)
         (text "［シーラ］どう？　何か匂う？")
         (wait)
         (text-reset 1)
         (text "［コール］こ、これは・・・！！")
         (wait)
         (text-reset 1)
         (text "［シーラ］どうしたの？　怖い顔して・・・。")
         (wait)
         (text-reset 1)
         (text "［コール］・・・蘇生薬だ・・・。")
         (wait)
         (text-reset 1)
         (text "［シーラ］嘘でしょ？")
         (wait)
         (text-reset 1)
         (text "［コール］間違いない。少し匂いがキツイが、これは２年前にドク　　　　　が作ったものと同じだ。ハッキリと覚えているよ。")
         (wait)
         (text-reset 1)
         (text "［シーラ］どうして！？　どうしてそんな物がここにあるの！？")
         (wait)
         (text-reset 1)
         (text "［コール］判らない・・・まてよ！　まさか、この二人は・・・。")
         (wait)
         (text-reset 1)
         (text
          "［シーラ］止めてコール！！　嘘よ、あの事件は終わったのよ！！　　　　　クーガーさんの蘇生薬を知っているのは、私達二人しか　　　　　居ないわ！　そうでしょ！？")
         (wait)
         (text-reset 1)
         (text
          "［コール］そうだ・・・。確かに２年前、俺がグールを倒して蘇生　　　　　薬の事を知っている人間は居なくなった。なら・・なら　　　　　どうしてその薬がここにあるんだよ！！")
         (wait)
         (text-reset 1)
         (text "［シーラ］知らないっ！")
         (set-reg 132 #t)
         (wait)
         (text-reset 1))))
   (exec-mem 3744 3 "P" 32768)
   (text-color 15)
   (seg-call)))
 (seg (? (= P 5) (= 132 #t) (= 133 #f))
   (text "［シーラ］どうするの？")
   (wait)
   (text-reset 1)
   (text "［コール］ちょっと頭部を調べさせてもらう。")
   (wait)
   (text-reset 1)
   (text "［シーラ］・・・・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］やっぱりそうだ・・・髪の毛ごと喰い千切られてるよ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］なんて事・・・。")
   (set-reg 133 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 132 #t))
   (text "［コール］確かにその位やられてないと、これだけ酷い出血はしな　　　　　いだろうな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］かじられてるの？")
   (wait)
   (text-reset 1)
   (text "［コール］ああ・・・。")
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 121 #f))
   (text "［コール］これがテリーか・・・。何かとてつもない恐怖に脅えて　　　　　いる表情だな。一体何を見たんだろう・・・？")
   (wait)
   (text-reset 1)
   (text "［シーラ］テリーの目が怖いわ・・・。")
   (set-reg 121 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 122 #f))
   (text "［コール］かなりの出血だな・・・。普通ならこれだけでも、出血　　　　　多量で死んでしまうだろうな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］どこかに傷はあるの？")
   (wait)
   (text-reset 1)
   (text "［コール］見た所、頭部に損傷があるが・・・壁にでもブチあてら　　　　　れたか・・・。")
   (set-reg 122 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 123 #f))
   (text "［コール］血はまだ固まっていないな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］二人が部屋から出て行って、ほんの１０数分しか経って　　　　　いないわよね・・・だけど変ね。")
   (wait)
   (text-reset 1)
   (text "［コール］何が？")
   (wait)
   (text-reset 1)
   (text "［シーラ］普通これだけ殺られるまでに、誰かを助けに呼ぼうと叫　　　　　んだりしないものかしら？")
   (wait)
   (text-reset 1)
   (text "［コール］そう言えばそうだな・・・。こんなひっそりと静まり返　　　　　った場所で叫べば、間違いなく俺達に聞こえるからな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］・・・だけど、叫び声どころか大きな物音もなかった。")
   (wait)
   (text-reset 1)
   (text "［コール］これは犯人は一人じゃないな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］どうして？")
   (wait)
   (text-reset 1)
   (text
    "［コール］不意打ちを食らったにしても、絶対もう一人が声を出す　　　　　筈だろ？　二人揃って声も出さないで死んだとなると、　　　　　二人を同時に襲ったとしか考えられないよ。")
   (set-reg 123 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "［コール］さっきまで楽しそうに話していたのが嘘のようだな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］・・・・・・。")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 132 #t) (= 134 #f))
   (text "［コール］やはりリンは頭を殺られているようだ・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］どうして今頃になって蘇生薬が？")
   (wait)
   (text-reset 1)
   (text "［コール］それは判らない・・・。だが、俺達の他に蘇生薬の事を　　　　　知っている人間がいたっていう事だ。")
   (set-reg 134 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 132 #t))
   (text "［シーラ］犯人は死霊なの？")
   (wait)
   (text-reset 1)
   (text "［コール］多分な・・・でなきゃ、頭をかじったりしないだろう。")
   (wait)
   (text-reset 1)
   (text "［シーラ］もし、死霊がここを出て行ったとなると大通りに居た人　　　　　はパニックになっているわ。")
   (wait)
   (text-reset 1)
   (text "［コール］確かにな・・・だが、ここからの様子では大通りはいつ　　　　　もと変わらない。皆は死霊に気付いていないようだな。")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 124 #f))
   (text "［コール］あそこに倒れているのがリンだな・・・。しかし、相手　　　　　は女の子だぜ？　少しは手加減すればいいものを・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］犯人は最初から二人を殺そうと思っていたのよ。でなけ　　　　　れば、こんなに酷い事をする筈がないわ。")
   (set-reg 124 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 125 #f))
   (text "［シーラ］リン・・・せっかくテリーとうまくいってたのに・・。")
   (wait)
   (text-reset 1)
   (text "［コール］ああ、そうだったな。なんか、そう思うと可哀想になっ　　　　　てきたな。")
   (set-reg 125 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 126 #f))
   (text "［コール］暴行されたり、何か持ち去ったような形跡はないようだ　　　　　な。")
   (wait)
   (text-reset 1)
   (text "［シーラ］まさか・・・。リンが襲われたらテリーがダマってない　　　　　と思うわ。それに誰かに襲われたら助けを呼ぶ筈よ。")
   (wait)
   (text-reset 1)
   (text "［コール］それもそうだな。犯人は明らかに殺しが目的のようだ。")
   (set-reg 126 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "［コール］しかし、一体誰がこんな事を・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］酷すぎるわ。")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 132 #t) (= 135 #f))
   (text "［コール］シーラ、この壁を良く見てみろよ。点々と蘇生薬の痕が　　　　　残っている。")
   (wait)
   (text-reset 1)
   (text "［シーラ］でも、どうしてこんなに付いているの？　元々蘇生薬は　　　　　体内に注射されるものでしょ？")
   (wait)
   (text-reset 1)
   (text
    "［コール］相手が死霊なら理由が付けられるよ。大量に蘇生薬を食　　　　　らった死霊なら、歩いただけでもこうして少しずつ流れ　　　　　出てしまうだろ。")
   (set-reg 135 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 132 #t))
   (text "［シーラ］しかし、どうしてこんな所に死霊が・・・？")
   (wait)
   (text-reset 1)
   (text "［コール］・・・・・・・・・。")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 127 #f))
   (text
    "［コール］この路地を使う奴と言ったら、俺のアパートの住人位な　　　　　ものだ。それに、こんな夜中に好き好んで薄気味悪い路　　　　　地に入る奴は、常識から考えてまず居ないだろうな。")
   (set-reg 127 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 128 #f))
   (text "［コール］壁にはたくさんの貼り紙が目に付くな。こんな所に貼っ　　　　　ても目にはつかないと思うが・・・。")
   (set-reg 128 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 129 #f))
   (text
    "［コール］ここは昼間でも建物の陰で薄暗い。大通りからは、真っ　　　　　暗でこちらの様子が見えないんだ。だから、ここで何が　　　　　起こっても目撃される心配はまずないだろう。")
   (wait)
   (text-reset 1)
   (text "［コール］ましてや、こんな夜中なら尚更だぜ。")
   (set-reg 129 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "［コール］辺りには二人の血痕と思われる跡が残っている。生々し　　　　　い現場だな。")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 132 #t))
   (text "［コール］死霊を見たら、まず街の人はパニクるだろうな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］そうよね・・・。だけど車の音も聞こえるし、大通りは　　　　　いつもと変わらないわ。")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 130 #f))
   (text "［コール］あそこまで行けば大通りだが、向こうからはこちらの様　　　　　子は薄暗くてまず見えないだろう。")
   (set-reg 130 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 131 #f))
   (text "［シーラ］犯人はきっと向こうへ逃げて行ったのね。")
   (wait)
   (text-reset 1)
   (text
    "［コール］間違いないだろう。後ろの壁は登って行ける程、低くな　　　　　いからな。だが、大通りへ逃げたとなると、犯人を捕ま　　　　　えるのは難しいぞ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］大通りは夜中でも栄えているからね。")
   (set-reg 131 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))
   (text "［コール］くそっ、どうして俺はこんなアパートに越してきたんだ　　　　　ろう・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］アパートのせいでもコールのせいでもないわ。")
   (wait)
   (text-reset 1))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))