(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB006.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 49 8 56 13)
  (exec-mem 3744 1 6 17 12 25 15)
  (exec-mem 3744 1 7 12 9 17 11)
  (exec-mem 3744 1 8 23 8 28 10)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB006.GPC")
  (image-mem 1 3)
  (if (</>
       (// (? (= 120 #f)) (image-file "B:¥GPC¥DB007.GPC") (image-mem 1 3))))
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC")
  (image-mem 1 0)
  (image-file "B:¥GPC¥DB009C.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (sound '|se | 3)
  (text-frame 15 298 74 356)
  (if (</>
       (//
        (? (= 132 #t))
        (text "Cole: Why would there be reanimation serum in a place like" 'br)
(text "this!?")
        (wait)
        (text-reset 1))
       (//
        (? (= 120 #f))
        (text "Cole: Lynn... Terry...!")
        (wait)
        (text-reset 1)
        (text "Sheila: Cole...")
        (wait)
        (text-reset 1)
        (text "Cole: Jesus... What happened here!?")
        (wait)
        (text-reset 1)
        (text "Sheila: I don't know... When I came down the stairs...")
        (wait)
        (text-reset 1)
        (text "Cole: Is he...dead?")
        (wait)
        (text-reset 1)
        (text "Sheila: I...I...")
        (wait)
        (text-reset 1)
        (text "Cole: Sheila...")
        (wait)
        (text-reset 1)
        (text "Sheila: Terry and Lynn are both dead?")
        (wait)
        (text-reset 1)
        (text "Cole: They've been beaten so badly...")
        (wait)
        (text-reset 1)
        (text "Sheila: What the hell...")
        (wait)
        (text-reset 1)
        (text "Cole: They both left my room ten minutes ago...did it happen" 'br)
(text "then?")
        (wait)
        (text-reset 1)
        (text "Sheila: Were...were they being targeted?")
        (wait)
        (text-reset 1)
        (text "Cole: I don't know...but Terry and Lynn wouldn't ever try to" 'br)
(text "hurt anyone.")
        (wait)
        (text-reset 1)
        (text "Sheila: They really wouldn't...")
        (wait)
        (text-reset 1)
        (text "Cole: Shit... Who could have done this to them?")
        (wait)
        (text-reset 1)
        (text "Sheila: Should we call the police?")
        (wait)
        (text-reset 1)
        (text "Cole: Wait..let me search the area first. If I can find any" 'br)
(text "kind of clue that might point towards a culprit...")
        (wait)
        (text-reset 1)
        (text
         "Sheila: It's too dangerous! Leave it to the cops. And if" 'br)
"someone else reports us here, they might think we were" 'br)
"responsible...")
        (wait)
        (text-reset 1)
        (text
         "Cole: I can't forgive whoever did this to my best friends!" 'br)
"And there's no reason anyone would be here. Nobody would" 'br)
"even notice if you did some vandalism back here...")
        (set-reg 120 #t)
        (wait)
        (text-reset 1)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (image-file "B:¥GPC¥DB006.GPC")
        (image-mem 1 3)
        (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50))))
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
  (sound '|| 1)
  (loop
   (if (</>
        (//
         (? (= 133 #t) (= 134 #t) (= 135 #t))
         (text "Cole: Was someone trying to lure me out...?")
         (wait)
         (text-reset 1)
         (text "Sheila: What!?")
         (wait)
         (text-reset 1)
         (text "Cole: Someone killed our friends in front of my apartment," 'br)
(text "and there are traces of the reanimation serum everywhere.")
         (wait)
         (text-reset 1)
         (text
          "Sheila: You're overthinking it! This is what you wanted when" 'br)
"you started searching for clues, isn't it? If you'd just" 'br)
"called the cops, you wouldn't have gotten caught up in" 'br)
"this...")
         (wait)
         (text-reset 1)
         (text "Cole: Maybe...")
         (wait)
         (text-reset 1)
         (text "Sheila: Cole, you're overanalyzing things!")
         (wait)
         (text-reset 1)
         (text "Cole: ...")
         (wait)
         (text-reset 1)
         (text "Sheila: Cole...")
         (wait)
         (text-reset 1)
         (text "Cole: ...Sheila, I have something to ask you...")
         (wait)
         (text-reset 1)
         (text "Sheila: No, Cole!")
         (wait)
         (text-reset 1)
         (text "Cole: I just can't sit back and pretend like this didn't" 'br)
(text "happen!")
         (wait)
         (text-reset 1)
         (text "Sheila: But tomorrow was our very first trip...we got" 'br)
(text "tickets...and you bought me a new bag...")
         (wait)
         (text-reset 1)
         (text "Cole: Sheila, you need to understand. Doc saved me during" 'br)
(text "the incident two years ago. That's why I'm still here.")
         (wait)
         (text-reset 1)
         (text "Sheila: But...")
         (wait)
         (text-reset 1)
         (text "Cole: If I don't do anything, he would have died for" 'br)
(text "nothing.")
         (wait)
         (text-reset 1)
         (text
          "Cole: I don't know who, but someone out there is using Doc's" 'br)
"reanimation serum. I can't just ignore that.")
         (wait)
         (text-reset 1)
         (text
          "Cole: If I leave things as they are, the damage is only" 'br)
"going to spread. And I'd be letting down Terry and" 'br)
"Lynn...who loved and supported us...")
         (wait)
         (text-reset 1)
         (text "Sheila: ...")
         (wait)
         (text-reset 1)
         (text "Cole: Sheila, please. The gun you had from back then...")
         (wait)
         (text-reset 1)
         (text "Sheila: You don't have to spell it out. I know you better" 'br)
(text "than anyone, Cole.")
         (wait)
         (text-reset 1)
         (text "Sheila: I'll go get the gun. You wait here.")
         (wait)
         (text-reset 1)
         (text
          "Cole: I know Sheila wanted me to stop. But I can't back down" 'br)
"after seeing how far things have gone...")
         (wait)
         (text-reset 1)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (image-file "B:¥GPC¥DB008.GPC")
         (image-mem 1 1)
         (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
         (text "Sheila: It's got three rounds. Don't go around shooting like" 'br)
(text "a crazy person and get arrested.")
         (wait)
         (text-reset 1)
         (exec-mem 912 "PUT 0 54 38,W 0,O 0")
         (text "Sheila: Here. Take it.")
         (wait)
         (text-reset 1)
         (text "Cole: Thanks. Wait for me, I'll be right back.")
         (wait)
         (text-reset 1)
         (exec-mem 912 "PUT 1 54 38,W 0,O 1")
         (exec-mem 912 "EXIT")
         (sound '|| 2)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (mes-jump "A:¥MES¥003.MES"))
        (//
         (? (= 123 #t) (= 126 #t) (= 129 #t) (= 131 #t) (= 132 #f))
         (text "Sheila: Cole, I've been wondering...what are those weird" 'br)
(text "spatters on the ground?")
         (wait)
         (text-reset 1)
         (text "Cole: I don't know, moss, maybe? That kind of thing can be" 'br)
(text "bioluminescent...")
         (wait)
         (text-reset 1)
         (text "Sheila: No, that's not it...")
         (wait)
         (text-reset 1)
         (text "Cole: If it's not moss, what could it be? Let's see.")
         (wait)
         (text-reset 1)
         (text "Sheila: What is it? Does it have a smell?")
         (wait)
         (text-reset 1)
         (text "Cole: Oh my god. This is...")
         (wait)
         (text-reset 1)
         (text "Sheila: What's wrong! You look like you've seen a ghost...")
         (wait)
         (text-reset 1)
         (text "Cole: It's the reanimation serum...")
         (wait)
         (text-reset 1)
         (text "Sheila: No way, you're kidding!")
         (wait)
         (text-reset 1)
         (text "Cole: There's no mistaking it. It smells strong...exactly" 'br)
(text "the same as the stuff Doc made two years ago. I'll never" 'br)
(text "forget it.")
         (wait)
         (text-reset 1)
         (text "Sheila: Why!? How could something like that wind up here?")
         (wait)
         (text-reset 1)
         (text "Cole: I don't know... Wait! Could it be...these two...")
         (wait)
         (text-reset 1)
         (text
          "Sheila: Cole, stop! That's a lie, the incident's all over!" 'br)
"We're the only people left who know about Doctor Cooger's" 'br)
"reanimation serum! Right!?")
         (wait)
         (text-reset 1)
         (text
          "Cole: That's right...two years ago after I defeated Ghoul," 'br)
"there isn't anyone left who knew about the serum...but how" 'br)
"is this here!?")
         (wait)
         (text-reset 1)
         (text "Sheila: How would I know!?")
         (set-reg 132 #t)
         (wait)
         (text-reset 1))))
   (exec-mem 3744 3 "P" 32768)
   (text-color 15)
   (seg-call)))
 (seg (? (= P 5) (= 132 #t) (= 133 #f))
   (text "Sheila: What are we going to do?")
   (wait)
   (text-reset 1)
   (text "Cole: Let me take a closer look at his head...")
   (wait)
   (text-reset 1)
   (text "Sheila: ...")
   (wait)
   (text-reset 1)
   (text "Cole: So that's how it is...his scalp's been torn off, and" 'br)
(text "his brain is...")
   (wait)
   (text-reset 1)
   (text "Sheila: What the hell...")
   (set-reg 133 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 132 #t))
   (text "Cole: He took a real hit, so that explains the blood...")
   (wait)
   (text-reset 1)
   (text "Sheila: His scalp's really been...chewed off?")
   (wait)
   (text-reset 1)
   (text "Cole: Yeah...")
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 121 #f))
   (text "Cole: That's Terry...his eyes still have an expression of" 'br)
(text "terror. Just what was the last thing he saw...?")
   (wait)
   (text-reset 1)
   (text "Sheila: Terry's eyes are scary...")
   (set-reg 121 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 122 #f))
   (text "Cole: He bled out. That amount of blood loss would kill" 'br)
(text "anyone...")
   (wait)
   (text-reset 1)
   (text "Sheila: What are the wounds?")
   (wait)
   (text-reset 1)
   (text "Cole: It looks like his head. He might have been slammed" 'br)
(text "into the wall...")
   (set-reg 122 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 123 #f))
   (text "Cole: And the blood still hasn't clotted.")
   (wait)
   (text-reset 1)
   (text "Sheila: It's only been ten minutes since they left the" 'br)
(text "room...but that IS peculiar.")
   (wait)
   (text-reset 1)
   (text "Cole: What is?")
   (wait)
   (text-reset 1)
   (text "Sheila: If someone were getting attacked like that, wouldn't" 'br)
(text "they have screamed for help?")
   (wait)
   (text-reset 1)
   (text "Cole: Now that you mention it, in a place as quiet as this," 'br)
(text "we should have heard it.")
   (wait)
   (text-reset 1)
   (text "Sheila: But there was no scream...there was no sound at all.")
   (wait)
   (text-reset 1)
   (text "Cole: That means the culprit wasn't acting alone.")
   (wait)
   (text-reset 1)
   (text "Sheila: How do you figure?")
   (wait)
   (text-reset 1)
   (text
    "Cole: If those two got ambushed, one of them would have" 'br)
"screamed, right? If both died without a sound, someone" 'br)
"attacked them at the same time.")
   (set-reg 123 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "Cole: It looks like the good times we had are just memories" 'br)
(text "now...")
   (wait)
   (text-reset 1)
   (text "Sheila: ...")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 132 #t) (= 134 #f))
   (text "Cole: Just like I feared. Lynn's head is totally caved in.")
   (wait)
   (text-reset 1)
   (text "Sheila: Why...why would the reanimation serum be here now?")
   (wait)
   (text-reset 1)
   (text "Cole: I don't know...but that means someone aside from us" 'br)
(text "knows about it.")
   (set-reg 134 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 132 #t))
   (text "Sheila: Could the culprit be...the undead?")
   (wait)
   (text-reset 1)
   (text "Cole: Probably...you don't see many other people gnawing on" 'br)
(text "heads.")
   (wait)
   (text-reset 1)
   (text "Sheila: If it was really a...zombie, people on the street" 'br)
(text "would be freaking out.")
   (wait)
   (text-reset 1)
   (text "Cole: That's true, but it doesn't look like anything's" 'br)
(text "different from usual. It doesn't look like everyone's on" 'br)
(text "zombie alert.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 124 #f))
   (text "Cole: Lynn lying down over there...she's just a girl... They" 'br)
(text "should have taken it easier on her, you know?")
   (wait)
   (text-reset 1)
   (text "Sheila: The culprits must have planned on killing them both." 'br)
(text "Otherwise they wouldn't have taken it so far...")
   (set-reg 124 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 125 #f))
   (text "Sheila: Lynn... you and Terry were doing so well together...")
   (wait)
   (text-reset 1)
   (text "Cole: It's true. I feel so sorry for her...")
   (set-reg 125 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 126 #f))
   (text "Cole: There's no signs of a struggle or anything stolen.")
   (wait)
   (text-reset 1)
   (text "Sheila: It isn't possible... If someone attacked Lynn, Terry" 'br)
(text "wouldn't have stood for it. He would have called out for" 'br)
(text "help.")
   (wait)
   (text-reset 1)
   (text "Cole: That's true. The culprit was deadset on killing them.")
   (set-reg 126 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "Cole: But just who could have done such a thing...")
   (wait)
   (text-reset 1)
   (text "Sheila: It's too awful!")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 132 #t) (= 135 #f))
   (text "Cole: Sheila, take a look at this wall. There's traces of" 'br)
(text "the reanimation serum all over it.")
   (wait)
   (text-reset 1)
   (text "Sheila: But why is it there? The serum's supposed to be" 'br)
(text "administered via injection, isn't it?")
   (wait)
   (text-reset 1)
   (text
    "Cole: A zombie would explain it. If a reanimated corpse were" 'br)
"shambling around, the serum would be oozing out of" 'br)
"it...right?")
   (set-reg 135 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 132 #t))
   (text "Sheila: But why would a zombie be here?")
   (wait)
   (text-reset 1)
   (text "Cole: ...")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 127 #f))
   (text
    "Cole: Anyone using this alley would live here. And who in" 'br)
"their right mind would come into this alley in the middle of" 'br)
"the night?")
   (set-reg 127 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 128 #f))
   (text "Cole: There's a lot of notices posted on the walls, not that" 'br)
(text "they'd really get anyone's attention.")
   (set-reg 128 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 129 #f))
   (text
    "Cole: The building's shadow makes this place dark even" 'br)
"during the daytime. You can't see anything that's going on" 'br)
"from the street. Nobody would see what went on here.")
   (wait)
   (text-reset 1)
   (text "Cole: Especially at this hour of the night.")
   (set-reg 129 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "Cole: You can see the bloodstains from those two... It's" 'br)
(text "gruesome.")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 132 #t))
   (text "Cole: If a zombie got spotted, everyone would lose their" 'br)
(text "minds.")
   (wait)
   (text-reset 1)
   (text "Sheila: Right...but I still hear cars passing by, and Main" 'br)
(text "Street looks the same as always.")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 130 #f))
   (text "Cole: Over there's Main Street, but it's so dark here that" 'br)
(text "nobody would be able to see.")
   (set-reg 130 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 131 #f))
   (text "Sheila: The culprit must have fled that way.")
   (wait)
   (text-reset 1)
   (text
    "Cole: Right. The wall's too high to climb. If they headed" 'br)
"towards Main Street, it might be hard to catch up.")
   (wait)
   (text-reset 1)
   (text "Sheila: Main Street is bustling even at night.")
   (set-reg 131 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))
   (text "Cole: Dammit, why did I move into an apartment like this?")
   (wait)
   (text-reset 1)
   (text "Sheila: Don't blame yourself...or the apartment, Cole.")
   (wait)
   (text-reset 1))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))