(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
         (text "Cole: Was someone trying to lure me out...?")
         (wait)
         (text-reset 1)
         (text "Sheila: What!?")
         (wait)
         (text-reset 1)
         (text "Cole: Someone killed our friends in front of my apartment," 'br)
        (text "and there are traces of the reanimation serum everywhere.")
         (wait)
         (text-reset 1)
         (text "Sheila: You're overthinking it! This is what you wanted" 'br)
         (text "when you started searching for clues, isn't it? If you'd" 'br)
         (text "just called the cops, you wouldn't have gotten caught up in" 'br)
         (text "this...")
         (wait)
         (text-reset 1)
         (text "Cole: Maybe...")
         (wait)
         (text-reset 1)
         (text "Sheila: Cole, you're overanalyzing things!")
         (wait)
         (text-reset 1)
         (text "Cole: ...")
         (wait)
         (text-reset 1)
         (text "Sheila: Cole...")
         (wait)
         (text-reset 1)
         (text "Cole: ...Sheila, I have something to ask you...")
         (wait)
         (text-reset 1)
         (text "Sheila: No, Cole!")
         (wait)
         (text-reset 1)
         (text "Cole: I just can't sit back and pretend like this didn't" 'br)
         (text "happen!")
         (wait)
         (text-reset 1)
         (text "Sheila: But tomorrow was our very first trip...we got" 'br)
         (text "tickets...and you bought me a new bag...")
         (wait)
         (text-reset 1)
         (text "Cole: Sheila, you need to understand. Doc saved me during" 'br)
         (text "the incident two years ago. That's why I'm still here.")
         (wait)
         (text-reset 1)
         (text "Sheila: But...")
         (wait)
         (text-reset 1)
         (text "Cole: If I don't do anything, he would have died for" 'br)
         (text "nothing.")
         (wait)
         (text-reset 1)
         (text "Cole: I don't know who, but someone out there is using" 'br)
         (text "Doc's reanimation serum. I can't just ignore that.")
         (wait)
         (text-reset 1)
         (text "Cole: If I leave things as they are, the damage is only" 'br)
         (text "going to spread. And I'd be letting down Terry and" 'br)
         (text "Lynn...who loved and supported us...")
         (wait)
         (text-reset 1)
         (text "Sheila: ...")
         (wait)
         (text-reset 1)
         (text "Cole: Sheila, please. The gun you had from back then...")
         (wait)
         (text-reset 1)
         (text "Sheila: You don't have to spell it out. I know you better" 'br)
         (text "than anyone, Cole.")
         (wait)
         (text-reset 1)
         (text "Sheila: I'll go get the gun. You wait here.")
         (wait)
         (text-reset 1)
         (text "Cole: I know Sheila wanted me to stop. But I can't back" 'br)
         (text "down after seeing how far things have gone...")
         (wait)
         (text-reset 1)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (image-file "B:¥GPC¥DB008.GPC")
         (image-mem 1 1)
         (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
         (text "Sheila: It's got three rounds. Don't go around shooting" 'br)
         (text "like a crazy person and get arrested.")
         (wait)
         (text-reset 1)
         (exec-mem 912 "PUT 0 54 38,W 0,O 0")
         (text "Sheila: Here. Take it.")
         (wait)
         (text-reset 1)
         (text "Cole: Thanks. Wait for me, I'll be right back.")
         (wait)
         (text-reset 1)
         (exec-mem 912 "PUT 1 54 38,W 0,O 1")
         (exec-mem 912 "EXIT")
         (sound '|| 2)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (mes-jump "A:¥MES¥003.MES"))
 (seg*))