; Dead of the Brain 2 (PC-98) - 005.MES
; Translated by Geometrizer
; Edited by trentsignia
; -----Scene:-----
; A Bloody Fox member confronts Cole after he intervenes with his business.
; --Progression:--
; Talk to the big, scary guy.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB012.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)			; Hotspots and buttons defined here...
  (exec-mem 3744 1 1 80 0 0 0)							; 	MOVE button
  (exec-mem 3744 1 2 80 0 0 0)							; 	SYSTEM button
  (exec-mem 3744 1 5 49 9 55 12)						; 	Onlookers
  (exec-mem 3744 1 6 27 4 37 8)							; 	Bloody Fox
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB010.GPC") (image-mem 1 3)
  (image-file "B:¥GPC¥DB012.GPC") (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (if (</>
       (//
        (? (= 156 #f))
        (sound '|| 0)
        (if (</>
             (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
             (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
        (sound '|| 1))))
  (if (</>
       (//
        (? (= 157 #f))								; Lead-in (only from previous MES script)
        (str "B.F.: It's all your fault you let that girl get away," 'br)
        (str "stickin' your nose where it don't belong! I hope you're" 'br)
        (str "ready for the king of all ass-kickings!")
        (set-reg 157 #t)
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 158 #f))							; Onlookers #1
   (str "Cole: Nobody around here will make eye contact with me. I" 'br)
        (str "guess they all know they don't wanna get mixed up with" 'br)
        (str "these guys.")
   (set-reg 158 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))								; Onlookers #2 (repeat line)
   (str "Cole: Everyone's taking a wide berth from us. There aren't" 'br)
   (str "even any gawkers.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 159 #f))							; Bloody Fox #1
   (str "B.F.: You dumbshit, you know we're with Bloody Fox, and" 'br)
   (str "you're still tryin' to pick a fight with us?")
   (wait)
   (text-reset 1)
   (str "Cole: I know who you are. But I'm not here to fight, I just" 'br)
   (str "need to ask you something.")
   (wait)
   (text-reset 1)
   (str "B.F.: Don't fuck with me! Steppin' to us in our own hood" 'br)
   (str "takes real balls, and I'm gonna cut 'em off!")
   (wait)
   (text-reset 1)
   (str "Cole: Oh boy, I've really kicked the hornet's nest now.")
   (wait)
   (text-reset 1)
   (str "B.F.: I'll show you why your dumb ass should be scared of" 'br)
   (str "Bloody Fox!")
   (wait)
   (text-reset 1)
   (str "Cole: Spare me the chest-puffing! If you're gonna make a" 'br)
   (str "move, do it now, grandpa. I ain't waitin' for you!")
   (wait)
   (text-reset 1)
   (str "B.F.: You little shit!")
   (wait)
   (text-reset 1)
   (str "B.F.: Uhhh...")
   (wait)
   (text-reset 1)
   (str "Cole: Huh? What's wrong? Come at me already!")
   (wait)
   (text-reset 1)
   (str "B.F.: Wait a minute. You're packing, aren't you?")
   (wait)
   (text-reset 1)
   (str "Cole: What happened to that swagger? You're giving me an" 'br)
   (str "itchy trigger finger!")
   (wait)
   (text-reset 1)
   (str "B.F.: W-wait! Hold on...I'll tell you anything, just put" 'br)
   (str "that piece away!")
   (wait)
   (text-reset 1)
   (str "Cole: I'll put it away, but make the wrong move and I'll" 'br)
   (str "blast a hole in your guts!")
   (wait)
   (text-reset 1)
   (str "B.F.: Fine, fine!")
   (set-reg 159 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 160 #f))							; Bloody Fox #2
   (str "B.F.: What is it you wanna know?")
   (wait)
   (text-reset 1)
   (str "Cole: You need to tell me what that is, splattered on your" 'br)
   (str "buddy's bike tire.")
   (wait)
   (text-reset 1)
   (str "B.F.: Huh? His tire?")
   (wait)
   (text-reset 1)
   (str "Cole: It's caked all over it. The stuff that looks like" 'br)
   (str "purple paint.")
   (wait)
   (text-reset 1)
   (str "B.F.: Oh, that stuff? Maybe he ran over it when he was" 'br)
   (str "riding... It's just paint, yeah?")
   (set-reg 160 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 161 #f))							; Bloody Fox #3
   (str "Cole: Where could it have happened?")
   (wait)
   (text-reset 1)
   (str "B.F.: I uh, don't know...")
   (wait)
   (text-reset 1)
   (str "Cole: Are you telling me you wanna die?")
   (wait)
   (text-reset 1)
   (str "B.F.: Come on, man! We've been hanging out at the Bayside" 'br)
   (str "Research Lab at the next town over all day, so it coulda" 'br)
   (str "happened there.")
   (wait)
   (text-reset 1)
   (str "Cole: The Bayside Research Lab! That's where the android" 'br)
   (str "Ghoul was hiding out two years ago!")
   (set-reg 161 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 162 #f))							; Bloody Fox #4
   (str "Cole: But why Bayside... Maybe Ghoul still had an extra" 'br)
   (str "stash of reanimation serum?")
   (wait)
   (text-reset 1)
   (str "B.F.: Bloody Fox owns that place, man.")
   (wait)
   (text-reset 1)
   (str "Cole: I guess there's no choice, I'm gonna go check it out.")
   (wait)
   (text-reset 1)
   (str "B.F.: You're crazy, man... No normal dude would willingly" 'br)
   (str "stroll into a Bloody Fox den. Are you FBI or something?")
   (wait)
   (text-reset 1)
   (str "Cole: Stop asking questions you don't wanna know the answer" 'br)
   (str "to.")
   (set-reg 162 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))								; Bloody Fox #5
   (str "Cole: We had a good chat. We should do this again sometime.")
   (wait)
   (text-reset 1)
   (str "B.F.: Hell no! I never wanna see your mug again!")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB010.GPC") (image-mem 1 3)
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (str "Cole: Right, time to hit the Bayside Research Lab.")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥006.MES"))
 (seg (? (= P 2))								; SYSTEM
   (exec-mem 6064 2 2)
   (menu1
    25 317  39 317  53 317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (nop@) (set-reg 156 #f) (flag-save 1))
        (/ (nop@) (set-reg 156 #f) (flag-save 2))
        (/ (nop@) (set-reg 156 #f) (flag-save 3))
        (/ (nop@) (set-reg 156 #f) (flag-save 4))
        (/ (nop@) (set-reg 156 #f) (flag-save 5))
        (/ (nop@) (set-reg 156 #f) (flag-save 6))
        (/ (nop@) (set-reg 156 #f) (flag-save 7))
        (/ (nop@) (set-reg 156 #f) (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))