(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB004A.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 15 5 24 13)
  (exec-mem 3744 1 6 27 5 36 13)
  (exec-mem 3744 1 7 23 2 40 3)
  (exec-mem 3744 1 8 3 8 7 12)
  (exec-mem 3744 1 9 37 7 47 14)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB003.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB004.GPC")
  (image-mem 1 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC")
  (image-mem 1 0)
  (image-file "B:¥GPC¥DB020C.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (image-file "B:¥GPC¥DB021C.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 2 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 184 #f))
        (text "Sheila: Cole! I've been worried sick about you! Where did you go?")
        (wait)
        (text-reset 1)
        (text "Cole: I'm okay...I've just been through...some stuff.")
        (wait)
        (text-reset 1)
        (text "Sheila: Stuff like what!? You're all beat up!")
        (wait)
        (text-reset 1)
        (text "Cole: I'm fine, it's nothing I can't sleep off.")
        (set-reg 184 #t)
        (wait)
        (text-reset 1))
       (// (text "Cole: I hope I'm not worrying Sheila too much. The bruises aren't helping.") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 185 #f))
   (text "Cole: I see the bodies were moved, at least.")
   (wait)
   (text-reset 1)
   (text
    "Sheila: Someone else must have called it in...right after you made tracks, the police showed up. They wouldn't stop asking me questions, but nobody saw the culprit, so there's not much to go on...")
   (set-reg 185 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 186 #f))
   (text "Sheila: Did you fare any better?")
   (wait)
   (text-reset 1)
   (text
    "Cole: I'm not sure. Bloody Fox is peddling a new drug, and it's got more than a passing resemblance to the reanimation serum.")
   (wait)
   (text-reset 1)
   (text "Sheila: No way, they turned it into a narcotic? Cole, what happens to someone once they're injected with the reanimation serum?")
   (wait)
   (text-reset 1)
   (text
    "Cole: As far as we know, once you get it, you actually die once, and then you get brought back before brain death. And once you're back, you can't die..unless your brain is destroyed.")
   (wait)
   (text-reset 1)
   (text
    "Cole: And someone who's been injected can go on living like before...normal thinking and speaking processes. It basically grants you immortality.")
   (set-reg 186 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 187 #f))
   (text "Sheila: Does that mean Bloody Fox is a gang of immortals!?")
   (wait)
   (text-reset 1)
   (text
    "Cole: Not exactly. I did manage to KO one guy with a punch. If he'd taken the serum, he would have just shrugged it off.")
   (wait)
   (text-reset 1)
   (text "Sheila: What do you mean?")
   (wait)
   (text-reset 1)
   (text "Cole: The splattered substance next to Terry and Lynn's bodies matched a Bloody Fox drug called Purple Sky.")
   (wait)
   (text-reset 1)
   (text "Sheila: But you thought it was the reanimation serum...")
   (wait)
   (text-reset 1)
   (text
    "Cole: Right, the color and smell matched the serum that Doc Cooger made. But Blue Sky doesn't have the full effects of the original reanimation serum.")
   (wait)
   (text-reset 1)
   (text "Sheila: So someone came up with a narcotic that has similarities to Doc's reanimation serum?")
   (wait)
   (text-reset 1)
   (text "Cole: I can't say for certain.")
   (set-reg 187 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 188 #f))
   (text "Cole: Doc used to say that the color of the reanimation serum was super unique and hard to replicate.")
   (wait)
   (text-reset 1)
   (text "Cole: I'm guessing here, but I'm thinking the serum is a component of Purple Sky.")
   (wait)
   (text-reset 1)
   (text
    "Sheila: But I thought we were the only people left alive who know about Doc's serum. How could it resurface now?")
   (wait)
   (text-reset 1)
   (text
    "Cole: Hard to say, but since Bloody Fox has the stuff, we're gonna need to solve the mystery of how they got it... for Doc's sake.")
   (wait)
   (text-reset 1)
   (text "Sheila: There's a lot of Bloody Fox members..and only two of us. We're gonna have to pick our targets.")
   (wait)
   (text-reset 1)
   (text "Cole: You're right.")
   (set-reg 188 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 189 #f))
   (text "Sheila: Do we have anything to go on?")
   (wait)
   (text-reset 1)
   (text "Cole: Now that I think about it, I heard someone mention the name 'Rease'...")
   (wait)
   (text-reset 1)
   (text "Sheila: Rease? Is that a name?")
   (wait)
   (text-reset 1)
   (text "Cole: Yeah, after they made tracks, I found this matchbook.")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 0 54 38,W 0,O 0")
   (text "Sheila: Bar Rease?")
   (wait)
   (text-reset 1)
   (text "Cole: You a regular?")
   (wait)
   (text-reset 1)
   (text "Sheila: Not quite. But there was an article about it in the morning paper. One sec...")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 2 54 38,W 0,O 0")
   (text "Sheila: Ah, here it is.")
   (wait)
   (text-reset 1)
   (text "Cole: Damn! It says here that Bloody Fox member Ben Raymond killed seven of his buddies at Bar Rease...")
   (wait)
   (text-reset 1)
   (text "Cole: And was promptly gunned down by...twenty cops? Holy shit, that's crazy!")
   (wait)
   (text-reset 1)
   (text "Sheila: Gang infighting, you think?")
   (wait)
   (text-reset 1)
   (text "Cole: No, says he was just a junkie...but something still feels off.")
   (wait)
   (text-reset 1)
   (text "Sheila: How do you figure?")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 1 54 38,W 0,O 1")
   (exec-mem 912 "EXIT")
   (text "Cole: How can one junkie take out seven people in a bar without getting subdued? He would have gotten mobbed by everyone else.")
   (wait)
   (text-reset 1)
   (text "Cole: I don't care what drug you're on, someone would have taken you out long before the cops finally showed up.")
   (wait)
   (text-reset 1)
   (text "Sheila: It doesn't make any sense. What went down in there?")
   (set-reg 189 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "Cole: I think we're gonna need to pay Rease a visit.")
   (wait)
   (text-reset 1)
   (text "Sheila: Taking on the big dogs. You sure you'll be okay?")
   (wait)
   (text-reset 1)
   (text "Cole: This is something I'm gonna have to unravel myself.")
   (set-reg 194 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 190 #f))
   (text "Cole: The wall's plastered with the photos and clippings I've pasted up.")
   (set-reg 190 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "Cole: It's more fun to put stuff on the wall instead of filing them away somewhere.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 191 #f))
   (text "Cole: There's a big ol' air conditioner mounted on the ceiling.")
   (set-reg 191 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "Cole: It's starting to get chilly, so I'll need to put the AC to work again.")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 192 #f))
   (text "Cole: Any calls while I was out?")
   (wait)
   (text-reset 1)
   (text "Sheila: None. Sorry.")
   (set-reg 192 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))
   (text "Cole: There's a phone on the wall, but I don't have anyone to call at the moment.")
   (wait)
   (text-reset 1))
 (seg (? (= P 9) (= 193 #f))
   (text "Cole: Did anyone stop by while I was out?")
   (wait)
   (text-reset 1)
   (text "Sheila: Not a soul. Were you expecting someone?")
   (wait)
   (text-reset 1)
   (text "Cole: No, not really.")
   (set-reg 193 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 9))
   (text "Sheila: So are you headed out?")
   (wait)
   (text-reset 1)
   (text "Cole: Not yet. I need to think a little longer.")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 193 #t) (= 194 #t))
   (exec-mem 6064 2 1)
   (text "Cole: Okay, I'm off to Bar Rease.")
   (wait)
   (text-reset 1)
   (text "Sheila: Don't come back in a pine box, Cole.")
   (wait)
   (text-reset 1)
   (text "Cole: I know, I know. I'll be careful.")
   (wait)
   (text-reset 1)
   (sound '|| 2)
   (exec-mem 6064 3)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥010.MES"))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))