(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB004A.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 15 5 24 13)
  (exec-mem 3744 1 6 27 5 36 13)
  (exec-mem 3744 1 7 23 2 40 3)
  (exec-mem 3744 1 8 3 8 7 12)
  (exec-mem 3744 1 9 37 7 47 14)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB003.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB004.GPC")
  (image-mem 1 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC")
  (image-mem 1 0)
  (image-file "B:¥GPC¥DB020C.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (image-file "B:¥GPC¥DB021C.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 2 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 184 #f))
        (text "［シーラ］コール！　心配してたのよ！　一体どこに居たの？")
        (wait)
        (text-reset 1)
        (text "［コール］いや、色々とあってね。")
        (wait)
        (text-reset 1)
        (text "［シーラ］怪我してるじゃない！！")
        (wait)
        (text-reset 1)
        (text "［コール］大丈夫だよ、大した怪我じゃない。")
        (set-reg 184 #t)
        (wait)
        (text-reset 1))
       (// (text "［コール］シーラに心配かけちゃったかな・・・。") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 185 #f))
   (text "［コール］二人の死体は片付いてたな。")
   (wait)
   (text-reset 1)
   (text
    "［シーラ］うん、通報があってね。コールの行った後、すぐに警察　　　　　が来たわ。私も色々と聞かれたけど・・・犯人は見てな　　　　　いし、何も分からないから・・・。")
   (set-reg 185 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 186 #f))
   (text "［シーラ］それで・・・何か分かった？")
   (wait)
   (text-reset 1)
   (text
    "［コール］いや・・・ブラッディフォックスが新しい麻薬を流して　　　　　いるらしいんだよ。それが蘇生薬に非常に良く似ている　　　　　んだ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］そんな・・・蘇生薬が麻薬とされているなんて・・・。　　　　　コール、蘇生薬を打った人間ってどうなるの？")
   (wait)
   (text-reset 1)
   (text
    "［コール］俺が知ってる限りでは、あの蘇生薬を打つと一度死に、　　　　　そして脳死までの間にまた復活する。復活した人間は、　　　　　脳が破壊されるまで二度と死ぬ事はないんだ。")
   (wait)
   (text-reset 1)
   (text
    "［コール］それに、薬を打った人間は今までと同じ様に生活する事　　　　　ができる。言葉も話せるし、普通に考えられるんだから　　　　　な。まさに不死身の身体だよ。")
   (set-reg 186 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 187 #f))
   (text "［シーラ］そしたら、ブラッディフォックスの人間はみんな不死身　　　　　の身体だって事？")
   (wait)
   (text-reset 1)
   (text
    "［コール］いや、それがそうでもないらしいんだ。俺が一人を殴っ　　　　　た時に相手は気を失ったんだ。もし、蘇生薬を打ってい　　　　　たのなら、俺のパンチなんかで気を失う事はないよ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］どういう事？")
   (wait)
   (text-reset 1)
   (text "［コール］テリーとリンの死体の側にあった薬品は、奴等の持って　　　　　いたパープル・スカイと言われる麻薬だったんだよ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］だって、コールは蘇生薬に間違いないって・・・。")
   (wait)
   (text-reset 1)
   (text
    "［コール］うん、確かにあの色と匂いではドクの作った蘇生薬に間　　　　　違いなかった。だけどあの薬は本来の蘇生薬の効能は得　　　　　られない物なんだ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］という事は、誰かが蘇生薬に似ている麻薬を開発したの　　　　　ね。")
   (wait)
   (text-reset 1)
   (text "［コール］いや、そうとも言い切れないよ。")
   (set-reg 187 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 188 #f))
   (text "［コール］ドクが生前に言ってたんだ。どんなカラーを使っても、　　　　　蘇生薬と全く同じ色は出せないってね。")
   (wait)
   (text-reset 1)
   (text "［コール］これは俺の推測だが、蘇生薬がパープル・スカイという　　　　　麻薬の一部に使われているんじゃないかと思うんだ。")
   (wait)
   (text-reset 1)
   (text
    "［シーラ］だけど、考えてみて。クーガーさんの蘇生薬を知ってい　　　　　る人間は、この世の中に私達だけしかいないのよ？　　　　　　　どうして今頃になってクーガーさんの薬が出て来るの？")
   (wait)
   (text-reset 1)
   (text
    "［コール］それは判らない・・・。だけど、ブラッディフォックス　　　　　の連中があの薬を持っている以上、ドクのためにもパー　　　　　プル・スカイの謎を解いておかないといけないよ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］ブラッディフォックスって言っても、あまりにも人数が　　　　　多すぎるわ。手当たり次第って訳にもいかないわよ。")
   (wait)
   (text-reset 1)
   (text "［コール］それもそうだ・・・。")
   (set-reg 188 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 189 #f))
   (text "［シーラ］何か手掛かりはないの？")
   (wait)
   (text-reset 1)
   (text "［コール］手掛かりね・・・あっ、そういえば奴等がリーズがどう　　　　　のって言ってたな・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］リーズ？　何かの名前？")
   (wait)
   (text-reset 1)
   (text "［コール］ああ、奴等が立ち去った場所にこのマッチが落ちてたん　　　　　だ。")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 0 54 38,W 0,O 0")
   (text "［シーラ］バー・リーズ！？")
   (wait)
   (text-reset 1)
   (text "［コール］知ってるのか？")
   (wait)
   (text-reset 1)
   (text "［シーラ］そういえば今日の朝刊に記事が載ってたわ・・ちょっと　　　　　まってて。")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 2 54 38,W 0,O 0")
   (text "［シーラ］あったわ・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］なになに・・・ブラッディフォックスのメンバー『ベン　　　　　・レイモンド』バー・リーズで仲間を７人殺害か・・。")
   (wait)
   (text-reset 1)
   (text "［コール］包囲していた２０人の警官に射殺され即死か・・完全に　　　　　イカれてるな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］仲間割れ？")
   (wait)
   (text-reset 1)
   (text "［コール］いや、この男ヤク中らしいな。だけど、どうも変だな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］なにが？")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 1 54 38,W 0,O 1")
   (exec-mem 912 "EXIT")
   (text "［コール］だって、たった一人でリーズで７人も殺しているんだ。　　　　　誰か彼を取り押さえる事はできなかったのか？")
   (wait)
   (text-reset 1)
   (text "［コール］いくらヤク中だって、それだけの人間に押さえつけられ　　　　　たら抵抗できないだろ？")
   (wait)
   (text-reset 1)
   (text "［シーラ］そう言われてみればそうよね・・・なぜかしら？")
   (set-reg 189 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "［コール］とにかく一度リーズに行ってみた方がいいな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］相手は大組織よ、大丈夫なの？")
   (wait)
   (text-reset 1)
   (text "［コール］こればっかりは、俺自身ハッキリさせたいんだ。")
   (set-reg 194 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 190 #f))
   (text "［コール］壁には俺の貼り付けた写真や雑誌の切り抜きが貼ってあ　　　　　る。")
   (set-reg 190 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "［コール］俺は切り抜きをファイルに挟んでしまっておくより、こ　　　　　うして壁に貼っておくのが好きなんだ。")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 191 #f))
   (text "［コール］天井に大型のエアコンが設置されている。")
   (set-reg 191 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "［コール］そろそろ寒くなってきたし、またこいつの世話になるだ　　　　　ろうな。")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 192 #f))
   (text "［コール］俺の居ない間に電話はなかったか？")
   (wait)
   (text-reset 1)
   (text "［シーラ］ええ、ないわよ。")
   (set-reg 192 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))
   (text "［コール］電話が壁に設置されている。今はどこにもかける必要も　　　　　ないな。")
   (wait)
   (text-reset 1))
 (seg (? (= P 9) (= 193 #f))
   (text "［コール］俺の居ない間に誰か来たか？")
   (wait)
   (text-reset 1)
   (text "［シーラ］ううん、誰も来てないけど・・・誰か来るの？")
   (wait)
   (text-reset 1)
   (text "［コール］いや、そうじゃないけどね。")
   (set-reg 193 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 9))
   (text "［シーラ］どこかへ出掛けるの？")
   (wait)
   (text-reset 1)
   (text "［コール］いや、もう少し考えてからにしよう。")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 193 #t) (= 194 #t))
   (exec-mem 6064 2 1)
   (text "［コール］よし、バー・リーズに行ってみよう。")
   (wait)
   (text-reset 1)
   (text "［シーラ］心配だから早く帰ってきてね。")
   (wait)
   (text-reset 1)
   (text "［コール］分かってるよ。")
   (wait)
   (text-reset 1)
   (sound '|| 2)
   (exec-mem 6064 3)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥010.MES"))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))