; Dead of the Brain 2 (PC-98) - 012.MES
; Translated by Geometrizer
; Edited by trentsignia
; -----Scene:-----
; Cole approaches the Bloody Fox table at Bar Rease.
; --Progression:--
; Inspect everything, then look at the woman, then talk to Briar.
; ----Battle:-----
; 1. Shoot Left Bloody Fox.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB025.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)			; Hotspots and buttons defined here...
  (exec-mem 3744 1 1 80 0 0 0)							; 	MOVE button
  (exec-mem 3744 1 2 80 0 0 0)							; 	SYSTEM button
  (exec-mem 3744 1 5 18 11 45 13)						;	Table
  (exec-mem 3744 1 6 29 3 34 6)							; 	Woman
  (exec-mem 3744 1 7 39 2 45 5)							; 	Briar
  (exec-mem 3744 1 8 4 4 9 6)							; 	Bloody Fox
  (exec-mem 9920 0 6 6 113 64 0)
  (text-frame 3 24 56 258)
  (text-reset 1)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC") (image-mem 1 0)
  (image-file "B:¥GPC¥DB028C.GPC") (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (image-file "B:¥GPC¥DB024.GPC") (image-mem 0 3)
  (image-file "B:¥GPC¥DB025.GPC") (image-mem 1 3)
  (exec-mem 15456 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  ((cmd 193) 0 "B:¥GPA¥DB026.GPA")
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (text-frame 15 298 74 356)
  (if (</>
       (//
        (? (= 215 #f))								; Lead-in from previous MES script
        (str "Cole: I don't think these guys are gonna roll over and give" 'br)
        (str "me the information I need...")
        (wait)
        (text-reset 1)
        (str "B.F.: Huh? Hey you, what are you sayin' to yourself over" 'br)
        (str "there?")
        (set-reg 215 #t)
        (wait)
        (text-reset 1))
       (//
        (str "B.F.: You gotta problem with us? Looking to start some shit?")	; Lead-in from loading game
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 216 #f))							; Table #1
   (str "Cole: That's a filthy table. Cigarette ashes have escaped" 'br)
   (str "the ashtrays and are covering just about every surface" 'br)
   (str "available.")
   (set-reg 216 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 217 #f))							; Table #2
   (str "Cole: I see vinyl baggies and syringes on the table..." 'br)
   (str "These dudes are the opposite of subtle. That's gotta be" 'br)
   (str "Purple Sky.")
   (set-reg 217 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))								; Table #3 (repeat line)
   (str "B.F.: Why don't you take a picture? It'll last longer.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 222 #t) (= 223 #t) (= 219 #t) (= 217 #t) (= 224 #f))	; Woman (after inspecting everything) #1
   (str "Woman: What's wrong, babe? You want something from me?")
   (wait)
   (text-reset 1)
   (str "B.F.: Leave her alone, she's drunk. People like her don't" 'br)
   (str "learn until they have it beaten into 'em.")
   (wait)
   (text-reset 1)
   (str "Woman: Hee hee... Briar, you're so naughty.")
   (wait)
   (text-reset 1)
   (str "Briar: Yeah, that's right. When Bloody Fox doesn't demand" 'br)
   (str "respect, that's when we're finished as a gang.")
   (wait)
   (text-reset 1)
   (str "Cole: So Briar there is the leader, huh?")
   (set-reg 224 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 222 #t) (= 223 #t) (= 219 #t) (= 217 #t) (= 225 #f))	; Woman (after inspecting everything) #2
   (str "Woman: This boy's persistent.")
   (wait)
   (text-reset 1)
   (str "Briar: Don't let it bother you. You need another hit? Here" 'br)
   (str "ya go.")
   (wait)
   (text-reset 1)
   (str "Woman: Hee hee... Appreciated, sweetie.")
   (wait)
   (text-reset 1)
   (str "Cole: No doubt about it, Briar just slipped her some junk" 'br)
   (str "that was the same color as the reanimation serum.")
   (set-reg 225 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 222 #t) (= 223 #t) (= 219 #t) (= 217 #t))			; Woman (after inspecting everything) #3 (repeat line)
   (str "Cole: That's gotta be Purple Sky. It's up to me to make the" 'br)
   (str "connection between it and Doc's serum.")
   (set-reg 226 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 218 #f))							; Woman #1
   (str "Cole: Heh... So Bloody Fox has its share of female members.")
   (set-reg 218 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 219 #f))							; Woman #2
   (str "Cole: She looks like she's in deep with the guy sitting" 'br)
   (str "next to her. Could that other guy be the leader?")
   (set-reg 219 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))								; Woman #3 (repeat line)
   (str "Cole: She looks like she's all over the place, mentally." 'br)
   (str "Probably a junkie.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 226 #t))							; Briar (after noticing Purple Sky)
   (str "Cole: Hey, did you just slip her some Purple Sky?")
   (wait)
   (text-reset 1)
   (str "Briar: So what if I did?")
   (wait)
   (text-reset 1)
   (str "Cole: Can I ask you about the incident yesterday?")
   (wait)
   (text-reset 1)
   (str "Briar: Don't know nothin' about no incidents.")
   (wait)
   (text-reset 1)
   (str "Cole: It was in the paper this morning and it's been the" 'br)
   (str "talk of the town. Don't play dumb with me.")
   (wait)
   (text-reset 1)
   (str "Briar: If I don't know, I don't know. And if YOU know" 'br)
   (str "what's good for you, piss off!")
   (wait)
   (text-reset 1)
   (str "Cole: I'm not here to cause trouble. Tell me, does Ben" 'br)
   (str "Raymond from yesterday's incident have anything to do with" 'br)
   (str "the Purple Sky that's sitting on the table right now?")
   (wait)
   (text-reset 1)
   (str "Briar: How many times do I gotta tell you to fuck off!?")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB024.GPC") (image-mem 1 3)
   (image-file "B:¥GPC¥DB026.GPC") (image-mem 1 3)
   (image-file "A:¥GPC¥COUNTER.GPC")
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (str "Cole: That's it. Don't any of you move, or I'll blow your" 'br)
   (str "heads off.")
   (wait)
   (text-reset 1)
   (str "B.F.: Haw haw haw! There's just one of you. Shoot one of" 'br)
   (str "us, and the rest of us will split your fuckin' skull open!")
   (wait)
   (text-reset 1)
   (str "Cole: I'm only gonna ask one more time!")
   (wait)
   (text-reset 1)
   (sound '|| 0)								; Battle starts here...
   (if (</>
        (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_06.USO"))
        (// (sound '|| "A:¥USO_D¥BR2_06.USO"))))
   (sound '|| 1)
   (str "B.F.: Don't fuck with us!")
   (wait)
   (text-reset 1)
   (load-mem "A:¥CLM¥DB026.CLM" 32768)
   (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 3 2)			; Battle's hotspots defined here
   (exec-mem 3744 1 5 15 4 19 5)						; 	Left Bloody Fox
   (exec-mem 3744 1 6 37 4 41 5)						; 	Right Bloody Fox
   (exec-mem 3744 1 7 80 0 0 0)							; 	???
   (exec-mem 15728 0 0 0 3 0 1)
   (exec-mem 15728 1 0 0 0 0 "Z") (image-mem 0 0)
   (exec-mem 15728 2 1)
   (exec-mem 17408 2)
   (exec-mem 15456 0)
   (exec-mem 14544 2 0)
   (exec-mem 15728 3)
   (exec-mem 3744 3 "P" 32768)
   (exec-mem 15728 4)
   (image-file "A:¥GPC¥DB_FRM3.GPC") (image-mem 0 0)
   (if (</>
        (//
         (? (= P 5) (= Z 2))							; Left Bloody Fox (winning move)
         (sound '|se | 13)
         ((cmd 196) 0 0) (delay 2 0)
         ((cmd 196) 0 1)
         ((cmd 196) 0 2)
         ((cmd 196) 0 3) (delay 8 0)
         (exec-mem 17408 3)
         (exec-mem 256 3 0 11 0)
         (exec-mem 256 4 0 7 0)
         (text-frame 3 24 56 258)
         (text-reset 1)
         (text-frame 15 298 74 356)
         (str "B.F.: You fucker!!!")
         (wait)
         (text-reset 1)
         (exec-mem 14544 2 2)
         (str "Cole: Gah...")
         (wait)
         (text-reset 1)
         (exec-mem 912 "PUT 0 54 38,W 0,O 0")
         (str "Cole: Shit, the gun!")
         (wait)
         (text-reset 1)
         (exec-mem 912 "PUT 1 54 38,W 0,O 1")
         (exec-mem 912 "EXIT")
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (image-file "B:¥GPC¥DB024.GPC") (image-mem 1 3)
         (image-file "B:¥GPC¥DB029.GPC") (image-mem 1 3)
         (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
         (str "B.F.: It's time to waste this little shit!")
         (wait)
         (text-reset 1)
         (str "Man: Wait!")
         (wait)
         (text-reset 1)
         (str "B.F.: Fuck off, not this guy again...!")
         (wait)
         (text-reset 1)
         (str "Briar: Hey hey, what's this all about, Steve?")
         (wait)
         (text-reset 1)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (image-file "B:¥GPC¥DB030.GPC") (image-mem 1 3)
         (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
         (str "Man: Don't act like I'm not here, Briar!")
         (wait)
         (text-reset 1)
         (str "Cole: Ghoul!?")
         (wait)
         (text-reset 1)
         (str "Cole: Give me the gun!")
         (wait)
         (text-reset 1)
         (str "B.F.: Gah, the hell?")
         (wait)
         (text-reset 1)
         (str "Cole: Ghoul, how are you here? You died at the Bayside" 'br)
         (str "Research Lab two years ago...!")
         (wait)
         (text-reset 1)
         (str "Man: ...“Ghoul?”You must have me confused with someone" 'br)
         (str "else...")
         (wait)
         (text-reset 1)
         (str "Cole: You've got some nerve... I'll kill you a second time!")
         (wait)
         (text-reset 1)
         (str "Man: I don't know what you're going on about. My name is" 'br)
         (str "Steve.")
         (wait)
         (text-reset 1)
         (str "Cole: Steve...?")
         (wait)
         (text-reset 1)
         (str "Steve: Boys, I have something to discuss with this young" 'br)
         (str "man. Whatever he's done, let it go...for my sake.")
         (wait)
         (text-reset 1)
         (str "Briar: Hold on one fucking second, Steve! This dude is ours!")
         (wait)
         (text-reset 1)
         (str "Steve: What just happened was a clear case of self-defense.")
         (wait)
         (text-reset 1)
         (str "B.F.: He just shot John in the fucking head! How is that" 'br)
         (str "self-defense!?")
         (wait)
         (text-reset 1)
         (str "Steve: Now now, Briar, you always knew when to listen...")
         (wait)
         (text-reset 1)
         (str "Briar: Well, shit... Steve, you owe us. Bigtime.")
         (wait)
         (text-reset 1)
         (str "Steve: If you would, I'd like to ask you to join me for a" 'br)
         (str "bit.")
         (wait)
         (text-reset 1)
         (str "Cole: Join you...?")
         (wait)
         (text-reset 1)
         (str "Steve: Don't worry, I won't take much of your precious time.")
         (wait)
         (text-reset 1)
         (sound '|| 2)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (mes-jump "A:¥MES¥013.MES"))
        (//
         (str "B.F.: Die, fucker!")						; Game Over sequence
         (wait)
         (text-reset 1)
         (exec-mem 14544 2 2)
         (str "Cole: Urrrrgh!")
         (wait)
         (text-reset 1)
         (exec-mem 17408 3)
         (exec-mem 256 3 0 11 0)
         (exec-mem 256 4 0 7 0)
         (sound '|| 0)
         (sound '|se | 10)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (text "　　　　　　　　　　　ＧＡＭＥ　ＯＶＥＲ")
         (menu1 32 337 48 337 (</> (/ (str "CONTINUE")) (/ (str "END GAME"))))
         (text-reset 1)
         (branch-var S
          (</>
           (/ (exec-mem 9920 0 6 6 113 64 0) (mes-jump "A:¥MES¥012.MES"))
           (/
            (text "　　　　　　ＮＩＧＨＴＭＡＲＥ　ＣＯＬＬＥＣＴＩＯＮ" 'br)
            (text "　　　　　　　ＤＥＡＤ　ＯＦ　ＴＨＥ　ＢＲＡＩＮⅡ" 'br)
            (text "　　　　　　　　　　　　ＧＡＭＥ　ＥＮＤ")
            (loop (wait)))))))))
 (seg (? (= P 7) (= 220 #f))							; Briar #1
   (str "Cole: That guy acting all high and mighty's gotta be the" 'br)
   (str "boss around here. Betcha he's involved with the Purple Sky.")
   (set-reg 220 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 221 #f))							; Briar #2
   (str "Cole: Listen up, I've got questions for you.")
   (wait)
   (text-reset 1)
   (str "B.F.: You got questions? How about you get down on your" 'br)
   (str "hands and knees first.")
   (wait)
   (text-reset 1)
   (str "B.F.: Har har har!")
   (set-reg 221 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 222 #f))							; Briar #3
   (str "B.F.: If you wanna ask a question, then bow down to me" 'br)
   (str "first!")
   (wait)
   (text-reset 1)
   (str "Cole: Bow...down?")
   (wait)
   (text-reset 1)
   (str "B.F.: Yeah, then I'll decide if I wanna answer or not!")
   (wait)
   (text-reset 1)
   (str "B.F.: Haw haw haw haw!")
   (set-reg 222 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))								; Briar #4 (repeat line)
   (str "B.F.: If you wanna ask a question, then bow down to me" 'br)
   (str "first!")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 223 #f))							; Bloody Fox #1
   (str "Cole: These assholes are just low-level thugs. They seem to" 'br)
   (str "be paying attention to the guy sitting to the right of the" 'br)
   (str "girl. Chain of command is king with these guys.")
   (set-reg 223 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))								; Bloody Fox #2 (repeat line)
   (str "Cole: I'm not talking with these punks. It's their leader" 'br)
   (str "or nothing.")
   (wait)
   (text-reset 1))
 (seg (? (= P 2))								; SYSTEM
   (exec-mem 6064 2 2)
   (menu1
    25 317  39 317  53 317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))