; Dead of the Brain 2 (PC-98) - 013.MES
; Translated by Geometrizer
; Edited by trentsignia
; -----Scene:-----
; Steve drives a suspicious Cole out of Bar Rease.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB031.GPC") (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (str "Steve: ...")
  (wait)
  (text-reset 1)
  (str "Cole: ......")
  (wait)
  (text-reset 1)
  (str "Cole: (So this guy calling himself Steve... Who the hell is" 'br)
  (str "he? Why did he help me?)")
  (wait)
  (text-reset 1)
  (str "Steve: ...")
  (wait)
  (text-reset 1)
  (str "Cole: (But the more I look at him, I can't deny that he" 'br)
  (str "looks just like Ghoul. Maybe it IS him, and this is a trap" 'br)
  (str "to kill me...)")
  (wait)
  (text-reset 1)
  (str "Cole: (No, no. I remember watching him die right in front" 'br)
  (str "of me two years ago. Blown apart by that explosion. It's" 'br)
  (str "impossible.)")
  (wait)
  (text-reset 1)
  (str "Steve: Stop eyeing me like that, I'm not gonna hurt you." 'br)
  (str "I'm Steve, from Precinct 32. I'm a detective there. Call" 'br)
  (str "'em yourself and ask if you want.")
  (wait)
  (text-reset 1)
  (str "Cole: A cop, huh... Man, I'm probably in the shit since I" 'br)
  (str "was waving my gun around back there, right?")
  (wait)
  (text-reset 1)
  (str "Steve: Nah, forget it, you're fine. And you still haven't" 'br)
  (str "told me your name.")
  (wait)
  (text-reset 1)
  (str "Cole: It's Cole.")
  (wait)
  (text-reset 1)
  (str "Steve: Cole, solid name. But that other name you were" 'br)
  (str "throwing around back there... Ghoul, wasn't it?")
  (wait)
  (text-reset 1)
  (str "Cole: Yeah, Ghoul.")
  (wait)
  (text-reset 1)
  (str "Steve: I know a guy called Ghoul. Or knew a guy, anyway." 'br)
  (str "Chief of Precinct 16 in the next town over, but one day, he" 'br)
  (str "was up and gone.")
  (wait)
  (text-reset 1)
  (str "Cole: And you're...")
  (wait)
  (text-reset 1)
  (str "Steve: ...Steve.")
  (wait)
  (text-reset 1)
  (str "Cole: Steve, are you looking into what happened to Ghoul?")
  (wait)
  (text-reset 1)
  (str "Steve: Well, if the Ghoul you're talking about is the same" 'br)
  (str "guy, I'd like to ask you some questions about him.")
  (wait)
  (text-reset 1)
  (str "Cole: Like what?")
  (wait)
  (text-reset 1)
  (str "Steve: Well, as the chief of Precinct 16, he made plenty of" 'br)
  (str "enemies in his line of work.")
  (wait)
  (text-reset 1)
  (str "Steve: And he's been missing since summer two years ago..." 'br)
  (str "Yeah, right around the same time as that certain incident" 'br)
  (str "in his town.")
  (wait)
  (text-reset 1)
  (str "Cole: (Damn, he's trying to figure out what happened with" 'br)
  (str "the incident... This is bad, especially if he puts together" 'br)
  (str "the truth about the reanimation serum.)")
  (wait)
  (text-reset 1)
  (str "Steve: You're well aware that the shit that went down over" 'br)
  (str "there was bad news. By the time we caught wind of it," 'br)
  (str "everyone in town was dead.")
  (wait)
  (text-reset 1)
  (str "Steve: At the time, I was tracking down junkies here in the" 'br)
  (str "city. But then I got orders to check out what was happening" 'br)
  (str "in the next town over.")
  (wait)
  (text-reset 1)
  (str "Steve: But when I got there, there were no survivors to" 'br)
  (str "tell the tale. The whole city was riddled with bodies, like" 'br)
  (str "a war had broken out.")
  (wait)
  (text-reset 1)
  (str "Steve: I went to Precinct 16, but the rotting corpses of a" 'br)
  (str "bunch of cops told no tales.")
  (wait)
  (text-reset 1)
  (str "Steve: When I was poking around, something grabbed my leg.")
  (wait)
  (text-reset 1)
  (str "Steve: I aimed my flashlight at it right quick. It was a" 'br)
  (str "human left arm...with no human attached to it.")
  (wait)
  (text-reset 1)
  (str "Steve: At first I thought it might have been a postmortem" 'br)
  (str "muscle spasm, but it was so decomposed I could see the" 'br)
  (str "finger bones sticking out.")
  (wait)
  (text-reset 1)
  (str "Steve: I ran outside to tell someone, but the second I got" 'br)
  (str "out the door, the station crumbled to the ground. Count" 'br)
  (str "your blessings, I guess.")
  (wait)
  (text-reset 1)
  (str "Steve: I tried to report what happened later, but everyone" 'br)
  (str "thought I was hopped up on something.")
  (wait)
  (text-reset 1)
  (str "Steve: After that, I interrogated anyone and everyone" 'br)
  (str "headed back into the town, but in the end it was futile.")
  (wait)
  (text-reset 1)
  (str "Steve: It was just a handful of confused residents, and a" 'br)
  (str "bunch of Bloody Fox thugs.")
  (wait)
  (text-reset 1)
  (str "Cole: ......")
  (wait)
  (text-reset 1)
  (str "Steve: Who would believe me, anyway? A detached human arm" 'br)
  (str "still moving...it's all crazy-sounding.")
  (wait)
  (text-reset 1)
  (str "Cole: But...but what does any of that have to do with" 'br)
  (str "Ghoul? He was the precinct chief...")
  (wait)
  (text-reset 1)
  (str "Steve: I'll explain later.")
  (wait)
  (text-reset 1)
  (str "Cole: Where are we going, anyway? The station is in the" 'br)
  (str "other direction.")
  (wait)
  (text-reset 1)
  (str "Steve: We're already here. This is my house. I wanted to" 'br)
  (str "invite you over.")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (mes-jump "A:¥MES¥014.MES"))
 (seg*))