(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB031.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (text "Steve: ...")
  (wait)
  (text-reset 1)
  (text "Cole: .....")
  (wait)
  (text-reset 1)
  (text "Cole: So this guy calling himself Steve... Who the hell is  he? Why did he help me?")
  (wait)
  (text-reset 1)
  (text "Steve: ...")
  (wait)
  (text-reset 1)
  (text
   "Cole: But the more I look at him, I can't deny that he looksjust like Ghoul. Maybe it IS him, and this is a trap to kill    me...")
  (wait)
  (text-reset 1)
  (text "Cole: No, no. I remember watching him die right in front of me two years ago. Blown apart by that explosion. It's       impossible.")
  (wait)
  (text-reset 1)
  (text
   "Steve: Stop eyeing me like that, I'm not gonna hurt you. I'mSteve, from Precinct 32. I'm a detective there. Call 'em yourself and ask if you want.")
  (wait)
  (text-reset 1)
  (text "Cole: A cop, huh... Man, I'm probably in the shit since I   was waving my gun around back there, right?")
  (wait)
  (text-reset 1)
  (text "Steve: Nah, forget it, you're fine. And you still haven't   told me your name.")
  (wait)
  (text-reset 1)
  (text "Cole: It's Cole.")
  (wait)
  (text-reset 1)
  (text "Steve: Cole, solid name. But that other name you were       throwing around back there... Ghoul, wasn't it?")
  (wait)
  (text-reset 1)
  (text "Cole: Yeah, Ghoul.")
  (wait)
  (text-reset 1)
  (text
   "Steve: I know a guy called Ghoul. Or knew a guy, anyway.    Chief of Precinct 16 in the next town over, but one day, he was up and gone.")
  (wait)
  (text-reset 1)
  (text "Cole: And you're...")
  (wait)
  (text-reset 1)
  (text "Steve: ...Steve.")
  (wait)
  (text-reset 1)
  (text "Cole: Steve, are you looking into what happened to Ghoul?")
  (wait)
  (text-reset 1)
  (text "Steve: Well, if the Ghoul you're talking about is the same  guy, I'd like to ask you some questions about him.")
  (wait)
  (text-reset 1)
  (text "Cole: Like what?")
  (wait)
  (text-reset 1)
  (text
   "Steve: Well, as the chief of Precinct 16, he made plenty of enemies in his line of work.")
  (wait)
  (text-reset 1)
  (text
   "Steve: And he's been missing since summer two years ago...  Yeah, right around the same time as that certain incident inhis town.")
  (wait)
  (text-reset 1)
  (text "Cole: (Damn, he's trying to figure out what happened with   the incident... This is bad, especially if he puts together the truth about the reanimation serum.)")
  (wait)
  (text-reset 1)
  (text
   "Steve: You're well aware that the shit that went down over  there was bad news. By the time we caught wind of it,       everyone in town was dead.")
  (wait)
  (text-reset 1)
  (text
   "Steve: At the time, I was tracking junkies here in the city.But then I got the orders to head over and figure out what was happening next town over.")
  (wait)
  (text-reset 1)
  (text
   "Steve: But when I got there, there were no survivors to tellthe tale. The whole city was riddled with bodies, like a war   had broken out.")
  (wait)
  (text-reset 1)
  (text
   "Steve: I went to Precinct 16, but the rotting corpses of a  bunch of cops told no tales.")
  (wait)
  (text-reset 1)
  (text "Steve: When I was poking around, something grabbed my leg.")
  (wait)
  (text-reset 1)
  (text "Steve: I aimed my flashlight at it right quick. It was a    human left arm...with no human attached to it.")
  (wait)
  (text-reset 1)
  (text "Steve: At first I thought it might have been a postmortem   muscle spasm, but it was so decomposed I could see the      finger bones sticking out.")
  (wait)
  (text-reset 1)
  (text
   "Steve: I ran outside to tell someone, but at the moment I   got out, the station crumbled into the ground. Count your   blessings, I guess.")
  (wait)
  (text-reset 1)
  (text "Steve: I tried to report what happened later, but everyone  thought I was hopped up on something.")
  (wait)
  (text-reset 1)
  (text
   "Steve: After that, I interrogated anyone and everyone headed back into the  town, but in the end it was futile.")
  (wait)
  (text-reset 1)
  (text "Steve: It was just a handful of confused residents, and a   bunch of Bloody Fox thugs.")
  (wait)
  (text-reset 1)
  (text "Cole: .....")
  (wait)
  (text-reset 1)
  (text "Steve: Who would believe me, anyway? A detached human arm   still moving...it's all crazy-sounding.")
  (wait)
  (text-reset 1)
  (text "Cole: But...but what does any of that have to do with Ghoul?He was the precinct chief...")
  (wait)
  (text-reset 1)
  (text "Steve: I'll explain later.")
  (wait)
  (text-reset 1)
  (text "Cole: Where are we going, anyway? The station is in the     other direction.")
  (wait)
  (text-reset 1)
  (text "Steve: We're already here. This is my house. I wanted to    invite you over.")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (mes-jump "A:¥MES¥014.MES"))
 (seg*))