(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (mes-load? "A:¥MES¥014A.CAL" 0)
  (mes-load? "A:¥MES¥014B.CAL" 3952)
  (load-mem "A:¥CLM¥DB032.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 48 9 56 14)
  (exec-mem 3744 1 6 41 10 44 13)
  (exec-mem 3744 1 7 12 3 18 7)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB032.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 227 #f))
        (text "［コール］いい家だ・・・。")
        (wait)
        (text-reset 1)
        (text "［スティーブ］ここは日当たりもいいし、一人で住むには実に都合　　　　　　　のいい場所だよ。")
        (set-reg 227 #t)
        (wait)
        (text-reset 1))
       (// (text "［コール］今、俺はスティーブさんの家に来ている。") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 228 #f))
   (text "［コール］机の上には様々な資料が並んでいるな。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］殆どここは仕事場と変わらないよ。")
   (set-reg 228 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text
    "［スティーブ］おっと、あまりいじらないでくれないか。これらの　　　　　　　ファイルは今まで苦労して集めた大切な資料だから　　　　　　　な。")
   (wait)
   (text-reset 1)
   (text "［コール］失礼・・・何しろ刑事の部屋なんて来たのは初めてだか　　　　　らね。興味を引くものはたくさんあるよ。")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 229 #f))
   (text
    "［コール］バーボン・ウイスキーだな。入口にもこれと同じ空き瓶　　　　　が捨ててあったが、スティーブさんは余程この酒が好き　　　　　らしいな。")
   (set-reg 229 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 230 #f))
   (text "［スティーブ］君も飲むか？　イケるバーボンだよ。")
   (wait)
   (text-reset 1)
   (text "［コール］あ、俺は遠慮しておきます。")
   (set-reg 230 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6)) (text "［コール］あんまり見てるとまた薦められそうだな。") (wait) (text-reset 1))
 (seg (? (= P 7) (= 231 #f))
   (text "［コール］自分の家に戻って来て、スティーブさんはほっとしてい　　　　　るようだな。")
   (set-reg 231 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 232 #f))
   (text "［スティーブ］さあ、本題に入ろうか。さっきはどこまで話したか　　　　　　　な？")
   (wait)
   (text-reset 1)
   (text "［コール］２年前の事件にどうしてグールが関っているかという事　　　　　です。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］そうだったな。なら、簡単に説明しよう。１６分署　　　　　　　の警官の死体は全て発見されたが、彼の死体だけは　　　　　　　未だに発見されていないんだよ。")
   (wait)
   (text-reset 1)
   (text "［コール］〔当たり前だ・・・俺がグールに初めて会った時から、　　　　　奴は完全なアンドロイドだったのだからな・・・〕")
   (wait)
   (text-reset 1)
   (text
    "［コール］〔だが、ここで今そんな話をしたところでスティーブさ　　　　　んはその事を本気にしてくれないだろう。どこかの映画　　　　　じゃあるまいし、人間が実はアンドロイドだなんてな〕")
   (set-reg 232 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 233 #f))
   (text "［スティーブ］・・・どうした？")
   (wait)
   (text-reset 1)
   (text
    "［コール］いえ、別に・・・。だけど死体なんて１ヶ月も放ってお　　　　　けば、見た目では誰なのか判断できないぐらい腐敗して　　　　　しまうものでしょ？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］確かにそうだよ。")
   (wait)
   (text-reset 1)
   (text "［コール］ひょっとしたら、腐敗されている物の中に混ざっている　　　　　のかもしれないし・・・。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］普通ならな。だが、隣街で発見された死体はおかし　　　　　　　な事に見た目だけで確認がとれる物ばかりだったの　　　　　　　だよ。")
   (wait)
   (text-reset 1)
   (text "［コール］腐敗していないと？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］そうだ。")
   (wait)
   (text-reset 1)
   (text "［コール］・・・・・・・・・。")
   (set-reg 233 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 234 #f))
   (text
    "［スティーブ］それらを解剖した結果、驚くべき事に殆どの死体の　　　　　　　血液には防腐剤に非常に似た薬品が検出された。　　　　　　　　おかしいとは思わないか？")
   (wait)
   (text-reset 1)
   (text "［コール］防腐剤？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ああ・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］〔死んだ者を生き返らせる蘇生薬だ、身体を腐らせない　　　　　薬が入っていても不思議ではないな・・・〕")
   (wait)
   (text-reset 1)
   (text "［コール］〔それにしてもスティーブさん、一体どこまであの事件　　　　　の事を知っているんだろう・・・〕")
   (set-reg 234 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 235 #f))
   (text
    "［スティーブ］私は、あの事件とその薬品を結び付けて捜査に乗り　　　　　　　出したが、ある日、部下からベイサイド研究所で爆　　　　　　　発の跡があるという知らせが入ったんだ。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］私もその研究所へ出向き、建物の中を調べた結果、　　　　　　　２階のセキュリティー・ルームでグールのバッヂを　　　　　　　見つけたのだよ。")
   (wait)
   (text-reset 1)
   (text "［コール］バッヂを！？")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］ああ、そして私は考えた。もしグールがその薬品に　　　　　　　ついて調べていた事になると、それに気付いた敵が　　　　　　　グールを殺したのかもしれないってね。")
   (set-reg 235 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 236 #f))
   (text "［コール］・・・・・・・・・。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］きっと裏があるに決まってる・・・。グールの死体　　　　　　　は海にでも捨てられたと考えられるが、どうもそん　　　　　　　な簡単な事件ではなさそうなんだよ。")
   (wait)
   (text-reset 1)
   (text "［コール］裏があると？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ああ、そうだ。")
   (set-reg 236 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 237 #f))
   (text "［コール］どうしてそんな事が言えるんですか？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］私はベイサイド研究所でバッヂの他に「ある物」を　　　　　　　拾ったんだよ。")
   (wait)
   (text-reset 1)
   (text "［コール］ある物？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］コールの後ろにある棚に乗っているだろう。")
   (wait)
   (text-reset 1)
   (text "［コール］この新聞紙にくるまったやつですか？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ああ、俺はそいつを拾うまでは害者のグールは他殺　　　　　　　だと思っていた。")
   (wait)
   (text-reset 1)
   (text "［コール］〔スープ皿の大きさの塊だが、一体何の包みなんだ？〕")
   (set-reg 237 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 238 #f))
   (text "［コール］あの・・・これ見てもいいですか？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］待て。その前に、その包みを見たら君の知っている　　　　　　　事を教えてくれないか？")
   (wait)
   (text-reset 1)
   (text "［コール］・・・・・・・・・。")
   (wait)
   (text-reset 1)
   (text
    "［コール］〔やはりスティーブさんは、２年前の事件の事で俺を疑　　　　　っているんだろうな・・・。あの話はドクとシーラと俺　　　　　だけの秘密だから人には話せないし・・・〕")
   (wait)
   (text-reset 1)
   (text
    "［コール］〔だけど、これ程までに捜査の事を俺に話してくれるの　　　　　は、やっぱり俺が何か知っていると感付いているからだ　　　　　ろうな〕")
   (wait)
   (text-reset 1)
   (text "［コール］〔とにかく、この包みを見てから決めよう〕")
   (set-reg 238 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text
    "［スティーブ］君の言った事は誰にも言わないと約束しよう。また　　　　　　　君が今までに犯罪を起こしていても、君を捕まえな　　　　　　　いと約束するよ。")
   (wait)
   (text-reset 1)
   (text "［コール］・・・俺が人を殺していても？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ああ、約束するよ。それに君は犯罪を犯すような男　　　　　　　には見えないからな。")
   (wait)
   (text-reset 1)
   (text "［コール］人を見掛けで判断すると後悔しますよ。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］俺はこう見えても一端の刑事だ。人を見る目はある　　　　　　　つもりだよ。")
   (wait)
   (text-reset 1)
   (text "［コール］・・・判りました。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］決まりだ、包みを開けてくれ。")
   (wait)
   (text-reset 1)
   (text "［コール］はい・・・。")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB033.GPC")
   (image-mem 0 3)
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (sound '|| 0)
   (sound '|se | 3)
   (text "［コール］グール・・・！？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］・・・やはりこいつがグールか。")
   (wait)
   (text-reset 1)
   (text "［コール］〔あの爆発で完全に破壊されたと思っていたが、まさか　　　　　首だけ残っていたとは・・・〕")
   (wait)
   (text-reset 1)
   (sound '|| 0)
   (if (</>
        (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
        (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
   (sound '|| 1)
   (text
    "［スティーブ］ベイサイド研究所の工場でそいつを見つけたんだ。　　　　　　　現場にはこの頭部と焦げた顔面の皮膚が転がってい　　　　　　　たよ・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］・・・皮膚？")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］グール、いや「リチャード・グリス」そっくりの顔　　　　　　　を形どったものだ。皮膚は特殊ビニール素材、頭部　　　　　　　はチタン合金が使われている。")
   (wait)
   (text-reset 1)
   (text "［コール］・・・・・・。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］こんな物が実際に動いていたとは信じられんが、調　　　　　　　べてもらった結果、ここまで酷く破壊されているた　　　　　　　め、何の手掛かりも得られなかったがね。")
   (wait)
   (text-reset 1)
   (text "［コール］ん？　後頭部はフタになっているのか・・・。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］こいつを発見した時にも、この後頭部のフタが開い　　　　　　　ていたんだ。中はこの様にカラッポだったが、紫色　　　　　　　に光った液体が飛び散っていた。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］きっとこのロボットを動かすためのコンピューター　　　　　　　か何かで使用するバッテリー液だったのだろうな。")
   (wait)
   (text-reset 1)
   (text "［コール］バッテリー液ね・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］だが、最近になってそれと似たような輝きをする薬　　　　　　　品を見るようになったんだ。")
   (wait)
   (text-reset 1)
   (text "［コール］ど、どこで？")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］ブラッディフォックスの中で流れているパープル・　　　　　　　スカイというドラッグだ。私は何とかその薬を入手　　　　　　　しようとバー・リーズに足を向けた。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］自分が警官である事を悟られないようにな。そして　　　　　　　昨日の事件が起こったんだ。")
   (wait)
   (text-reset 1)
   (text "［コール］昨日の事件というとブラッディフォックスの７人殺し？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ああ、その通りだ。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］ベン・レイモンドという男がパープルスカイを服用　　　　　　　していた事は以前から知っていたが、奴は必要以上　　　　　　　の薬を注入していたんだ。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］多分、そのために脳をやられてしまったのだろう。　　　　　　　店にいたブラッディフォックスを素手で７人殺した　　　　　　　んだ。")
   (wait)
   (text-reset 1)
   (text "［コール］素手で・・・！？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］私は彼が暴れている時、隙を狙ってどさくさ紛れに　　　　　　　床に落ちたパープル・スカイを拾った。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］そして今朝調べて貰った結果、隣街で発見した死体　　　　　　　の血液に入っていた物に非常によく似ている事が判　　　　　　　ったのだよ。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］私はパープル・スカイの出所を調べるために、今日　　　　　　　もあの店で張り込んでたという訳だ。")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB032.GPC")
   (image-mem 1 3)
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (mes-load? 0)
   (mes-load? 3952)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   ((cmd 209) 0 5)
   (image-file "A:¥GPC¥title.gpc")
   (image-mem 0 3)
   (exec-mem 912 "INIT")
   (exec-mem 912 "A 1")
   (text-frame 0 0 79 399)
   (text-reset 0)
   (exec-mem 912 "A 0")
   (exec-mem 912 "EXIT")
   (text-frame 0 0 79 399)
   (text-reset 0)
   (exec-mem 9920 0 6 6 113 64 8)
   ((cmd 204) 99 899)
   (sound '|| 0)
   ((cmd 209) 1)
   (mes-jump "A:¥MES¥015.MES"))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))