(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (mes-load? "A:¥MES¥014A.CAL" 0)
  (mes-load? "A:¥MES¥014B.CAL" 3952)
  (load-mem "A:¥CLM¥DB032.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 48 9 56 14)
  (exec-mem 3744 1 6 41 10 44 13)
  (exec-mem 3744 1 7 12 3 18 7)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB032.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 227 #f))
        (text "Cole: Wow, nice place.")
        (wait)
        (text-reset 1)
        (text "Steve: It's got plenty of sunlight, and not a bad little    bachelor pad.")
        (set-reg 227 #t)
        (wait)
        (text-reset 1))
       (// (text "Cole: I'm at Steve's place.") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 228 #f))
   (text "Cole: There's documents aplenty all over the desk.")
   (wait)
   (text-reset 1)
   (text "Steve: It's practically no different from my workplace. Shiteverywhere.")
   (set-reg 228 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text
    "Steve: Hey, hands off. I had to work my ass off to get all  this stuff collected.")
   (wait)
   (text-reset 1)
   (text "Cole: My bad, it's my first time in a detective's office.   You've got a lot going on in here.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 229 #f))
   (text
    "Cole: Bourbon, huh? There was an empty bottle near the      entrance. That's your preferred liquor, huh?")
   (set-reg 229 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 230 #f))
   (text "Steve: You want some? It really does the trick.")
   (wait)
   (text-reset 1)
   (text "Cole: Ah, I'll pass for now.")
   (set-reg 230 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6)) (text "Cole: If I keep staring, he'll probably pour me a shot, so  let's not.") (wait) (text-reset 1))
 (seg (? (= P 7) (= 231 #f))
   (text "Cole: Steve seems to have calmed down now that we're back inhis house.")
   (set-reg 231 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 232 #f))
   (text "Steve: Right, down to business. Now, where were we?")
   (wait)
   (text-reset 1)
   (text "Cole: We were talking about how Ghoul's connected to the    incident from two years ago.")
   (wait)
   (text-reset 1)
   (text
    "Steve: Yeah. Let me explain. The body of every officer was  recovered from Precinct 16...except for Ghoul's.")
   (wait)
   (text-reset 1)
   (text "Cole: (Well, that makes sense. From the first time I met    Ghoul, he was nothing more than an android.)")
   (wait)
   (text-reset 1)
   (text
    "Cole: (But Steve will throw me in the loony bin if I tell   him that murderous androids were walking around. It sounds  like a B-movie plot.)")
   (set-reg 232 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 233 #f))
   (text "Steve: What's the matter?")
   (wait)
   (text-reset 1)
   (text
    "Cole: Nothing, but... if you leave a corpse unattended for amonth, it decays so much that you can't ID it by looking at it, right?")
   (wait)
   (text-reset 1)
   (text "Steve: That's true.")
   (wait)
   (text-reset 1)
   (text "Cole: So maybe it just kinda blended in with the rubble...")
   (wait)
   (text-reset 1)
   (text
    "Steve: Normally, yeah. But all the other corpses had one    peculiar trait: we could ID each one by looking at them.")
   (wait)
   (text-reset 1)
   (text "Cole: You mean decay had never set in?")
   (wait)
   (text-reset 1)
   (text "Steve: You got it.")
   (wait)
   (text-reset 1)
   (text "Cole: ...")
   (set-reg 233 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 234 #f))
   (text
    "Steve: After performing the autopsies, we made a startling  discovery... Each body's blood contained a chemical compoundstrikingly similar to a preservative. Funny, ain't it?")
   (wait)
   (text-reset 1)
   (text "Cole: ...A preservative?")
   (wait)
   (text-reset 1)
   (text "Steve: Mm-hmm.")
   (wait)
   (text-reset 1)
   (text "Cole: (It's gotta be the reanimation serum, keeping the     bodies from rotting.)")
   (wait)
   (text-reset 1)
   (text "Cole: (Still, how much does Steve REALLY know about the     incident...?)")
   (set-reg 234 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 235 #f))
   (text
    "Steve: I launched an investigation to see if we could link  the incident with the compound, but I got the news that     there was an explosion at the Bayside Research Facility.")
   (wait)
   (text-reset 1)
   (text
    "Steve: After searching the building, I found Ghoul's badge  in a security room on the second floor.")
   (wait)
   (text-reset 1)
   (text "Cole: His badge?")
   (wait)
   (text-reset 1)
   (text
    "Steve: Yeah. And that's when I realized...if Ghoul had been investigating that drug, he might have gotten too close to  the truth, and someone took him out.")
   (set-reg 235 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 236 #f))
   (text "Cole: ...")
   (wait)
   (text-reset 1)
   (text
    "Steve: There's got to be more to it, though. You'd assume   someone just dumped Ghoul's body into the ocean, but I don'tthink that's what happened.")
   (wait)
   (text-reset 1)
   (text "Cole: So you think there's more to the story?")
   (wait)
   (text-reset 1)
   (text "Steve: I sure do.")
   (set-reg 236 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 237 #f))
   (text "Cole: How can you be so sure?")
   (wait)
   (text-reset 1)
   (text "Steve: I found something else at Bayside.")
   (wait)
   (text-reset 1)
   (text "Cole: Don't leave me in suspense.")
   (wait)
   (text-reset 1)
   (text "Steve: It's sitting on the shelf behind you, Cole.")
   (wait)
   (text-reset 1)
   (text "Cole: That thing wrapped in newspaper?")
   (wait)
   (text-reset 1)
   (text "Steve: Mm. Until I saw it, I assumed that Ghoul had been    murdered by someone else.")
   (wait)
   (text-reset 1)
   (text "Cole: (It's the size of a football. What the hell is it?)")
   (set-reg 237 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 238 #f))
   (text "Cole: Can I...look at it?")
   (wait)
   (text-reset 1)
   (text "Steve: Hold on. Before you do, I want you to take a good    look at it and tell me what you think is in there.")
   (wait)
   (text-reset 1)
   (text "Cole: ...")
   (wait)
   (text-reset 1)
   (text
    "Cole: (I knew it! Steve suspects I was involved with the    incident two years ago. What went down was a secret between Doc, Sheila, and me... Nobody else can know.)")
   (wait)
   (text-reset 1)
   (text
    "Cole: (But the fact that he's explaining the investigation  in such detail... He must think I know something.)")
   (wait)
   (text-reset 1)
   (text "Cole: (I'll figure out what to do once I see what's wrapped up in the newspaper.)")
   (set-reg 238 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text
    "Steve: I promise that what you say stays between you and me.And even if you're guilty of something, I won't arrest you.")
   (wait)
   (text-reset 1)
   (text "Cole: Even if I killed someone?")
   (wait)
   (text-reset 1)
   (text "Steve: Even if you killed someone. Besides, you don't strikeme as the criminal type.")
   (wait)
   (text-reset 1)
   (text "Cole: Don't judge a book by its cover.")
   (wait)
   (text-reset 1)
   (text "Steve: Even if I don't look the part, I'm a detective. I    like to think I have a good eye for people.")
   (wait)
   (text-reset 1)
   (text "Cole: I'll take that as a compliment.")
   (wait)
   (text-reset 1)
   (text "Steve: Good enough. Now open the package.")
   (wait)
   (text-reset 1)
   (text "Cole: Okay...")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB033.GPC")
   (image-mem 0 3)
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (sound '|| 0)
   (sound '|se | 3)
   (text "Cole: Ghoul...!?")
   (wait)
   (text-reset 1)
   (text "Steve: Yeah. That's Ghoul.")
   (wait)
   (text-reset 1)
   (text "Cole: (I thought he'd been obliterated by the explosion, buthis head survived...!)")
   (wait)
   (text-reset 1)
   (sound '|| 0)
   (if (</>
        (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
        (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
   (sound '|| 1)
   (text
    "Steve: I found it at Bayside. His head, and charred skin    from his face scattered everywhere.")
   (wait)
   (text-reset 1)
   (text "Cole: Is this...Skin!?")
   (wait)
   (text-reset 1)
   (text
    "Steve: This isn't the real Ghoul. It's something...modeled  to resemble Richard Gris. The skin is a special vinyl, and  the skull is titanium alloy.")
   (wait)
   (text-reset 1)
   (text "Cole: ...")
   (wait)
   (text-reset 1)
   (text
    "Steve: I can't believe something like this even...worked.   Even after examining the hell out of it, it was so damaged  we couldn't pull any clues from it.")
   (wait)
   (text-reset 1)
   (text "Cole: Wha? So the back of the head opens like..a lid?")
   (wait)
   (text-reset 1)
   (text
    "Steve: When I found it, the back of the head was open. The  inside was empty, save some glowing purple liquid.")
   (wait)
   (text-reset 1)
   (text "Steve: I'm gonna guess that was battery fluid -- like you'd use in a computer or something -- to power the robot.")
   (wait)
   (text-reset 1)
   (text "Cole: Battery fluid, huh?")
   (wait)
   (text-reset 1)
   (text "Steve: But lately, I've become aware of a drug that's got   similar properties.")
   (wait)
   (text-reset 1)
   (text "Cole: Where have you seen it?")
   (wait)
   (text-reset 1)
   (text
    "Steve: It's the drug called 'Purple Sky' that's been making the rounds with Bloody Fox. I went to Bar Rease to get my   hands on it.")
   (wait)
   (text-reset 1)
   (text "Steve: I went in undercover. And then yesterday's shitstorm hit.")
   (wait)
   (text-reset 1)
   (text "Cole: You mean when the seven Bloody Fox members got killed?")
   (wait)
   (text-reset 1)
   (text "Steve: That's the one.")
   (wait)
   (text-reset 1)
   (text
    "Steve: I'd heard that a guy named Ben Raymond was taking    Purple Sky, but injecting way more than he needed.")
   (wait)
   (text-reset 1)
   (text
    "Steve: That's probably what messed with his brain and made  him go on that killing spree, taking out seven Bloody Fox   members in the bar with his bare hands.")
   (wait)
   (text-reset 1)
   (text "Cole: With his bare hands...!")
   (wait)
   (text-reset 1)
   (text "Steve: In the middle of the chaos, I took the opportunity tosnatch some Purple Sky that had fallen on the floor.")
   (wait)
   (text-reset 1)
   (text
    "Steve: And after having a lab analysis run this morning, I  discovered that it has more than a passing resemblance to   the substance found in a body in a neighboring town.")
   (wait)
   (text-reset 1)
   (text "Steve: That's why I was staking out Bar Rease today -- to   figure out the origin of Purple Sky.")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB032.GPC")
   (image-mem 1 3)
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (mes-load? 0)
   (mes-load? 3952)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   ((cmd 209) 0 5)
   (image-file "A:¥GPC¥title.gpc")
   (image-mem 0 3)
   (exec-mem 912 "INIT")
   (exec-mem 912 "A 1")
   (text-frame 0 0 79 399)
   (text-reset 0)
   (exec-mem 912 "A 0")
   (exec-mem 912 "EXIT")
   (text-frame 0 0 79 399)
   (text-reset 0)
   (exec-mem 9920 0 6 6 113 64 8)
   ((cmd 204) 99 899)
   (sound '|| 0)
   ((cmd 209) 1)
   (mes-jump "A:¥MES¥015.MES"))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))