; Dead of the Brain 2 (PC-98) - 014A.MES
; Translated by Geometrizer
; Edited by trentsignia and JackDBS
; -----Notes:-----
; This chunk of text was originally part of two CAL files that was loaded in by 014.MES and called when needed.
; I had problems getting the translated scripts to work in this arrangement, so I merged the CAL files and the code after it into a single MES script.
; This only works because there is no opportunity to save between the jump happening and the next script; saving in a different file to the Save dialog will cause problems when loading.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (str "Steve: Cole, I can tell you were involved with the incident" 'br)	; 014A.CAL starts here
  (str "in some way. Why don't you tell me what you know?")
  (wait)
  (text-reset 1)
  (str "Cole: Steve, why are you so desperate to discover what" 'br)
  (str "happened?")
  (wait)
  (text-reset 1)
  (str "Steve: ...What do you mean?")
  (wait)
  (text-reset 1)
  (str "Cole: After hearing your story, I'm not convinced you're" 'br)
  (str "officially investigating a cold case from two years ago.")
  (wait)
  (text-reset 1)
  (str "Steve: You're right.")
  (wait)
  (text-reset 1)
  (str "Steve: As you'd expect... Ghoul -- no, Richard Gris, was my" 'br)
  (str "brother.")
  (wait)
  (text-reset 1)
  (str "Cole: !?!")
  (wait)
  (text-reset 1)
  (str "Steve: The first time you identified me as Ghoul and" 'br)
  (str "pointed your gun at me, I realized you had something to do" 'br)
  (str "with my brother. And the incident from two years ago...")
  (wait)
  (text-reset 1)
  (str "Cole: So that's what's happening here...")
  (wait)
  (text-reset 1)
  (str "Steve: I was proud of him. He was brilliant. It's not odd" 'br)
  (str "for a detective to go deep undercover, but he vanished two" 'br)
  (str "months before the incident.")
  (wait)
  (text-reset 1)
  (str "Steve: He wasn't the type of the person who'd go that long" 'br)
  (str "without any contact.")
  (wait)
  (text-reset 1)
  (str "Steve: I heard he vanished, and just as I was about to call" 'br)
  (str "the 16th Precinct, I was ordered to the neighboring town." 'br)
  (str "If only I'd noticed sooner...")
  (wait)
  (text-reset 1)
  (str "Cole: ...I get it. Let's talk about everything.")
  (wait)
  (text-reset 1)
  (str "Steve: Please, tell me what you know.")
  (wait)
  (text-reset 1)
  (str "Cole: Back then, I knew a scientist named Dr. Cooger.")
  (wait)
  (text-reset 1)
  (str "Steve: A scientist?")
  (wait)
  (text-reset 1)
  (str "Cole: Yeah. Back then he was primarily doing cancer cell" 'br)
  (str "research.")
  (wait)
  (text-reset 1)
  (str "Cole: He'd invent artificial organs and call me over to his" 'br)
  (str "place to show me, all the while with this big goofy grin.")
  (wait)
  (text-reset 1)
  (str "Cole: And one time he called me over to his house, and in" 'br)
  (str "his lab, he showed me a drug that was a match for Purple" 'br)
  (str "Sky.")
  (wait)
  (text-reset 1)
  (str "Steve: So it was purple?")
  (wait)
  (text-reset 1)
  (str "Cole: Yeah.")
  (wait)
  (text-reset 1)
  (str "Steve: And it's definitely the same thing on the inside of" 'br)
  (str "that robot's cranium.")
  (wait)
  (text-reset 1)
  (str "Cole: He said that he invented a reanimation serum.")
  (wait)
  (text-reset 1)
  (str "Steve: A reanimation serum!?")
  (wait)
  (text-reset 1)
  (str "Cole: I know, I know, it sounds crazy.")
  (wait)
  (text-reset 1)
  (str "Steve: I don't think it sounds crazy.")
  (wait)
  (text-reset 1)
  (str "Cole: It isn't... He brought back a cat from the dead. But" 'br)
  (str "it came back with a ferociousness that could kill a human.")
  (wait)
  (text-reset 1)
  (str "Cole: Then, we got a visit from Jack from Precinct 16...and" 'br)
  (str "the cat killed him.")
  (wait)
  (text-reset 1)
  (str "Cole: ....")
  (wait)
  (text-reset 1)
  (str "Steve: Don't stop there.")
  (wait)
  (text-reset 1)
  (str "Cole: In his panic, Doc injected the serum into Jack's" 'br)
  (str "corpse. I guess he thought if he brought him back to life," 'br)
  (str "it wouldn't be murder. Well, murder by undead cat.")
  (wait)
  (text-reset 1)
  (str "Steve: ...")
  (wait)
  (text-reset 1)
  (str "Cole: But that experiment was a failure. Jack came back," 'br)
  (str "and attacked us. We ran back to my apartment and tried to" 'br)
  (str "figure out what to do.")
  (wait)
  (text-reset 1)
  (str "Cole: Doc decided he'd turn himself in.")
  (wait)
  (text-reset 1)
  (str "Cole: I mean, even if I told the truth, nobody would" 'br)
  (str "believe me, even though someone got killed. And then my" 'br)
  (str "fiancee ran in.")
  (wait)
  (text-reset 1)
  (str "Cole: Her name is Sheila, and she saw a wandering corpse in" 'br)
  (str "the middle of the street and ran away.")
  (wait)
  (text-reset 1)
  (str "Steve: In the street?")
  (wait)
  (text-reset 1)
  (str "Cole: Yeah, and when we were running away, Doc managed to" 'br)
  (str "drop his bag containing the reanimation serum.")
  (wait)
  (text-reset 1)
  (str "Cole: At that point, the vial with the serum must have" 'br)
  (str "shattered, and its contents seeped into the ground...")
  (wait)
  (text-reset 1)
  (str "Cole: Or maybe Jack had bitten someone else.")
  (wait)
  (text-reset 1)
  (str "Steve: Biting someone turns them into...a zombie?")
  (wait)
  (text-reset 1)
  (str "Cole: Yes. The serum can transfer via mucous membranes, so" 'br)
  (str "a bitten person can turn zombie in just a few minutes. But" 'br)
  (str "there's more to the chemicals in it...")
  (wait)
  (text-reset 1)
  (str "Cole: As I mentioned before, there's a substance similar to" 'br)
  (str "embalming fluid that keeps the bodies from decomposing.")
  (wait)
  (text-reset 1)
  (str "Steve: So does that mean Jack was responsible for the" 'br)
  (str "zombies?")
  (wait)
  (text-reset 1)
  (str "Cole: No, that's likely not the case.")
  (wait)
  (text-reset 1)
  (str "Cole: With zombies running through the streets and" 'br)
  (str "attacking my apartment, we headed to Precinct 16, but it" 'br)
  (str "was too late... It had already been overrun by zombies.")
  (wait)
  (text-reset 1)
  (str "Cole: In the chief's office, we found a memo that pointed" 'br)
  (str "us in the direction of the Central Hotel. There we found" 'br)
  (str "five survivors...and Ghoul.")
  (wait)
  (text-reset 1)
  (str "Cole: I guess whoever wrote the memo assumed that everyone" 'br)
  (str "left alive would head to the police station.")
  (wait)
  (text-reset 1)
  (str "Cole: Ghoul took the lead, and we battled the zombies in an" 'br)
  (str "attempt to find more survivors. But Doc got bitten by a" 'br)
  (str "zombie...")
  (wait)
  (text-reset 1)
  (str "Steve: Did he turn?")
  (wait)
  (text-reset 1)
  (str "Cole: No... I shot him first. He insisted that he would" 'br)
  (str "turn into a zombie and attack me, so I had to pull the" 'br)
  (str "trigger before that happened.")
  (wait)
  (text-reset 1)
  (str "Steve: ...")
  (wait)
  (text-reset 1)
  (str "Cole: After that, I met a journalist from the city to the" 'br)
  (str "West...his name was Cain. He showed up because his own city" 'br)
  (str "had a similar incident two months before.")
  (wait)
  (text-reset 1)
  (str "Cole: ...As it happens, right around the time you mentioned" 'br)
  (str "that Ghoul vanished.")
  (wait)
  (text-reset 1)
  (str "Steve: !?!")
  (wait)
  (text-reset 1)
  (str "Cole: From that point on, the number of zombies just" 'br)
  (str "skyrocketed.")
  (wait)
  (text-reset 1)
  (str "Steve: So it was all Cooger's doing?")					; 014B.CAL starts here
  (wait)
  (text-reset 1)
  (str "Cole: Jack was the first human Doc injected.")
  (wait)
  (text-reset 1)
  (str "Steve: Are you positive?")
  (wait)
  (text-reset 1)
  (str "Cole: I am. Another reason I don't think Jack was the first" 'br)
  (str "zombie is because someone had broken into Doc's lab" 'br)
  (str "beforehand...a man named Killer, one of Ghoul's underlings.")
  (wait)
  (text-reset 1)
  (str "Cole: Under Ghoul's orders, Killer stole the reanimation" 'br)
  (str "serum research and handed it off to the Bayside Research" 'br)
  (str "Institute director.")
  (wait)
  (text-reset 1)
  (str "Steve: The Institute director? So Ghoul was working with" 'br)
  (str "him?")
  (wait)
  (text-reset 1)
  (str "Cole: No. In fact, Ghoul was being manipulated by the" 'br)
  (str "director, who was using him as a guinea pig for the" 'br)
  (str "reanimation serum.")
  (wait)
  (text-reset 1)
  (str "Cole: As Ghoul's body parts decayed, the director replaced" 'br)
  (str "them with machinery, until he became a full android. And" 'br)
  (str "one day, realizing his true power, Ghoul killed him.")
  (wait)
  (text-reset 1)
  (str "Cole: After that, Ghoul, who had planned to kill anyone" 'br)
  (str "with knowledge of the serum, tried to have Jack kill Doc.")
  (wait)
  (text-reset 1)
  (str "Cole: But Jack couldn't kill Doc, who he'd known for many" 'br)
  (str "years.")
  (wait)
  (text-reset 1)
  (str "Steve: ...")
  (wait)
  (text-reset 1)
  (str "Steve: So what happened to Cain?")
  (wait)
  (text-reset 1)
  (str "Cole: Oh, the story doesn't end there.")
  (wait)
  (text-reset 1)
  (str "Cole: We took refuge in the Central Hotel, but Ghoul" 'br)
  (str "ambushed us with zombies he controlled. The only survivors" 'br)
  (str "were me, Sheila, and a girl named Cathy.")
  (wait)
  (text-reset 1)
  (str "Steve: Ghoul killed them all...?")
  (wait)
  (text-reset 1)
  (str "Cole: Yes. And up until then, you could kill any zombie by" 'br)
  (str "shooting them in the head...but Killer was different.")
  (wait)
  (text-reset 1)
  (str "Steve: Different like how?")
  (wait)
  (text-reset 1)
  (str "Cole: Ghoul had me shoot Killer, who had kidnapped Sheila." 'br)
  (str "But even though I shot him in the head...he didn't die.")
  (wait)
  (text-reset 1)
  (str "Steve: What!?")
  (wait)
  (text-reset 1)
  (str "Cole: When you inject the serum into a corpse, it revives." 'br)
  (str "But when you inject it into a living person, they don't die.")
  (wait)
  (text-reset 1)
  (str "Steve: !?!")
  (wait)
  (text-reset 1)
  (str "Cole: Rather, it circulates through the body first and the" 'br)
  (str "heart stops. Then there's a brief period before brain death" 'br)
  (str "sets in.")
  (wait)
  (text-reset 1)
  (str "Cole: Then, the serum reacts with the brain to pull the" 'br)
  (str "person back to life. The heartbeat restarts, and the serum" 'br)
  (str "turns them into a superhuman...unknown to you or me.")
  (wait)
  (text-reset 1)
  (str "Steve: ...")
  (wait)
  (text-reset 1)
  (str "Cole: As Killer lay dying, he mentioned Ghoul had gone to" 'br)
  (str "his hideout, the Bayside Institute.")
  (wait)
  (text-reset 1)
  (str "Cole: There, a number of townsfolk were being held captive." 'br)
  (str "I saw my friend Cain trapped in a glass chamber.")
  (wait)
  (text-reset 1)
  (str "Cole: Ghoul had mixed the reanimation serum with other" 'br)
  (str "chemicals from the institute, turned it into a vapor, and" 'br)
  (str "then injected it into Cain's chamber...")
  (wait)
  (text-reset 1)
  (str "Steve: That's horrific.")
  (wait)
  (text-reset 1)
  (str "Cole: Ghoul was loving it the whole time. I can never" 'br)
  (str "forgive him.")
  (wait)
  (text-reset 1)
  (str "Steve: ...")
  (wait)
  (text-reset 1)
  (str "Cole: I fought with Ghoul on the first floor of the" 'br)
  (str "factory. But with his android body, I didn't stand a chance.")
  (wait)
  (text-reset 1)
  (str "Cole: And even worse, he had a laser cannon built into his" 'br)
  (str "arm. He shot me in the shoulder, and I thought I was done" 'br)
  (str "for...")
  (wait)
  (text-reset 1)
  (str "Cole: But then Cathy saved the day by blowing him up with" 'br)
  (str "plastic explosives.")
  (wait)
  (text-reset 1)
  (str "Steve: So those remains that I found are from...")
  (wait)
  (text-reset 1)
  (str "Cole: That's right.")
  (wait)
  (text-reset 1)
  (str "Cole: And that's it. That's all I can tell you.")
  (wait)
  (text-reset 1)
  (str "Steve: One more thing, Cole. Why did you come to Bar Rease?")
  (wait)
  (text-reset 1)
  (str "Cole: Earlier that night, two of our friends who had come" 'br)
  (str "to celebrate our engagement got killed. And their bodies..." 'br)
  (str "their brains were...eaten.")
  (wait)
  (text-reset 1)
  (str "Steve: The zombies crave human brains!?")
  (wait)
  (text-reset 1)
  (str "Cole: Yes, that's what they eat. And around the bodies," 'br)
  (str "there were traces of something similar to the reanimation" 'br)
  (str "serum.")
  (wait)
  (text-reset 1)
  (str "Cole: I spotted some on a Bloody Fox biker's tire, and I" 'br)
  (str "tracked them down...")
  (wait)
  (text-reset 1)
  (str "Steve: So you identified the serum as Purple Sky, then?")
  (wait)
  (text-reset 1)
  (str "Cole: Yeah.")
  (wait)
  (text-reset 1)
  (str "Steve: Does anyone else know about the existence of the" 'br)
  (str "reanimation serum?")
  (wait)
  (text-reset 1)
  (str "Cole: Just Sheila, and she has nothing to do with it.")
  (wait)
  (text-reset 1)
  (str "Steve: So aside from everyone you mentioned, there has to" 'br)
  (str "be another...")
  (wait)
  (text-reset 1)
  (str "Cole: No...it can't be...")
  (wait)
  (text-reset 1)
  (str "Steve: Two years ago, that person forced the Bayside" 'br)
  (str "Institute director and Ghoul into working for them.")
  (wait)
  (text-reset 1)
  (str "Steve: And it sounds to me like said mastermind has refined" 'br)
  (str "the serum as Purple Sky, and is channeling it through" 'br)
  (str "Bloody Fox...")
  (wait)
  (text-reset 1)
  (str "Cole: I thought we were the only people who knew about the" 'br)
  (str "serum, though.")
  (wait)
  (text-reset 1)
  (str "Steve: We'll need to keep investigating Bloody Fox to learn" 'br)
  (str "more about Purple Sky.")
  (wait)
  (text-reset 1)
  (str "Steve: Cole, I'm gonna need your help.")
  (wait)
  (text-reset 1)
  (str "Cole: And you can have it. For Doc's sake, we need to track" 'br)
  (str "down whoever the mastermind is here.")
  (wait)
  (text-reset 1)
  (str "Steve: I'll keep an eye on Rease for a while. You contact" 'br)
  (str "me if anything happens.")
  (wait)
  (text-reset 1)
  (str "Cole: Gotcha. I need to head home. Sheila must be worried" 'br)
  (str "sick about me.")
  (wait)
  (text-reset 1)
  (str "Steve: I understand.")
  (wait)
  (text-reset 1)
  (str "Cole: I'll see you later, then.")
  (wait)
  (text-reset 1)
  (sound '|| 2)									; Jump back to 014.MES starts here
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  ((cmd 209) 0 5)
  (image-file "A:¥GPC¥title.gpc")
  (image-mem 0 3)
  (exec-mem 912 "INIT")
  (exec-mem 912 "A 1")
  (text-frame 0 0 79 399)
  (text-reset 0)
  (exec-mem 912 "A 0")
  (exec-mem 912 "EXIT")
  (text-frame 0 0 79 399)
  (text-reset 0)
  (exec-mem 9920 0 6 6 113 64 8)
  ((cmd 204) 99 899)
  (sound '|| 0)
  ((cmd 209) 1)
  (mes-jump "A:¥MES¥015.MES"))
 (seg*))