(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (text
   "Steve: Cole, I can tell you were involved with the incident" 'br)
"in some way. Why don't you tell me what you know?")
  (wait)
  (text-reset 1)
  (str "Cole: Steve, why are you so desperate to discover what" 'br)
(str "happened?")
  (wait)
  (text-reset 1)
  (str "Steve: ...What do you mean?")
  (wait)
  (text-reset 1)
  (str "Cole: After hearing your story, I'm not convinced you're" 'br)
(str "officially investigating a cold case from two years ago.")
  (wait)
  (text-reset 1)
  (str "Steve: You're right.")
  (wait)
  (text-reset 1)
  (str "Steve: As you'd expect...Ghoul -- no, Richard Gris, was my" 'br)
(str "brother.")
  (wait)
  (text-reset 1)
  (str "Cole: !?!")
  (wait)
  (text-reset 1)
  (text
   "Steve: The first time you identified me as Ghoul and pointed" 'br)
"your gun at me, I realized you had something to do with my" 'br)
"brother. And the incident from two years ago...")
  (wait)
  (text-reset 1)
  (str "Cole: So that's what's happening here...")
  (wait)
  (text-reset 1)
  (text
   "Steve: I was proud of my brother. He was brilliant. It" 'br)
"wasn't abnormal for a detective to go deep undercover, but" 'br)
"he had completely disappeared two months before the" 'br)
"incident.")
  (wait)
  (text-reset 1)
  (str "Steve: He wasn't the type of the person who'd go that long" 'br)
(str "without any contact.")
  (wait)
  (text-reset 1)
  (text
   "Steve: I got the news that he'd been incommunicado, and just" 'br)
"as I was about to check with the 16th precinct, I got orders" 'br)
"to check on the neighboring town. If only I'd noticed" 'br)
"sooner...")
  (wait)
  (text-reset 1)
  (str "Cole: ...I get it. Let's talk about everything.")
  (wait)
  (text-reset 1)
  (str "Steve: Please, tell me what you know.")
  (wait)
  (text-reset 1)
  (str "Cole: Back then, I knew a scientist named Dr. Cooger.")
  (wait)
  (text-reset 1)
  (str "Steve: A scientist?")
  (wait)
  (text-reset 1)
  (str "Cole: Yeah. Back then he was primarily doing cancer cell" 'br)
(str "research.")
  (wait)
  (text-reset 1)
  (text
   "Cole: He'd come up with artificial organs and call me over" 'br)
"to his place to show me, all the time with this big goofy" 'br)
"grin.")
  (wait)
  (text-reset 1)
  (text
   "Cole: And one time he called me over to his house, and in" 'br)
"his lab, she showed me a drug that was a match for Purple" 'br)
"Sky.")
  (wait)
  (text-reset 1)
  (str "Steve: So it was purple?")
  (wait)
  (text-reset 1)
  (str "Cole: Yeah.")
  (wait)
  (text-reset 1)
  (str "Steve: And it's definitely the same thing on the inside of" 'br)
(str "that robot's cranium.")
  (wait)
  (text-reset 1)
  (str "Cole: He said that he invented a reanimation serum.")
  (wait)
  (text-reset 1)
  (str "Steve: A reanimation serum!?")
  (wait)
  (text-reset 1)
  (str "Cole: I know, I know, it sounds crazy.")
  (wait)
  (text-reset 1)
  (str "Steve: I don't think it sounds crazy.")
  (wait)
  (text-reset 1)
  (str "Cole: It isn't... He brought back a cat from the dead. But" 'br)
(str "it came back with a ferociousness that could kill a human.")
  (wait)
  (text-reset 1)
  (str "Cole: Then, we got a visit from Jack from Precinct 16...and" 'br)
(str "the cat killed him.")
  (wait)
  (text-reset 1)
  (str "Cole: ....")
  (wait)
  (text-reset 1)
  (str "Steve: Don't stop there.")
  (wait)
  (text-reset 1)
  (text
   "Cole: In his panic, Doc injected the serum into Jack's" 'br)
"corpse. I guess he thought if he brought him back to life," 'br)
"it wouldn't be murder. Well, murder by undead cat.")
  (wait)
  (text-reset 1)
  (str "Steve: ...")
  (wait)
  (text-reset 1)
  (text
   "Cole: But that experiment was a failure. Jack came back, and" 'br)
"attacked us. We ran back to my apartment and tried to figure" 'br)
"out what to do.")
  (wait)
  (text-reset 1)
  (str "Cole: Doc decided he'd turn himself in.")
  (wait)
  (text-reset 1)
  (text
   "Cole: I mean, even if I told the truth, nobody would believe" 'br)
"me, even though someone got killed. And then my fiancee ran" 'br)
"in.")
  (wait)
  (text-reset 1)
  (str "Cole: Her name is Sheila, and she saw a wandering corpse in" 'br)
(str "the middle of the street and ran away.")
  (wait)
  (text-reset 1)
  (str "Steve: In the street?")
  (wait)
  (text-reset 1)
  (str "Cole: Yeah, and when we were running away, Doc managed to" 'br)
(str "drop his bag containing the reanimation serum.")
  (wait)
  (text-reset 1)
  (str "Cole: At that point, the vial with the serum must have" 'br)
(str "shattered, and its contents seeped into the ground...")
  (wait)
  (text-reset 1)
  (str "Cole: Or maybe Jack had bitten someone else.")
  (wait)
  (text-reset 1)
  (str "Steve: Biting someone turns them into...a zombie?")
  (wait)
  (text-reset 1)
  (text
   "Cole: Yes. The reanimation serum can be passed on via mucous" 'br)
"membranes. If someone's bitten, they'll become a zombie in" 'br)
"just a few minutes. But there's more to it in terms of the" 'br)
"chemical contents...")
  (wait)
  (text-reset 1)
  (str "Cole: As I mentioned before, there's a substance similar to" 'br)
(str "embalming fluid that keeps the bodies from decomposing.")
  (wait)
  (text-reset 1)
  (str "Steve: So does that mean Jack was responsible for the" 'br)
(str "zombies?")
  (wait)
  (text-reset 1)
  (str "Cole: No, that's likely not the case.")
  (wait)
  (text-reset 1)
  (text
   "Cole: With zombies running through the streets and attacking" 'br)
"my apartment, we headed to Precinct 16, but it was too" 'br)
"late... It had already been overrun by zombies.")
  (wait)
  (text-reset 1)
  (text
   "Cole: In the chief's office, we found a memo that pointed us" 'br)
"in the direction of the Central Hotel. There we found five" 'br)
"survivors...and Ghoul.")
  (wait)
  (text-reset 1)
  (str "Cole: I guess whoever wrote the memo assumed that everyone" 'br)
(str "left alive would head to the police station.")
  (wait)
  (text-reset 1)
  (text
   "Cole: Ghoul took the lead, and we battled the zombies in an" 'br)
"attempt to find more survivors. But Doc got bitten by a" 'br)
"zombie...")
  (wait)
  (text-reset 1)
  (str "Steve: Did he turn?")
  (wait)
  (text-reset 1)
  (text
   "Cole: No... I shot him first. He insisted that he would turn" 'br)
"into a zombie and attack me, so I had to pull the trigger" 'br)
"before that happened.")
  (wait)
  (text-reset 1)
  (str "Steve: ...")
  (wait)
  (text-reset 1)
  (text
   "Cole: After that, I met a journalist from the city to the" 'br)
"West...his name was Cain. His own city had a similar" 'br)
"incident two months before, and that's why he showed up.")
  (wait)
  (text-reset 1)
  (str "Cole: ...Two months previous would put that at the same time" 'br)
(str "you mentioned, when Ghoul vanished.")
  (wait)
  (text-reset 1)
  (str "Steve: !?!")
  (wait)
  (text-reset 1)
  (str "Cole: From that point on, the number of zombies just" 'br)
(str "skyrocketed.")
  (wait)
  (text-reset 1)
  ((cmd 212))))