(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (text "Steve: So it was all Cooger's doing?")
  (wait)
  (text-reset 1)
  (text "Cole: The first human who Doc Cooger injected was Jack.")
  (wait)
  (text-reset 1)
  (text "Steve: Are you positive?")
  (wait)
  (text-reset 1)
  (text
   "Cole: I am. Another reason I don't think Jack was the first zombie is because someone had broken into Doc's lab beforehand...a man named Killer, one of Ghoul's underlings.")
  (wait)
  (text-reset 1)
  (text "Cole: Under Ghoul's orders, Killer stole the reanimation serum research and handed it off to the Bayside Research Institute director.")
  (wait)
  (text-reset 1)
  (text "Steve: The Institute director? So Ghoul was working with him?")
  (wait)
  (text-reset 1)
  (text "Cole: No. In fact, Ghoul was being manipulated by the director, who was using him as a guinea pig for the reanimation serum.")
  (wait)
  (text-reset 1)
  (text
   "Cole: As Ghoul's body parts lost their effectiveness, the director replaced them with machinery, to the point where Ghoul fully became an android. Then one day, realizing his true power, Ghoul killed him.")
  (wait)
  (text-reset 1)
  (text
   "Cole: After that, Ghoul, who had planned to kill anyone with knowledge of the serum, tried to have Jack kill Doc.")
  (wait)
  (text-reset 1)
  (text "Cole: But Jack couldn't kill Doc, who he'd known for many years.")
  (wait)
  (text-reset 1)
  (text "Steve: ...")
  (wait)
  (text-reset 1)
  (text "Steve: So what happened to Cain?")
  (wait)
  (text-reset 1)
  (text "Cole: Oh, the story doesn't end there.")
  (wait)
  (text-reset 1)
  (text
   "Cole: We were operating out of the Central Hotel, but Ghoul, with his control over the zombies, ambushed us. In the end, the only survivors were me, Sheila, and a girl named Cathy.")
  (wait)
  (text-reset 1)
  (text "Steve: Ghoul killed them all...?")
  (wait)
  (text-reset 1)
  (text "Cole: Yes. And up until then, you could kill any zombie by shooting them in the head...but Killer was different.")
  (wait)
  (text-reset 1)
  (text "Steve: Different like how?")
  (wait)
  (text-reset 1)
  (text
   "Cole: Ghoul had me shoot Killer, who had kidnapped Sheila. But even though I shot him in the head...he didn't die.")
  (wait)
  (text-reset 1)
  (text "Steve: What!?")
  (wait)
  (text-reset 1)
  (text "Cole: When you inject the serum into a corpse, it revives. But when you inject it into a living person, they don't die.")
  (wait)
  (text-reset 1)
  (text "Steve: !?!")
  (wait)
  (text-reset 1)
  (text "Cole: Rather, it circulates through the body first and the heart stops. Then there's a brief period before brain death sets in.")
  (wait)
  (text-reset 1)
  (text "Cole: In that short time, the reanimation serum reacts with the brain to pull the person back to life. The heart starts beating again, and the serum turns them into a superhuman, but indiscernible to you or me.")
  (wait)
  (text-reset 1)
  (text "Steve: ...")
  (wait)
  (text-reset 1)
  (text "Cole: As Killer lay dying, he mentioned Ghoul had gone to his hideout, the Bayside Institute.")
  (wait)
  (text-reset 1)
  (text "Cole: There, a number of townsfolk were being held captive. I saw my friend Cain trapped in a glass chamber.")
  (wait)
  (text-reset 1)
  (text
   "Cole: Ghoul had mixed the reanimation serum with other chemicals from the institute, turned it into a vapor, and then injected it into Cain's chamber...")
  (wait)
  (text-reset 1)
  (text "Steve: That's horrific.")
  (wait)
  (text-reset 1)
  (text "Cole: Ghoul was loving it the whole time. I can never forgive him.")
  (wait)
  (text-reset 1)
  (text "Steve: ...")
  (wait)
  (text-reset 1)
  (text "Cole: I fought with Ghoul on the first floor of the factory. But with his android body, I didn't stand a chance.")
  (wait)
  (text-reset 1)
  (text "Cole: And even worse, he had a laser cannon built into his arm. He shot me in the shoulder, and I thought I was done for...")
  (wait)
  (text-reset 1)
  (text "Cole: But then Cassie saved the day by blowing him up with plastic explosives.")
  (wait)
  (text-reset 1)
  (text "Steve: So those remains that I found are from...")
  (wait)
  (text-reset 1)
  (text "Cole: That's right.")
  (wait)
  (text-reset 1)
  (text "Cole: And that's it. That's all I can tell you.")
  (wait)
  (text-reset 1)
  (text "Steve: One more thing, Cole. Why did you come to Bar Rease?")
  (wait)
  (text-reset 1)
  (text
   "Cole: Earlier that night, two of our friends who had come to celebrate our engagement got killed. And their bodies...their brains were...eaten.")
  (wait)
  (text-reset 1)
  (text "Steve: Do the zombies crave human brains!?")
  (wait)
  (text-reset 1)
  (text "Cole: Yes, that's what they eat. And around the bodies, there were traces of something similar to the reanimation serum.")
  (wait)
  (text-reset 1)
  (text "Cole: I spotted some on a Bloody Fox biker's tire, and I tracked them down...")
  (wait)
  (text-reset 1)
  (text "Steve: So you identified the serum as Purple Sky, then?")
  (wait)
  (text-reset 1)
  (text "Cole: Yeah.")
  (wait)
  (text-reset 1)
  (text "Steve: Does anyone else know about the existence of the reanimation serum?")
  (wait)
  (text-reset 1)
  (text "Cole: Just Sheila, and she has nothing to do with it.")
  (wait)
  (text-reset 1)
  (text "Steve: So aside from everyone you mentioned, there has to be another...")
  (wait)
  (text-reset 1)
  (text "Cole: No...it can't be...")
  (wait)
  (text-reset 1)
  (text "Steve: Two years ago, that person forced the Bayside Institute director and Ghoul into working for them.")
  (wait)
  (text-reset 1)
  (text
   "Steve: And it sounds to me like said mastermind has refined the serum as Purple Sky, and is channeling it through Bloody Fox...")
  (wait)
  (text-reset 1)
  (text "Cole: I thought we were the only people who knew about the serum, though.")
  (wait)
  (text-reset 1)
  (text "Steve: We'll need to keep investigating Bloody Fox to learn more about Purple Sky.")
  (wait)
  (text-reset 1)
  (text "Steve: Cole, I'm gonna need your help.")
  (wait)
  (text-reset 1)
  (text "Cole: And you can have it. For Doc's sake, we need to track down whoever the mastermind is here.")
  (wait)
  (text-reset 1)
  (text "Steve: I'll keep an eye on Rease for a while. You contact me if anything happens.")
  (wait)
  (text-reset 1)
  (text "Cole: Gotcha. I need to head home. Sheila must be worried sick about me.")
  (wait)
  (text-reset 1)
  (text "Steve: I understand.")
  (wait)
  (text-reset 1)
  (text "Cole: I'll see you later, then.")
  (wait)
  (text-reset 1)
  ((cmd 212))))