(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB041.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 3 2 10 11)
  (exec-mem 3744 1 6 4 12 20 15)
  (exec-mem 3744 1 7 31 5 38 9)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB041.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (if (</>
       (//
        (? (= 134 #f))
        (sound '|| 0)
        (if (</>
             (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_09.USO"))
             (// (sound '|| "A:¥USO_D¥BR2_09.USO"))))
        (sound '|| 1))))
  (if (</>
       (//
        (? (= 135 #f))
        (str "Cole: Steve.")
        (wait)
        (text-reset 1)
        (str "Steve: Hey, Cole, come on in. Take a seat.")
        (wait)
        (text-reset 1)
        (str "Cole: It's okay, I'll stay standing.")
        (set-reg 135 #t)
        (wait)
        (text-reset 1))
       (// (str "Cole: I'm in the Investigation Division at Precinct 32.") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 136 #f))
   (str "Cole: Looks like that wall's been patched over.")
   (wait)
   (text-reset 1)
   (str "Steve: We had a perp go buckwild and he punched a hole in" 'br)
   (str "it. ")
   (wait)
   (text-reset 1)
   (str "Steve: Place was falling apart anyway, so I had them fix it" 'br)
   (str "all at once.")
   (wait)
   (text-reset 1)
   (str "Cole: He went berserk inside a police station? Now that's" 'br)
   (str "dedication. To something.")
   (wait)
   (text-reset 1)
   (str "Steve: Guy was a junkie, so you never know what'll make 'em" 'br)
   (str "snap.")
   (set-reg 136 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 137 #f))
   (str "Cole: There are vinyl sheets pasted over the wall.")
   (wait)
   (text-reset 1)
   (str "Steve: It's fine to do repairs, but how long are they" 'br)
   (str "planning to leave their equipment here?")
   (wait)
   (text-reset 1)
   (str "Cole: Oh yeah, look at that...there's even a red toolbox" 'br)
   (str "sitting here.")
   (set-reg 137 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (str "Steve: They need to finish the repairs sooner or later," 'br)
   (str "their tools are blocking the way.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 138 #f))
   (str "Cole: So this is your desk, Steve?")
   (wait)
   (text-reset 1)
   (str "Steve: Yeah, and ever since I joined, it's been getting" 'br)
   (str "more and more buried in desk work. I'd prefer to be on an" 'br)
   (str "actual investigation...")
   (wait)
   (text-reset 1)
   (str "Cole: Speaking of which, you're the boss around here," 'br)
   (str "aren't you?")
   (wait)
   (text-reset 1)
   (str "Steve: Who told you that?")
   (wait)
   (text-reset 1)
   (str "Cole: The guy downstairs.")
   (wait)
   (text-reset 1)
   (str "Steve: What a chatterbox.")
   (set-reg 138 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 139 #f))
   (str "Cole: A boss looks better if he's always at the station.")
   (wait)
   (text-reset 1)
   (str "Steve: Ha! Makes me happy to hear that.")
   (set-reg 139 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 140 #f))
   (str "Cole: Steve's desk is covered in various thick documents.")
   (wait)
   (text-reset 1)
   (str "Steve: Here, have a look.")
   (wait)
   (text-reset 1)
   (str "Cole: They're all files on Bloody Fox...")
   (wait)
   (text-reset 1)
   (str "Steve: And even with all these documents, we've only got a" 'br)
   (str "sliver of information on Purple Sky.")
   (wait)
   (text-reset 1)
   (str "Cole: If you're having trouble finding info, how am I gonna" 'br)
   (str "be of any help?")
   (set-reg 140 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (str "Steve: It's only a matter of time before we can pinpoint" 'br)
   (str "the source for this stuff.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 137 #t) (= 140 #t) (= 141 #t) (= 142 #f))
   (str "Steve: I wanted to get you to help with that too, but I" 'br)
   (str "still had some more investigating to do first.")
   (wait)
   (text-reset 1)
   (str "Cole: Actually, more importantly...")
   (wait)
   (text-reset 1)
   (str "Steve: Yeah?")
   (wait)
   (text-reset 1)
   (str "Cole: We talked about Sheila, didn't we?")
   (wait)
   (text-reset 1)
   (str "Steve: She's your fiancee, right? And you said she's" 'br)
   (str "connected to the incident too.")
   (wait)
   (text-reset 1)
   (str "Cole: Yes... Actually, when I got home yesterday, I found" 'br)
   (str "my place empty with a note saying she went looking for me.")
   (wait)
   (text-reset 1)
   (str "Steve: To Bar Rease?")
   (wait)
   (text-reset 1)
   (str "Cole: Yeah. I ran off to the bar, but by the time I" 'br)
   (str "arrived, Bloody Fox had already injected her with Purple" 'br)
   (str "Sky.")
   (wait)
   (text-reset 1)
   (str "Steve: Goddamn.")
   (set-reg 142 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 137 #t) (= 140 #t) (= 141 #t) (= 143 #f))
   (str "Cole: The main reason I'm here is because I'm worried about" 'br)
   (str "her getting injected with that junk. I wanted to ask you" 'br)
   (str "about what to expect.")
   (wait)
   (text-reset 1)
   (str "Steve: Did you see any symptoms?")
   (wait)
   (text-reset 1)
   (str "Cole: She blacked out for a little while, I think. And" 'br)
   (str "since she was about to get assaulted, she was traumatized" 'br)
   (str "to hell and back.")
   (wait)
   (text-reset 1)
   (str "Cole: I took her home, but she still seemed out of it.")
   (wait)
   (text-reset 1)
   (str "Steve: Well, Purple Sky isn't like weed in that it makes" 'br)
   (str "you trip, but it does temporarily increase blood flow to" 'br)
   (str "the brain.")
   (wait)
   (text-reset 1)
   (str "Steve: Sounds like Sheila had something like a mild" 'br)
   (str "concussion from it.")
   (set-reg 143 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 137 #t) (= 140 #t) (= 141 #t) (= 144 #f))
   (str "Cole: Steve, is Purple Sky capable of inflicting permanent" 'br)
   (str "damage?")
   (wait)
   (text-reset 1)
   (str "Steve: In the drug, the compound that revives cells--" 'br)
   (str "created by your buddy Dr. Cooger--is about half of what it" 'br)
   (str "usually is.")
   (wait)
   (text-reset 1)
   (str "Cole: So only fifty percent of the drug is the reanimation" 'br)
   (str "serum?")
   (wait)
   (text-reset 1)
   (str "Cole: Then what makes up the other fifty percent?")
   (wait)
   (text-reset 1)
   (str "Steve: Heroin.")
   (wait)
   (text-reset 1)
   (str "Cole: Fuck me!")
   (set-reg 144 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 137 #t) (= 140 #t) (= 141 #t))
   (str "Steve: Unless you're a regular heroin user, the effects on" 'br)
   (str "the body aren't too severe, but in the case of Purple Sky," 'br)
   (str "it sticks around in your bloodstream for a longer time.")
   (wait)
   (text-reset 1)
   (str "Steve: And that's the problem. A longer residence in the" 'br)
   (str "body creates the same effects as regular injections spread" 'br)
   (str "out over time.")
   (wait)
   (text-reset 1)
   (str "Steve: In other words, you'd get the equivalent of multiple" 'br)
   (str "injections' worth of damage in just one dose.")
   (wait)
   (text-reset 1)
   (str "Cole: ...")
   (wait)
   (text-reset 1)
   (str "Steve: Well, of course, it varies from person to person...")
   (wait)
   (text-reset 1)
   (str "Cole: What do you mean by \"damage?\"")
   (wait)
   (text-reset 1)
   (str "Steve: That's the scariest part of Purple Sky. You came at" 'br)
   (str "a good time, though, because I'm about to go see our" 'br)
   (str "researcher, Dr. Lisle.")
   (wait)
   (text-reset 1)
   (str "Steve: Would you like to come along?")
   (wait)
   (text-reset 1)
   (str "Cole: Yeah, of course.")
   (wait)
   (text-reset 1)
   (str "Steve: All right, let's head out.")
   (wait)
   (text-reset 1)
   (nop@)
   (set-reg 145 #t)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥022.MES"))
 (seg (? (= P 7) (= 141 #f))
   (str "Cole: Steve, I want to thank you again for yesterday. ")
   (wait)
   (text-reset 1)
   (str "Steve: It's nothing, I should be the one thanking you. You" 'br)
   (str "provided me with so much good info.")
   (set-reg 141 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (str "Steve: It's nothing, I should be the one thanking you. You" 'br)
   (str "provided me with so much good info.")
   (wait)
   (text-reset 1))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (nop@) (set-reg 134 #f) (flag-save 1))
        (/ (nop@) (set-reg 134 #f) (flag-save 2))
        (/ (nop@) (set-reg 134 #f) (flag-save 3))
        (/ (nop@) (set-reg 134 #f) (flag-save 4))
        (/ (nop@) (set-reg 134 #f) (flag-save 5))
        (/ (nop@) (set-reg 134 #f) (flag-save 6))
        (/ (nop@) (set-reg 134 #f) (flag-save 7))
        (/ (nop@) (set-reg 134 #f) (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))