; Dead of the Brain 2 (PC-98) - 023.MES
; Translated by Geometrizer
; Edited by trentsignia and JackDBS
; -----Scene:-----
; Cole meets Dr. Lisle inside the Perain Research Institute.
; --Progression:--
; Inspect everything, talk to Lisle, then MOVE.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB043.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)			; Hotspots and buttons defined here...
  (exec-mem 3744 1 1 80 0 0 0)							; 	MOVE button
  (exec-mem 3744 1 2 80 0 0 0)							; 	SYSTEM button
  (exec-mem 3744 1 5 16 3 21 7)							; 	Lisle
  (exec-mem 3744 1 6 38 2 44 6)							; 	Steve
  (exec-mem 3744 1 7 25 2 34 7)							; 	Lab
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB043.GPC") (image-mem 0 3)
  (image-file "B:¥GPC¥DB044.GPC") (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC") (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 153 #f))								; Lead-in from previous MES script
        (str "Steve: Let me introduce you both. This is Dr. Lisle from" 'br)
        (str "the Perain Institute's Pharmaceutical Development" 'br)
        (str "Department.")
        (wait)
        (text-reset 1)
        (str "Cole: Nice to meet you, I'm Cole.")
        (wait)
        (text-reset 1)
        (str "Lisle: Hey, glad you could make it.")
        (set-reg 153 #t)
        (wait)
        (text-reset 1))
       (//
        (str "Cole: This is the Perain Pharmaceutical Development" 'br)		; Lead-in from loading game
        (str "Department, and we're in Dr. Lisle's lab.")
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 161 #f))			; Lisle (after inspecting everything) #1
   (str "Cole: I hate to ask so abruptly, but I have to know. What" 'br)
   (str "happens to someone when they're injected with Purple Sky?")
   (wait)
   (text-reset 1)
   (str "Lisle: Well, before I can tell you that, I'd like to hear" 'br)
   (str "about the person you mentioned to Steve...the one who made" 'br)
   (str "the Reanimation Serum.")
   (wait)
   (text-reset 1)
   (str "Steve: We talked about it over the phone.")
   (wait)
   (text-reset 1)
   (str "Lisle: It was from a scientist named Cooger, who mainly" 'br)
   (str "conducted research on cancer cells...")
   (wait)
   (text-reset 1)
   (str "Cole: That's right, Dr. Lisle. He was a brilliant" 'br)
   (str "scientist, but...")
   (wait)
   (text-reset 1)
   (str "Lisle: I was a bit curious. You see, I once worked under a" 'br)
   (str "scientist named Cooger. I wanted to know if it was the same" 'br)
   (str "one.")
   (wait)
   (text-reset 1)
   (str "Cole: Could it be...?")
   (set-reg 161 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 162 #f))			; Lisle (after inspecting everything) #2
   (str "Lisle: What was Cooger's last name?")
   (wait)
   (text-reset 1)
   (str "Cole: Hamilton. Cooger Hamilton.")
   (wait)
   (text-reset 1)
   (str "Lisle: So that's how it is... Yes, I remember him well.")
   (wait)
   (text-reset 1)
   (str "Cole: No way... You were Doc's assistant?")
   (set-reg 162 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 163 #f))			; Lisle (after inspecting everything) #3
   (str "Lisle: I worked in the same lab as him for two years. His" 'br)
   (str "research was staggering. I was always amazed by his results.")
   (wait)
   (text-reset 1)
   (str "Lisle: He was constantly one step ahead, and it ate at me." 'br)
   (str "I always hoped to surpass him one day.")
   (wait)
   (text-reset 1)
   (str "Lisle: At that time, he had a wife named Mary, but she died" 'br)
   (str "in a tragic traffic accident.")
   (wait)
   (text-reset 1)
   (str "Lisle: Back then, he was deeply depressed, but he often" 'br)
   (str "reassured me, and maybe himself, saying“I have reliable" 'br)
   (str "companions.”")
   (wait)
   (text-reset 1)
   (str "Lisle: But of all things, he wound up creating a" 'br)
   (str "Reanimation Serum... I'll never be able to surpass that, no" 'br)
   (str "matter how hard I try.")
   (wait)
   (text-reset 1)
   (str "Cole: ...")
   (set-reg 163 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 164 #f))			; Lisle (after inspecting everything) #4
   (str "Steve: Lisle, there's something else. Yesterday, Cole's" 'br)
   (str "fiancee was injected with Purple Sky.")
   (wait)
   (text-reset 1)
   (str "Lisle: I see. At what time?")
   (wait)
   (text-reset 1)
   (str "Cole: Around 3:30AM.")
   (wait)
   (text-reset 1)
   (str "Lisle: What was her name...Stella...Shelly...?")
   (wait)
   (text-reset 1)
   (str "Cole: Sheila.")
   (wait)
   (text-reset 1)
   (str "Lisle: I see. So what was her reaction to it?")
   (wait)
   (text-reset 1)
   (str "Cole: She lost consciousness right after those Bloody Fox" 'br)
   (str "bastards injected her. She said she was fine when she came" 'br)
   (str "to, but...")
   (set-reg 164 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 165 #f))			; Lisle (after inspecting everything) #5
   (str "Lisle: I hope the potency of the Purple Sky was..." 'br)
   (str "suboptimal, for her sake.")
   (wait)
   (text-reset 1)
   (str "Cole: Potency?")
   (wait)
   (text-reset 1)
   (str "Lisle: Purple sky is cut with heroin, which lessens the" 'br)
   (str "effect of the reanimation serum. So the risk of..." 'br)
   (str "reanimation...is low.")
   (wait)
   (text-reset 1)
   (str "Lisle: It's dependent on how much of the bacterium DNV," 'br)
   (str "which is produced by mixing heroin with the serum, has" 'br)
   (str "multiplied.")
   (wait)
   (text-reset 1)
   (str "Cole: DNV...?")
   (set-reg 165 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 166 #f))			; Lisle (after inspecting everything) #6
   (str "Lisle: It comes down to the length of time between the" 'br)
   (str "refinement of the Purple Sky and the time of injection;" 'br)
   (str "that's when the DNV multiplies.")
   (wait)
   (text-reset 1)
   (str "Lisle: To put it simply, DNV keeps multiplying when it's in" 'br)
   (str "the unused Purple Sky, but once injected into the human" 'br)
   (str "body, it dies off within several hours.")
   (wait)
   (text-reset 1)
   (str "Lisle: However, if the DNV had the time to grow" 'br)
   (str "significantly before injection, it can develop a resistance" 'br)
   (str "and survive.")
   (wait)
   (text-reset 1)
   (str "Lisle: DNV's resilience likely comes from Cooger's" 'br)
   (str "reanimation serum. Without resistance, bacteria injected" 'br)
   (str "into a corpse would die almost immediately.")
   (wait)
   (text-reset 1)
   (str "Lisle: That resistance is what's needed for staying alive" 'br)
   (str "in a corpse.")
   (set-reg 166 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 167 #f))			; Lisle (after inspecting everything) #7
   (str "Lisle: It varies by person, but if DNV gets to the brain," 'br)
   (str "fainting is just the start. The body numbs and weakens.")
   (wait)
   (text-reset 1)
   (str "Lisle: Since the drug is so fast-acting, if Sheila is awake" 'br)
   (str "and speaking, there's not much reason for concern. But if" 'br)
   (str "you're still worried, feel free to bring her here.")
   (wait)
   (text-reset 1)
   (str "Lisle: We can run a blood test on her.")
   (wait)
   (text-reset 1)
   (str "Steve: Where is she now?")
   (wait)
   (text-reset 1)
   (str "Cole: I tried calling her, but I guess she's out.")
   (set-reg 167 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t))				; Lisle (after inspecting everything) #8 (repeat line)
   (str "Steve: We should do this sooner than later. Can we get her" 'br)
   (str "blood soon?")
   (wait)
   (text-reset 1)
   (str "Cole: Right. She should be home soon, so I'll bring her in.")
   (set-reg 168 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 154 #f))							; Lisle #1
   (str "Lisle: I must let you know Steve filled me in on your" 'br)
   (str "situation. It really is...unfortunate.")
   (wait)
   (text-reset 1)
   (str "Cole: Yeah, it sure is...")
   (wait)
   (text-reset 1)
   (str "Steve: Cole's tough as nails to have made it this far.")
   (set-reg 154 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #f))							; Lisle #2
   (str "Lisle: If there's anything I can do, let me know.")
   (wait)
   (text-reset 1)
   (str "Steve: Lisle's the one in charge of the lab. He's a" 'br)
   (str "dependable guy.")
   (set-reg 155 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))								; Lisle #3 (repeat line)
   (str "Cole: This Lisle guy...I think I can trust him.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 168 #t))							; Steve (after talking to Lisle)
   (str "Steve: It's wild that Lisle wound up being the assistant to" 'br)
   (str "your doctor buddy who came up with the reanimation serum.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 156 #f))							; Steve #1
   (str "Steve: When it comes to Purple Sky, Dr. Lisle knows" 'br)
   (str "everything...except where it came from.")
   (wait)
   (text-reset 1)
   (str "Lisle: I haven't been able to return to my normal pharma" 'br)
   (str "research ever since I started investigating Purple Sky.")
   (set-reg 156 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 157 #f))							; Steve #2
   (str "Steve: I already filled in Dr. Lisle about your situation" 'br)
   (str "over the phone yesterday. We're safe in trusting him with" 'br)
   (str "that information.")
   (wait)
   (text-reset 1)
   (str "Cole: That's good to hear.")
   (wait)
   (text-reset 1)
   (str "Lisle: I'll keep things discreet.")
   (set-reg 157 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))								; Steve #3 (repeat line)
   (str "Steve: If you want to know about Purple Sky, Lisle is far" 'br)
   (str "more well informed than me.")
   (wait)
   (text-reset 1)
   (str "Lisle: Ask me anything you want to know.")
   (set-reg 158 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 159 #f))							; Lab #1
   (str "Cole: Hell of a lab you have here.")
   (wait)
   (text-reset 1)
   (str "Steve: It doesn't matter what the drug is, if you ask" 'br)
   (str "Lisle, he can tell you what it's made from.")
   (wait)
   (text-reset 1)
   (str "Lisle: That's thanks to all the equipment I have here. In" 'br)
   (str "theory, I could create potent drugs that leave no trace.")
   (wait)
   (text-reset 1)
   (str "Steve: Hey now, don't go talking about weird stuff.")
   (wait)
   (text-reset 1)
   (str "Cole: Could you make the reanimation serum?")
   (wait)
   (text-reset 1)
   (str "Lisle: Ah, that's beyond even me. The person who came up" 'br)
   (str "with that is a genius.")
   (set-reg 159 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 160 #f))							; Lab #2
   (str "Cole: I see a door on the left...")
   (wait)
   (text-reset 1)
   (str "Lisle: That leads to my private lab. It's locked so" 'br)
   (str "intruders can't get in.")
   (wait)
   (text-reset 1)
   (str "Steve: Don't feel bad, Cole, I'm not allowed in there" 'br)
   (str "either.")
   (wait)
   (text-reset 1)
   (str "Lisle: There are things I would prefer others not see.")
   (set-reg 160 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))								; Lab #3 (repeat line)
   (str "Cole: There's lots of gadgets set up along the walls." 'br)
   (str "Definitely a laboratory vibe.")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 168 #t))							; MOVE (after )
   (exec-mem 6064 2 1)
   (str "Cole: All right, I'll head over to Sheila's apartment and" 'br)
   (str "bring her back. I'll see you soon.")
   (wait)
   (text-reset 1)
   (str "Lisle: I'll be here, so come back anytime.")
   (wait)
   (text-reset 1)
   (str "Cole: I haven't been to Sheila's apartment in a while...")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥024.MES"))
 (seg (? (= P 2))								; SYSTEM
   (exec-mem 6064 2 2)
   (menu1
    25 317  39 317  53 317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))