(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB043.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 16 3 21 7)
  (exec-mem 3744 1 6 38 2 44 6)
  (exec-mem 3744 1 7 25 2 34 7)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB043.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB044.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 153 #f))
        (text "［スティーブ］紹介しよう、こちらがピレイン薬品開発部のライル　　　　　　　博士だ。")
        (wait)
        (text-reset 1)
        (text "［コール］初めまして、コールです。")
        (wait)
        (text-reset 1)
        (text "［ライル］やあ、よく来たね。")
        (set-reg 153 #t)
        (wait)
        (text-reset 1))
       (// (text "［コール］ここはピレイン化学研究所、ライルさんの研究室だ。") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 161 #f))
   (text "［コール］早速ですが、ライルさん。パープル・スカイを打たれた　　　　　時の身体の影響を知りたいんですが・・・。")
   (wait)
   (text-reset 1)
   (text "［ライル］その前に、君がスティーブに話してくれた蘇生薬を作っ　　　　　た人物というのを聞きたいな。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］それは電話で話した筈だが・・・。")
   (wait)
   (text-reset 1)
   (text "［ライル］クーガーという科学者と聞いた。主に癌細胞の研究をし　　　　　ているとね・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］そうです、ライルさんの言うとおり彼は優秀な科学者で　　　　　した。でも、それが何か？")
   (wait)
   (text-reset 1)
   (text
    "［ライル］ちょっと気になってね・・・。実は私も以前、クーガー　　　　　という名前の科学者の下で働いていた事があったんだ。　　　　　それで確認したかったんでな。")
   (wait)
   (text-reset 1)
   (text "［コール］まさか・・・！？")
   (set-reg 161 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 162 #f))
   (text "［ライル］クーガー博士の性は何ていうのかね？")
   (wait)
   (text-reset 1)
   (text "［コール］ハミルトン・・・クーガー・ハミルトンです。")
   (wait)
   (text-reset 1)
   (text "［ライル］やはりそうか・・・。彼の事は今でも覚えているよ。")
   (wait)
   (text-reset 1)
   (text "［コール］そんな・・・ライルさんがドクの助手をしていたなんて　　　　　・・・。")
   (set-reg 162 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 163 #f))
   (text "［ライル］彼とは２年ほど同じ研究所にいた事があるよ。彼の研究　　　　　はこの私でも目を見張るものがあった。")
   (wait)
   (text-reset 1)
   (text
    "［ライル］いつも私の一歩先を研究していたのが、私は酷くくやし　　　　　がった事を覚えている。いつか追い抜いてやろうと思っ　　　　　ていたがね。")
   (wait)
   (text-reset 1)
   (text "［ライル］当時、メアリーという奥さんがいたが交通事故で亡くな　　　　　ってしまったんだ。")
   (wait)
   (text-reset 1)
   (text "［ライル］あの時は酷く落ち込んでいたが「私には信頼できる仲間　　　　　がいるから」ってよく私に言い聞かせてくれたよ。")
   (wait)
   (text-reset 1)
   (text "［ライル］しかし、よりによって彼が蘇生薬を作ったとは・・・。　　　　　私は一生かけても彼を追い抜く事はできそうにないな。")
   (wait)
   (text-reset 1)
   (text "［コール］・・・・・・・・・。")
   (set-reg 163 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 164 #f))
   (text "［スティーブ］ライル、それより昨日コールのフィアンセがパープ　　　　　　　ル・スカイを打たれてしまったんだ。")
   (wait)
   (text-reset 1)
   (text "［ライル］パープル・スカイを？　何時頃だ？")
   (wait)
   (text-reset 1)
   (text "［コール］夜中の３時半頃です。")
   (wait)
   (text-reset 1)
   (text "［ライル］彼女の名前はシ・・・シ・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］シーラです。")
   (wait)
   (text-reset 1)
   (text "［ライル］そうだった。それでシーラの様子はどうだったかね？")
   (wait)
   (text-reset 1)
   (text
    "［コール］ブラッディフォックスの奴等に薬を打たれた直後、失神　　　　　してしまったようでした。目を覚ました時には、もう大　　　　　丈夫だと言ってましたが・・・。")
   (set-reg 164 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 165 #f))
   (text "［ライル］パープル・スカイの純度が高くなければいいが・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］純度？")
   (wait)
   (text-reset 1)
   (text
    "［ライル］ああ、純度が高いといっても実際に流れている物はヘロ　　　　　インを混合しているため、蘇生薬をそのまま打った物よ　　　　　りは遥かに低いから蘇生の心配はまずないだろう。")
   (wait)
   (text-reset 1)
   (text
    "［ライル］だが、ヘロインと蘇生薬を混合させる事によって出来る　　　　　細菌「ＤＮＶ」が、どのくらい増えているかにかかって　　　　　くるんだ。")
   (wait)
   (text-reset 1)
   (text "［コール］ＤＮＶ・・・。")
   (set-reg 165 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 166 #f))
   (text
    "［ライル］パープル・スカイが精製される時から、実際に打たれる　　　　　までにかかる時間によってＤＮＶがどのくらい育つかに　　　　　よる訳だよ。")
   (wait)
   (text-reset 1)
   (text
    "［ライル］判りやすく言えば、ＤＮＶはパープル・スカイに入って　　　　　いる間はずっと育っているが人間の体内に入ると数時間　　　　　で死んでしまう。")
   (wait)
   (text-reset 1)
   (text
    "［ライル］しかし、ＤＮＶがかなり増えてしまった時に打った場合　　　　　にだけ、一部のＤＮＶは抵抗力が増して生き続ける事が　　　　　できるんだ。")
   (wait)
   (text-reset 1)
   (text
    "［ライル］この細菌の抵抗力はクーガー博士の蘇生薬にある物だろ　　　　　う。死体に打った菌は抵抗力がないとすぐに消滅してし　　　　　まう。")
   (wait)
   (text-reset 1)
   (text "［ライル］死体の中で生き続けさせるには、決して欠かす事のでき　　　　　ないものだからな。")
   (set-reg 166 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 167 #f))
   (text
    "［ライル］人によってまちまちだが、脳に送る血液にＤＮＶが入っ　　　　　てしまったら、まず失神なんかじゃ済まないだろう。　　　　　　身体が痺れて次第に衰弱してくるよ。")
   (wait)
   (text-reset 1)
   (text
    "［ライル］薬が即効性なだけに、シーラ君のように普通に話せるよ　　　　　うだったらまず心配はないと思うがね。それでも心配な　　　　　ら、一度この研究所にシーラ君を連れてくるといい。")
   (wait)
   (text-reset 1)
   (text "［ライル］彼女の血液を検査してあげるよ。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］彼女は今どこに？")
   (wait)
   (text-reset 1)
   (text "［コール］さっき電話してみたんですが、丁度出かけているようで　　　　　した。")
   (set-reg 167 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t))
   (text "［スティーブ］こういう事は早い方がいい。シーラの血液を診ても　　　　　　　らったらどうだ？")
   (wait)
   (text-reset 1)
   (text "［コール］そうですね、もう帰っている頃だと思いますから、一度　　　　　連れてきます。")
   (set-reg 168 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 154 #f))
   (text "［ライル］スティーブから君の事は聞かせて貰ったよ。不幸な事件　　　　　だったね。")
   (wait)
   (text-reset 1)
   (text "［コール］え、ええ・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］そんな中で生き抜いて来たコールは実にたくましい　　　　　　　よ。")
   (set-reg 154 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #f))
   (text "［ライル］私にできる事なら何でも言ってくれ。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］こう見えてもライルは、この研究室を任せられてい　　　　　　　るんだ。なかなか頼もしい奴だよ。")
   (set-reg 155 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5)) (text "［コール］ライルさんか・・・なかなか頼れそうな人だな。") (wait) (text-reset 1))
 (seg (? (= P 6) (= 168 #t))
   (text "［スティーブ］まさかライルが、蘇生薬を作った博士の助手だった　　　　　　　とはな・・・。")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 156 #f))
   (text "［スティーブ］ライル博士なら、パープル・スカイの事は何でも知　　　　　　　っているよ。出所以外なら・・・な。")
   (wait)
   (text-reset 1)
   (text "［ライル］パープル・スカイを調べだしたお陰で、いつまで経って　　　　　も薬品開発の研究に戻れないがね。")
   (set-reg 156 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 157 #f))
   (text "［スティーブ］コールの事は、昨日電話でライルに話してあるよ。　　　　　　　なに、こいつは信じれる男だから大丈夫だ。")
   (wait)
   (text-reset 1)
   (text "［コール］宜しくお願いします。")
   (wait)
   (text-reset 1)
   (text "［ライル］こちらこそ。")
   (set-reg 157 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "［スティーブ］パープル・スカイの事を聞きたいのなら、私よりラ　　　　　　　イルの方が正確だよ。")
   (wait)
   (text-reset 1)
   (text "［ライル］私の知っている事なら何でも聞いてくれ。")
   (set-reg 158 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 159 #f))
   (text "［コール］すごい研究室だな・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］どんな薬だろうが、ライルに頼めばその成分が何で　　　　　　　も判ってしまうよ。")
   (wait)
   (text-reset 1)
   (text "［ライル］これだけの研究室があるからさ。まあ、この研究室があ　　　　　れば証拠の残らない劇薬が作れるよ。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］おいおい、あまり変な事を教えるなよ。")
   (wait)
   (text-reset 1)
   (text "［コール］蘇生薬も？")
   (wait)
   (text-reset 1)
   (text "［ライル］蘇生薬だけは残念ながら私にも無理だな。それを作った　　　　　人は、まさに天才だよ。")
   (set-reg 159 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 160 #f))
   (text "［コール］左側にドアが見えるが・・・。")
   (wait)
   (text-reset 1)
   (text "［ライル］あのドアの先は私のプライベート・ルームだよ。侵入者　　　　　がいても入れないようにドアロックがしてあるがね。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］あの部屋にだけは私も入れてもらえないんだ。")
   (wait)
   (text-reset 1)
   (text "［ライル］誰でも見せたくないものはあるんだ。")
   (set-reg 160 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "［コール］たくさんの装置が壁際に設置されている。いかにも研究　　　　　室といった感じだな。")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 168 #t))
   (exec-mem 6064 2 1)
   (text "［コール］じゃあ、彼女のマンションに行って、シーラを連れてき　　　　　ますので、俺はこれで失礼します。")
   (wait)
   (text-reset 1)
   (text "［ライル］私はずっとここにいるから、いつでもいらっしゃい。")
   (wait)
   (text-reset 1)
   (text "［コール］シーラのマンションに行くのは久しぶりだな・・・。")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥024.MES"))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))