(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB043.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 16 3 21 7)
  (exec-mem 3744 1 6 38 2 44 6)
  (exec-mem 3744 1 7 25 2 34 7)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB043.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB044.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 153 #f))
        (text "Steve: Let me introduce you both. This is Dr. Lisle from thePerain Institute's Pharmaceutical Development Department.")
        (wait)
        (text-reset 1)
        (text "Cole: Nice to meet you. Cole.")
        (wait)
        (text-reset 1)
        (text "Lisle: Hey, glad you could make it.")
        (set-reg 153 #t)
        (wait)
        (text-reset 1))
       (// (text "Cole: This is the Perain Pharmaceutical Development         Department. This is Dr. Lisle's lab.") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 161 #f))
   (text "Cole: I hate to ask so abruptly, but I have to know. What   happens to someone when they're injected with Purple Sky?")
   (wait)
   (text-reset 1)
   (text "Lisle: Well, before I can tell you that, I'd like to hear   about the person you mentioned to Steve...the one who made  the Reanimation Serum.")
   (wait)
   (text-reset 1)
   (text "Steve: We had talked about it over the phone.")
   (wait)
   (text-reset 1)
   (text "Lisle: It was from a scientist named Cooger, who mainly     conducted research on cancer cells...")
   (wait)
   (text-reset 1)
   (text "Cole: That's right, Dr. Lisle. He was a brilliant scientist,but...")
   (wait)
   (text-reset 1)
   (text
    "Lisle: I was a bit curious. You see, I once worked under a  scientist named Cooger. I wanted to know if it was the same one.")
   (wait)
   (text-reset 1)
   (text "Cole: No way...?")
   (set-reg 161 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 162 #f))
   (text "Lisle: What was Cooger's first name?")
   (wait)
   (text-reset 1)
   (text "Cole: Hamilton. Hamilton Cooger.")
   (wait)
   (text-reset 1)
   (text "Lisle: So that's how it is... Yes, I remember him well.")
   (wait)
   (text-reset 1)
   (text "Cole: No way... You were Doc's assistant?")
   (set-reg 162 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 163 #f))
   (text "Lisle: I worked in the same lab as him for two years. His   research was staggering. I was always amazed by his results.")
   (wait)
   (text-reset 1)
   (text
    "Lisle: He was constantly one step ahead, and it ate at me. Ialways hoped to surpass him one day.")
   (wait)
   (text-reset 1)
   (text "Lisle: At that time, he had a wife named Mary, but she died in a tragic traffic accident.")
   (wait)
   (text-reset 1)
   (text "Lisle: He fell into a state of depression, but kept telling me how he had friends he could trust, to console himself.")
   (wait)
   (text-reset 1)
   (text "Lisle: But of all things, he wound up creating a ReanimationSerum... I'll never be able to surpass that, no matter how hard I   try.")
   (wait)
   (text-reset 1)
   (text "Cole: ...")
   (set-reg 163 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 164 #f))
   (text "Steve: Lisle, there's something else. Yesterday, Cole's     fiancee was injected with Purple Sky.")
   (wait)
   (text-reset 1)
   (text "Lisle: I see. At what time?")
   (wait)
   (text-reset 1)
   (text "Cole: Around 3:30am.")
   (wait)
   (text-reset 1)
   (text "Lisle: What was her name...Stella...Shelly...?")
   (wait)
   (text-reset 1)
   (text "Cole: Sheila.")
   (wait)
   (text-reset 1)
   (text "Lisle: I see. So what was her reaction to it?")
   (wait)
   (text-reset 1)
   (text
    "Cole: She lost consciousness right after those Bloody Fox   bastards injected her. She said she was fine when she came  to, but...")
   (set-reg 164 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 165 #f))
   (text "Lisle: I hope the potency of the Purple Sky                 was...suboptimal, for her sake.")
   (wait)
   (text-reset 1)
   (text "Cole: Potency?")
   (wait)
   (text-reset 1)
   (text
    "Lisle: Even if it's classified as high potency, what's      actually circulating is laced with heroin, which lessens theeffect of the reanimation serum. So the risk of...reanimation...islow.")
   (wait)
   (text-reset 1)
   (text
    "Lisle: It's dependent on how much of the bacterium DNV,     which is produced by mixing heroin with the serum, has      multiplied.")
   (wait)
   (text-reset 1)
   (text "Cole: DNV...?")
   (set-reg 165 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 166 #f))
   (text
    "Lisle: It comes down to the length of time between the      refinement of the Purple Sky and the time of injection;     that's when the DNV multiplies.")
   (wait)
   (text-reset 1)
   (text
    "Lisle: To put it simply, DNV keeps multiplying when it's in the unused Purple Sky, but once injected into the human     body, it dies off within several hours.")
   (wait)
   (text-reset 1)
   (text
    "Lisle: However, if the DNV has had the time to grow         significantly before injection, it can develop a resistance and survive.")
   (wait)
   (text-reset 1)
   (text
    "Lisle: DNV's resilience likely comes from the efficacy of   Dr. Cooger's reanimation serum. Without resistance, bacteriainjected into a dead body would die almost immediately.")
   (wait)
   (text-reset 1)
   (text "Lisle: That resistance is what's needed for staying alive ina corpse.")
   (set-reg 166 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t) (= 167 #f))
   (text
    "Lisle: Depending on the person, if DNV entered the          bloodstream and reached the brain, fainting would just be   the start. The body would go numb and deteriorate from      there.")
   (wait)
   (text-reset 1)
   (text
    "Lisle: Since the drug is so fast-acting, if Sheila is awake and speaking, there's not much reason for concern. But if   you're still worried, feel free to bring her here.")
   (wait)
   (text-reset 1)
   (text "Lisle: We can run a blood test on her.")
   (wait)
   (text-reset 1)
   (text "Steve: Where is she now?")
   (wait)
   (text-reset 1)
   (text "Cole: I tried calling her, but I guess she's out.")
   (set-reg 167 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #t) (= 157 #t) (= 160 #t))
   (text "Steve: We should do this sooner than later. Can we get her  blood soon?")
   (wait)
   (text-reset 1)
   (text "Cole: Right. She should be home soon, so I'll bring her in.")
   (set-reg 168 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 154 #f))
   (text "Lisle: I must let you know Steve filled me in on your       situation. It really is...unfortunate.")
   (wait)
   (text-reset 1)
   (text "Cole: Yeah, it sure is...")
   (wait)
   (text-reset 1)
   (text "Steve: Cole's tough as nails to have made it this far.")
   (set-reg 154 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 155 #f))
   (text "Lisle: If there's anything I can do, let me know.")
   (wait)
   (text-reset 1)
   (text "Steve: Lisle's the one in charge of the lab. He's a         dependable guy.")
   (set-reg 155 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5)) (text "Cole: This Lisle guy...I think I can trust him.") (wait) (text-reset 1))
 (seg (? (= P 6) (= 168 #t))
   (text "Steve: It's wild that Lisle wound up being the assistant to your doctor buddy who came up with the reanimation serum.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 156 #f))
   (text "Steve: When it comes to Purple Sky, Dr. Lisle knows         everything...except where it came from.")
   (wait)
   (text-reset 1)
   (text "Lisle: I haven't been able to return to my normal pharma    research ever since I started investigating Purple Sky.")
   (set-reg 156 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 157 #f))
   (text "Steve: I already filled in Dr. Lisle about your situation   over the phone yesterday. We're safe in trusting him with   that information.")
   (wait)
   (text-reset 1)
   (text "Cole: Take care.")
   (wait)
   (text-reset 1)
   (text "Lisle: You too.")
   (set-reg 157 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "Steve: If you want to know about Purple Sky, Lisle is far   more well informed than me.")
   (wait)
   (text-reset 1)
   (text "Lisle: Ask me anything you want to know.")
   (set-reg 158 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 159 #f))
   (text "Cole: Hell of a lab you have here.")
   (wait)
   (text-reset 1)
   (text "Steve: It doesn't matter what the drug is, if you ask Lisle,he can tell you what it's made from.")
   (wait)
   (text-reset 1)
   (text "Lisle: Thanks to all the equipment I have here. I can also  create potent drugs that leave no trace.")
   (wait)
   (text-reset 1)
   (text "Steve: Hey now, don't go talking about the weird stuff.")
   (wait)
   (text-reset 1)
   (text "Cole: Could you make the reanimation serum?")
   (wait)
   (text-reset 1)
   (text "Lisle: Ah, that's beyond even me. The person who came up    with that is a genius.")
   (set-reg 159 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 160 #f))
   (text "Cole: I see a door on the left...")
   (wait)
   (text-reset 1)
   (text "Lisle: That leads to my private lab. It's locked so         intruders can't get in.")
   (wait)
   (text-reset 1)
   (text "Steve: Don't feel bad, Cole, I'm not allowed in there       either.")
   (wait)
   (text-reset 1)
   (text "Lisle: There are things I would prefer others not see.")
   (set-reg 160 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "Cole: There's lots of gadgets set up along the walls.       Definitely a laboratory vibe.")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 168 #t))
   (exec-mem 6064 2 1)
   (text "Cole: All right, I'll head over to Sheila's apartment and   bring her back. I'll see you soon.")
   (wait)
   (text-reset 1)
   (text "Lisle: I'll be here, so come back anytime.")
   (wait)
   (text-reset 1)
   (text "Cole: I haven't been to Sheila's apartment in a while...")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥024.MES"))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))