(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (image-file "B:¥GPC¥DB047.GPC")
  (str "Cole: I've made it to the 9th floor.")
  (wait)
  (text-reset 1)
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (str "Cole: Huh? I smell disinfectant...")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (str "Cole: Was that the guy from earlier...? In a fancy" 'br)
  (str "apartment like this, there's all kinds of different people," 'br)
  (str "I guess.")
  (wait)
  (text-reset 1)
  (str "Cole: Sheila's door is open. She's already back, huh?")
  (wait)
  (text-reset 1)
  (str "Cole: Sheila, it's me!")
  (wait)
  (text-reset 1)
  (sound '|| 2)
  (mes-jump "A:¥MES¥026.MES"))
 (seg*))