(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (image-file "B:¥GPC¥DB047.GPC")
  (text "Cole: I've made it to the 9th floor.")
  (wait)
  (text-reset 1)
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "Cole: Huh? I smell disinfectant...")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (text "Cole: Was that the guy from earlier...? In a fancy apartmentlike this, there's all kinds of different people, I guess.")
  (wait)
  (text-reset 1)
  (text "Cole: Sheila's door is open. She's already back, huh?")
  (wait)
  (text-reset 1)
  (text "Cole: Sheila, it's me!")
  (wait)
  (text-reset 1)
  (sound '|| 2)
  (mes-jump "A:¥MES¥026.MES"))
 (seg*))