(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB049.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 29 14 43 15)
  (exec-mem 3744 1 6 18 9 29 12)
  (exec-mem 3744 1 7 46 3 56 12)
  (exec-mem 3744 1 8 10 10 19 12)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB049.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (if (</>
       (//
        (? (= 174 #f))
        (sound '|| 0)
        (sound '|se | 4)
        (text "Cole: !?")
        (wait)
        (text-reset 1)
        (text "Cole: The hell is this!?")
        (wait)
        (text-reset 1)
        (text "Cole: Sheila! Where are you!?")
        (set-reg 174 #t)
        (wait)
        (text-reset 1)
        (sound '|| 0)
        (if (</>
             (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
             (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
        (sound '|| 1))
       (//
        (sound '|| 0)
        (if (</>
             (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
             (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
        (sound '|| 1)
        (text "Cole: This is Sheila's room, but there's no sign of her" 'br)
(text "anywhere.")
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 183 #t))
   (branch-random
    (</>
     (/ (text "Cole: Let's check on Catherine."))
     (/ (text "Cole: Let's head over to Shuffle Food."))))
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 176 #t) (= 178 #t) (= 180 #t) (= 182 #t) (= 183 #f))
   (text "Cole: I can't waste any more time here, I've got to tell" 'br)
(text "Steve ASAP!")
   (wait)
   (text-reset 1)
   (text "Cole: I gotta call the 32nd Precinct.")
   (wait)
   (text-reset 1)
   (text "Cole: Damn, the receiver's been cut off!")
   (wait)
   (text-reset 1)
   (text "Cole: No way. I gotta use the cordless phone." 'br)
   (text "*Ring* *Ring* *Ring* *Ring* ")
   (wait)
   (text-reset 1)
   (text "Police: Hello, 32nd Precinct.")
   (wait)
   (text-reset 1)
   (text "Cole: This is Cole. Can I talk with Detective Steve Gris" 'br)
(text "from the Investigation Division?")
   (wait)
   (text-reset 1)
   (text "Police: One moment, please.")
   (wait)
   (text-reset 1)
   (text "Steve: Cole? What's wrong?")
   (wait)
   (text-reset 1)
   (text "Cole: Steve! I went to Sheila's apartment, but...")
   (wait)
   (text-reset 1)
   (text "Steve: What happened?")
   (wait)
   (text-reset 1)
   (text "Cole: The room's been ransacked.")
   (wait)
   (text-reset 1)
   (text "Steve: What do you mean?")
   (wait)
   (text-reset 1)
   (text "Cole: I don't know. It was all torn up when I got here.")
   (wait)
   (text-reset 1)
   (text "Steve: Did you see anyone suspicious?")
   (wait)
   (text-reset 1)
   (text "Cole: Suspicious? I didn't see anyone, but...")
   (wait)
   (text-reset 1)
   (text "Cole: ...Wait, I did pass someone near the elevator who had" 'br)
(text "a weird disinfectant smell. Probably one of the residents.")
   (wait)
   (text-reset 1)
   (text "Steve: And Sheila?")
   (wait)
   (text-reset 1)
   (text "Cole: She's gone.")
   (wait)
   (text-reset 1)
   (text "Steve: Is there anywhere she might have gone?")
   (wait)
   (text-reset 1)
   (text "Cole: She's off work today...")
   (wait)
   (text-reset 1)
   (text "Steve: Can you try one of her friends?")
   (wait)
   (text-reset 1)
   (text "Cole: Well, Catherine is the only one who comes to mind...")
   (wait)
   (text-reset 1)
   (text "Steve: Got it. I'll head over ASAP. In the meantime, you go" 'br)
(text "check on that friend of hers.")
   (wait)
   (text-reset 1)
   (text "Cole: Understood.")
   (wait)
   (text-reset 1)
   (text "Steve: Be careful, Cole. Do you have your gun?")
   (wait)
   (text-reset 1)
   (text "Cole: I do. Oh, and I need to know the address for a" 'br)
(text "restaurant called Shuffle Food.")
   (wait)
   (text-reset 1)
   (text "Steve: Shuffle Food?")
   (wait)
   (text-reset 1)
   (text "Cole: Yeah, I'm pretty sure Catherine works there part-time.")
   (wait)
   (text-reset 1)
   (text "Steve: One sec.")
   (wait)
   (text-reset 1)
   (text "Cole: Okay.")
   (wait)
   (text-reset 1)
   (repeat 3 (<> (text "Cole: ....................") (wait) (text-reset 1)))
   (text "Steve: Got the location. It's right behind the station.")
   (wait)
   (text-reset 1)
   (text "Cole: OK, I'm on my way.")
   (wait)
   (text-reset 1)
   (text "Steve: Let me know if you find anything. *Click*")
   (wait)
   (text-reset 1)
   (text "Cole: Shuffle Food... I've only heard about Catherine from" 'br)
(text "Sheila, but I've never actually met her.")
   (wait)
   (text-reset 1)
   (text "Cole: All I can do is hope Sheila is safe.")
   (set-reg 183 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 175 #f))
   (text "Cole: The floor is a mess. It looks like the room's been" 'br)
(text "utterly ransacked.")
   (set-reg 175 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 176 #f))
   (text "Cole: There's no sign of Sheila anywhere...could she have" 'br)
(text "been kidnapped?")
   (wait)
   (text-reset 1)
   (text "Cole: That's impossible, she doesn't have any enemies.")
   (set-reg 176 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5)) (text "Cole: Who would do something like this?") (wait) (text-reset 1))
 (seg (? (= P 6) (= 183 #t))
   (text "Cole: There's no reason to stay around. I need to find" 'br)
(text "Sheila immediately.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 177 #f))
   (text "Cole: The bed is cold. It's been a while since Sheila was" 'br)
(text "here.")
   (set-reg 177 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 178 #f))
   (text "Cole: Yesterday I put Sheila to bed here and left. And I'd" 'br)
(text "locked the door with the spare key she gave me.")
   (wait)
   (text-reset 1)
   (text "Cole: She was supposed to sleep the night...she's not the" 'br)
(text "type to wake up in the middle of the night and head out.")
   (set-reg 178 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "Cole: So where did Sheila go? I've got a feeling about this," 'br)
(text "and it isn't good.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 183 #t))
   (text "Cole: Sheila's not here. We need to find Catherine at" 'br)
(text "Shuffle Food.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 179 #f))
   (text "Cole: Even the closet's been ransacked. Why would anyone do" 'br)
(text "this?")
   (set-reg 179 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 180 #f))
   (text
    "Cole: Was the culprit searching for something in Sheila's" 'br)
"room? No way... She couldn't have gotten pulled into" 'br)
"anything shady.")
   (wait)
   (text-reset 1)
   (text "Cole: And besides, she would let me know about it from the" 'br)
(text "second something went wrong.")
   (set-reg 180 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "Cole: Anyway, I can't just leave the room like this.")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 183 #t))
   (text "Cole: Steve will be here soon... I'd better hurry over to" 'br)
(text "Shuffle Food to look for Sheila.")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 181 #f))
   (text "Cole: The desk drawer is open.")
   (set-reg 181 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 182 #f))
   (text
    "Cole: It doesn't look like anything expensive was taken. The" 'br)
"culprit wasn't just an ordinary thief...they must have had a" 'br)
"particular target in mind.")
   (set-reg 182 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))
   (text "Cole: What was the culprit looking for in here?")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 183 #t))
   (exec-mem 6064 2 1)
   (text "Cole: I just hope that Sheila's at Shuffle Food when I get" 'br)
(text "there...")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥027.MES"))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))