(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB049.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 29 14 43 15)
  (exec-mem 3744 1 6 18 9 29 12)
  (exec-mem 3744 1 7 46 3 56 12)
  (exec-mem 3744 1 8 10 10 19 12)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB049.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (if (</>
       (//
        (? (= 174 #f))
        (sound '|| 0)
        (sound '|se | 4)
        (text "［コール］！？")
        (wait)
        (text-reset 1)
        (text "［コール］なんだこれは！？")
        (wait)
        (text-reset 1)
        (text "［コール］シーラ！！　どこだ！？　どこにいる！？")
        (set-reg 174 #t)
        (wait)
        (text-reset 1)
        (sound '|| 0)
        (if (</>
             (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
             (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
        (sound '|| 1))
       (//
        (sound '|| 0)
        (if (</>
             (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
             (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
        (sound '|| 1)
        (text "［コール］ここはシーラの部屋だ。彼女の姿はどこにも見えない。")
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 183 #t))
   (branch-random
    (</>
     (/ (text "［コール］はやくキャサリンのところに会いに行こうぜ。"))
     (/ (text "［コール］はやくシャッフル・フードに行ってみよう。"))))
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 176 #t) (= 178 #t) (= 180 #t) (= 182 #t) (= 183 #f))
   (text "［コール］ここで無駄に時間を潰す訳にはいかないな。早くこの事　　　　　をスティーブさんに知らせないと・・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］よし、３２分署に電話しよう。")
   (wait)
   (text-reset 1)
   (text "［コール］あ・・・受話器が切れてる・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］仕方ない、コードレスを使うか・・・。" 'br)
   (text "　　　　　　プー　プー　プー　プー")
   (wait)
   (text-reset 1)
   (text "［警察署］はい、３２分署。")
   (wait)
   (text-reset 1)
   (text "［コール］コールといいますが、捜査課のスティーブ・グリスさん　　　　　をお願いします。")
   (wait)
   (text-reset 1)
   (text "［警察署］少々お待ち下さい。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］コールか？　どうした？")
   (wait)
   (text-reset 1)
   (text "［コール］あ、スティーブさん。実はシーラの部屋に来たんですが　　　　　・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］シーラがどうした？")
   (wait)
   (text-reset 1)
   (text "［コール］部屋が荒らされているんです。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］部屋が！？　どういう事だ？")
   (wait)
   (text-reset 1)
   (text "［コール］判りません、俺がここに来た時には既に・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］怪しい奴はみかけなかったか？")
   (wait)
   (text-reset 1)
   (text "［コール］怪しい奴・・・これといって見掛けてはいないが・・。")
   (wait)
   (text-reset 1)
   (text "［コール］そういえば、エレベーターの所で妙に薬品臭い奴とすれ　　　　　違いましたが・・・多分、ここの住人でしょう。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］シーラは？")
   (wait)
   (text-reset 1)
   (text "［コール］いません・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］どこか彼女の行きそうな所は？")
   (wait)
   (text-reset 1)
   (text "［コール］今日は会社が休みだし・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］友達の所はどうだ？")
   (wait)
   (text-reset 1)
   (text "［コール］シーラの友達というと、キャサリンくらいしか思い付か　　　　　ないな・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］判った。俺は現場検証にそっちに行くから、君はそ　　　　　　　の友達の所へ行ってくれ。")
   (wait)
   (text-reset 1)
   (text "［コール］判りました。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］くれぐれも注意してくれ。銃は持ってるか？")
   (wait)
   (text-reset 1)
   (text "［コール］はい、持ってます。それと、シャッフル・フードという　　　　　レストランの場所を知りたいんですが・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］シャッフル？")
   (wait)
   (text-reset 1)
   (text "［コール］ええ、今の時間だと、きっとキャサリンはそこでバイト　　　　　していると思うんです。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ちょっと待ってくれ。")
   (wait)
   (text-reset 1)
   (text "［コール］はい。")
   (wait)
   (text-reset 1)
   (repeat 3 (<> (text "［コール］・・・・・") (wait) (text-reset 1)))
   (text "［スティーブ］場所が判った。シャッフル・フードは駅の丁度裏側　　　　　　　だ。")
   (wait)
   (text-reset 1)
   (text "［コール］判りました。じゃあ、早速行ってみます。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］何か判ったら連絡してくれ。　　　ガチャ・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］シャッフル・フードか・・・。俺もキャサリンの事は、　　　　　シーラから聞いただけで、実際に会った事はないんだ。")
   (wait)
   (text-reset 1)
   (text "［コール］とにかく、今はシーラが無事でいてくれる事を願うだけ　　　　　だな。")
   (set-reg 183 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 175 #f))
   (text "［コール］床が酷く散らかっている・・・。まるで部屋を荒らされ　　　　　た後のようだ。")
   (set-reg 175 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 176 #f))
   (text "［コール］シーラの姿がどこにも見えないが・・・まさか、ここで　　　　　さらわれたとか・・・！？")
   (wait)
   (text-reset 1)
   (text "［コール］まさか・・・シーラは人に恨まれるような奴じゃない。")
   (set-reg 176 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5)) (text "［コール］一体誰がこんな事を・・・。") (wait) (text-reset 1))
 (seg (? (= P 6) (= 183 #t))
   (text "［コール］いつまでも、こんな所に居る必要はないな。早くシーラ　　　　　を捜しに行こう。")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 177 #f))
   (text "［コール］布団に人の体温が感じられない所をみると、シーラが居　　　　　なくなってから、かなり時間が経過しているのだろう。")
   (set-reg 177 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 178 #f))
   (text "［コール］昨日、俺はシーラをここに寝かせて帰ったんだ。勿論、　　　　　前に貰った合鍵でドアに鍵をかけた・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］シーラは朝まで寝ていた筈だし・・・夜中に起きてどこ　　　　　かに出かけるような奴ではない。")
   (set-reg 178 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "［コール］シーラはどこに行ったんだ・・・。何か嫌な予感がする　　　　　な・・・。")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 183 #t))
   (text "［コール］ここにシーラが居ない事は判ったな。早くキャサリンの　　　　　居るシャッフル・フードに行ってみよう。")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 179 #f))
   (text "［コール］タンスの中もめちゃめちゃに荒らされている。誰が何の　　　　　ためにこんな事をしたんだ！？")
   (set-reg 179 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 180 #f))
   (text
    "［コール］犯人はシーラの部屋で何かを探していたのか・・・・？　　　　　まさか・・・殆ど毎日のように会っているシーラが事件　　　　　に巻き込まれる筈はない。")
   (wait)
   (text-reset 1)
   (text "［コール］それに、もしそんな事実があれば一番最初の時点で俺に　　　　　相談してくるに違いない。")
   (set-reg 180 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "［コール］とにかく、この部屋をこのまま放置しておくわけにはい　　　　　かないな。")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 183 #t))
   (text "［コール］もうすぐスティーブさんがここに来るぞ。早くシーラを　　　　　捜しにシャッフル・フードに行こう。")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 181 #f))
   (text "［コール］小型の机は、引き出しが開いているぞ。")
   (set-reg 181 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 182 #f))
   (text
    "［コール］高価なものは何も持ち出されていないようだ。犯人は、　　　　　ただの泥棒じゃないようだな。何か狙いがあってここに　　　　　侵入したのだろう。")
   (set-reg 182 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))
   (text "［コール］犯人は、何を狙ってシーラの部屋を荒らしたんだろう？")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 183 #t))
   (exec-mem 6064 2 1)
   (text "［コール］シャッフル・フードに、タイミング良くシーラがいてく　　　　　れればいいが・・・。")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥027.MES"))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))