; Dead of the Brain 2 (PC-98) - 030.MES
; Translated by Geometrizer
; Edited by trentsignia
; --Description:--
; Inside Disco Zeena.
; --Progression:--
; Talk to everyone, then the Black Dragon, then MOVE.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB053.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)			; Hotspots and buttons defined here...
  (exec-mem 3744 1 1 80 0 0 0)							; 	MOVE button
  (exec-mem 3744 1 2 80 0 0 0)							; 	SYSTEM button
  (exec-mem 3744 1 5 4 9 20 13)							; 	Girls
  (exec-mem 3744 1 6 34 12 44 15)						; 	Couple
  (exec-mem 3744 1 7 52 7 56 10)						; 	Black Dragon
  (exec-mem 3744 1 8 42 8 45 11)						; 	Right Dancer
  (exec-mem 3744 1 9 23 8 27 11)						; 	Left Dancer
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB053.GPC") (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_03.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_03.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 212 #f))								; Lead-in from previous MES script
        (str "Cole: The night is young, but this place is packed.")
        (set-reg 212 #t)
        (wait)
        (text-reset 1))
       (//
        (str "Cole: This is the interior of Disco Zeena. Uh, wow.")		; Lead-in from loading game
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 213 #f))							; Girls #1
   (str "Cole: There are two girls sitting at the front table. The" 'br)
   (str "chick on the left's been stealing glances at me.")
   (set-reg 213 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 214 #f))							; Girls #2
   (str "Cole: If they're regulars here, maybe they know about" 'br)
   (str "Sheila. Better ask them.")
   (set-reg 214 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 215 #f))							; Girls #3
   (str "Woman (Right): Uh...yeah? Can I help you?")
   (wait)
   (text-reset 1)
   (str "Cole: Can I ask you something?")
   (wait)
   (text-reset 1)
   (str "Woman (Right): Yeah? What?")
   (wait)
   (text-reset 1)
   (str "Cole: Do you come here often?")
   (wait)
   (text-reset 1)
   (str "Woman (Right): Occasionally.")
   (wait)
   (text-reset 1)
   (str "Woman (Left): Uh-huh. Occasionally.")
   (wait)
   (text-reset 1)
   (str "Cole: Okay, great. I lucked out.")
   (set-reg 215 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 216 #f))							; Girls #4
   (str "Cole: I'm trying to find someone, you see?")
   (wait)
   (text-reset 1)
   (str "Woman (Right): Yuh-huh? Who?")
   (wait)
   (text-reset 1)
   (str "Cole: There's a regular here, a woman named Sheila. Do you" 'br)
   (str "know her?")
   (wait)
   (text-reset 1)
   (str "Woman (Right): Sheila? That's not a name I hear too often.")
   (wait)
   (text-reset 1)
   (str "Cole: Hmm, and what about you?")
   (wait)
   (text-reset 1)
   (str "Woman (Left): I dunno.")
   (wait)
   (text-reset 1)
   (str "Cole: Damn...")
   (set-reg 216 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 217 #f))							; Girls #5
   (str "Woman (Left): Hey, why don't you take us somewhere? I've" 'br)
   (str "got tomorrow off and we're bored as hell. We're probably" 'br)
   (str "more fun than that Sheila girl.")
   (wait)
   (text-reset 1)
   (str "Cole: Sorry... It's because of Sheila, you know how she is.")
   (wait)
   (text-reset 1)
   (str "Woman (Right): Oh, look at that ring! You're looking for" 'br)
   (str "your wife?")
   (wait)
   (text-reset 1)
   (str "Cole: Well, she's not my wife yet.")
   (wait)
   (text-reset 1)
   (str "Woman (Left): Haha! Maybe she's out partying somewhere?")
   (wait)
   (text-reset 1)
   (str "Cole: I hope she is...")
   (set-reg 217 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))								; Girls #6 (repeat line)
   (str "Woman (Right): Forget her, man. Why don't we go party our" 'br)
   (str "asses off?")
   (wait)
   (text-reset 1)
   (str "Cole: Maybe another time.")
   (wait)
   (text-reset 1)
   (str "Woman (Left): Ohhh my god, could this guy be any more" 'br)
   (str "square?")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 218 #f))							; Couple #1
   (str "Cole: There's a couple sitting at the table in the back. I" 'br)
   (str "wonder if they know anything about Sheila.")
   (set-reg 218 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 219 #f))							; Couple #2
   (str "Cole: Sorry to interrupt you guys while you're having fun...")
   (wait)
   (text-reset 1)
   (str "Man: Yeah, you'd better be sorry. Who the hell are you?")
   (wait)
   (text-reset 1)
   (str "Cole: I'm looking for a girl named Sheila.")
   (wait)
   (text-reset 1)
   (str "Man: Sheila? Don't know her.")
   (wait)
   (text-reset 1)
   (str "Cole: What about her?")
   (wait)
   (text-reset 1)
   (str "Woman: ...")
   (wait)
   (text-reset 1)
   (str "Man: She's been drinking.")
   (wait)
   (text-reset 1)
   (str "Cole: For real...her eyes are drooping and she looks" 'br)
   (str "totally out of it.")
   (wait)
   (text-reset 1)
   (str "Man: Wow, you must be a scientist to come up with that. Now" 'br)
   (str "get lost.")
   (set-reg 219 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 220 #f))							; Couple #3
   (str "Man: God, you don't take the hint, do you?")
   (wait)
   (text-reset 1)
   (str "Cole: You're not with Bloody Fox, are you?")
   (wait)
   (text-reset 1)
   (str "Man: Don't you lump me in with those assholes. I may look" 'br)
   (str "the part, but I bust my ass at my parking lot job every day.")
   (wait)
   (text-reset 1)
   (str "Cole: I see... Sorry about that.")
   (set-reg 220 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))								; Couple #4 (repeat line)
   (str "Man: There's only so many ways I can tell you I don't know" 'br)
   (str "shit about your friend.")
   (wait)
   (text-reset 1)
   (str "Cole: Yeah... I guess you're right.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 216 #t) (= 220 #t) (= 223 #t) (= 226 #f))			; Black Dragon (after talking to everyone else) #1
   (str "Cole: It's no use. No matter how much I ask, they won't" 'br)
   (str "open their mouth.")
   (wait)
   (text-reset 1)
   (str "Man: Huh? What are you muttering?")
   (wait)
   (text-reset 1)
   (str "Cole: Oh, a reply!")
   (wait)
   (text-reset 1)
   (str "Man: You need something from me?")
   (wait)
   (text-reset 1)
   (str "Cole: I'm wondering if you come here often.")
   (wait)
   (text-reset 1)
   (str "Man: When they refer to the Black Dragon of Zeena's," 'br)
   (str "they're talking about yours truly.")
   (wait)
   (text-reset 1)
   (str "Cole: Then I'm talking to the right guy. Do you know a" 'br)
   (str "woman named Sheila?")
   (wait)
   (text-reset 1)
   (str "Man: Sheila... Ahhh, you talking about Miss Sheila, who got" 'br)
   (str "engaged to that dude?")
   (wait)
   (text-reset 1)
   (str "Cole: Ah, um...maybe...?")
   (wait)
   (text-reset 1)
   (str "Man: If it's about Miss Sheila, ask me anything. I know it" 'br)
   (str "all. Everything from bust, waist, hips, to the fact that" 'br)
   (str "her fiancee is a hopeless gambling addict.")
   (wait)
   (text-reset 1)
   (str "Cole: Whoa whoa, hey now--")
   (set-reg 226 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 216 #t) (= 220 #t) (= 223 #t) (= 227 #f))			; Black Dragon (after talking to everyone else) #2
   (str "Man: Come on, what do you wanna know?")
   (wait)
   (text-reset 1)
   (str "Cole: Uh, so what are you to Sheila?")
   (wait)
   (text-reset 1)
   (str "Man: Well, actually, I used to chase after her. But then" 'br)
   (str "she got engaged to that slot fiend. Whadda shock, huh?")
   (wait)
   (text-reset 1)
   (str "Man: Though when I ran into her today, I gave her a nod and" 'br)
   (str "a smile and a“congratulations!”I'm pretty cool, aren't I?")
   (wait)
   (text-reset 1)
   (str "Cole: Hold up--you said she was here today?")
   (wait)
   (text-reset 1)
   (str "Man: ...She even gave me a little smile. That was enough" 'br)
   (str "for me.")
   (wait)
   (text-reset 1)
   (str "Cole: I don't care about that! Where did she go?")
   (wait)
   (text-reset 1)
   (str "Man: Who?")
   (wait)
   (text-reset 1)
   (str "Cole: Oh for god's sake, the person we've been talking" 'br)
   (str "about! Sheila!")
   (wait)
   (text-reset 1)
   (str "Man: Hey, you've just been calling her Sheila, not MISS" 'br)
   (str "Sheila. What's up with that? You keep dissing her like" 'br)
   (str "that, there's gonna be consequences!")
   (wait)
   (text-reset 1)
   (str "Cole: Maybe I'm calling her that because I AM her slot" 'br)
   (str "fiend fiancee!")
   (wait)
   (text-reset 1)
   (str "Man: Oh, shit.")
   (wait)
   (text-reset 1)
   (str "Cole: So now that we're clear on that, where did my fiancee" 'br)
   (str "go?")
   (wait)
   (text-reset 1)
   (str "Man: Uh, uh, I'm not sure. She's usually here with" 'br)
   (str "Catherine, but today she came alone.")
   (wait)
   (text-reset 1)
   (str "Cole: Alone? Was she having a good time?")
   (wait)
   (text-reset 1)
   (str "Man: Ah, now that you mention it, I didn't see her tearing" 'br)
   (str "up the floor like usual... She was just talking with" 'br)
   (str "people, then peaced out after about 20 minutes.")
   (set-reg 227 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 216 #t) (= 220 #t) (= 223 #t) (= 228 #f))			; Black Dragon (after talking to everyone else) #3
   (str "Cole: Where'd she go?")
   (wait)
   (text-reset 1)
   (str "Man: I wouldn't know, but she did seem kinda restless...")
   (wait)
   (text-reset 1)
   (str "Cole: Well, shit. That's an important detail, though.")
   (wait)
   (text-reset 1)
   (str "Man: Oh, one more thing.")
   (wait)
   (text-reset 1)
   (str "Cole: What?")
   (wait)
   (text-reset 1)
   (str "Man: I heard someone mention Light Dance Street, or" 'br)
   (str "something.")
   (wait)
   (text-reset 1)
   (str "Cole: Light Dance Street? That's the street that leads off" 'br)
   (str "to that country road, isn't it...?")
   (wait)
   (text-reset 1)
   (str "Man: You guys planning on heading out into the mountains or" 'br)
   (str "something?")
   (wait)
   (text-reset 1)
   (str "Cole: No, nothing like that...")
   (set-reg 228 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 216 #t) (= 220 #t) (= 223 #t) (= 229 #f))			; Black Dragon (after talking to everyone else) #4
   (str "Man: Something happen with Miss Sheila I should know about?")
   (wait)
   (text-reset 1)
   (str "Cole: Nothing...nothing to worry about. If something went" 'br)
   (str "wrong, she would have contacted me.")
   (wait)
   (text-reset 1)
   (str "Man: Ah, I feel ya. Maybe you should just stay at home and" 'br)
   (str "wait for her, then?")
   (wait)
   (text-reset 1)
   (str "Cole: Makes sense. Steve was going to check out Sheila's" 'br)
   (str "apartment, so maybe he found some clues.")
   (set-reg 229 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 216 #t) (= 220 #t) (= 223 #t))				; Black Dragon (after talking to everyone else) #5 (repeat line)
   (str "Man: If Miss Sheila gets in touch, please give her my" 'br)
   (str "regards.")
   (wait)
   (text-reset 1)
   (str "Cole: Don't you worry.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 221 #f))							; Black Dragon #1
   (str "Cole: There's a guy standing next to the pillar who looks" 'br)
   (str "like a regular.")
   (set-reg 221 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 222 #f))							; Black Dragon #2
   (str "Cole: Erm... Could I have a moment?")
   (wait)
   (text-reset 1)
   (str "Man: ...")
   (wait)
   (text-reset 1)
   (str "Cole: There's something I'd like to ask...")
   (wait)
   (text-reset 1)
   (str "Man: ...")
   (wait)
   (text-reset 1)
   (str "Cole: You're not saying anything...are you drunk?")
   (set-reg 222 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 223 #f))							; Black Dragon #3
   (str "Cole: Yo, listen for a second.")
   (wait)
   (text-reset 1)
   (str "Man: ...")
   (wait)
   (text-reset 1)
   (str "Cole: Can you say anything at all?")
   (wait)
   (text-reset 1)
   (str "Man: ...")
   (wait)
   (text-reset 1)
   (str "Cole: God, I'm wasting my time here.")
   (set-reg 223 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))								; Black Dragon #4 (repeat line)
   (str "Cole: I can't get anything out of this guy, he's been quiet" 'br)
   (str "from the start." 'br)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 224 #f))							; Right Dancer #1
   (str "Cole: Hey man, can I ask you something?")
   (wait)
   (text-reset 1)
   (str "Man: YEAHHHHHHH! WOOOOO!!!")
   (wait)
   (text-reset 1)
   (str "Cole: Hey hey, I'm trying to ask you a question!")
   (wait)
   (text-reset 1)
   (str "Man: YEAH YEAH YEAH!!! WOOBALOOOOOO!")
   (wait)
   (text-reset 1)
   (str "Cole: The music's so loud, I'm not having much luck.")
   (set-reg 224 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))								; Right Dancer #2 (repeat line)
   (str "Man: ")
   (branch-random
    (</>
     (/ (str "YEAH! YEAH!"))
     (/ (str "UNF UNF UNF!"))
     (/ (str "WOOOOOOOOOO!"))))
   (wait)
   (text-reset 1)
   (str "Cole: ")
   (branch-random
    (</>
     (/
      (str "This is a waste of time, guy's totally out of it."))
     (/
      (str "That's the booze talking... I should really ask" 'br)
      (str "someone else."))
     (/
      (str "He's so busy cutting a rug that he can't hear what" 'br)
      (str "I'm saying."))))
   (wait)
   (text-reset 1))
 (seg (? (= P 9) (= 225 #f))							; Left Dancer #1
   (str "Cole: Hey, can I ask you something?")
   (wait)
   (text-reset 1)
   (str "Man: Damn, look at that gorgeous broad over there! C'mon," 'br)
   (str "let's have some fun!")
   (wait)
   (text-reset 1)
   (str "Cole: Hey man, listen to me!")
   (wait)
   (text-reset 1)
   (str "Man: Oh shit! That chick over there is stunning too!")
   (wait)
   (text-reset 1)
   (str "Cole: I keep saying words, and they keep getting ignored.")
   (set-reg 225 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 9))								; Left Dancer #2 (repeat line)
   (str "Cole: ")
   (branch-random
    (</>
     (/
      (str "Hey, let me ask you something..."))
     (/
      (str "I wanna ask you a question."))
     (/
      (str "If you're a regular around here, you know a lady" 'br)
      (str "named Sheila, right?"))))
   (wait)
   (text-reset 1)
   (str "Man: ")
   (branch-random
    (</>
     (/
      (str "Yo! Hey, sugarlips! You're so hot it's criminal!"))
     (/
      (str "Hey, bodycon lady! Bodycon is totally out these days!" 'br)
      (str "Let's go shopping and I'll pick you out something that's" 'br)
      (str "actually in style!"))
     (/
      (str "Damn, there's so many hotties here today! I'm dying," 'br)
      (str "dude!"))))
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 229 #t))							; MOVE (after talking to Black Dragon)
   (exec-mem 6064 2 1)
   (str "Cole: I need to get in touch with Steve, better get back to" 'br)
   (str "the apartment.")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥031.MES"))
 (seg (? (= P 2))								; SYSTEM
   (exec-mem 6064 2 2)
   (menu1
    25 317  39 317  53 317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))