(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB053.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 4 9 20 13)
  (exec-mem 3744 1 6 34 12 44 15)
  (exec-mem 3744 1 7 52 7 56 10)
  (exec-mem 3744 1 8 42 8 45 11)
  (exec-mem 3744 1 9 23 8 27 11)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB053.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_03.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_03.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 212 #f))
        (text "Cole: The night is young, but this place is packed.")
        (set-reg 212 #t)
        (wait)
        (text-reset 1))
       (// (text "Cole: This is the interior of Disco Zeena. Damn.") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 213 #f))
   (text
    "Cole: There are two girls sitting at the front table. The   chick on the left's been stealing glances at me.")
   (set-reg 213 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 214 #f))
   (text "Cole: If they're regulars here, maybe they know about       Sheila. Better ask them.")
   (set-reg 214 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 215 #f))
   (text "Woman (Right): Uh...yeah? Can I help you?")
   (wait)
   (text-reset 1)
   (text "Cole: Can I ask you something?")
   (wait)
   (text-reset 1)
   (text "Woman (Right): Yeah? What?")
   (wait)
   (text-reset 1)
   (text "Cole: Do you come here often?")
   (wait)
   (text-reset 1)
   (text "Woman (Right): Occasionally.")
   (wait)
   (text-reset 1)
   (text "Woman (Left): Uh-huh. Occasionally.")
   (wait)
   (text-reset 1)
   (text "Cole: Okay, great. I lucked out.")
   (set-reg 215 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 216 #f))
   (text "Cole: I'm trying to find someone, you see?")
   (wait)
   (text-reset 1)
   (text "Woman (Right): Yuh-huh? Who?")
   (wait)
   (text-reset 1)
   (text "Cole: There's a regular here, a woman named Sheila. Do you  know her?")
   (wait)
   (text-reset 1)
   (text "Woman (Right): Sheila? That's not a name I hear too often.")
   (wait)
   (text-reset 1)
   (text "Cole: Hmm, and what about you?")
   (wait)
   (text-reset 1)
   (text "Woman (Left): I dunno.")
   (wait)
   (text-reset 1)
   (text "Cole: Damn...")
   (set-reg 216 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 217 #f))
   (text "Woman (Left): Hey, why don't you take us somewhere? I've gottomorrow off and we're bored as hell. We're more fun than that      Sheila girl anyway.")
   (wait)
   (text-reset 1)
   (text "Cole: Sorry... It's because of Sheila, you know how she is.")
   (wait)
   (text-reset 1)
   (text "Woman (Right): Oh, look at that ring! You're looking for    your wife?")
   (wait)
   (text-reset 1)
   (text "Cole: She's not my wife yet, to be honest.")
   (wait)
   (text-reset 1)
   (text "Woman (Left): Haha! Maybe she's out partying somewhere?")
   (wait)
   (text-reset 1)
   (text "Cole: That would be preferable...")
   (set-reg 217 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "Woman (Right): Forget her, man. Why don't we go party our   asses off?")
   (wait)
   (text-reset 1)
   (text "Cole: Maybe another time.")
   (wait)
   (text-reset 1)
   (text "Woman (Left): Ohhh my god, could this guy be any more       square.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 218 #f))
   (text "Cole: There's a couple sitting at the table in the back. I  wonder if they know anything about Sheila.")
   (set-reg 218 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 219 #f))
   (text "Cole: Sorry to interrupt you guys while you're having fun...")
   (wait)
   (text-reset 1)
   (text "Man: Yeah, you'd better be sorry. The hell are you?")
   (wait)
   (text-reset 1)
   (text "Cole: I'm looking for a girl named Sheila.")
   (wait)
   (text-reset 1)
   (text "Man: Sheila? Don't know her.")
   (wait)
   (text-reset 1)
   (text "Cole: What about her?")
   (wait)
   (text-reset 1)
   (text "Woman: ...")
   (wait)
   (text-reset 1)
   (text "Man: She's been drinking.")
   (wait)
   (text-reset 1)
   (text "Cole: For real...her eyes are drooping and she looks totallyout of it.")
   (wait)
   (text-reset 1)
   (text "Man: Wow, you must be a scientist to come up with that. Now get lost.")
   (set-reg 219 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 220 #f))
   (text "Man: God, you don't take the hint, do you?")
   (wait)
   (text-reset 1)
   (text "Cole: You're not with Bloody Fox, are you?")
   (wait)
   (text-reset 1)
   (text "Man: Don't you lump me in with those assholes. Even though Imay look the part, I bust my ass at my parking lot job every   day.")
   (wait)
   (text-reset 1)
   (text "Cole: I see... Sorry about that.")
   (set-reg 220 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "Man: There's only so many times I can tell you I don't know shit about your friend.")
   (wait)
   (text-reset 1)
   (text "Cole: Yeah... I guess you're right.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 216 #t) (= 220 #t) (= 223 #t) (= 226 #f))
   (text "Cole: It's no use. No matter how much I ask, they won't opentheir mouth.")
   (wait)
   (text-reset 1)
   (text "Man: Huh? What are you muttering?")
   (wait)
   (text-reset 1)
   (text "Cole: Oh! you replied!")
   (wait)
   (text-reset 1)
   (text "Man: You need something from me?")
   (wait)
   (text-reset 1)
   (text "Cole: I'm wondering if you come here often.")
   (wait)
   (text-reset 1)
   (text "Man: When they refer to the Black Dragon of Zeena's, they'retalking about yours truly.")
   (wait)
   (text-reset 1)
   (text "Cole: Then I'm talking to the right guy. Do you know a womannamed Sheila?")
   (wait)
   (text-reset 1)
   (text "Man: Sheila... Ahhh, you talking about Miss Sheila, who got engaged to that dude?")
   (wait)
   (text-reset 1)
   (text "Cole: Ah, um...maybe...?")
   (wait)
   (text-reset 1)
   (text
    "Man: If it's about Miss Sheila, ask me anything. I know it  all. Everything from bust, waist, hips, to the fact that herfiancee is a hopeless gambling addict.")
   (wait)
   (text-reset 1)
   (text "Cole: Whoa whoa, hey now--")
   (set-reg 226 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 216 #t) (= 220 #t) (= 223 #t) (= 227 #f))
   (text "Man: Come on, what do you wanna know?")
   (wait)
   (text-reset 1)
   (text "Cole: Uh, so what are you to Sheila?")
   (wait)
   (text-reset 1)
   (text
    "Man: Well, actually, I used to chase after her. But then shegot engaged to that slot fiend. Whadda shock, huh?")
   (wait)
   (text-reset 1)
   (text
    "Man: Though when I ran into her today, I gave her a nod and a smile and a 'congratulations!' I'm pretty cool, aren't I?")
   (wait)
   (text-reset 1)
   (text "Cole: Hold up--you said she was here today?")
   (wait)
   (text-reset 1)
   (text "Man: ...She even gave me a little smile. That was enough forme.")
   (wait)
   (text-reset 1)
   (text "Cole: I don't care about that! Where did she go?")
   (wait)
   (text-reset 1)
   (text "Man: Who?")
   (wait)
   (text-reset 1)
   (text "Cole: Oh for god's sake, the person we've been talking      about! Sheila!")
   (wait)
   (text-reset 1)
   (text
    "Man: Hey, you've just been calling her Sheila, not MISS     Sheila. What's up with that? You keep dissing her like that,there's gonna be consequences!")
   (wait)
   (text-reset 1)
   (text "Cole: Maybe I'm calling her that because I AM her slot-fiendfiancee!")
   (wait)
   (text-reset 1)
   (text "Man: Oh shit!")
   (wait)
   (text-reset 1)
   (text "Cole: So now that we're clear on that, where did my fiancee go?")
   (wait)
   (text-reset 1)
   (text "Man: Uh, uh, I'm not sure. She's usually here with          Catherine, but today she came alone.")
   (wait)
   (text-reset 1)
   (text "Cole: Alone? Was she having a good time?")
   (wait)
   (text-reset 1)
   (text
    "Man: Ah, now that you mention it, I didn't see her tearing  up the floor like usual... She was just talking with people,then peaced out after about 20 minutes.")
   (set-reg 227 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 216 #t) (= 220 #t) (= 223 #t) (= 228 #f))
   (text "Cole: Where'd she go?")
   (wait)
   (text-reset 1)
   (text "Man: I wouldn't know, but she did seem kinda restless...")
   (wait)
   (text-reset 1)
   (text "Cole: Well, shit. That's an important detail, though.")
   (wait)
   (text-reset 1)
   (text "Man: Oh, one more thing.")
   (wait)
   (text-reset 1)
   (text "Cole: What?")
   (wait)
   (text-reset 1)
   (text "Man: I heard someone mention Light Dance Street, or         something.")
   (wait)
   (text-reset 1)
   (text "Cole: Light Dance Street? That's the street that leads off  to that country road, isn't it...?")
   (wait)
   (text-reset 1)
   (text "Man: You guys planning on heading out into the mountains or something?")
   (wait)
   (text-reset 1)
   (text "Cole: No, nothing like that...")
   (set-reg 228 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 216 #t) (= 220 #t) (= 223 #t) (= 229 #f))
   (text "Man: Something happen with Miss Sheila I should know about?")
   (wait)
   (text-reset 1)
   (text "Cole: Nothing...nothing to worry about. If something went   wrong, she would have contacted me.")
   (wait)
   (text-reset 1)
   (text "Man: Ah, I feel ya. Maybe you should just stay at home and  wait for her, then?")
   (wait)
   (text-reset 1)
   (text
    "Cole: Makes sense. Steve was going to check out Sheila's    apartment, so maybe he found some clues.")
   (set-reg 229 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 216 #t) (= 220 #t) (= 223 #t))
   (text "Man: If Miss Sheila gets in touch, please give her my       regards.")
   (wait)
   (text-reset 1)
   (text "Cole: Don't you worry.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 221 #f))
   (text "Cole: There's a guy standing next to the pillar who looks   like a regular.")
   (set-reg 221 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 222 #f))
   (text "Cole: Erm... Could I have a moment?")
   (wait)
   (text-reset 1)
   (text "Man: ...")
   (wait)
   (text-reset 1)
   (text "Cole: There's something I'd like to ask...")
   (wait)
   (text-reset 1)
   (text "Man: ...")
   (wait)
   (text-reset 1)
   (text "Cole: You're not saying anything...are you drunk?")
   (set-reg 222 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 223 #f))
   (text "Cole: Yo, listen for a second.")
   (wait)
   (text-reset 1)
   (text "Man: ...")
   (wait)
   (text-reset 1)
   (text "Cole: Can you say anything at all?")
   (wait)
   (text-reset 1)
   (text "Man: ...")
   (wait)
   (text-reset 1)
   (text "Cole: God, I'm wasting my time here.")
   (set-reg 223 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "Cole: It's no use. No matter how much I ask, they won't opentheir mouth.")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 224 #f))
   (text "Cole: Hey man, can I ask you something?")
   (wait)
   (text-reset 1)
   (text "Man: YEAHHHHHHH! WOOOOO!!!")
   (wait)
   (text-reset 1)
   (text "Cole: Hey hey, I'm trying to ask you a question!")
   (wait)
   (text-reset 1)
   (text "Man: YEAH YEAH YEAH!!! WOOBALOOOOOO!")
   (wait)
   (text-reset 1)
   (text "Cole: The music's so loud, I'm not having much luck.")
   (set-reg 224 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))
   (text "［　男　］")
   (branch-random
    (</> (/ (text "YEAH! YEAH! UNF UNF UNF! WOOOOOOOOOO!")) (/ (text "YEAH! YEAH! UNF UNF UNF! WOOOOOOOOOO!")) (/ (text "YEAH! YEAH! UNF UNF UNF! WOOOOOOOOOO!"))))
   (wait)
   (text-reset 1)
   (text "［コール］")
   (branch-random
    (</>
     (/ (text "This is a waste of time, guy's totally out of it."))
     (/ (text "That's the booze talking... I should really ask someone     else."))
     (/ (text "He's so busy cutting a rug that he can't hear what I'm      saying."))))
   (wait)
   (text-reset 1))
 (seg (? (= P 9) (= 225 #f))
   (text "Cole: Hey, can I ask you something?")
   (wait)
   (text-reset 1)
   (text "Man: Damn, look at that gorgeous broad over there! C'mon,   let's have some fun!")
   (wait)
   (text-reset 1)
   (text "Cole: Hey man, listen to me!")
   (wait)
   (text-reset 1)
   (text "Man: Oh shit! That chick over there is stunning too!")
   (wait)
   (text-reset 1)
   (text "Cole: I keep saying words, and they keep getting ignored.")
   (set-reg 225 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 9))
   (text "［コール］")
   (branch-random
    (</>
     (/ (text "Hey, let me ask you something..."))
     (/ (text "I wanna ask you a question."))
     (/ (text "If you're a regular around here, you know a lady named      Sheila, right?"))))
   (wait)
   (text-reset 1)
   (text "［　男　］")
   (branch-random
    (</>
     (/ (text "Yo! Hey, sugarlips! You're so hot it's criminal!"))
     (/ (text "Hey, bodycon lady! Bodycon is totally out these days! We    should go shopping and I'll pick you out something that's   actually in style!"))
     (/ (text "Damn, there's so many hotties here today! I'm dying, dude!"))))
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 229 #t))
   (exec-mem 6064 2 1)
   (text "Cole: I need to get in touch with Steve, so let's go back tothe apartment.")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥031.MES"))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))