(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB053.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 4 9 20 13)
  (exec-mem 3744 1 6 34 12 44 15)
  (exec-mem 3744 1 7 52 7 56 10)
  (exec-mem 3744 1 8 42 8 45 11)
  (exec-mem 3744 1 9 23 8 27 11)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB053.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_03.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_03.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 212 #f))
        (text "［コール］まだ時間は早いのに、結構人が入っているんだな。")
        (set-reg 212 #t)
        (wait)
        (text-reset 1))
       (// (text "［コール］ここはディスコ「ジーナ」の店内だ。") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 213 #f))
   (text
    "［コール］正面のテーブルには、女の子が二人で座っているな。　　　　　　向かって左側の娘が、さっきから俺の事をチラチラ見て　　　　　いるようだ。")
   (set-reg 213 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 214 #f))
   (text "［コール］ここの常連だったら、シーラの事も知っているかもしれ　　　　　ないな。ちょっと聞いてみた方がいいだろう。")
   (set-reg 214 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 215 #f))
   (text "［右の女］あの・・・何か？")
   (wait)
   (text-reset 1)
   (text "［コール］いや、少し尋ねたいんだが・・・。")
   (wait)
   (text-reset 1)
   (text "［右の女］なにかしら？")
   (wait)
   (text-reset 1)
   (text "［コール］このディスコには良く来るのか？")
   (wait)
   (text-reset 1)
   (text "［右の女］たまに・・・よね？")
   (wait)
   (text-reset 1)
   (text "［左の女］うん、たまに。")
   (wait)
   (text-reset 1)
   (text "［コール］そうか・・・なら話は早いな。")
   (set-reg 215 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 216 #f))
   (text "［コール］人を捜しているんだけどさ・・・。")
   (wait)
   (text-reset 1)
   (text "［右の女］誰？")
   (wait)
   (text-reset 1)
   (text "［コール］ここの常連で、シーラって女性なんだけど・・・知って　　　　　るかな？")
   (wait)
   (text-reset 1)
   (text "［右の女］シーラさんねぇ・・・あまり聞かない名ね。")
   (wait)
   (text-reset 1)
   (text "［コール］そうか・・・。そっちの彼女は？")
   (wait)
   (text-reset 1)
   (text "［左の女］ううん、知らない。")
   (wait)
   (text-reset 1)
   (text "［コール］そっか・・・。")
   (set-reg 216 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 217 #f))
   (text "［左の女］ねね、どっか連れてってよ。明日、休みだし暇なんだよ　　　　　ね・・・。シーラっていう人より、私達じゃあ役不足？")
   (wait)
   (text-reset 1)
   (text "［コール］悪いね・・・シーラってコレだから。")
   (wait)
   (text-reset 1)
   (text "［右の女］指輪・・・なんだ、捜してるのは奥さんだったの？")
   (wait)
   (text-reset 1)
   (text "［コール］まだ奥さんじゃないけどね。")
   (wait)
   (text-reset 1)
   (text "［左の女］どこかで遊びほうけてるんじゃないの？")
   (wait)
   (text-reset 1)
   (text "［コール］・・・だったらいいけどね。")
   (set-reg 217 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "［右の女］その人の事は放っておいてさ、私達と楽しまない？")
   (wait)
   (text-reset 1)
   (text "［コール］今度ね。")
   (wait)
   (text-reset 1)
   (text "［左の女］なんだぁ・・・つまんないの。")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 218 #f))
   (text "［コール］奥のテーブルにはカップルが座っている。彼等はシーラ　　　　　について、何か知らないかな？")
   (set-reg 218 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 219 #f))
   (text "［コール］楽しんでる所、ちょっとすまないが・・・。")
   (wait)
   (text-reset 1)
   (text "［　男　］あん？　なんだ、テメエは！？")
   (wait)
   (text-reset 1)
   (text "［コール］シーラって娘を捜しているんだが・・・。")
   (wait)
   (text-reset 1)
   (text "［　男　］シーラ？　知らねえな。")
   (wait)
   (text-reset 1)
   (text "［コール］彼女は？")
   (wait)
   (text-reset 1)
   (text "［　女　］・・・・・・。")
   (wait)
   (text-reset 1)
   (text "［　男　］こいつ、かなり酔ってるんだ。")
   (wait)
   (text-reset 1)
   (text "［コール］ほんとだ・・・目がショボショボしてて眠そうだな。")
   (wait)
   (text-reset 1)
   (text "［　男　］判ったら、早くどっか行けよ。")
   (set-reg 219 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 220 #f))
   (text "［　男　］まだ何か用があんのか？")
   (wait)
   (text-reset 1)
   (text "［コール］あんた、まさかブラッディフォックスじゃないよな？　")
   (wait)
   (text-reset 1)
   (text "［　男　］冗談じゃない、俺をあんな奴等と一緒にするな！　こう　　　　　見えても毎日パーキングで一生懸命働いているんだ。")
   (wait)
   (text-reset 1)
   (text "［コール］そうか、悪かったな。")
   (set-reg 220 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "［　男　］あんたもしつこいな・・・俺は知らねえって何度も言っ　　　　　てんだろ？")
   (wait)
   (text-reset 1)
   (text "［コール］ああ、そうだったな。")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 216 #t) (= 220 #t) (= 223 #t) (= 226 #f))
   (text "［コール］だめだよ、あの人はさっきから何を言っても口を利いて　　　　　くれないんだ。")
   (wait)
   (text-reset 1)
   (text "［　男　］ん？　何か言ったか？")
   (wait)
   (text-reset 1)
   (text "［コール］あっ、初めて返事をしてくれた・・・。")
   (wait)
   (text-reset 1)
   (text "［　男　］何か俺に用か？")
   (wait)
   (text-reset 1)
   (text "［コール］いや、この店には良く来るのか？")
   (wait)
   (text-reset 1)
   (text "［　男　］まあな、ジーナの黒龍って言ったら俺の事だからな。")
   (wait)
   (text-reset 1)
   (text "［コール］そうか、じゃあシーラって女性は知ってるか？")
   (wait)
   (text-reset 1)
   (text "［　男　］シーラって・・・ひょっとして、この間男と婚約したっ　　　　　て言う、あのシーラさん？")
   (wait)
   (text-reset 1)
   (text "［コール］ま、まあそうだが・・・。")
   (wait)
   (text-reset 1)
   (text
    "［　男　］なんだぁ、シーラさんの事だったら何でも俺に聞いてく　　　　　れよ。バスト・ウェスト・ヒップから婚約相手がやけに　　　　　ギャンブル好きだって事も何でも知ってるぜ。")
   (wait)
   (text-reset 1)
   (text "［コール］オイオイオイ・・・。")
   (set-reg 226 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 216 #t) (= 220 #t) (= 223 #t) (= 227 #f))
   (text "［　男　］で、そのシーラさんの何を聞きたいんだ？")
   (wait)
   (text-reset 1)
   (text "［コール］あんた、シーラの何なんだ？")
   (wait)
   (text-reset 1)
   (text
    "［　男　］いやね、実は俺、前にシーラさんの追っかけやってたん　　　　　だ。だけどそのギャンブル好きの間男と婚約しちまった　　　　　だろ？　俺、それ聞いてショックでさ・・・。")
   (wait)
   (text-reset 1)
   (text
    "［　男　］で、今日ここで会った時に軽く微笑んで「おめでとう」　　　　　って言ってあげたんだ。くぅー！　俺って何てかっこい　　　　　いんだろうなぁ！")
   (wait)
   (text-reset 1)
   (text "［コール］なに！？　今日来たって？")
   (wait)
   (text-reset 1)
   (text "［　男　］シーラさんも軽く微笑んでくれてさ・・・これで良かっ　　　　　たんだよね。")
   (wait)
   (text-reset 1)
   (text "［コール］で、どこへ行ったんだ？")
   (wait)
   (text-reset 1)
   (text "［　男　］誰が？")
   (wait)
   (text-reset 1)
   (text "［コール］シーラだよ、奴はどこへ行ったんだ？")
   (wait)
   (text-reset 1)
   (text
    "［　男　］あんた、さっきからシーラ、シーラって呼び捨てにして　　　　　るけどさ。一体、なんなの？　俺の理想のシーラさんを　　　　　呼び捨てにしてるとタダじゃおかないよ？")
   (wait)
   (text-reset 1)
   (text "［コール］俺はそのギャンブル好きの間男だよ！")
   (wait)
   (text-reset 1)
   (text "［　男　］ゲっ・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］やっと判ったか・・・。それでシーラはどこへ行ったん　　　　　だ？")
   (wait)
   (text-reset 1)
   (text "［　男　］いやあ、何も聞いてないなぁ。いつもはキャサリンと来　　　　　ていたみたいだけど、今日はシーラさん一人だったし。")
   (wait)
   (text-reset 1)
   (text "［コール］一人でここに？　遊びに来てたのか？")
   (wait)
   (text-reset 1)
   (text
    "［　男　］そういえば今日は踊ってる姿をみなかったなぁ・・・。　　　　　なんか皆と話していただけで、２０分ぐらいで出て行っ　　　　　ちゃったよ。")
   (set-reg 227 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 216 #t) (= 220 #t) (= 223 #t) (= 228 #f))
   (text "［コール］行き先は？")
   (wait)
   (text-reset 1)
   (text "［　男　］そんな事まで知ってるはずがないだろ。でも、今日はな　　　　　んだかソワソワしていたな・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］ったく、肝心な事なのに・・・。")
   (wait)
   (text-reset 1)
   (text "［　男　］あっ、それともう一つ。")
   (wait)
   (text-reset 1)
   (text "［コール］何だ？")
   (wait)
   (text-reset 1)
   (text "［　男　］ライトダンス・ストリートがどうとか言ってるのを聞い　　　　　たぜ。")
   (wait)
   (text-reset 1)
   (text "［コール］ライトダンス・ストリートっていったら、あの田舎道へ　　　　　続く通りだな・・・。")
   (wait)
   (text-reset 1)
   (text "［　男　］あんたと山奥に旅行でも行こうと思ってるんじゃないの　　　　　か？")
   (wait)
   (text-reset 1)
   (text "［コール］いや、それはまずないよ。")
   (set-reg 228 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 216 #t) (= 220 #t) (= 223 #t) (= 229 #f))
   (text "［　男　］シーラさん、何かあったのか？")
   (wait)
   (text-reset 1)
   (text "［コール］いや、気にする事はないよ。奴は、何かあったらすぐに　　　　　俺の所へ連絡してくるからな。")
   (wait)
   (text-reset 1)
   (text "［　男　］そうか、なら家に居て連絡を待っていた方がいいんじゃ　　　　　ないか？")
   (wait)
   (text-reset 1)
   (text
    "［コール］それもそうだな・・・。シーラの部屋をスティーブさん　　　　　に調べてもらっていたし、何か手掛かりがあったかもし　　　　　れないもんな。")
   (set-reg 229 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 216 #t) (= 220 #t) (= 223 #t))
   (text "［　男　］シーラさんから連絡があったら、宜しく言っておいてく　　　　　れよ。")
   (wait)
   (text-reset 1)
   (text "［コール］ああ、判ったよ。")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 221 #f))
   (text "［コール］柱の陰にも客らしい人が立っているな。")
   (set-reg 221 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 222 #f))
   (text "［コール］あの・・・ちょっといいかな？")
   (wait)
   (text-reset 1)
   (text "［　男　］・・・・・・・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］聞きたい事があるんだけど・・・。")
   (wait)
   (text-reset 1)
   (text "［　男　］・・・・・・・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］何も言ってくれないな・・・酔ってるのかな？")
   (set-reg 222 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 223 #f))
   (text "［コール］なあ、ちょっと聞いてくれよ。")
   (wait)
   (text-reset 1)
   (text "［　男　］・・・・・・・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］なぁ・・・少しくらいいいだろ？")
   (wait)
   (text-reset 1)
   (text "［　男　］・・・・・・・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］やっぱりダメだな。")
   (set-reg 223 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "［コール］だめだよ、あの人はさっきから何を言っても口を利いて　　　　　くれないんだ。")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 224 #f))
   (text "［コール］ちょっと悪いな、聞きたい事があるんだが・・・。")
   (wait)
   (text-reset 1)
   (text "［　男　］イェーイ！")
   (wait)
   (text-reset 1)
   (text "［コール］おい、俺の話を聞いてくれよ。")
   (wait)
   (text-reset 1)
   (text "［　男　］イェイ、イェーイ！")
   (wait)
   (text-reset 1)
   (text "［コール］ああ、音がうるさくて俺の声が伝わらないよ。")
   (set-reg 224 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))
   (text "［　男　］")
   (branch-random
    (</> (/ (text "イェーイ！")) (/ (text "イェイ、イェーイ！")) (/ (text "イ、イェーイ！　イェーイ！"))))
   (wait)
   (text-reset 1)
   (text "［コール］")
   (branch-random
    (</>
     (/ (text "だめだ・・・あの人は、かなりイっちゃってるみたいだ　　　　　よ。"))
     (/ (text "酒がまわってるみたいだな・・・他の人に聞いた方がよ　　　　　さそうだ。"))
     (/ (text "ノリノリで踊ってるから、俺の声なんか聞こえないみた　　　　　いだな。"))))
   (wait)
   (text-reset 1))
 (seg (? (= P 9) (= 225 #f))
   (text "［コール］ちょっといいかな？")
   (wait)
   (text-reset 1)
   (text "［　男　］へいっ、そこの美人なお姉ちゃん！　あそぼ、あそぼ！")
   (wait)
   (text-reset 1)
   (text "［コール］おいっ、俺の話を聞いてくれよ。")
   (wait)
   (text-reset 1)
   (text "［　男　］あっ、そっちのお姉ちゃんもきれいだねっ！")
   (wait)
   (text-reset 1)
   (text "［コール］あの男、まるっきり俺の話を聞いてないな。")
   (set-reg 225 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 9))
   (text "［コール］")
   (branch-random
    (</>
     (/ (text "俺の話を聞けって・・・。"))
     (/ (text "なあ、ちょっと聞かせてくれよ。"))
     (/ (text "ここの常連なら知ってると思うけど、シーラって名前の　　　　　女だけど・・・。"))))
   (wait)
   (text-reset 1)
   (text "［　男　］")
   (branch-random
    (</>
     (/ (text "よっ！　お姉ちゃん！　きれいだよっ！"))
     (/ (text "おっ、ボディコンのお姉ちゃん！　今時、ボディコンは　　　　　流行らないよっ！　俺が一緒に服選んでやろうか？"))
     (/ (text "わーはははは、今日は女の子いっぱいだねっ！　お兄さ　　　　　ん嬉しいよっ！"))))
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 229 #t))
   (exec-mem 6064 2 1)
   (text "［コール］スティーブさんにも連絡しないといけないし、一度アパ　　　　　ートに戻ろう。")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥031.MES"))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))