(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB058.GPC")
  (image-mem 0 3)
  ((cmd 193) 0 "B:¥GPA¥DB060.GPA")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (text "Woman: Look, there's only one of him!")
  (wait)
  (text-reset 1)
  (text "B.F.: Heh heh heh...")
  (wait)
  (text-reset 1)
  (text "Briar: Check out the rocks on this guy, coming all by his   lonesome!")
  (wait)
  (text-reset 1)
  (text "Cole: It's you!")
  (wait)
  (text-reset 1)
  (text "B.F.: Hahahaha!")
  (wait)
  (text-reset 1)
  (text "Cole: You? You guys are the ones who kidnapped Sheila?")
  (wait)
  (text-reset 1)
  (text "B.F.: And what if that's the case? What are you gonna do    about it?")
  (wait)
  (text-reset 1)
  (text "Briar: Back in the bar, you had the balls to kill one of my buddies! You got some debts to pay, kid.")
  (wait)
  (text-reset 1)
  (text "Cole: What are you talking about! That was self-defense,    wasn't it?")
  (wait)
  (text-reset 1)
  (text "Briar: Self-defense? Holy shit, kid, do you even think      before you open your mouth?")
  (wait)
  (text-reset 1)
  (text "B.F.: Nya-ha-ha-ha!")
  (wait)
  (text-reset 1)
  (text
   "Briar: I can't stand pieces of shit like you who look down  on Bloody Fox!")
  (wait)
  (text-reset 1)
  (text "Cole: You assholes started it!")
  (wait)
  (text-reset 1)
  (text "Briar: Who fuckin' cares! What matters here is, you're too  dumb to be scared of us in the first place!")
  (wait)
  (text-reset 1)
  (text "Cole: What are you gonna do?")
  (wait)
  (text-reset 1)
  (text "Briar: You shot John, and you're gonna pay!")
  (wait)
  (text-reset 1)
  (text "Briar: Kill him!")
  (wait)
  (text-reset 1)
  (text "Cole: Shit!!!")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB059.GPC")
  (image-mem 0 3)
  (exec-mem 15456 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "B.F.: Nya-ha-ha!")
  (wait)
  (text-reset 1)
  (exec-mem 14544 2 2)
  (text "Cole: Unnngh!")
  (wait)
  (text-reset 1)
  (text "Briar: Scream all you want, nobody's saving you here!")
  (wait)
  (text-reset 1)
  (text "B.F.: Hunh!")
  (wait)
  (text-reset 1)
  (exec-mem 14544 2 2)
  (text "Cole: Urghhhh!")
  (wait)
  (text-reset 1)
  (text "B.F.: Lemme have a swing at this idiot too!")
  (wait)
  (text-reset 1)
  (text "B.F.: Nya-ha-ha!")
  (wait)
  (text-reset 1)
  (text "Cole: Fuck...fuck you!")
  (wait)
  (text-reset 1)
  (text "B.F.: Urg!!!")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB060.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "Cole: Don't move!")
  (wait)
  (text-reset 1)
  (text "B.F.: The fuck!?")
  (wait)
  (text-reset 1)
  (text "Briar: Now hold on a second...")
  (wait)
  (text-reset 1)
  (text "Cole: I don't have time to waste with your stupid games. Nowhand over Sheila...")
  (wait)
  (text-reset 1)
  (text "Cole: Or there's gonna be even more corpses than there were in Rease!")
  (wait)
  (text-reset 1)
  (text "B.F.: L-lemme go!")
  (wait)
  (text-reset 1)
  (text "Briar: You wanna start a shootout?")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 0 1)
  ((cmd 196) 0 2)
  (delay 2)
  (sound '|se | 13)
  ((cmd 196) 0 3)
  (delay 2)
  ((cmd 196) 0 4)
  (delay 2)
  ((cmd 196) 0 5)
  (delay 2)
  ((cmd 196) 0 6)
  (delay 2)
  ((cmd 196) 0 0)
  (text "B.F.: FAAAAACK!")
  (wait)
  (text-reset 1)
  (text "Cole: I'm serious as cancer. The next shot won't miss!")
  (wait)
  (text-reset 1)
  (text "B.F.: Ahhh, you fucker!")
  (wait)
  (text-reset 1)
  (text
   "Cole: You wanna have a go at me? Come on! Each one of you   gets a bullet until I'm empty! You think I'm bluffing, test me!")
  (wait)
  (text-reset 1)
  (text "B.F.: Aw, shit...")
  (wait)
  (text-reset 1)
  (text "Cole: So what's it gonna be?")
  (wait)
  (text-reset 1)
  (text "Briar: We're doing this, then?")
  (wait)
  (text-reset 1)
  (text "Cole: !?")
  (wait)
  (text-reset 1)
  (text "B.F.: Uhh... Briar...")
  (wait)
  (text-reset 1)
  (text "Briar: The next time he pulls the trigger, blast the girl!")
  (wait)
  (text-reset 1)
  (text "Cole: You...!")
  (wait)
  (text-reset 1)
  (text "Briar: Heh heh heh!")
  (wait)
  (text-reset 1)
  (text "B.F.: The fuck!?")
  (wait)
  (text-reset 1)
  (text "Briar: Or maybe we won't need to go down that route...")
  (wait)
  (text-reset 1)
  (text "Cole: Dammit...")
  (wait)
  (text-reset 1)
  (sound '|| 2)
  (exec-mem 9920 0 6 6 113 64 0)
  (text "Suddenly, I felt a blow to my head. As I started to fade, I realized I might not wake up again...")
  (wait)
  (text-reset 1)
  (text "But after several minutes, unable to bear the pain coursing through my body, I was brought back to consciousness.")
  (wait)
  (text-reset 1)
  (text "I couldn't move...but I felt a sweet breath on my face, and I slowly opened my eyes...")
  (wait)
  (text-reset 1)
  (image-file "B:¥GPC¥DB061.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB062.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB063.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "Woman: He's not a bad-looking specimen when you look at him up close...")
  (wait)
  (text-reset 1)
  (text "Woman: Looks like he's back with us.")
  (wait)
  (text-reset 1)
  (text "Briar: Get outta here!")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (sound '|| 0)
  (mes-jump "A:¥MES¥034.MES"))
 (seg*))