(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB058.GPC")
  (image-mem 0 3)
  ((cmd 193) 0 "B:¥GPA¥DB060.GPA")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (text "［　女　］一人みたいね・・・。")
  (wait)
  (text-reset 1)
  (text "［Ｂ・Ｆ］クックックッ・・・。")
  (wait)
  (text-reset 1)
  (text "［ブライア］たった一人でよく来れたもんだな。")
  (wait)
  (text-reset 1)
  (text "［コール］お、お前は！")
  (wait)
  (text-reset 1)
  (text "［Ｂ・Ｆ］ハッハッハッ！")
  (wait)
  (text-reset 1)
  (text "［コール］お前らか！？　シーラをさらったのは！？")
  (wait)
  (text-reset 1)
  (text "［Ｂ・Ｆ］だったらどうだってんだ、あんちゃんよぅ？")
  (wait)
  (text-reset 1)
  (text "［ブライア］リーズでは俺の可愛い仲間をよくも殺してくれたな。　　　　　　この貸しはでけえぞ。")
  (wait)
  (text-reset 1)
  (text "［コール］なんだと！？　あれは正当防衛だっただろ？")
  (wait)
  (text-reset 1)
  (text "［ブライア］正当防衛だと？　てめえ、周りを見てから口を利くん　　　　　　だな。")
  (wait)
  (text-reset 1)
  (text "［Ｂ・Ｆ］ヒャッヒャッヒャッ！")
  (wait)
  (text-reset 1)
  (text
   "［ブライア］俺はてめえみてぇなド素人が、ブラッディフォックス　　　　　　を見下したような態度をとっているのが、すげえ気に　　　　　　食わねぇんだよ！！")
  (wait)
  (text-reset 1)
  (text "［コール］元はお前達が俺にチョッカイを出して来たんだろ！？")
  (wait)
  (text-reset 1)
  (text "［ブライア］そんな事は問題じゃねぇ！　問題なのは、テメエにブ　　　　　　ラッディフォックスの恐ろしさが判ってない事だ！")
  (wait)
  (text-reset 1)
  (text "［コール］どうする気だ？")
  (wait)
  (text-reset 1)
  (text "［ブライア］テメエが撃ったジョンのかたきを討たせてもらうぜ！")
  (wait)
  (text-reset 1)
  (text "［ブライア］殺れ！")
  (wait)
  (text-reset 1)
  (text "［コール］ぐっ！")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB059.GPC")
  (image-mem 0 3)
  (exec-mem 15456 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "［Ｂ・Ｆ］ヒャーハハハハ！！")
  (wait)
  (text-reset 1)
  (exec-mem 14544 2 2)
  (text "［コール］ぐわっ！！")
  (wait)
  (text-reset 1)
  (text "［ブライア］叫んだところで、こんな所に誰も助けには来てくれな　　　　　　いぜ！！")
  (wait)
  (text-reset 1)
  (text "［Ｂ・Ｆ］オラッ！！")
  (wait)
  (text-reset 1)
  (exec-mem 14544 2 2)
  (text "［コール］ぐふっ・・・。")
  (wait)
  (text-reset 1)
  (text "［Ｂ・Ｆ］俺にもやらせろよ、こいつにゃ散々だったからな。")
  (wait)
  (text-reset 1)
  (text "［Ｂ・Ｆ］ヒャッヒャッヒャッヒャッ！")
  (wait)
  (text-reset 1)
  (text "［コール］こ、この野郎！！")
  (wait)
  (text-reset 1)
  (text "［Ｂ・Ｆ］ぐっ・・・。")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB060.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "［コール］動くな！！")
  (wait)
  (text-reset 1)
  (text "［Ｂ・Ｆ］野郎！！")
  (wait)
  (text-reset 1)
  (text "［ブライア］待て！")
  (wait)
  (text-reset 1)
  (text "［コール］これ以上、お前達の遊びに付き合ってる暇はないんだ。　　　　　さあ、シーラを返してもらおうか・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］でなきゃ、リーズの時より死体が増えるぜ。")
  (wait)
  (text-reset 1)
  (text "［Ｂ・Ｆ］は、放せ！！")
  (wait)
  (text-reset 1)
  (text "［ブライア］テメエ、俺達と殺り合おうってのか？")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 0 1)
  ((cmd 196) 0 2)
  (delay 2)
  (sound '|se | 13)
  ((cmd 196) 0 3)
  (delay 2)
  ((cmd 196) 0 4)
  (delay 2)
  ((cmd 196) 0 5)
  (delay 2)
  ((cmd 196) 0 6)
  (delay 2)
  ((cmd 196) 0 0)
  (text "［Ｂ・Ｆ］ヒ、ヒエェェェ！！")
  (wait)
  (text-reset 1)
  (text "［コール］俺は本気だ、次は外さない・・・。")
  (wait)
  (text-reset 1)
  (text "［Ｂ・Ｆ］てめえ！！")
  (wait)
  (text-reset 1)
  (text
   "［コール］来るなら来てみろ！　その代わり、この拳銃の弾がなく　　　　　なるまでお前の身体に全弾撃ち込んでやるからな！！　　　　　　嘘だと思うならかかって来い！！")
  (wait)
  (text-reset 1)
  (text "［Ｂ・Ｆ］くっ・・・・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］さあ、どうした！？")
  (wait)
  (text-reset 1)
  (text "［ブライア］やってみろ？")
  (wait)
  (text-reset 1)
  (text "［コール］！？")
  (wait)
  (text-reset 1)
  (text "［Ｂ・Ｆ］うっ・・・ブライアさん・・・。")
  (wait)
  (text-reset 1)
  (text "［ブライア］その代わり、こいつが撃ったら女を殺せ！！")
  (wait)
  (text-reset 1)
  (text "［コール］貴様！！")
  (wait)
  (text-reset 1)
  (text "［ブライア］フフフフ・・・。")
  (wait)
  (text-reset 1)
  (text "［Ｂ・Ｆ］野郎！！")
  (wait)
  (text-reset 1)
  (text "［ブライア］だが、その必要もなくなったようだな・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］グッ・・・！")
  (wait)
  (text-reset 1)
  (sound '|| 2)
  (exec-mem 9920 0 6 6 113 64 0)
  (text "俺は突然、頭部に今までに無い強い衝撃を覚えた。意識が薄れていく中、俺はこのまま二度と目覚める事はないと実感していた・・・")
  (wait)
  (text-reset 1)
  (text "しかし、数十分後。俺は全身の痛みに耐えられず、次第に意識が戻ってくるのを感じた。")
  (wait)
  (text-reset 1)
  (text "だが、思うように動けない・・・俺の頬に甘い息が吹き掛けられるのを感じ、俺はゆっくりと目を開けた。")
  (wait)
  (text-reset 1)
  (image-file "B:¥GPC¥DB061.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB062.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB063.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "［　女　］よく見るとなかなかいい男ね・・・。")
  (wait)
  (text-reset 1)
  (text "［　女　］あっ、目が覚めたわ。")
  (wait)
  (text-reset 1)
  (text "［ブライア］向こうに行ってろ！")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (sound '|| 0)
  (mes-jump "A:¥MES¥034.MES"))
 (seg*))