(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB062.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 20 2 27 7)
  (exec-mem 3744 1 6 41 5 48 8)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB061.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB062.GPC")
  (image-mem 1 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC")
  (image-mem 1 0)
  (image-file "B:¥GPC¥DB064RC.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (image-file "B:¥GPC¥DB064LC.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 1 54 38 23 134")
  (image-file "B:¥GPC¥DB065C.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 2 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 3 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 107 #f))
        (str "Briar: He's a tough sonofabitch...")
        (wait)
        (text-reset 1)
        (str "Cole: Bastard...")
        (wait)
        (text-reset 1)
        (str "Briar: We beat you half to death so you can't move, but you" 'br)
        (str "still can run your mouth.")
        (set-reg 107 #t)
        (wait)
        (text-reset 1))
       (//
        (str "Cole: Shit...I've been beaten so badly I don't have the" 'br)
        (str "strength to do anything.")
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 108 #f))
   (str "Cole: Sheila... Let me see Sheila.")
   (wait)
   (text-reset 1)
   (str "Briar: Bad news, she ain't here.")
   (wait)
   (text-reset 1)
   (str "Cole: But...where...?")
   (wait)
   (text-reset 1)
   (str "Briar: We locked her up in Rease, but Steve busted her out." 'br)
   (str "Our beef was with you. We didn't give a shit about the girl.")
   (set-reg 108 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 109 #f))
   (str "Cole: Steve rescued Sheila...?")
   (wait)
   (text-reset 1)
   (str "Briar: Someday I'm gonna end that guy.")
   (wait)
   (text-reset 1)
   (str "B.F.: Nya-ha-ha!")
   (set-reg 109 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 110 #f))
   (str "Briar: You've got some nerve, though.")
   (wait)
   (text-reset 1)
   (str "Cole: ...")
   (wait)
   (text-reset 1)
   (str "Briar: You show up at Rease, you take down two Bloody Fox" 'br)
   (str "members there, and now you show up all by yourself...")
   (wait)
   (text-reset 1)
   (str "Cole: What are you trying to say?")
   (wait)
   (text-reset 1)
   (str "Briar: You're taking on Bloody Fox, a gang that makes" 'br)
   (str "people piss themselves in fear. You've got some sorta" 'br)
   (str "ulterior motive, don't you?")
   (wait)
   (text-reset 1)
   (str "Cole: ...")
   (wait)
   (text-reset 1)
   (str "Briar: You wanna keep it to yourself, that's fine too.")
   (set-reg 110 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (str "Briar: Pity, I thought you were gonna be more of an open" 'br)
   (str "book.")
   (wait)
   (text-reset 1)
   (str "Briar: Yo, bring me that thing.")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 0 54 38,W 0,O 0")
   (str "Woman: Hee hee hee!")
   (wait)
   (text-reset 1)
   (exec-mem 912 "A 1")
   (exec-mem 912 "PUT 1 54 38,W 0,O 0")
   (exec-mem 912 "A 0")
   (exec-mem 19216 55 39 73 146 2 6 1 19)
   (str "Cole: !?")
   (wait)
   (text-reset 1)
   (str "Briar: The cops have been on our ass lately, making it a" 'br)
   (str "real pain to get rid of leftover Purple Sky. Maybe you can" 'br)
   (str "help us out a little?")
   (wait)
   (text-reset 1)
   (str "Cole: Leftover Purple Sky...!? Are you guys cooking it?")
   (wait)
   (text-reset 1)
   (str "Briar: Naw, we're just the guys handling the shipments, and" 'br)
   (str "there's a ton of it. Maybe it's time for you to get some" 'br)
   (str "chemical relief...")
   (wait)
   (text-reset 1)
   (str "Cole: Whoa whoa whoa, if that stuff gets injected into" 'br)
   (str "someone and it's got a bunch of DNV--")
   (wait)
   (text-reset 1)
   (str "B.F.: Stop struggling!")
   (wait)
   (text-reset 1)
   (str "Briar: Yeah! Yeah! Do it!")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 2 54 38,W 0,O 0")
   (str "Woman: Hee hee hee... Time for me to give you the ultimate" 'br)
   (str "ecstacy!")
   (wait)
   (text-reset 1)
   (str "Cole: Stop! STOP!!!!")
   (wait)
   (text-reset 1)
   (sound '|| 0)
   (sound '|se | 8)
   (str "Woman: Huh?")
   (wait)
   (text-reset 1)
   (str "Briar: Who's there?")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 3 54 38,W 0,O 0")
   (exec-mem 912 "EXIT")
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB061.GPC")
   (image-mem 0 3)
   (image-file "B:¥GPC¥DB066.GPC")
   (image-mem 1 3)
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (str "B.F.: Yo! This is bad!")
   (wait)
   (text-reset 1)
   (str "Briar: What's wrong?")
   (wait)
   (text-reset 1)
   (str "B.F.: The city's fucked, man!")
   (wait)
   (text-reset 1)
   (str "Briar: What are you talking about!?")
   (wait)
   (text-reset 1)
   (str "B.F.: Hundreds of fuckin' zombies came outta nowhere!")
   (sound '|| 0)
   (sound '|se | 4)
   (wait)
   (text-reset 1)
   (str "Cole: !?")
   (wait)
   (text-reset 1)
   (str "Briar: Zombies? Bro, are you high?")
   (wait)
   (text-reset 1)
   (str "B.F.: No bullshit! They killed most of my buddies! Mary," 'br)
   (str "Jonathan, Sting,... They got fuckin' EATEN! Come on, you" 'br)
   (str "gotta help!")
   (wait)
   (text-reset 1)
   (str "B.F.: What?!")
   (wait)
   (text-reset 1)
   (str "Briar: Aw, man...")
   (wait)
   (text-reset 1)
   (str "Briar: Okay, I get it. We gotta jet!")
   (wait)
   (text-reset 1)
   (str "B.F.: What about this asshole?")
   (wait)
   (text-reset 1)
   (str "Briar: Forget him! Saddle up, boys!")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB061.GPC")
   (image-mem 0 3)
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (str "Cole: Zombies tearing up the city? AGAIN? I knew this was" 'br)
   (str "gonna happen!")
   (wait)
   (text-reset 1)
   (str "Cole: There's no time to waste, I gotta go!")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (sound '|| 0)
   (mes-jump "A:¥MES¥035.MES"))
 (seg (? (= P 6))
   (branch-random
    (</>
     (/
      (str "Cole: ...")
      (wait)
      (text-reset 1)
      (str "B.F.: It's amazing how punching this idiot just makes me" 'br)
      (str "want to punch him more.")
      (wait)
      (text-reset 1))
     (/
      (str "B.F.: Havin' a good conversation with Briar? The fuck you" 'br)
      (str "starin' at? I'll flatten you!")
      (wait)
      (text-reset 1)
      (str "Cole: Just try me. You're gonna die!")
      (wait)
      (text-reset 1)
      (str "B.F.: The fuck did you just say!?")
      (wait)
      (text-reset 1)
      (str "Briar: Back off!")
      (wait)
      (text-reset 1))
     (/
      (str "B.F.: Let's just finish him off already.")
      (wait)
      (text-reset 1)
      (str "Briar: Hold on, let's not be so hasty.")
      (wait)
      (text-reset 1))
     (/
      (str "Cole: Come on, gimme a cig too.")
      (wait)
      (text-reset 1)
      (str "B.F.: Lookin' for some more pain? Are ya?")
      (wait)
      (text-reset 1)))))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))