; Dead of the Brain 2 (PC-98) - 037.MES
; Translated by Geometrizer
; Edited by trentsignia
; -----Scene:-----
; Steve meets Cole inside the Perain Research Institute.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB070.GPC") (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC") (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (str "Steve: Cole!!! God damn, you made it!")
  (wait)
  (text-reset 1)
  (str "Cole: Steve! The town...it's...")
  (wait)
  (text-reset 1)
  (str "Steve: I know. How'd you get in here?")
  (wait)
  (text-reset 1)
  (str "Cole: Fire escape door. I...uh, guessed the code.")
  (wait)
  (text-reset 1)
  (str "Steve: Ah, we didn't shutter that one yet, then...")
  (wait)
  (text-reset 1)
  (str "Cole: Where's Sheila?")
  (wait)
  (text-reset 1)
  (str "Steve: She's here, in the room at the end of the hallway on" 'br)
  (str "the left.")
  (wait)
  (text-reset 1)
  (str "Cole: I'm gonna go see her.")
  (wait)
  (text-reset 1)
  (str "Steve: When you're done talking, come to the main lab up" 'br)
  (str "front. We need to talk about our next steps.")
  (wait)
  (text-reset 1)
  (str "Cole: Okay.")
  (wait)
  (text-reset 1)
  (sound '|| 2)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  ((cmd 204) 100 899)
  (mes-jump "A:¥MES¥039.MES"))							; Note that this script jumps to 039, not 038
 (seg*))