(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB070.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (text "Steve: Cole!!! God damn, you made it!")
  (wait)
  (text-reset 1)
  (text "Cole: Steve! The town...it's...")
  (wait)
  (text-reset 1)
  (text "Steve: I know. How'd you get in here?")
  (wait)
  (text-reset 1)
  (text "Cole: Fire escape door. I...uh, guessed the code.")
  (wait)
  (text-reset 1)
  (text "Steve: Ah, we didn't shutter that one yet, then...")
  (wait)
  (text-reset 1)
  (text "Cole: Where's Sheila?")
  (wait)
  (text-reset 1)
  (text "Steve: She's here, in the room on the far left.")
  (wait)
  (text-reset 1)
  (text "Cole: i'm gonna go see her.")
  (wait)
  (text-reset 1)
  (text "Steve: When you're done talking, come to the main lab up    front. We need to talk about our next steps.")
  (wait)
  (text-reset 1)
  (text "Cole: Okay.")
  (wait)
  (text-reset 1)
  (sound '|| 2)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  ((cmd 204) 100 899)
  (mes-jump "A:¥MES¥039.MES"))
 (seg*))