(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB070.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (text "［スティーブ］コール！！　無事だったか！！")
  (wait)
  (text-reset 1)
  (text "［コール］スティーブさん！！　街が・・・街が・・・！！")
  (wait)
  (text-reset 1)
  (text "［スティーブ］ああ、知っている。それより、どこから入ってきた　　　　　　　んだ？")
  (wait)
  (text-reset 1)
  (text "［コール］非常階段のドアです。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］そうか、あそこはまだシャッターを閉めてなかった　　　　　　　んだ・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］それよりシーラは！？")
  (wait)
  (text-reset 1)
  (text "［スティーブ］ああ、奥の左手の部屋だ。")
  (wait)
  (text-reset 1)
  (text "［コール］ちょっと会ってきます。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］後で正面の研究室に来るんだ。今後の事について話　　　　　　　し合うからな。")
  (wait)
  (text-reset 1)
  (text "［コール］はい。")
  (wait)
  (text-reset 1)
  (sound '|| 2)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  ((cmd 204) 100 899)
  (mes-jump "A:¥MES¥039.MES"))
 (seg*))