; Dead of the Brain 2 (PC-98) - 038.MES
; Translated by Geometrizer
; Edited by trentsignia
; -----Scene:-----
; Cole visits Sheila in her room at Perain for the first time.
; --Progression:--
; Talk to Sheila, then MOVE.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (nop@)
  (set-reg 112 #t)
  (load-mem "A:¥CLM¥DB073.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)			; Hotspots and buttons defined here...
  (exec-mem 3744 1 1 80 0 0 0)							; 	MOVE button
  (exec-mem 3744 1 2 80 0 0 0)							; 	SYSTEM button
  (exec-mem 3744 1 5 30 3 37 7)							; 	Sheila
  (exec-mem 3744 1 6 50 3 56 14)						; 	Shower
  (exec-mem 3744 1 7 4 10 23 15)						; 	Bed
  (exec-mem 3744 1 8 15 2 27 9)							; 	Curtains
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB072.GPC") (image-mem 1 3)
  (image-file "B:¥GPC¥DB073.GPC") (image-mem 1 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 102 #f))								; Lead-in for first visit
        (str "Sheila: Cole!!!")
        (wait)
        (text-reset 1)
        (str "Cole: Sheila!!! Thank god, you're okay!")
        (set-reg 102 #t)
        (wait)
        (text-reset 1))
       (//
        (str "Cole: Sheila's alright...thankfully...")				; Lead-in from second visit onwards
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 103 #f))							; Sheila #1
   (str "Cole: It's Sheila... She's in one piece.")
   (wait)
   (text-reset 1)
   (str "Sheila: Cole...")
   (set-reg 103 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 104 #f))							; Sheila #2
   (str "Cole: Sheila, I've been worried sick about you. You could" 'br)
   (str "have at least called me...")
   (wait)
   (text-reset 1)
   (str "Sheila: I'm sorry... I've been researching Purple Sky all" 'br)
   (str "morning long...")
   (wait)
   (text-reset 1)
   (str "Cole: It's us against Bloody Fox. You can't take them on" 'br)
   (str "alone.")
   (wait)
   (text-reset 1)
   (str "Cole: And didn't you learn your lesson after what happened" 'br)
   (str "at Rease last night?")
   (wait)
   (text-reset 1)
   (str "Sheila: I... I couldn't just sit back once I started" 'br)
   (str "thinking about Doctor Cooger yesterday...")
   (wait)
   (text-reset 1)
   (str "Cole: ...")
   (wait)
   (text-reset 1)
   (str "Sheila: I can't forgive anyone who'd use his research for" 'br)
   (str "such twisted purposes.")
   (set-reg 104 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 105 #f))
   (str "Cole: Did you see what happened to your apartment?")
   (wait)
   (text-reset 1)
   (str "Sheila: Not yet, but you found it all torn up, right? Steve" 'br)
   (str "told me all about it.")
   (wait)
   (text-reset 1)
   (str "Cole: It was ransacked, yeah. Someone was trying to send a" 'br)
   (str "message.")
   (wait)
   (text-reset 1)
   (str "Sheila: !?")
   (wait)
   (text-reset 1)
   (str "Cole: My guess is that you discovered something about" 'br)
   (str "Purple Sky, and they've been trying to get you ever since.")
   (wait)
   (text-reset 1)
   (str "Cole: When you were trying to find out more about Purple" 'br)
   (str "Sky, you went to Disco Zeena and got kidnapped by Bloody" 'br)
   (str "Fox, didn't you?")
   (wait)
   (text-reset 1)
   (str "Sheila: How'd you know that?")
   (wait)
   (text-reset 1)
   (str "Cole: I've been busy chasing you down.")
   (set-reg 105 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 106 #f))							; Sheila #3
   (str "Sheila: When I asked about Purple Sky, someone mentioned" 'br)
   (str "they saw a case stamped with the Razovan Pharmaceuticals" 'br)
   (str "logo.")
   (wait)
   (text-reset 1)
   (str "Cole: Razovan?")
   (wait)
   (text-reset 1)
   (str "Sheila: Yes... They're out in the countryside, you can get" 'br)
   (str "there via Light Dance Street.")
   (wait)
   (text-reset 1)
   (str "Cole: Ah, that makes sense.. Did you go out there to see" 'br)
   (str "them?")
   (wait)
   (text-reset 1)
   (str "Sheila: I didn't get the chance. Bloody Fox grabbed me just" 'br)
   (str "minutes after I left Zeena.")
   (wait)
   (text-reset 1)
   (str "Cole: Damn.")
   (set-reg 106 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 107 #f))							; Sheila #4
   (str "Sheila: They took me back to Bar Rease and stole my ring.")
   (wait)
   (text-reset 1)
   (str "Cole: This ring?")
   (wait)
   (text-reset 1)
   (str "Sheila: Ah! Cole, how'd you get that?")
   (wait)
   (text-reset 1)
   (str "Cole: Bloody Fox used it as bait. They even left" 'br)
   (str "bloodstains on it...")
   (wait)
   (text-reset 1)
   (str "Sheila: And you fell for it?")
   (wait)
   (text-reset 1)
   (str "Cole: Of course! But by then, Steve had already rescued" 'br)
   (str "you. I wound up in their trap...")
   (wait)
   (text-reset 1)
   (str "Cole: And they almost injected me with Purple Sky.")
   (set-reg 107 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 108 #f))							; Sheila #5
   (str "Cole: Sheila, why didn't you call me? It was reckless to go" 'br)
   (str "digging all by yourself...")
   (wait)
   (text-reset 1)
   (str "Sheila: I'm sorry, Cole... I'll never do anything like that" 'br)
   (str "again.")
   (set-reg 108 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 109 #f))							; Sheila #6
   (str "Sheila: After Bloody Fox kidnapped me... If Steve hadn't" 'br)
   (str "shown up...")
   (wait)
   (text-reset 1)
   (str "Cole: That's right, we owe him big. And we need to look" 'br)
   (str "into Razovan Pharmaceuticals.")
   (set-reg 109 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))								; Sheila #7 (repeat line)
   (str "Sheila: I think Steve's probably still in the lab.")
   (wait)
   (text-reset 1)
   (str "Cole: Yeah, let's go.")
   (set-reg 110 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 111 #f))							; Shower #1
   (str "Cole: Where's this now?")
   (wait)
   (text-reset 1)
   (str "Sheila: Looks like a shower room. The facility has lots of" 'br)
   (str "rest facilities, I guess.")
   (set-reg 111 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))								; Shower #2 (repeat line)
   (str "Cole: Looks like a shower room...")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 113 #f))							; Bed #1
   (str "Cole: A typical pipe-frame bed. Got one of these back in" 'br)
   (str "the apartment, it's comfier than it looks.")
   (set-reg 113 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 114 #f))							; Bed #2
   (str "Sheila: What is it? You eyeing up the bed?")
   (wait)
   (text-reset 1)
   (str "Cole: Oh no, it's just you don't see that pipe-frame design" 'br)
   (str "a lot.")
   (wait)
   (text-reset 1)
   (str "Sheila: Cole, you've got one just like it in your" 'br)
   (str "apartment, right?")
   (wait)
   (text-reset 1)
   (str "Cole: Yeah, they're cheap and all...")
   (set-reg 114 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))								; Bed #3 (repeat line)
   (str "Cole: Just a standard pipe-frame bed.")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 115 #f))							; Curtains #1
   (str "Cole: The window. The curtains are closed. At this time of" 'br)
   (str "night it's pitch black outside.")
   (set-reg 115 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))								; Curtains #2 (repeat line)
   (str "Sheila: It gets cold at night, so I always close the" 'br)
   (str "curtains.")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 110 #t))							; MOVE (after talking to Sheila)
   (exec-mem 6064 2 1)
   (str "Cole: Okay, back to the hallway.")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥039.MES"))
 (seg (? (= P 2))
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25 317  39 317  53 317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))