(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (if (</>
       (// (? (= 146 #t)) (load-mem "A:¥CLM¥DB043A.CLM" 32768))
       (// (load-mem "A:¥CLM¥DB043.CLM" 32768))))
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 16 3 21 7)
  (if (</> (// (? (= 146 #f)) (exec-mem 3744 1 6 38 2 44 6))))
  (exec-mem 3744 1 7 25 2 34 7)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB043.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB044.GPC")
  (image-mem 1 3)
  (if (</>
       (// (? (= 146 #f)) (image-file "B:¥GPC¥DB071.GPC") (image-mem 1 3))))
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (sound '|se | 5)
  (if (</>
       (//
        (? (= 133 #f))
        (text "Lisle: Ah, Cole! You've made it back safely.")
        (wait)
        (text-reset 1)
        (text "Cole: Yes, thanks to you.")
        (wait)
        (text-reset 1)
        (text "Steve: How's Sheila doing?")
        (wait)
        (text-reset 1)
        (text "Cole: She's holding up well enough.")
        (set-reg 133 #t)
        (wait)
        (text-reset 1))
       (// (text "Lisle: Cole, you need something?") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 146 #t))
   (text "Lisle: Steve headed to the 32nd Precinct to grab whatever he" 'br)
(text "could find on Razovan Pharmaceuticals.")
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 134 #f))
   (text
    "Lisle: Dr. Cooger's research sure went apocalyptic. His" 'br)
"serum brought a whole city to its knees in a matter of" 'br)
"hours.")
   (wait)
   (text-reset 1)
   (text
    "Cole: I got no beef with Doc. He was trying to conquer" 'br)
"mankind's greatest enemy...Death. Then his work wound up in" 'br)
"the wrong hands...")
   (wait)
   (text-reset 1)
   (text "Cole: And here we are.")
   (wait)
   (text-reset 1)
   (text "Lisle: I'm sorry, perhaps I should have held my tongue.")
   (wait)
   (text-reset 1)
   (text "Cole: Naw, it's fine.")
   (set-reg 134 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 135 #f))
   (text "Lisle: How fares the city?")
   (wait)
   (text-reset 1)
   (text "Cole: Annihilated by those zombie freaks. There's no coming" 'br)
(text "back from that anytime soon.")
   (wait)
   (text-reset 1)
   (text "Lisle: So that's the case...")
   (set-reg 135 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 136 #f))
   (text "Lisle: How many zombies were there?")
   (wait)
   (text-reset 1)
   (text "Cole: Hard to put a number on it, but at least a hundred in" 'br)
(text "the shopping district.")
   (wait)
   (text-reset 1)
   (text "Lisle: A hundred!? That means there could be what, five, six" 'br)
(text "hundred in the whole city!")
   (set-reg 136 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 137 #f))
   (text "Lisle: Can you tell me more about these abominations?")
   (wait)
   (text-reset 1)
   (text
    "Cole: People who come back from the serum don't die from a" 'br)
"standard gunshot. To stop them, you have to destroy their" 'br)
"brains.")
   (wait)
   (text-reset 1)
   (text "Lisle: Is the serum injected into the brain?")
   (wait)
   (text-reset 1)
   (text "Cole: Yeah. When you inject it into a corpse's brain, that's" 'br)
(text "the organ that revives first, then the drug spreads out" 'br)
(text "through the body.")
   (wait)
   (text-reset 1)
   (text "Cole: Even if you crush a zombie's legs, as long as the" 'br)
(text "brain survives, it'll keep crawling at you...to eat yours.")
   (wait)
   (text-reset 1)
   (text "Lisle: Sweet Jesus. So...the brain is the problem here.")
   (wait)
   (text-reset 1)
   (text "Cole: What do you mean?")
   (wait)
   (text-reset 1)
   (text
    "Lisle: The human brain contains thousands of mysteries that" 'br)
"modern science has yet to solve. And Doctor Cooger solved" 'br)
"one of them...")
   (set-reg 137 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 138 #f))
   (text "Lisle: Ah, speaking of. Sheila was injected with Purple Sky," 'br)
(text "so I did a blood draw from her.")
   (wait)
   (text-reset 1)
   (text "Cole: Could you tell anything from the results?")
   (wait)
   (text-reset 1)
   (text "Lisle: I'll need some time for analysis, but she seems" 'br)
(text "chipper, so I wouldn't worry much.")
   (wait)
   (text-reset 1)
   (text "Cole: Thanks, Doctor.")
   (set-reg 138 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "Lisle: Sheila seems up and about, so there's not much cause" 'br)
(text "for concern.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 139 #f))
   (text "Steve: Cole, did you talk to Sheila?")
   (wait)
   (text-reset 1)
   (text "Cole: Yeah, she filled me in on everything.")
   (wait)
   (text-reset 1)
   (text "Steve: She's one tough cookie.")
   (wait)
   (text-reset 1)
   (text "Cole: You really saved her bacon.")
   (wait)
   (text-reset 1)
   (text
    "Steve: But I saved her and nobody else. Based on what I've" 'br)
"seen, we're the only survivors left.")
   (wait)
   (text-reset 1)
   (text "Cole: Shit! Are you serious!?")
   (wait)
   (text-reset 1)
   (text
    "Steve: At this rate, the zombies will keep multiplying and the city will be at an epidemic level. We need to find the culprit  before that happens.")
   (wait)
   (text-reset 1)
   (text "Cole: What about reinforcements?")
   (wait)
   (text-reset 1)
   (text "Steve: The State Police visits the 32nd Precinct regularly," 'br)
(text "but I'd say this is ultimately going to fall under military" 'br)
(text "jurisdiction.")
   (wait)
   (text-reset 1)
   (text "Cole: Then when does the cavalry arrive?")
   (wait)
   (text-reset 1)
   (text
    "Steve: The State Police? Tomorrow. After that they'll meet" 'br)
"with the military, so it'd take...three days for them to" 'br)
"arrive.")
   (wait)
   (text-reset 1)
   (text "Cole: Three days! Aw, man.")
   (set-reg 139 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 140 #f))
   (text "Cole: Oh, but Sheila had some information about Razovan" 'br)
(text "Pharmaceuticals...")
   (wait)
   (text-reset 1)
   (text "Steve: Right, she said there was a Purple Sky case with" 'br)
(text "their logo on it...? That seems damning.")
   (wait)
   (text-reset 1)
   (text "Cole: It sounds like Razovan was manufacturing the Purple" 'br)
(text "Sky.")
   (set-reg 140 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 141 #f))
   (text "Steve: ...Ah, that's it!")
   (wait)
   (text-reset 1)
   (text "Cole: What now?")
   (wait)
   (text-reset 1)
   (text
    "Steve: It's all coming back to me... Not long ago, Razovan" 'br)
"got raided for violating the Narcotics Control Act. Yeah," 'br)
"that was them...")
   (wait)
   (text-reset 1)
   (text "Cole: Narcotics?")
   (wait)
   (text-reset 1)
   (text "Steve: Yes. The boxes we seized tested positive for heroin," 'br)
(text "and we arrested four of their sales reps.")
   (wait)
   (text-reset 1)
   (text "Cole: Steve, Purple Sky is half heroin!")
   (wait)
   (text-reset 1)
   (text "Steve: It's all connected. They're the ones making the junk.")
   (wait)
   (text-reset 1)
   (text "Cole: We gotta go do something!")
   (wait)
   (text-reset 1)
   (text "Steve: Hold your horses, Cole. Heading straight into Razovan" 'br)
(text "is like walking into a meat grinder.")
   (wait)
   (text-reset 1)
   (text "Cole: But at this rate...")
   (set-reg 141 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 142 #f))
   (text "Steve: Back at the precinct, we've got materials on Razovan" 'br)
(text "from the raid.")
   (wait)
   (text-reset 1)
   (text "Cole: I'll go get them!")
   (wait)
   (text-reset 1)
   (text "Steve: No no, I'll do it. After all, you've finally got" 'br)
(text "Sheila back, right? You should stick around a little longer.")
   (wait)
   (text-reset 1)
   (text "Cole: ...")
   (wait)
   (text-reset 1)
   (text "Steve: I'll leave the lab matters to you and Dr. Lisle.")
   (set-reg 142 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "Cole: Watch your back, Steve. You never know where those" 'br)
(text "flesh-eating bastards will come from next.")
   (wait)
   (text-reset 1)
   (text "Steve: Don't worry, I'm confident in my marksmanship.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 143 #f))
   (text "Cole: I'm always overwhelmed by all the complicated-looking" 'br)
(text "stuff in this lab.")
   (wait)
   (text-reset 1)
   (text "Lisle: This lab is my entire existence.")
   (set-reg 143 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 144 #f))
   (if (</>
        (// (? (= 146 #t)) (text "Lisle: What's wrong? Why do you keep looking around" 'br)
(text "nervously?"))
        (// (text "Steve: Cole, calm down for once.") (set-reg 144 #t))))
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 145 #f))
   (text "Cole: Lisle, you said you were Doc Cooger's assistant back" 'br)
(text "in the day. Was he working here?")
   (wait)
   (text-reset 1)
   (text
    "Lisle: No, back then I was in the lab at Central Hospital." 'br)
"Two years later, Dr. Cooger struck out on his own.")
   (wait)
   (text-reset 1)
   (text
    "Lisle: I wanted to follow him, but for some reason he said" 'br)
"he didn't need assistants anymore... So I had to stick" 'br)
"around.")
   (wait)
   (text-reset 1)
   (text "Cole: So what was Doc doing back then?")
   (wait)
   (text-reset 1)
   (text "Lisle: Mmm... He must have discovered a way to rejuvenate" 'br)
(text "cells.")
   (set-reg 145 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "Lisle: I always wanted to work here with Dr. Cooger...")
   (wait)
   (text-reset 1)
   (text "Cole: ...")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 138 #f))
   (exec-mem 6064 2 1)
   (text "Cole: If you'll excuse me for a moment.")
   (wait)
   (text-reset 1)
   (text "Steve: We've still got some things to discuss. Head back" 'br)
(text "here when you're ready.")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥039.MES"))
 (seg (? (= P 1) (= 142 #f))
   (exec-mem 6064 2 1)
   (text "Cole: If you'll excuse me for a moment.")
   (wait)
   (text-reset 1)
   (text "Steve: We've still got some things to discuss. Head back" 'br)
(text "here when you're ready.")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥039.MES"))
 (seg (? (= P 1) (= 138 #t) (= 142 #t) (= 146 #f))
   (exec-mem 6064 2 1)
   (text "Cole: Okay, I'm gonna go check on Sheila.")
   (wait)
   (text-reset 1)
   (text
    "Lisle: Cole? You can use the room at the front right of the" 'br)
"hallway. And when you need to go out, use the station wagon" 'br)
"parked out back. The keys are in the ignition.")
   (wait)
   (text-reset 1)
   (text "Cole: I'll remember that.")
   (wait)
   (text-reset 1)
   (text "Steve: I'll head to the station to grab the records on" 'br)
(text "Razovan.")
   (wait)
   (text-reset 1)
   (text "Cole: Steve, don't let those zombies cancel your plans.")
   (wait)
   (text-reset 1)
   (text "Steve: I got it covered.")
   (set-reg 146 #t)
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "a:¥mes¥039.MES"))
 (seg (? (= P 1))
   (exec-mem 6064 2 1)
   (text "Cole: Okay, I'm off.")
   (wait)
   (text-reset 1)
   (text "Lisle: Come back if you need anything.")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥039.MES"))
 (seg (? (= P 2))
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))