(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (if (</>
       (// (? (= 146 #t)) (load-mem "A:¥CLM¥DB043A.CLM" 32768))
       (// (load-mem "A:¥CLM¥DB043.CLM" 32768))))
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 16 3 21 7)
  (if (</> (// (? (= 146 #f)) (exec-mem 3744 1 6 38 2 44 6))))
  (exec-mem 3744 1 7 25 2 34 7)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB043.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB044.GPC")
  (image-mem 1 3)
  (if (</>
       (// (? (= 146 #f)) (image-file "B:¥GPC¥DB071.GPC") (image-mem 1 3))))
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (sound '|se | 5)
  (if (</>
       (//
        (? (= 133 #f))
        (text "［ライル］コール、よく無事だったな！")
        (wait)
        (text-reset 1)
        (text "［コール］ええ、お陰様で・・・。")
        (wait)
        (text-reset 1)
        (text "［スティーブ］シーラの様子はどうだったかね？")
        (wait)
        (text-reset 1)
        (text "［コール］ええ、落ち着いていました。")
        (set-reg 133 #t)
        (wait)
        (text-reset 1))
       (// (text "［ライル］コールか、何か用かな？") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 146 #t))
   (text "［ライル］スティーブならラゾバン製薬会社の資料を取りに、３２　　　　　分署に行ったよ。")
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 134 #f))
   (text
    "［ライル］しかしクーガー博士は大変な物を作ってくれたな。彼の　　　　　薬は、数時間で街を崩壊してしまう程の力があるなんて　　　　　な・・・。")
   (wait)
   (text-reset 1)
   (text
    "［コール］ドクに恨みはありません。彼は人間の一番の恐怖である　　　　　死を克服しようとしていたんですから・・・それがちょ　　　　　っとした手違いで人の手に渡ってしまった・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］それでこんな事に・・・。")
   (wait)
   (text-reset 1)
   (text "［ライル］すまない・・・変な事を言ってしまったようだ。許して　　　　　くれ・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］いえ、いいんです。")
   (set-reg 134 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 135 #f))
   (text "［ライル］それで、街はどうだったのかね？")
   (wait)
   (text-reset 1)
   (text "［コール］死霊に壊滅されていました・・・。もう、しばらくあの　　　　　街を復旧させる事はできないでしょう。")
   (wait)
   (text-reset 1)
   (text "［ライル］そうか・・・。")
   (set-reg 135 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 136 #f))
   (text "［ライル］それで、死霊の数は？")
   (wait)
   (text-reset 1)
   (text "［コール］判りません・・・・。ですが、俺が見た商店街だけでも　　　　　１００体はいると思います。")
   (wait)
   (text-reset 1)
   (text "［ライル］商店街だけで１００体とは・・・。これでは街全体で５　　　　　・６００体は居そうだな。")
   (set-reg 136 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 137 #f))
   (text "［ライル］死霊について詳しく教えてくれないか？")
   (wait)
   (text-reset 1)
   (text
    "［コール］蘇生薬によって蘇った死霊は、銃で撃ったところで死に　　　　　ません。完全に奴等の息の根を止めるには、彼等の脳を　　　　　破壊することです。")
   (wait)
   (text-reset 1)
   (text "［ライル］蘇生薬の注射も脳なのか？")
   (wait)
   (text-reset 1)
   (text "［コール］はい、死体の脳に蘇生薬を打った場合、一番最初に蘇る　　　　　のは脳で、次第に薬は全身に回ります。")
   (wait)
   (text-reset 1)
   (text "［コール］例え、蘇った死霊の足をヒットして破壊しても、脳が正　　　　　常である限り、奴等は這ってでも俺達人間を襲います。")
   (wait)
   (text-reset 1)
   (text "［ライル］問題は脳か・・・。くそっ！")
   (wait)
   (text-reset 1)
   (text "［コール］？")
   (wait)
   (text-reset 1)
   (text
    "［ライル］人間の脳には、現代の科学では解明できない未知なる謎　　　　　がたくさんあるんだ。まさに、クーガー博士はその謎を　　　　　一つ解明してしまったんだな。")
   (set-reg 137 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 138 #f))
   (text "［ライル］あ、そうそう。シーラ君がパープル・スカイを打たれた　　　　　と言っていたから、さっき血液を採らせてもらったよ。")
   (wait)
   (text-reset 1)
   (text "［コール］それで・・・どうでした？")
   (wait)
   (text-reset 1)
   (text "［ライル］結果の方は少々、時間がかかるが・・・まあ、あれだけ　　　　　元気ならまず心配はないと思うがね。　")
   (wait)
   (text-reset 1)
   (text "［コール］そうですか、宜しくお願いします。")
   (set-reg 138 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "［ライル］まあ、シーラ君があれだけ元気なら、まず心配はないだ　　　　　ろうね。")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 139 #f))
   (text "［スティーブ］コール、シーラから聞いたか？")
   (wait)
   (text-reset 1)
   (text "［コール］ええ、全て聞きました。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］まったく・・・勇気のある彼女だな。")
   (wait)
   (text-reset 1)
   (text "［コール］すいませんでした・・・。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］しかし、大変な事が起こってしまったな。先程、私　　　　　　　が調べた結果、我々以外に生き残っている人間はゼ　　　　　　　ロに等しい。")
   (wait)
   (text-reset 1)
   (text "［コール］クソッ・・・。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］このままでは死体が増え続けてしまい、街全体に伝　　　　　　　染病が広まってしまう。何とかその前に犯人を見つ　　　　　　　けだしたい。")
   (wait)
   (text-reset 1)
   (text "［コール］救援は？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］州警察が定期的に３２分署に来る事になっているが　　　　　　　この状況じゃあ、全て軍に任せる事になるだろう。")
   (wait)
   (text-reset 1)
   (text "［コール］いつ頃になりそうですか？")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］明日だ。だが、その後、軍に連絡されて会議にかか　　　　　　　るだろう。単純に計算しても、軍がここに来る迄に　　　　　　　３日はかかるだろうな。")
   (wait)
   (text-reset 1)
   (text "［コール］３日か・・・。")
   (set-reg 139 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 140 #f))
   (text "［コール］でも、シーラはラゾバン製薬についての情報を持ってい　　　　　ました。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ああ、パープル・スカイのケースにラゾバン製薬の　　　　　　　社印があったそうだな。")
   (wait)
   (text-reset 1)
   (text "［コール］パープル・スカイをラゾバン製薬で作っている可能性が　　　　　ありそうですね。")
   (set-reg 140 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 141 #f))
   (text "［スティーブ］・・・・そうか！")
   (wait)
   (text-reset 1)
   (text "［コール］！？")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］思い出したぞ！　ついこの間、ラゾバン製薬が麻薬　　　　　　　取締法違反でガサ入れされていたんだ。そうか、あ　　　　　　　そこがラゾバン製薬だったのか・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］麻薬！？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ああ、押収したダンボールからヘロインの反応が出　　　　　　　てね、販売の担当者を４名パクったんだ。")
   (wait)
   (text-reset 1)
   (text "［コール］スティーブさん、ヘロインと言ったらパープル・スカイ　　　　　に混合されていますよ！")
   (wait)
   (text-reset 1)
   (text "［スティーブ］これで繋がったな・・・。パープル・スカイを製造　　　　　　　しているのはラゾバン製薬に間違いないだろう。")
   (wait)
   (text-reset 1)
   (text "［コール］早速、行きましょう！")
   (wait)
   (text-reset 1)
   (text "［スティーブ］待て、コール。このままラゾバン製薬に行く事は、　　　　　　　ノコノコと殺されに行くようなモンだよ。")
   (wait)
   (text-reset 1)
   (text "［コール］でも、このままじゃ・・・。")
   (set-reg 141 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 142 #f))
   (text "［スティーブ］署に行けば、ガサ入れした時のラゾバン製薬に関す　　　　　　　る資料がある筈だ。")
   (wait)
   (text-reset 1)
   (text "［コール］じゃあ、俺が取ってきます。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］いや、私が行こう。折角、シーラに会えたんだろ？　　　　　　　少しは彼女の側にいてやった方がいい。")
   (wait)
   (text-reset 1)
   (text "［コール］・・・・・・・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］研究所の事はライルとコールに任せるよ。")
   (set-reg 142 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "［コール］気を付けてください。死霊はどこに潜んでいるか判りま　　　　　せんから・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］大丈夫だ、こんな私でも射撃の腕には多少の自信が　　　　　　　あるよ。")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 143 #f))
   (text "［コール］相変わらず、いつ来てもこの研究室には圧倒されるな。")
   (wait)
   (text-reset 1)
   (text "［ライル］この研究室は私の命だよ。")
   (set-reg 143 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 144 #f))
   (if (</>
        (// (? (= 146 #t)) (text "［ライル］どうした？　キョロキョロして？"))
        (// (text "［スティーブ］コール、落ち着かないな。") (set-reg 144 #t))))
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 145 #f))
   (text "［コール］ライルさん、ドクの助手をやっていたって言ってたけど　　　　　この研究室で？")
   (wait)
   (text-reset 1)
   (text
    "［ライル］いや、当時はセントラル・ホスピタルの研究室に居たん　　　　　だ。それから２年程してから、急にクーガー博士は独立　　　　　したんだよ。")
   (wait)
   (text-reset 1)
   (text
    "［ライル］私も一緒について行きたかったが、クーガー博士は何を　　　　　思ったのか、もう助手はいらないとね・・・。私は仕方　　　　　なく残ったんだ。")
   (wait)
   (text-reset 1)
   (text "［コール］じゃあ、その時にドクは・・・。")
   (wait)
   (text-reset 1)
   (text "［ライル］そう、細胞の蘇生について道が見えてきたんだろうな。")
   (set-reg 145 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "［ライル］ここでずっとクーガー博士と仕事をしたかったよ。")
   (wait)
   (text-reset 1)
   (text "［コール］・・・・・・・・・。")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 138 #f))
   (exec-mem 6064 2 1)
   (text "［コール］ちょっと失礼しますが・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ああ、俺達はまだ話す事があるから用が済んだら、　　　　　　　またここに来なさい。")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥039.MES"))
 (seg (? (= P 1) (= 142 #f))
   (exec-mem 6064 2 1)
   (text "［コール］ちょっと失礼しますが・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ああ、俺達はまだ話す事があるから用が済んだら、　　　　　　　またここに来なさい。")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥039.MES"))
 (seg (? (= P 1) (= 138 #t) (= 142 #t) (= 146 #f))
   (exec-mem 6064 2 1)
   (text "［コール］じゃあ、シーラの様子を見てきます。")
   (wait)
   (text-reset 1)
   (text
    "［ライル］あ、コール。廊下の右手前の部屋は君が使っていいよ。　　　　　それと、表に用がある時は裏に止めてあるバンを使うと　　　　　いい。キーは車についている。")
   (wait)
   (text-reset 1)
   (text "［コール］ありがとうございます。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］俺も、署に行ってラゾバン製薬の資料を探してみる　　　　　　　よ。")
   (wait)
   (text-reset 1)
   (text "［コール］スティーブさん、死霊にはくれぐれも注意してください　　　　　ね。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］任せておいてくれ。")
   (set-reg 146 #t)
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "a:¥mes¥039.MES"))
 (seg (? (= P 1))
   (exec-mem 6064 2 1)
   (text "［コール］じゃあ、俺はこれで・・・。")
   (wait)
   (text-reset 1)
   (text "［ライル］用があったらまた来るといい。")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥039.MES"))
 (seg (? (= P 2))
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))