(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB078.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "［キャサリン］ありがとう・・・少し落ち着いた。")
  (wait)
  (text-reset 1)
  (text "［コール］そうか、良かった・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］街が変わってしまったみたい・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］ああ、死霊にやられてしまったよ。２年前と同じさ。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］２年前？")
  (wait)
  (text-reset 1)
  (text "［コール］ああ・・・。")
  (wait)
  (text-reset 1)
  (text
   "俺は２年前の事件の事をキャサリンに聞かせた。普通なら、誰でも疑うようなその話を、現状を見ているキャサリンは俺の一言一言の全てを聞き入れた。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］・・・そうだったの・・・知らなかった・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］ああ、この話はシーラと俺しか知らなかった筈だったん　　　　　だが・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］そのスティーブさんって刑事さん、可哀想・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］ああ・・・兄さんが利用されていたんだもんな・・・。　　　　　彼の辛い気持ちは痛いほど判るよ・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］でも、その蘇生薬を作ったドクは天才ね。")
  (wait)
  (text-reset 1)
  (text "［コール］天才か・・・。そうだよな、天才だからあんな薬が作れ　　　　　るんだよな・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］ん？　なんだ、キャサリン。元気出てきたじゃないか？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］不思議ね・・・今までに無い悲惨な経験をしたのに　　　　　　　なんだかコールと喋っていると元気になってくる。")
  (wait)
  (text-reset 1)
  (text "［コール］そうか、それは良かったな。")
  (wait)
  (text-reset 1)
  (text "［コール］だけど、また覆すようで悪いんだけど、ちょっと気にな　　　　　った事があるんだが・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］何？　言ってみて？")
  (wait)
  (text-reset 1)
  (text
   "［コール］シャッフル・フードでブラッディフォックスの死体を見　　　　　たんだが・・・最近じゃ、奴等もレストランに来るよう　　　　　になったのか？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］・・・どうした？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］あの人達、食事に来たのではないわ・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］？")
  (wait)
  (text-reset 1)
  (text
   "［キャサリン］実は私は彼等に呼び出されたの・・・。強引に連れ　　　　　　　て行かれそうになって・・・私、何が何だか判らな　　　　　　　くて抵抗している所に死霊が・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］ブラッディフォックスの連中を襲ったのか？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］ええ・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］でも、どうしてキャサリンを連れて行こうと？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］判らない・・ただ彼等は「お前の親父に頼まれた」　　　　　　　って言ってたけど・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］親父さんに？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］親父さん、どうしたんだ？")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB079.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text
   "［キャサリン］私の両親は５年前に別れたの。私は母と一緒に暮ら　　　　　　　していたけど、２年前に母が再婚して３人で暮らす　　　　　　　ようになったわ。")
  (wait)
  (text-reset 1)
  (text
   "［キャサリン］だけど、最初のうちは、さすがに新しい父には抵抗　　　　　　　があった・・・。だけど母が愛した人だから、３人　　　　　　　で仲良くやろうと努力したわ。")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB080.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text
   "［キャサリン］だけど、ある日あの人は母の居ない間を狙って私に　　　　　　　乱暴をしたわ。それから私はシャッフルでバイトし　　　　　　　ながら一人で暮らすようになったの・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］そうか・・・なんだか悪い事を聞いちゃったな・・・。")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB078.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text
   "［キャサリン］いいのよ、ラゾバンだか何だか知らないけど、大手　　　　　　　製薬会社の所長がそんな事をしてるって事を、色々　　　　　　　な人に知ってもらいたいしね。")
  (wait)
  (text-reset 1)
  (text "［コール］そうだよな、いくら大手企業だって・・ん？　ちょっと　　　　　待って・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］今、ラゾバン製薬って言ったか？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］ええ、言ったわ。ラゾバン製薬の所長よ、あのタヌ　　　　　　　キ親父は。")
  (wait)
  (text-reset 1)
  (text
   "［コール］そうか！　ラゾバン製薬はブラッディフォックスと繋が　　　　　っているんだ。それでキャサリンの親父がブラッディフ　　　　　ォックスを使って彼女を・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］キャサリン、その親父さんの名前は？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］ダニエルよ、ダニエル・ホワイト。")
  (wait)
  (text-reset 1)
  (text "［コール］ダニエル・ホワイトか・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］あ、もう研究所だな。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］あそこ？")
  (wait)
  (text-reset 1)
  (text "［コール］そうだよ。早くこの事をスティーブさんにも伝えた方が　　　　　いいな。")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (sound '|| 2)
  (mes-jump "A:¥MES¥048.MES"))
 (seg*))