; Dead of the Brain 2 (PC-98) - 04.MES
; Translated by Geometrizer
; Edited by JackDBS, commented by trentsignia
; -----Scene:-----
; Catherine talks to Cole as he drives them back to the lab. (Sexual harassment counter: 4)
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB078.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (str "Catherine: Thank you... I'm starting to feel a little" 'br)
  (str "better.")
  (wait)
  (text-reset 1)
  (str "Cole: That's a good thing.")
  (wait)
  (text-reset 1)
  (str "Catherine: I can barely recognize the city from before...")
  (wait)
  (text-reset 1)
  (str "Cole: That's what zombies do to a place. Just like two" 'br)
  (str "years ago.")
  (wait)
  (text-reset 1)
  (str "Catherine: Two years ago?")
  (wait)
  (text-reset 1)
  (str "Cole: Yeah...")
  (wait)
  (text-reset 1)
  (str "I told Catherine about the incident. Most people would have" 'br)
  (str "shrugged it off as crazy, but given the circumstances," 'br)
  (str "Catherine believed every last word.")
  (wait)
  (text-reset 1)
  (str "Catherine: So that's what happened... I had no idea.")
  (wait)
  (text-reset 1)
  (str "Cole: Yeah, only Sheila and I knew the whole story...")
  (wait)
  (text-reset 1)
  (str "Catherine: That poor detective, Steve...")
  (wait)
  (text-reset 1)
  (str "Cole: His brother was totally manipulated... I understand" 'br)
  (str "his pain all too well.")
  (wait)
  (text-reset 1)
  (str "Catherine: But Doc... He created that serum... He was a" 'br)
  (str "genius.")
  (wait)
  (text-reset 1)
  (str "Cole: You could call him that... Because of his big brain" 'br)
  (str "he made that crazy drug.")
  (wait)
  (text-reset 1)
  (str "Cole: What's up, Catherine? You look like you're perking up.")
  (wait)
  (text-reset 1)
  (str "Catherine: It's strange... Even after getting traumatized," 'br)
  (str "talking with you makes me feel better.")
  (wait)
  (text-reset 1)
  (str "Cole: Well, that's a plus.")
  (wait)
  (text-reset 1)
  (str "Cole: I'm sorry to change the subject, but there's been" 'br)
  (str "something bugging me.")
  (wait)
  (text-reset 1)
  (str "Catherine: What is it?")
  (wait)
  (text-reset 1)
  (str "Cole: I saw all the dead Bloody Fox members in the" 'br)
  (str "restaurant. But... Were they really there to eat?")
  (wait)
  (text-reset 1)
  (str "Catherine: ...")
  (wait)
  (text-reset 1)
  (str "Cole: ...What's wrong?")
  (wait)
  (text-reset 1)
  (str "Catherine: They weren't there for the food.")
  (wait)
  (text-reset 1)
  (str "Cole: ?")
  (wait)
  (text-reset 1)
  (str "Catherine: The truth is, they had come for me... And as I" 'br)
  (str "was fighting back, the zombies showed up...")
  (wait)
  (text-reset 1)
  (str "Cole: And they wiped out the Bloody Fox gang?")
  (wait)
  (text-reset 1)
  (str "Catherine: Yes...")
  (wait)
  (text-reset 1)
  (str "Cole: But why were they trying to kidnap you?")
  (wait)
  (text-reset 1)
  (str "Catherine: I don't know... They just told me that my" 'br)
  (str "stepfather asked them to.")
  (wait)
  (text-reset 1)
  (str "Cole: Your stepfather?")
  (wait)
  (text-reset 1)
  (str "Catherine: ...")
  (wait)
  (text-reset 1)
  (str "Cole: What's the deal with you and your stepdad?")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB079.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (str "Catherine: My parents split up five years ago. I was living" 'br)
  (str "with my mom, but two years ago, she remarried and he moved" 'br)
  (str "in with us...")
  (wait)
  (text-reset 1)
  (str "Catherine: At first, I resisted having a new father... But" 'br)
  (str "since my mother loved him so much, we tried to make it work" 'br)
  (str "as a family.")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB080.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (str "Catherine: But one day when my mother wasn't home, that" 'br)
  (str "man...took advantage of me. After that, I moved out and" 'br)
  (str "lived on my own while working part-time at Shuffle Food...")
  (wait)
  (text-reset 1)
  (str "Cole: That is...fucked up. I'm sorry to hear that happened" 'br)
  (str "to you.")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB078.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (str "Catherine: It's okay. I want everyone to know that the" 'br)
  (str "director of that pharma company -- Razovan, or whatever --" 'br)
  (str "is a person who does that kind of thing.")
  (wait)
  (text-reset 1)
  (str "Cole: You can be at the top of a company and still be a" 'br)
  (str "real piece of -- wait, did you say Razovan?")
  (wait)
  (text-reset 1)
  (str "Cole: The Pharmaceutical Company, Razovan?")
  (wait)
  (text-reset 1)
  (str "Catherine: One and the same. Their director...that grinning" 'br)
  (str "coward.")
  (wait)
  (text-reset 1)
  (str "Cole: Damn! So Razovan is in cahoots with Bloody Fox, and" 'br)
  (str "your father was trying to get them to...")
  (wait)
  (text-reset 1)
  (str "Cole: Catherine, what's your father's name?")
  (wait)
  (text-reset 1)
  (str "Catherine: Daniel. Daniel White.")
  (wait)
  (text-reset 1)
  (str "Cole: Daniel White...")
  (wait)
  (text-reset 1)
  (str "Cole: Ah, we're almost at the Institute.")
  (wait)
  (text-reset 1)
  (str "Catherine: It's over there?")
  (wait)
  (text-reset 1)
  (str "Cole: Yeah. We should let Steve know about this.")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (sound '|| 2)
  (mes-jump "A:¥MES¥048.MES"))
 (seg*))