(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB081A.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 13 3 20 7)
  (exec-mem 3744 1 6 38 2 44 6)
  (exec-mem 3744 1 7 25 2 34 7)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB043.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB081A.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC")
  (image-mem 1 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC")
  (image-mem 1 0)
  (image-file "B:¥GPC¥DB099C.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 100 #f))
        (text "Steve: Cole, are you alright!?")
        (wait)
        (text-reset 1)
        (text "Cole: Yeah, somehow... But I came real close to not making  it back this time.")
        (set-reg 100 #t)
        (wait)
        (text-reset 1))
       (//
        (text "Cole: I guess I managed to miss you, Steve. I should have   waited for you back here.")
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 101 #f))
   (text "Catherine: Cole, thank god you made it back.")
   (wait)
   (text-reset 1)
   (text "Cole: You and me both.")
   (wait)
   (text-reset 1)
   (text "Catherine: Everyone was having a fit because you didn't comeback.")
   (wait)
   (text-reset 1)
   (text "Cole: The zombies cornered me... And once I ran out of ammo,I was scared shitless.")
   (set-reg 101 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 102 #f))
   (text
    "Catherine: Cole... I'm sorry about before. I guess I got    emotional... I couldn't stop thinking about my mother.")
   (wait)
   (text-reset 1)
   (text "Cole: No, it's alright. I understand exactly how you feel,  Catherine.")
   (wait)
   (text-reset 1)
   (text "Catherine: I can't forgive Daniel, who's sent everyone to   hell with the reanimation serum.")
   (set-reg 102 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5)) (text "Catherine: So what are you planning to do next?") (wait) (text-reset 1))
 (seg (? (= P 6) (= 102 #t) (= 110 #t) (= 111 #t) (= 112 #f))
   (text "Steve: Everyone's got to be exhausted. Let's call it a day  and get some rest.")
   (wait)
   (text-reset 1)
   (text "Cole: What about Doctor Lisle?")
   (wait)
   (text-reset 1)
   (text "Steve: I'm sure he's still here. He said he'd give us a     heads-up if he had to go anywhere.")
   (wait)
   (text-reset 1)
   (text "Cole: Good enough.")
   (set-reg 112 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 102 #t) (= 110 #t) (= 111 #t))
   (text "Steve: Okay, all. Get some rest.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 103 #f))
   (text "Steve: Cole, what did you mean by almost not making it back?")
   (wait)
   (text-reset 1)
   (text "Cole: Well, when I got jumped by zombies on the first floor of the precinct, I ran out of ammo... Amateur move, I know.")
   (wait)
   (text-reset 1)
   (text "Steve: It's on me, I should have stocked you up before you  left.")
   (wait)
   (text-reset 1)
   (text "Cole: No, I should have checked my gun beforehand. It's my  fault.")
   (set-reg 103 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 104 #f))
   (text "Steve: So you managed to escape from the precinct after theyjumped you?")
   (wait)
   (text-reset 1)
   (text "Cole: Not quite. The entrance was blocked, so I had to go upto the second floor.")
   (wait)
   (text-reset 1)
   (text "Steve: To the Investigation Division?")
   (wait)
   (text-reset 1)
   (text "Cole: Yeah. There were three zombies in total. They came up the stairs to get me.")
   (wait)
   (text-reset 1)
   (text "Steve: So you saw how the Investigation Division turned     out... What a mess.")
   (wait)
   (text-reset 1)
   (text "Cole: Yeah, and that's when I started searching for a       weapon. There was a toolbox by the wall that was getting    fixed, right?")
   (wait)
   (text-reset 1)
   (text "Steve: Sure, I remember that.")
   (wait)
   (text-reset 1)
   (text "Cole: I grabbed a screwdriver from it and gouged out one of the zombie's eyes.")
   (set-reg 104 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 105 #f))
   (text "Steve: Good god. How'd that go down?")
   (wait)
   (text-reset 1)
   (text "Cole: The screwdriver managed to pierce its brain, so it    died quick. But he had a friend that showed up.")
   (wait)
   (text-reset 1)
   (text "Steve: Did you manage to brain that one too?")
   (wait)
   (text-reset 1)
   (text "Cole: No, the screwdriver got stuck, so I wound up crushing its eye with my finger.")
   (wait)
   (text-reset 1)
   (text "Steve: Cole, you're a goddamn savage.")
   (wait)
   (text-reset 1)
   (text "Cole: That zombie started screaming and managed to fall out a window.")
   (set-reg 105 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 106 #f))
   (text "Steve: Serves him right. How about the third zombie?")
   (wait)
   (text-reset 1)
   (text
    "Cole: By that time my strength was basically spent.")
   (wait)
   (text-reset 1)
   (text "Steve: Zombies have insane power. It's inexplicable.")
   (wait)
   (text-reset 1)
   (text "Cole: He rushed me and I lost my balance and went onto the  floor. I thought I was done for.")
   (wait)
   (text-reset 1)
   (text "Cole: But then I felt something cold in my right hand.")
   (wait)
   (text-reset 1)
   (text "Steve: Something cold?")
   (wait)
   (text-reset 1)
   (text "Cole: A power saw they were using to tix the wall.")
   (wait)
   (text-reset 1)
   (text "Steve: Oh oh oh.")
   (wait)
   (text-reset 1)
   (text "Cole: I guess you can figure out the rest.")
   (wait)
   (text-reset 1)
   (text "Steve: Even as a jaded cop, I'm gotta admit that you're a   helluva guy, Cole. You got some tough mental chops.")
   (wait)
   (text-reset 1)
   (text
    "Steve: Your experience killing zombies has really stacked   up. In the same situation, I would have been dead.")
   (set-reg 106 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 107 #f))
   (text "Steve: Before I forget, here's some extra ammo for you.")
   (wait)
   (text-reset 1)
   (text "Cole: Appreciated. Hopefully I won't run out of bullets thistime.")
   (set-reg 107 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 108 #f))
   (text "Cole: So what about those documents about Razovan           Pharmaceuticals?")
   (wait)
   (text-reset 1)
   (text
    "Steve: Ah, here they are. And Catherine told me her account of what happened.  Nasty coincidences.")
   (wait)
   (text-reset 1)
   (text "Cole: If we don't settle the score with Daniel, the damage  is going to go global.")
   (wait)
   (text-reset 1)
   (text "Steve: Exactly.")
   (wait)
   (text-reset 1)
   (text "Cole: Catherine, you understand, don't you?")
   (wait)
   (text-reset 1)
   (text "Catherine: I do.")
   (set-reg 108 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 109 #f))
   (text "Cole: Steve, what's the new info on Razovan?")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 0 54 38,W 0,O 0")
   (text
    "Steve: Established 1926. In 1980, 4 kilos of heroin were    seized from their property. And that's just the first       incident.")
   (wait)
   (text-reset 1)
   (text "Steve: The director at the time, Kuran Aresta, was arrested,and Daniel White filled his shoes.")
   (wait)
   (text-reset 1)
   (text
    "Steve: In a recent raid, two more kilos of heroin were      seized, but since Daniel couldn't be located, there's a     warrant out for him.")
   (wait)
   (text-reset 1)
   (text "Cole: His whereabouts are unknown?")
   (wait)
   (text-reset 1)
   (text "Steve: Yeah, and we have no leads.")
   (wait)
   (text-reset 1)
   (text "Cole: What about Catherine's old home?")
   (wait)
   (text-reset 1)
   (text "Steve: According to the paperwork, it's in Montana.")
   (wait)
   (text-reset 1)
   (text "Catherine: That's right. When Daniel married Mom, they movedto Montana.")
   (wait)
   (text-reset 1)
   (text
    "Steve: It looks like the cops are already investigating, buthe's been missing for about a month.")
   (wait)
   (text-reset 1)
   (text "Catherine: What...? I call home once a week, but Mom never  mentioned that...")
   (wait)
   (text-reset 1)
   (text "Cole: I'm sure she didn't want to worry you.")
   (set-reg 109 #t)
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 1 54 38,W 0,O 1")
   (exec-mem 912 "EXIT"))
 (seg (? (= P 6))
   (text
    "Cole: So it turns out that Daniel was behind the director atthe Bayside Institute as well. Steve, all the pieces seem tobe in place.")
   (wait)
   (text-reset 1)
   (text "Steve: I would never have guessed Razovan was the           masterminds behind the original incident, too.")
   (wait)
   (text-reset 1)
   (text "Cole: But unless we find Daniel, we're out of luck, right?")
   (wait)
   (text-reset 1)
   (text "Steve: Yeah. We've got to track him down before the militaryarrives.")
   (set-reg 110 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 111 #f))
   (text "Cole: By the by, I haven't seen Doctor Lisle around.")
   (wait)
   (text-reset 1)
   (text
    "Steve: Mmm, neither have I, since I got back, anyway. There are only two cars in the parking lot, so I doubt he left. ")
   (set-reg 111 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "Steve: He's likely still inside the Institute, then.")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 112 #t))
   (exec-mem 6064 2 1)
   (text "Cole: Let's regroup and talk about this tomorrow.")
   (wait)
   (text-reset 1)
   (text "Steve: Thanks, Cole. Everyone's doing great work here.")
   (wait)
   (text-reset 1)
   (text "Cole: Oh, and Steve, which room are you staying in?")
   (wait)
   (text-reset 1)
   (text "Steve: The room at the front left of the corridor.")
   (wait)
   (text-reset 1)
   (text "Cole: That had been locked beforehand, right?")
   (wait)
   (text-reset 1)
   (text "Steve: Yeah, I got the key from Lisle.")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥056.MES"))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))