(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB081A.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 13 3 20 7)
  (exec-mem 3744 1 6 38 2 44 6)
  (exec-mem 3744 1 7 25 2 34 7)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB043.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB081A.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC")
  (image-mem 1 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC")
  (image-mem 1 0)
  (image-file "B:¥GPC¥DB099C.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 100 #f))
        (text "［スティーブ］コール、無事だったか！？")
        (wait)
        (text-reset 1)
        (text "［コール］ええ、何とか・・・だけど今回だけは、さすがの俺も生　　　　　きた心地はしませんでした。")
        (set-reg 100 #t)
        (wait)
        (text-reset 1))
       (//
        (text "［コール］やはりスティーブさんとすれ違いだったか・・・。もう　　　　　少し研究所で待っていればよかったな。")
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 101 #f))
   (text "［キャサリン］コール、良かった・・・無事だったのね。")
   (wait)
   (text-reset 1)
   (text "［コール］ああ、何とかね。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］コールが遅いので皆で心配してたのよ。")
   (wait)
   (text-reset 1)
   (text "［コール］死霊に襲われててね・・・銃の弾が切れた時には流石の　　　　　俺もビビったけどね。")
   (set-reg 101 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 102 #f))
   (text
    "［キャサリン］コール・・・さっきはごめんね。私、少し感情的に　　　　　　　なってたみたい・・・。自分の母親の事ばかり考え　　　　　　　ていて・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］いや、いいんだよ。キャサリンの気持ちは痛いほど判っ　　　　　てるさ。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］街の人を蘇生薬の研究で苦しめているダニエルを、　　　　　　　許せる筈がないもんね。")
   (set-reg 102 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5)) (text "［キャサリン］それで、これからどうするつもり？") (wait) (text-reset 1))
 (seg (? (= P 6) (= 102 #t) (= 110 #t) (= 111 #t) (= 112 #f))
   (text "［スティーブ］皆、いろいろあって疲れただろう。今日はもう休む　　　　　　　としよう。")
   (wait)
   (text-reset 1)
   (text "［コール］ライルさんは？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］彼は研究所内に居る事は確かだよ。もしここを出る　　　　　　　時には、誰かに伝えておくと言っていたしな。")
   (wait)
   (text-reset 1)
   (text "［コール］そうですか、判りました。")
   (set-reg 112 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 102 #t) (= 110 #t) (= 111 #t))
   (text "［スティーブ］さあ、皆もう休んだ方がいい。")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 103 #f))
   (text "［スティーブ］生きた心地がしないというのは？")
   (wait)
   (text-reset 1)
   (text "［コール］署の１階で死霊に襲われた時、恥ずかしい話ですが弾切　　　　　れになってしまったんです。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］すまない・・・私の責任だ。前もってコールに渡し　　　　　　　ておくんだったな。")
   (wait)
   (text-reset 1)
   (text "［コール］いえ、俺が銃のチェックを行っていなかったんですよ。　　　　　自業自得というやつです。")
   (set-reg 103 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 104 #f))
   (text "［スティーブ］それで、署から脱出したのか・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］いいえ、出入口は奴等に固められていて、俺は２階に上　　　　　がったんです。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］捜査課に？")
   (wait)
   (text-reset 1)
   (text "［コール］はい。死霊は全部で３体いました。奴等は俺を追って、　　　　　ゆっくり階段を登ってきたんです。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］捜査課を見たのか・・凄い荒れようだっただろう。")
   (wait)
   (text-reset 1)
   (text "［コール］ええ、そこで俺は武器になるような物を探して・・・。　　　　　修理中である壁の所に工具箱がありましたよね。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］あの工具箱か・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］そこからドライバーを取って死霊の目に刺したんです。")
   (set-reg 104 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 105 #f))
   (text "［スティーブ］死霊の目にドライバーを？　それで反応は？")
   (wait)
   (text-reset 1)
   (text "［コール］ドライバーは脳に達したらしく、一体目の死霊は倒す事　　　　　ができました。ですが、すぐに２体目の死霊が現れまし　　　　　た。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］そいつもドライバーで？")
   (wait)
   (text-reset 1)
   (text "［コール］いいえ、ドライバーは抜けず、俺は２体目の死霊の片目　　　　　を指で潰しました。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］コールは凄い男だな・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］目を潰された死霊は、悲鳴を上げてそのまま窓を破って　　　　　地面に落ちました。")
   (set-reg 105 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 106 #f))
   (text "［スティーブ］それで最後の３体目の死霊が現れたんだな。")
   (wait)
   (text-reset 1)
   (text
    "［コール］ええ。俺はその時すでに体力の限界でした。奴等に喰わ　　　　　れまいと、必死で抵抗しているうちに体力を消耗してし　　　　　まっていたんです。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］死霊の出す力は並み大抵のパワーじゃないからな。")
   (wait)
   (text-reset 1)
   (text "［コール］死霊のパワーに、俺はバランスを崩して床に倒れてしま　　　　　ったんです。さすがに、もう助からないと思いました。")
   (wait)
   (text-reset 1)
   (text "［コール］ですがその時、右手に冷たいものを感じました。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］冷たいもの？")
   (wait)
   (text-reset 1)
   (text "［コール］ええ、壁の修理に使っていたと思われる電ノコです。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］！！")
   (wait)
   (text-reset 1)
   (text "［コール］・・・後は想像通りです。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］驚いた・・・・永年、刑事をやっている私でさえ、　　　　　　　コールのその精神力と判断力には脱帽するよ。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］死霊に対して戦い慣れしているというか、私がもし　　　　　　　その状況だったとしたら、確実に死を迎えているだ　　　　　　　ろう。")
   (set-reg 106 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 107 #f))
   (text "［スティーブ］忘れないうちに、コールに弾を渡しておこう。")
   (wait)
   (text-reset 1)
   (text "［コール］これで、もう弾切れはないだろう。")
   (set-reg 107 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 108 #f))
   (text "［コール］それで、ラゾバン製薬の資料はどうでした？")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］ああ、取って来たよ。それと、キャサリンの話も聞　　　　　　　かせてもらった。まったく、偶然とは恐ろしいもの　　　　　　　だよ。")
   (wait)
   (text-reset 1)
   (text "［コール］だけど、ここでダニエルと決着をつけないと、被害は世　　　　　界中に広まってしまいますからね。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］その通りだ。")
   (wait)
   (text-reset 1)
   (text "［コール］キャサリン、判っているね。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］・・・ええ。")
   (set-reg 108 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 109 #f))
   (text "［コール］スティーブさん、ラゾバン製薬について詳しく教えて下　　　　　さい。")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 0 54 38,W 0,O 0")
   (text
    "［スティーブ］ラゾバン製薬、１９２６年に設立。１９８０年に約　　　　　　　４キロのヘロインを押収。これが一番最初にラゾバ　　　　　　　ン製薬が犯した事件だ。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］当時の所長、クーラン・アレスタは逮捕され、後に　　　　　　　ダニエル・ホワイトが会社を継いでいる。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］この間のガサ入れでは、約２キロのヘロインが押収　　　　　　　されたが、ダニエルという男の消息が不明なために　　　　　　　指名手配に踏み切ったようだな。")
   (wait)
   (text-reset 1)
   (text "［コール］消息不明！？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ああ、手掛かりは見つかっていない。")
   (wait)
   (text-reset 1)
   (text "［コール］キャサリンの実家には？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］この資料にはモンタナ州と・・・。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］ええ、確かにダニエルと母が結婚した時、モンタナ　　　　　　　に越したわ。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］既に警察は、キャサリンの実家を調べているようだ　　　　　　　な・・・だが、これによるとダニエルは１ヶ月前か　　　　　　　ら消息を断ったままのようだ。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］そんな・・・私、週に一度は家に電話してたけど、　　　　　　　そんな話は一度も・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］・・・きっと、君には心配かけたくなかったんだろう。")
   (set-reg 109 #t)
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 1 54 38,W 0,O 1")
   (exec-mem 912 "EXIT"))
 (seg (? (= P 6))
   (text
    "［コール］ベイサイド研究所の所長を動かしていたのもダニエルの　　　　　仕業だったのか・・・。スティーブさん、これで駒は揃　　　　　いましたね。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］まさかラゾバン製薬の所長が黒幕だったとはな。")
   (wait)
   (text-reset 1)
   (text "［コール］だけど、ダニエルの居場所が掴めない限り、俺達も動け　　　　　ないですね。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］そうだな・・・なんとか軍がこの街に来る前に、見　　　　　　　つけだしたいな。")
   (set-reg 110 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 111 #f))
   (text "［コール］そういえばライルさんの姿がないが・・・。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］そうなんだ、私が帰って来た時からライルの姿は見　　　　　　　えないんだ。研究所の車は２台しか置いていないか　　　　　　　ら、表に出ているとは思えないがね。")
   (set-reg 111 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "［スティーブ］多分、ライルは研究所内のどこかに居るだろうな。")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 112 #t))
   (exec-mem 6064 2 1)
   (text "［コール］じゃあ、明日また考えましょう。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］御苦労だったな。")
   (wait)
   (text-reset 1)
   (text "［コール］あ、それとスティーブさんはどの部屋で休むんですか？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］廊下から見て左手前の部屋だよ。")
   (wait)
   (text-reset 1)
   (text "［コール］あそこの部屋は鍵がかかっていましたね。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ああ、ライルから鍵を預かっているからな。")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥056.MES"))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))