; Dead of the Brain 2 (PC-98) - 055.MES
; Translated by Geometrizer
; Edited by JackDBS, commented by trentsignia
; -----Scene:-----
; Cole has survived his first zombie encounter in two years, and is now back in the lab with a worried Catherine and Steve.
; --Progression:--
; Inspect the lab and talk to everyone, then talk to Steve and MOVE.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB081A.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)			; Hotspots and buttons defined here...
  (exec-mem 3744 1 1 80 0 0 0)							; 	MOVE button
  (exec-mem 3744 1 2 80 0 0 0)							; 	SYSTEM button
  (exec-mem 3744 1 5 13 3 20 7)							; 	Catherine
  (exec-mem 3744 1 6 38 2 44 6)							; 	Steve
  (exec-mem 3744 1 7 25 2 34 7)							; 	Lab
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB043.GPC") (image-mem 0 3)
  (image-file "B:¥GPC¥DB081A.GPC") (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC") (image-mem 1 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC") (image-mem 1 0)
  (image-file "B:¥GPC¥DB099C.GPC") (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 100 #f))								; Lead-in from previous MES script
        (str "Steve: Cole, are you alright!?")
        (wait)
        (text-reset 1)
        (str "Cole: Yeah, somehow... But I came real close to not making" 'br)
        (str "it back this time.")
        (set-reg 100 #t)
        (wait)
        (text-reset 1))
       (//
        (str "Cole: I guess I managed to miss you, Steve. I should have" 'br)	; Lead-in from loading game
        (str "waited for you back here.")
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 101 #f))							; Catherine #1
   (str "Catherine: Cole, thank god you made it back.")
   (wait)
   (text-reset 1)
   (str "Cole: You and me both.")
   (wait)
   (text-reset 1)
   (str "Catherine: Everyone was having a fit because you didn't" 'br)
   (str "come back.")
   (wait)
   (text-reset 1)
   (str "Cole: The zombies cornered me... And once I ran out of" 'br)
   (str "ammo, I was scared shitless.")
   (set-reg 101 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 102 #f))							; Catherine #2
   (str "Catherine: Cole... I'm sorry about before. I guess I got" 'br)
   (str "emotional... I couldn't stop thinking about my mother.")
   (wait)
   (text-reset 1)
   (str "Cole: No, it's alright. I understand exactly how you feel," 'br)
   (str "Catherine.")
   (wait)
   (text-reset 1)
   (str "Catherine: I can't forgive Daniel. He's putting everyone" 'br)
   (str "through hell with the reanimation serum.")
   (set-reg 102 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))								; Catherine #3 (repeat line)
   (str "Catherine: So what are you planning to do next?")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 102 #t) (= 110 #t) (= 111 #t) (= 112 #f))			; Steve (after talking to Catherine and looking at lab) #1
   (str "Steve: Everyone's got to be exhausted. Let's call it a day" 'br)
   (str "and get some rest.")
   (wait)
   (text-reset 1)
   (str "Cole: What about Doctor Lisle?")
   (wait)
   (text-reset 1)
   (str "Steve: I'm sure he's still here. He said he'd give us a" 'br)
   (str "heads-up if he had to go anywhere.")
   (wait)
   (text-reset 1)
   (str "Cole: Good enough.")
   (set-reg 112 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 102 #t) (= 110 #t) (= 111 #t))				; Steve (after talking to Catherine and looking at lab) #2
   (str "Steve: Okay, all. Get some rest.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 103 #f))							; Steve #1
   (str "Steve: Cole, what did you mean by almost not making it back?")
   (wait)
   (text-reset 1)
   (str "Cole: Well, when I got jumped by zombies on the first floor" 'br)
   (str "of the precinct, I ran out of ammo... Amateur move, I know.")
   (wait)
   (text-reset 1)
   (str "Steve: It's on me, I should have stocked you up before I" 'br)
   (str "left.")
   (wait)
   (text-reset 1)
   (str "Cole: No, I should have checked my gun beforehand. It's my" 'br)
   (str "fault.")
   (set-reg 103 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 104 #f))							; Steve #2
   (str "Steve: So you managed to escape from the precinct after" 'br)
   (str "they jumped you?")
   (wait)
   (text-reset 1)
   (str "Cole: Not quite. The entrance was blocked, so I had to go" 'br)
   (str "up to the second floor.")
   (wait)
   (text-reset 1)
   (str "Steve: To the Investigation Division?")
   (wait)
   (text-reset 1)
   (str "Cole: Yeah. There were three zombies in total. They came up" 'br)
   (str "the stairs to get me.")
   (wait)
   (text-reset 1)
   (str "Steve: So you saw how the Investigation Division turned" 'br)
   (str "out... What a mess.")
   (wait)
   (text-reset 1)
   (str "Cole: Yeah, and that's when I started searching for a" 'br)
   (str "weapon. There was a toolbox by the wall that was getting" 'br)
   (str "fixed, right?")
   (wait)
   (text-reset 1)
   (str "Steve: Sure, I remember that.")
   (wait)
   (text-reset 1)
   (str "Cole: I grabbed a screwdriver from it and gouged out one of" 'br)
   (str "the zombie's eyes.")
   (set-reg 104 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 105 #f))							; Steve #3
   (str "Steve: Good god. How'd that go down?")
   (wait)
   (text-reset 1)
   (str "Cole: The screwdriver managed to pierce its brain, so it" 'br)
   (str "died quick. But he had a friend that showed up.")
   (wait)
   (text-reset 1)
   (str "Steve: Did you manage to brain that one too?")
   (wait)
   (text-reset 1)
   (str "Cole: No, the screwdriver got stuck, so I wound up crushing" 'br)
   (str "its eye with my finger.")
   (wait)
   (text-reset 1)
   (str "Steve: Cole, you're a goddamn savage.")
   (wait)
   (text-reset 1)
   (str "Cole: That zombie started screaming and managed to fall out" 'br)
   (str "a window.")
   (set-reg 105 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 106 #f))							; Steve #4
   (str "Steve: Serves him right. How about the third zombie?")
   (wait)
   (text-reset 1)
   (str "Cole: By that time my strength was basically spent.")
   (wait)
   (text-reset 1)
   (str "Steve: Zombies have insane power. It's inexplicable.")
   (wait)
   (text-reset 1)
   (str "Cole: He rushed me and I lost my balance and went onto the" 'br)
   (str "floor. I thought I was done for.")
   (wait)
   (text-reset 1)
   (str "Cole: But then I felt something cold in my right hand.")
   (wait)
   (text-reset 1)
   (str "Steve: Something cold?")
   (wait)
   (text-reset 1)
   (str "Cole: A power saw they were using to fix the wall.")
   (wait)
   (text-reset 1)
   (str "Steve: Oh...!")
   (wait)
   (text-reset 1)
   (str "Cole: I guess you can figure out the rest.")
   (wait)
   (text-reset 1)
   (str "Steve: Even as a jaded cop, I'm gotta admit that you're a" 'br)
   (str "helluva guy, Cole. You got some tough mental chops.")
   (wait)
   (text-reset 1)
   (str "Steve: Your experience killing zombies has really stacked" 'br)
   (str "up. In the same situation, I would have been dead.")
   (set-reg 106 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 107 #f))							; Steve #5
   (str "Steve: Before I forget, here's some extra ammo for you.")
   (wait)
   (text-reset 1)
   (str "Cole: Appreciated. Hopefully I won't run out of bullets" 'br)
   (str "this time.")
   (set-reg 107 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 108 #f))							; Steve #6
   (str "Cole: So what about those documents about Razovan" 'br)
   (str "Pharmaceuticals?")
   (wait)
   (text-reset 1)
   (str "Steve: Ah, here they are. And Catherine told me her account" 'br)
   (str "of what happened. Nasty coincidences.")
   (wait)
   (text-reset 1)
   (str "Cole: If we don't settle the score with Daniel, the damage" 'br)
   (str "is going to go global.")
   (wait)
   (text-reset 1)
   (str "Steve: Exactly.")
   (wait)
   (text-reset 1)
   (str "Cole: Catherine, you understand, don't you?")
   (wait)
   (text-reset 1)
   (str "Catherine: I do.")
   (set-reg 108 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 109 #f))							; Steve #7
   (str "Cole: Steve, what's the new info on Razovan?")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 0 54 38,W 0,O 0")
   (str "Steve: Established 1926. In 1980, 4 kilos of heroin were" 'br)
   (str "seized from their property. And that's just the first" 'br)
   (str "incident.")
   (wait)
   (text-reset 1)
   (str "Steve: The director at the time, Aleste Courant, was" 'br)
   (str "arrested, and Daniel White filled his shoes.")
   (wait)
   (text-reset 1)
   (str "Steve: In a recent raid, two more kilos of heroin were" 'br)
   (str "seized, but since Daniel couldn't be located, there's a" 'br)
   (str "warrant out for him.")
   (wait)
   (text-reset 1)
   (str "Cole: His whereabouts are unknown?")
   (wait)
   (text-reset 1)
   (str "Steve: Yeah, and we have no leads.")
   (wait)
   (text-reset 1)
   (str "Cole: What about Catherine's old home?")
   (wait)
   (text-reset 1)
   (str "Steve: According to the paperwork, it's in Montana.")
   (wait)
   (text-reset 1)
   (str "Catherine: That's right. When Daniel married Mom, they" 'br)
   (str "moved to Montana.")
   (wait)
   (text-reset 1)
   (str "Steve: It looks like the cops are already investigating," 'br)
   (str "but he's been missing for about a month.")
   (wait)
   (text-reset 1)
   (str "Catherine: What...? I call home once a week, but Mom never" 'br)
   (str "mentioned that...")
   (wait)
   (text-reset 1)
   (str "Cole: I'm sure she didn't want to worry you.")
   (set-reg 109 #t)
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 1 54 38,W 0,O 1")
   (exec-mem 912 "EXIT"))
 (seg (? (= P 6))								; Steve #8 (repeat line)
   (str "Cole: So it turns out that Daniel was behind the director" 'br)
   (str "at the Bayside Institute as well. Steve, all the pieces" 'br)
   (str "seem to be in place.")
   (wait)
   (text-reset 1)
   (str "Steve: I would never have guessed Razovan were the" 'br)
   (str "masterminds behind the original incident, too.")
   (wait)
   (text-reset 1)
   (str "Cole: But unless we find Daniel, we're out of luck, right?")
   (wait)
   (text-reset 1)
   (str "Steve: Yeah. We've got to track him down before the" 'br)
   (str "military arrives.")
   (set-reg 110 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 111 #f))							; Lab #1
   (str "Cole: By the by, I haven't seen Doctor Lisle around.")
   (wait)
   (text-reset 1)
   (str "Steve: Mmm, neither have I, since I got back anyway. There" 'br)
   (str "are only two cars in the parking lot, so I doubt he left.")
   (set-reg 111 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))								; Lab #2 (repeat line)
   (str "Steve: He's likely still inside the Institute, then.")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 112 #t))							; MOVE (after talking to Steve)
   (exec-mem 6064 2 1)
   (str "Cole: Let's regroup and talk about this tomorrow.")
   (wait)
   (text-reset 1)
   (str "Steve: Thanks, Cole. Everyone's doing great work here.")
   (wait)
   (text-reset 1)
   (str "Cole: Oh, and Steve, which room are you staying in?")
   (wait)
   (text-reset 1)
   (str "Steve: The room at the front left of the corridor.")
   (wait)
   (text-reset 1)
   (str "Cole: That had been locked beforehand, right?")
   (wait)
   (text-reset 1)
   (str "Steve: Yeah, I got the key from Lisle.")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥056.MES"))
 (seg (? (= P 2))								; SYSTEM
   (exec-mem 6064 2 2)
   (menu1
    25 317  39 317  53 317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))