(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB073.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 30 3 37 7)
  (exec-mem 3744 1 6 50 3 56 14)
  (exec-mem 3744 1 7 4 10 23 15)
  (exec-mem 3744 1 8 15 2 27 9)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB072.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB073.GPC")
  (image-mem 1 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 120 #f))
        (text "［コール］シーラ、まだ起きていたのか？")
        (wait)
        (text-reset 1)
        (text "［シーラ］コールが警察に行ったって聞いて、心配で眠れなかった　　　　　の・・・何かとても嫌な予感がして・・・。")
        (wait)
        (text-reset 1)
        (text "［コール］悪い予感ね・・・確かに警察署では今までに無い戦いを　　　　　したが、だけど、こうして今生きているからね。")
        (wait)
        (text-reset 1)
        (text "［シーラ］うん、安心してる。")
        (set-reg 120 #t)
        (wait)
        (text-reset 1))
       (//
        (text "［コール］まだ起きているか？")
        (wait)
        (text-reset 1)
        (text "［シーラ］コール、寝たんじゃなかったの？")
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 121 #f))
   (text "［コール］そういえば、ライルさんと会ったか？")
   (wait)
   (text-reset 1)
   (text "［シーラ］さっき、廊下で会ったわ。")
   (wait)
   (text-reset 1)
   (text "［コール］そうか・・・それならいいが・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］だけど、何だか落ち着かなくてソワソワしていたみたい　　　　　ね。")
   (wait)
   (text-reset 1)
   (text "［コール］何かあったのかな？")
   (wait)
   (text-reset 1)
   (text "［シーラ］さぁ・・・？　だけど、何かあったら自分で言ってくる　　　　　でしょ？")
   (wait)
   (text-reset 1)
   (text "［コール］まあね。")
   (set-reg 121 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 122 #f))
   (text "［シーラ］シャツに血がついているわよ。")
   (wait)
   (text-reset 1)
   (text "［コール］ああ、きっとこれは警察署で死霊を相手にした時の返り　　　　　血だよ。俺は傷一つつけられていないからさ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］感染するんでしょ？")
   (wait)
   (text-reset 1)
   (text "［コール］死霊の血が混ざったら終わりだな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］コール、無茶はしないでね。")
   (wait)
   (text-reset 1)
   (text "［コール］ああ、分かっているさ。")
   (set-reg 122 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 123 #f))
   (text "［シーラ］キャサリンの事なんだけど・・・。彼女、義父のダニエ　　　　　ルの事で相当なショックを受けているみたいなの。")
   (wait)
   (text-reset 1)
   (text "［コール］ああ、そうらしいな。だけど、彼女だって何が悪いかぐ　　　　　らいは自分で判断できるだろ。")
   (wait)
   (text-reset 1)
   (text "［コール］厳しい言い方かもしれないけど、俺はこのまま世界中の　　　　　人間が死霊によって殺される事だけは避けたいからな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］うん。")
   (wait)
   (text-reset 1)
   (text "［コール］キャサリンに対しては、俺もあまりダニエルについての　　　　　話は避けるようにするよ。")
   (set-reg 123 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 124 #f))
   (text "［コール］シーラ、考えてみれば街があんな事になってしまったの　　　　　は俺の責任なんだよ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］どうして？")
   (wait)
   (text-reset 1)
   (text
    "［コール］２年前、グールの他にも蘇生薬を知っている人間、そう　　　　　ダニエルに気付いていれば、多分それなりに処置できた　　　　　と思うんだ。")
   (wait)
   (text-reset 1)
   (text "［コール］それに気付かなかったばっかりに、また２年前のくり返　　　　　しを冒してしまった・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］ううん、悪いのはクーガーさんの薬を使って罪を犯して　　　　　いるダニエルっていう人よ。コールの責任じゃないわ。")
   (wait)
   (text-reset 1)
   (text "［コール］・・・・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］コール、あんまり自分を責めないで。")
   (set-reg 124 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "［シーラ］疲れているみたいね・・・今日はもう休んだら？")
   (wait)
   (text-reset 1)
   (text "［コール］そうだな・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］あんまり自分を責めないでね。")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 125 #f))
   (text "［コール］ここはシャワーか・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］あっ、開けちゃだめっ！")
   (wait)
   (text-reset 1)
   (text "［コール］ん？　シーラ、どうした？")
   (wait)
   (text-reset 1)
   (text "［シーラ］う、ううん。私、さっきシャワー浴びたの。それで下着　　　　　を洗濯したから・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］あ、ごめんな。")
   (set-reg 125 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 126 #f))
   (text "［コール］シャワーを浴びてどうだった？")
   (wait)
   (text-reset 1)
   (text "［シーラ］どうって？")
   (wait)
   (text-reset 1)
   (text "［コール］シャワーを浴びた感じさ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］気持ち良かったわ。お湯もすぐ出たしね。")
   (wait)
   (text-reset 1)
   (text "［コール］お前なぁ、うちのシャワーがなかなかお湯が出ないから　　　　　って馬鹿にしてんの？")
   (wait)
   (text-reset 1)
   (text "［シーラ］ふふふ、そんな事ないわよ。")
   (set-reg 126 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "［シーラ］コールも浴びていく？")
   (wait)
   (text-reset 1)
   (text "［コール］いや、遠慮しておくよ。")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 127 #f))
   (text "［コール］大きなベッドだな。俺が寝たら足が出ちゃうだろうな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］コールの部屋のベッドは小さいの？")
   (wait)
   (text-reset 1)
   (text "［コール］ベッドのすぐ脇に邪魔な机があるんだよ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］コールは寝相が悪いからね、気をつけなさい。")
   (wait)
   (text-reset 1)
   (text "［コール］はいはい。")
   (set-reg 127 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "［シーラ］コールが帰ってきたら寝ようと思っていたの。")
   (wait)
   (text-reset 1)
   (text "［コール］待ってなくてもいいのに・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］心配で目が冴えちゃうのよ。")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 128 #f))
   (text "［コール］ここから死霊がいきなり飛び出して来たら怖いな。")
   (wait)
   (text-reset 1)
   (text
    "［シーラ］コールって意地悪ね・・・すぐそうやって脅かすんだか　　　　　ら・・・。でも、もしそうなったら助けに来てくれるん　　　　　でしょ？")
   (wait)
   (text-reset 1)
   (text "［コール］熟睡してなかったらな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］意地悪ね。")
   (set-reg 128 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))
   (text "［コール］まあ、この高さだったらさすがの死霊も登っては来れな　　　　　いな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］そうね。")
   (wait)
   (text-reset 1))
 (seg (? (= P 1))
   (exec-mem 6064 2 1)
   (text "［コール］じゃ、行くよ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］うん、おやすみなさい。")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥056.MES"))
 (seg (? (= P 2))
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))