(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB073.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 30 3 37 7)
  (exec-mem 3744 1 6 50 3 56 14)
  (exec-mem 3744 1 7 4 10 23 15)
  (exec-mem 3744 1 8 15 2 27 9)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB072.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB073.GPC")
  (image-mem 1 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 120 #f))
        (text "Cole: Sheila, you still awake?")
        (wait)
        (text-reset 1)
        (text "Sheila: I heard you went to the police station, and I was so" 'br)
(text "worried I couldn't sleep... I had a bad feeling about" 'br)
(text "things...")
        (wait)
        (text-reset 1)
        (text "Cole: Well, you weren't wrong. That was one of the gnarliest" 'br)
(text "situations I've been in, but I made it through.")
        (wait)
        (text-reset 1)
        (text "Sheila: Yeah, I'm relieved.")
        (set-reg 120 #t)
        (wait)
        (text-reset 1))
       (//
        (text "Cole: So you're still up?")
        (wait)
        (text-reset 1)
        (text "Sheila: Cole, weren't you sleeping before?")
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 121 #f))
   (text "Cole: Oh, did you run into Doctor Lisle?")
   (wait)
   (text-reset 1)
   (text "Sheila: I met him just now in the hallway.")
   (wait)
   (text-reset 1)
   (text "Cole: Oh, that's good, then.")
   (wait)
   (text-reset 1)
   (text "Sheila: You seem kind of uneasy.")
   (wait)
   (text-reset 1)
   (text "Cole: Did something happen?")
   (wait)
   (text-reset 1)
   (text "Sheila: I don't know. But if anything did happen, you'd tell" 'br)
(text "me yourself, right?")
   (wait)
   (text-reset 1)
   (text "Cole: I suppose so.")
   (set-reg 121 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 122 #f))
   (text "Sheila: Oh, there's blood on your shirt...")
   (wait)
   (text-reset 1)
   (text "Cole: Oh, that's just the splatter from when I was dealing" 'br)
(text "with the zombies at the precinct. I didn't get a scratch on" 'br)
(text "me.")
   (wait)
   (text-reset 1)
   (text "Sheila: But won't you get infected from the blood?")
   (wait)
   (text-reset 1)
   (text "Cole: If any zombie blood mixes with mine, I'm basically" 'br)
(text "done for.")
   (wait)
   (text-reset 1)
   (text "Sheila: Don't do anything reckless, Cole.")
   (wait)
   (text-reset 1)
   (text "Cole: I know, I know.")
   (set-reg 122 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 123 #f))
   (text "Sheila: About Catherine... It really seems like she's been" 'br)
(text "thrown for a loop about her stepfather Daniel.")
   (wait)
   (text-reset 1)
   (text "Cole: It's understandable. But she should be able to decide" 'br)
(text "for herself what's right or wrong.")
   (wait)
   (text-reset 1)
   (text "Cole: I don't wanna sound too harsh, but we really need to" 'br)
(text "avoid a scenario where zombies wind up murdering everyone on" 'br)
(text "the planet.")
   (wait)
   (text-reset 1)
   (text "Sheila: Yeah.")
   (wait)
   (text-reset 1)
   (text "Cole: I'll try to avoid bringing up Daniel when I'm around" 'br)
(text "Catherine.")
   (set-reg 123 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 124 #f))
   (text "Cole: Sheila, when you really think about it... It's my" 'br)
(text "fault the town ended up this way.")
   (wait)
   (text-reset 1)
   (text "Sheila: Why?")
   (wait)
   (text-reset 1)
   (text
    "Cole: Two years ago, if anyone...well, aside from" 'br)
"Ghoul...had noticed Daniel knew about the reanimation serum," 'br)
"things could have wound up different.")
   (wait)
   (text-reset 1)
   (text "Cole: And by not making that connection, he made the same" 'br)
(text "mistakes from two years ago...")
   (wait)
   (text-reset 1)
   (text "Sheila: That's where you're wrong. Daniel is wholly the one" 'br)
(text "to blame. He's doing evil with Dr. Cooger's serum. It isn't" 'br)
(text "your fault.")
   (wait)
   (text-reset 1)
   (text "Cole: ...")
   (wait)
   (text-reset 1)
   (text "Sheila: Cole, don't be so hard on yourself.")
   (set-reg 124 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "Sheila: You look exhausted, anyway. Why don't you get some" 'br)
(text "rest tonight?")
   (wait)
   (text-reset 1)
   (text "Cole: You're right, I should.")
   (wait)
   (text-reset 1)
   (text "Sheila: Seriously. You're too hard on yourself.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 125 #f))
   (text "Cole: Here's the shower...")
   (wait)
   (text-reset 1)
   (text "Sheila: Ah, don't open it!")
   (wait)
   (text-reset 1)
   (text "Cole: Huh? Why not?")
   (wait)
   (text-reset 1)
   (text "Sheila: It... It's nothing. I just took a shower a little" 'br)
(text "while ago, and then hung up my underwear to dry.")
   (wait)
   (text-reset 1)
   (text "Cole: Ah, sorry.")
   (set-reg 125 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 126 #f))
   (text "Cole: So how was your shower?")
   (wait)
   (text-reset 1)
   (text "Sheila: What do you mean?")
   (wait)
   (text-reset 1)
   (text "Cole: Did you feel better after taking one?")
   (wait)
   (text-reset 1)
   (text "Sheila: Mm, it was nice. Good water pressure, too. And hot.")
   (wait)
   (text-reset 1)
   (text "Cole: Are you dogging on my shower that takes forever to" 'br)
(text "heat up?")
   (wait)
   (text-reset 1)
   (text "Sheila: Hee! It's not like that.")
   (set-reg 126 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "Sheila: Will you join me for a shower, Cole?")
   (wait)
   (text-reset 1)
   (text "Cole: Nah, I'll pass.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 127 #f))
   (text "Cole: That's a big bed. But if I slept on it, my legs would" 'br)
(text "stick out.")
   (wait)
   (text-reset 1)
   (text "Sheila: Is the bed in your room small, Cole?")
   (wait)
   (text-reset 1)
   (text "Cole: There's that annoying desk right next to it.")
   (wait)
   (text-reset 1)
   (text "Sheila: You always toss and turn in your sleep, Cole. Be" 'br)
(text "careful.")
   (wait)
   (text-reset 1)
   (text "Cole: Yeah, yeah.")
   (set-reg 127 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "Sheila: I was going to sleep once you got back.")
   (wait)
   (text-reset 1)
   (text "Cole: You didn't have to wait for me...")
   (wait)
   (text-reset 1)
   (text "Sheila: I was so worried that I couldn't sleep.")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 128 #f))
   (text "Cole: It would be scary as hell if a zombie jumped out of" 'br)
(text "here.")
   (wait)
   (text-reset 1)
   (text
    "Sheila: Don't you try to scare me like that, Cole. But if" 'br)
"that happened, you'd save me, right?")
   (wait)
   (text-reset 1)
   (text "Cole: Not if I slept through it.")
   (wait)
   (text-reset 1)
   (text "Sheila: You're so mean!")
   (set-reg 128 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))
   (text "Cole: Well, at this height, it's not like a zombie could" 'br)
(text "climb up here.")
   (wait)
   (text-reset 1)
   (text "Sheila: That's true.")
   (wait)
   (text-reset 1))
 (seg (? (= P 1))
   (exec-mem 6064 2 1)
   (text "Cole: Okay, I'm off.")
   (wait)
   (text-reset 1)
   (text "Sheila: All right. Good night.")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥056.MES"))
 (seg (? (= P 2))
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))