; Dead of the Brain 2 (PC-98) - 058.MES
; Translated by Geometrizer
; Edited by JackDBS, commented by trentsignia
; -----Scene:-----
; Cole visits Sheila after his 32nd Precinct excursion. She's concerned.
; --Progression:--
; Talk to Sheila, and look at the shower.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB073.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)			; Hotspots and buttons defined here...
  (exec-mem 3744 1 1 80 0 0 0)							; 	MOVE button
  (exec-mem 3744 1 2 80 0 0 0)							; 	SYSTEM button
  (exec-mem 3744 1 5 30 3 37 7)							; 	Sheila
  (exec-mem 3744 1 6 50 3 56 14)						; 	Shower
  (exec-mem 3744 1 7 4 10 23 15)						; 	Bed
  (exec-mem 3744 1 8 15 2 27 9)							; 	Curtains
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB072.GPC") (image-mem 1 3)
  (image-file "B:¥GPC¥DB073.GPC") (image-mem 1 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 120 #f))								; Lead-in for first visit
        (str "Cole: Sheila, you still awake?")
        (wait)
        (text-reset 1)
        (str "Sheila: I heard you went to the police station, and I was" 'br)
        (str "so worried I couldn't sleep... I had a bad feeling about" 'br)
        (str "things...")
        (wait)
        (text-reset 1)
        (str "Cole: Well, you weren't wrong. That was one of the" 'br)
        (str "gnarliest situations I've been in, but I made it through.")
        (wait)
        (text-reset 1)
        (str "Sheila: Yeah, I'm relieved.")
        (set-reg 120 #t)
        (wait)
        (text-reset 1))
       (//
        (str "Cole: So you're still up?")					; Lead-in from second visit onwards
        (wait)
        (text-reset 1)
        (str "Sheila: Cole, weren't you sleeping before?")
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 121 #f))							; Sheila #1
   (str "Cole: Oh, did you run into Doctor Lisle?")
   (wait)
   (text-reset 1)
   (str "Sheila: I met him just now in the hallway.")
   (wait)
   (text-reset 1)
   (str "Cole: Oh, that's good, then.")
   (wait)
   (text-reset 1)
   (str "Sheila: You seem kind of uneasy.")
   (wait)
   (text-reset 1)
   (str "Cole: Did something happen?")
   (wait)
   (text-reset 1)
   (str "Sheila: I don't know. But if anything did happen, you'd" 'br)
   (str "tell me yourself, right?")
   (wait)
   (text-reset 1)
   (str "Cole: I suppose so.")
   (set-reg 121 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 122 #f))							; Sheila #2
   (str "Sheila: Oh, there's blood on your shirt...")
   (wait)
   (text-reset 1)
   (str "Cole: Oh, that's just the splatter from when I was dealing" 'br)
   (str "with the zombies at the precinct. I didn't get a scratch on" 'br)
   (str "me.")
   (wait)
   (text-reset 1)
   (str "Sheila: But won't you get infected from the blood?")
   (wait)
   (text-reset 1)
   (str "Cole: If any zombie blood mixes with mine, I'm basically" 'br)
   (str "done for.")
   (wait)
   (text-reset 1)
   (str "Sheila: Don't do anything reckless, Cole.")
   (wait)
   (text-reset 1)
   (str "Cole: I know, I know.")
   (set-reg 122 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 123 #f))							; Sheila #3
   (str "Sheila: About Catherine... It really seems like she's been" 'br)
   (str "thrown for a loop about her stepfather Daniel.")
   (wait)
   (text-reset 1)
   (str "Cole: It's understandable. But she should be able to decide" 'br)
   (str "for herself what's right or wrong.")
   (wait)
   (text-reset 1)
   (str "Cole: I don't wanna sound too harsh, but we really need to" 'br)
   (str "avoid a scenario where zombies wind up murdering everyone" 'br)
   (str "on the planet.")
   (wait)
   (text-reset 1)
   (str "Sheila: Yeah.")
   (wait)
   (text-reset 1)
   (str "Cole: I'll try to avoid bringing up Daniel when I'm around" 'br)
   (str "Catherine.")
   (set-reg 123 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 124 #f))							; Sheila #4
   (str "Cole: Sheila, when you really think about it... It's my" 'br)
   (str "fault the town ended up this way.")
   (wait)
   (text-reset 1)
   (str "Sheila: Why?")
   (wait)
   (text-reset 1)
   (str "Cole: Two years ago, if anyone...well, aside from" 'br)
   (str "Ghoul...had noticed Daniel knew about the reanimation" 'br)
   (str "serum, things could have wound up different.")
   (wait)
   (text-reset 1)
   (str "Cole: And by not making that connection, he made the same" 'br)
   (str "mistakes from two years ago...")
   (wait)
   (text-reset 1)
   (str "Sheila: That's where you're wrong. Daniel is wholly the one" 'br)
   (str "to blame. He's doing evil with Dr. Cooger's serum. It isn't" 'br)
   (str "your fault.")
   (wait)
   (text-reset 1)
   (str "Cole: ...")
   (wait)
   (text-reset 1)
   (str "Sheila: Cole, don't be so hard on yourself.")
   (set-reg 124 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))								; Sheila #5 (repeat line)
   (str "Sheila: You look exhausted, anyway. Why don't you get some" 'br)
   (str "rest tonight?")
   (wait)
   (text-reset 1)
   (str "Cole: You're right, I should.")
   (wait)
   (text-reset 1)
   (str "Sheila: Seriously. You're too hard on yourself.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 125 #f))							; Shower #1
   (str "Cole: Here's the shower...")
   (wait)
   (text-reset 1)
   (str "Sheila: Ah, don't open it!")
   (wait)
   (text-reset 1)
   (str "Cole: Huh? Why not?")
   (wait)
   (text-reset 1)
   (str "Sheila: It... It's nothing. I just took a shower a little" 'br)
   (str "while ago, and then hung up my underwear to dry.")
   (wait)
   (text-reset 1)
   (str "Cole: Ah, sorry.")
   (set-reg 125 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 126 #f))							; Shower #2
   (str "Cole: So how was your shower?")
   (wait)
   (text-reset 1)
   (str "Sheila: What do you mean?")
   (wait)
   (text-reset 1)
   (str "Cole: Did you feel better after taking one?")
   (wait)
   (text-reset 1)
   (str "Sheila: Mm, it was nice. Good water pressure, too. And hot.")
   (wait)
   (text-reset 1)
   (str "Cole: Are you dogging on my shower that takes forever to" 'br)
   (str "heat up?")
   (wait)
   (text-reset 1)
   (str "Sheila: Hee! It's not like that.")
   (set-reg 126 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))								; Shower #3 (repeat line)
   (str "Sheila: Will you join me for a shower, Cole?")
   (wait)
   (text-reset 1)
   (str "Cole: Nah, I'll pass.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 127 #f))							; Bed #1
   (str "Cole: That's a big bed. But if I slept on it, my legs would" 'br)
   (str "stick out.")
   (wait)
   (text-reset 1)
   (str "Sheila: Is the bed in your room small, Cole?")
   (wait)
   (text-reset 1)
   (str "Cole: There's that annoying desk right next to it.")
   (wait)
   (text-reset 1)
   (str "Sheila: You always toss and turn in your sleep, Cole. Be" 'br)
   (str "careful.")
   (wait)
   (text-reset 1)
   (str "Cole: Yeah, yeah.")
   (set-reg 127 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))								; Bed #2 (repeat line)
   (str "Sheila: I was going to sleep once you got back.")
   (wait)
   (text-reset 1)
   (str "Cole: You didn't have to wait for me...")
   (wait)
   (text-reset 1)
   (str "Sheila: I was so worried that I couldn't sleep.")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 128 #f))							; Curtains #1
   (str "Cole: It would be scary as hell if a zombie jumped out of" 'br)
   (str "here.")
   (wait)
   (text-reset 1)
   (str "Sheila: Don't you try to scare me like that, Cole. But if" 'br)
   (str "that happened, you'd save me, right?")
   (wait)
   (text-reset 1)
   (str "Cole: Not if I slept through it.")
   (wait)
   (text-reset 1)
   (str "Sheila: You're so mean!")
   (set-reg 128 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))								; Curtains #2 (repeat line)
   (str "Cole: Well, at this height, it's not like a zombie could" 'br)
   (str "climb up here.")
   (wait)
   (text-reset 1)
   (str "Sheila: That's true.")
   (wait)
   (text-reset 1))
 (seg (? (= P 1))								; MOVE
   (exec-mem 6064 2 1)
   (str "Cole: Okay, I'm off.")
   (wait)
   (text-reset 1)
   (str "Sheila: All right. Good night.")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥056.MES"))
 (seg (? (= P 2))								; SYSTEM
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25 317  39 317  53 317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))