; Dead of the Brain 2 (PC-98) - 059.MES
; Translated by Geometrizer
; Edited by JackDBS, commented by trentsignia
; -----Scene:-----
; Cole visits Catherine in her room after his trip to the police station.
; --Progression:--
; Talk to Catherine, and look at the calendar.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB108A.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)			; Hotspots and buttons defined here...
  (exec-mem 3744 1 1 80 0 0 0)							; 	MOVE button
  (exec-mem 3744 1 2 80 0 0 0)							; 	SYSTEM button
  (exec-mem 3744 1 5 7 10 25 14)						; 	Bed
  (exec-mem 3744 1 6 17 2 24 9)							; 	Window
  (exec-mem 3744 1 7 51 4 54 7)							; 	Calendar
  (exec-mem 3744 1 8 27 3 36 7)							; 	Catherine
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB108.GPC") (image-mem 0 3)
  (image-file "B:¥GPC¥DB103.GPC") (image-mem 1 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 129 #f))								; Lead-in for first visit
        (str "Catherine: Cole, what's wrong?")
        (wait)
        (text-reset 1)
        (str "Cole: Nothing, I just wanted to talk a bit.")
        (set-reg 129 #t)
        (wait)
        (text-reset 1))
       (//
        (str "Catherine: Are you having problems sleeping?")			; Lead-in from second visit onwards
        (wait)
        (text-reset 1)
        (str "Cole: Naw, just bored.")
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 8) (= 130 #f))							; Catherine #1
   (str "Catherine: Cole, tell me...")
   (wait)
   (text-reset 1)
   (str "Cole: Tell you what?")
   (wait)
   (text-reset 1)
   (str "Catherine: About what happened at the police station" 'br)
   (str "earlier... How were you able to hold it together?")
   (wait)
   (text-reset 1)
   (str "Cole: Well, I'm not sure I'd call it that. When those" 'br)
   (str "zombies popped out at the station, I nearly shit myself.")
   (wait)
   (text-reset 1)
   (str "Catherine: Well, you're quick-thinking at least, right?")
   (wait)
   (text-reset 1)
   (str "Cole: Quick-thinking? Never thought of myself that way.")
   (set-reg 130 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 131 #f))							; Catherine #2
   (str "Catherine: I've always wondered, why do you call them" 'br)
   (str "zombies and not undead?")
   (wait)
   (text-reset 1)
   (str "Cole: Hmm... Well, in movies, they're usually called" 'br)
   (str "zombies, aren't they?")
   (wait)
   (text-reset 1)
   (str "Cole: But originally, that term was used by people of the" 'br)
   (str "West Indies for the dead who they revived because they" 'br)
   (str "desperately needed workers.")
   (wait)
   (text-reset 1)
   (str "Catherine: They brought back the dead...and made them work?")
   (wait)
   (text-reset 1)
   (str "Cole: Exactly. Dead men don't complain. And they don't even" 'br)
   (str "need to eat.")
   (wait)
   (text-reset 1)
   (str "Catherine: I didn't know that. But the zombies here are" 'br)
   (str "completely different.")
   (wait)
   (text-reset 1)
   (str "Cole: They sure are. They don't work for us... We're their" 'br)
   (str "dinner.")
   (set-reg 131 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 132 #f))							; Catherine #3
   (str "Catherine: So I guess the undead eat...brains.")
   (wait)
   (text-reset 1)
   (str "Cole: Yeah. Apparently, the key to the reanimation serum is" 'br)
   (str "all in the human brain.")
   (wait)
   (text-reset 1)
   (str "Catherine: I wonder what makes them want to eat brains." 'br)
   (str "What happens once they eat them?")
   (wait)
   (text-reset 1)
   (str "Cole: I dunno. Even if they eat them, they just get" 'br)
   (str "digested in their stomach...right?")
   (wait)
   (text-reset 1)
   (str "Catherine: I guess you wouldn't understand unless you" 'br)
   (str "become one yourself.")
   (wait)
   (text-reset 1)
   (str "Cole: Ew, don't say stuff like that.")
   (set-reg 132 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))								; Catherine #4 (repeat line)
   (str "Catherine: I feel lucky to have someone like you nearby," 'br)
   (str "Cole.")
   (wait)
   (text-reset 1)
   (str "Cole: Why's that now?")
   (wait)
   (text-reset 1)
   (str "Catherine: Because nobody is better than you at fighting" 'br)
   (str "the undead, and if it weren't for you, I'd be sloshing" 'br)
   (str "around in some zombie's stomach.")
   (wait)
   (text-reset 1)
   (str "Cole: I'm not sure if I'm proud of that skillset of mine..." 'br)
   (str "I have mixed feelings.")
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 133 #f))							; Bed #1
   (str "Cole: This bed looks really comfortable.")
   (wait)
   (text-reset 1)
   (str "Catherine: But nobody's used it for a while, so it smells a" 'br)
   (str "little musty.")
   (set-reg 133 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))								; Bed #2 (repeat line)
   (str "Catherine: I'll wash the sheets tomorrow.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 134 #f))							; Window #1
   (str "Cole: Aren't you going to close the curtains?")
   (wait)
   (text-reset 1)
   (str "Catherine: It's feeling warm and stuffy, so I'll leave them" 'br)
   (str "as-is.")
   (set-reg 134 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))								; Window #2 (repeat line)
   (str "Cole: There are clouds in the sky tonight.")
   (wait)
   (text-reset 1)
   (str "Catherine: I wonder if it's going to rain... The weather's" 'br)
   (str "been unpleasant lately.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 135 #f))							; Calendar #1
   (str "Catherine: I was really looking forward to Christmastime in" 'br)
   (str "town...")
   (wait)
   (text-reset 1)
   (str "Cole: So was I. But how about this... Let's have a big" 'br)
   (str "Christmas party with everyone this year... Just somewhere" 'br)
   (str "else.")
   (wait)
   (text-reset 1)
   (str "Catherine: Really? You'd invite me?")
   (wait)
   (text-reset 1)
   (str "Cole: You'd be first on the list.")
   (wait)
   (text-reset 1)
   (str "Catherine: Awesome! I'll mark the date.")
   (set-reg 135 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))								; Calendar #2 (repeat line)
   (str "Cole: The year will be over soon.")
   (wait)
   (text-reset 1)
   (str "Catherine: Yes... And good riddance to it.")
   (wait)
   (text-reset 1))
 (seg (? (= P 1))								; MOVE
   (exec-mem 6064 2 1)
   (str "Cole: Well then, I'll take my leave.")
   (wait)
   (text-reset 1)
   (str "Catherine: See you, Cole.")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥056.MES"))
 (seg (? (= P 2))								; SYSTEM
   (exec-mem 6064 2 2)
   (menu1
    25 317  39 317  53 317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))