(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_10.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_10.USO"))))
  (sound '|| 1)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB104.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "［コール］少し寒いかな・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］ううん、平気。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］コール、ダニエルの話だけど・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］ん？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］私は、ダニエルが嫌で家を飛び出したのは知ってる　　　　　　　よね？")
  (wait)
  (text-reset 1)
  (text "［コール］ああ、そう言ってたな。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］だけど最近になって、私は彼を許してあげようと思　　　　　　　っていたの・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text
   "［キャサリン］私の母はね、彼を心の底から愛しているの・・。私　　　　　　　から見れば、どんなに最低な男でも母はその人を心　　　　　　　から信じているのよ。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］母が彼を愛している以上、私もダニエルを愛してあ　　　　　　　げないといけないって思い始めたのよ・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］だけど君は彼に乱暴されたんだろ？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］ええ、されたわ。母を愛している筈なのにって、私　　　　　　　は彼を許せなかった・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］だけど、それ以来ダニエルは私に近寄って来なかっ　　　　　　　たわ。")
  (wait)
  (text-reset 1)
  (text "［コール］そりゃそうだろ。そんな事をした後に、君に易々と声を　　　　　かけるなんて事は普通できないよ。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］そう、彼はその事を凄く悔やんでた・・・彼は反省　　　　　　　してたの・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］ちょっと待てよ、君は乱暴されたんだぜ？　それに、ダ　　　　　ニエルという男はこの事件の黒幕でもあるんだぜ？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］わかってる・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］そんな奴に同情するなんて・・・。")
  (wait)
  (text-reset 1)
  (text
   "［キャサリン］私は、ダニエルが私にした事を許してあげようと思　　　　　　　っているの。この事件を引き起こした事は、例え私　　　　　　　が許しても皆は許さないでしょう。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］勿論、私だってこの事件でたくさんの人の命を奪っ　　　　　　　たダニエルは許せないわ。")
  (wait)
  (text-reset 1)
  (text "［コール］君は優しすぎるよ・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］コールだったらどう・・・？")
  (wait)
  (text-reset 1)
  (text
   "［コール］君には悪いが、俺はそんな奴がいたら絶対に許せない。　　　　　君の立場だったら、一度家を飛び出したら二度と戻らな　　　　　いだろうな。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］相手がいくら反省してても？")
  (wait)
  (text-reset 1)
  (text "［コール］ああ。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］・・・それじゃあ可哀想だわ。")
  (wait)
  (text-reset 1)
  (text "［コール］可哀想かもしれない・・・だけど、俺は２年前の事件で　　　　　人を信じる事ができなくなったんだ・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］隣街の事件？")
  (wait)
  (text-reset 1)
  (text "［コール］ああ・・・。死霊退治のリーダー「グール」を信じたお　　　　　陰で、俺は大切な仲間を全て失ったんだ・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］コール・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］悪い・・・こんな話を君にするなんて・・・。どうかし　　　　　てたよ・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］ううん・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］コール・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］うん？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］ダニエルはきっとラゾバン製薬に居ると思うわ。" 'br)
  (text "［コール］！？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］私を連れだそうとシャッフル・フードに来たブラッ　　　　　　　ディフォックスは二人居たわ。")
  (wait)
  (text-reset 1)
  (text "［コール］ああ、そういえばブラッディフォックスの死体は２体あ　　　　　ったな。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］嫌がっている私を見たもう一人の男が言ってたの。　　　　　　　『めんどくせえからラゾに連れて行こうぜ』って。")
  (wait)
  (text-reset 1)
  (text "［コール］な、何故それを研究室で言わなかったんだ？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］だって・・・コール達はダニエルを殺そうとしてい　　　　　　　るんでしょ？")
  (wait)
  (text-reset 1)
  (text "［コール］・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］ダニエルが死んでしまったら、母が可哀想だと思っ　　　　　　　ていたから・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］でも、もう平気・・・。ダニエルが生きている以上　　　　　　　死霊が増え続けると判っているから・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］なんだか、話したらすっきりしたわ。")
  (wait)
  (text-reset 1)
  (text "［コール］キャサリン・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］それより、コール。")
  (wait)
  (text-reset 1)
  (text "［コール］何だ？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］最近、シーラとはうまくいってるの？")
  (wait)
  (text-reset 1)
  (text "［コール］うまくいってるとも言えないし・・・普通じゃないか？　　　　　でもどうしてそんな事を聞くんだ？")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB105.GPC")
  (image-mem 0 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC")
  (image-mem 1 0)
  (image-file "B:¥GPC¥DB107C.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "［コール］な、なんだよ急に・・・おやすみの挨拶か？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］ご想像にお任せするわ・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］シーラに悪い・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］お願い・・・今だけでいいから・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］ちょっと待って・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］コール、逃げるの？")
  (wait)
  (text-reset 1)
  (text "［コール］いや、そうじゃない。車の音が聞こえたんだ・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］え？")
  (wait)
  (text-reset 1)
  (text "［コール］ほら、聞こえる。研究所の入口だ・・・。")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 0 54 38,W 0,O 0")
  (text "［キャサリン］誰？")
  (wait)
  (text-reset 1)
  (text "［コール］スティーブさんだ・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］スティ・・・" 'br)
  (wait)
  (text-reset 1)
  (text "［コール］シッ！")
  (wait)
  (text-reset 1)
  (text "［コール］さっきスティーブさんの部屋に行ったとき、彼は疲れて　　　　　いて部屋に入れてくれなかったのに・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］こんな時間にどこへ行くのかしら？")
  (wait)
  (text-reset 1)
  (text "［コール］判らない・・・何か大きな荷物を運んでいるようだが。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］あっ、行ってしまうわ。")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 1 54 38,W 0,O 1")
  (exec-mem 912 "EXIT")
  (text "［キャサリン］どこに行くのかしら？")
  (wait)
  (text-reset 1)
  (text "［コール］まあ、起きたら直接スティーブさんに聞いてみればいい　　　　　よ・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］そんな事より、コール・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text
   "［キャサリン］お願い・・・抱いて・・・。私、一人でいるのがと　　　　　　　ても怖いの。今だけ・・・お願い・・・、今だけで　　　　　　　いいから・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text "［キャサリン］コール、返事をして・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］俺なんかでいいのか？")
  (wait)
  (text-reset 1)
  (text "［キャサリン］お願い・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］さあ、何て答えよう・・・。")
  (menu1 25 337 45 337 (</> (/ (text "判ったよ・・・・。")) (/ (text "やめとくよ・・・。"))))
  (text-reset 1)
  (branch-var
   S
   (</>
    (/
     (text "［コール］判ったよ・・・俺が君の心の中にある恐怖を全て消して　　　　　やるよ・・・。")
     (wait)
     (text-reset 1)
     (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
     (image-file "B:¥GPC¥DB106.GPC")
     (image-mem 0 3)
     (exec-mem 15456 0)
     (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
     (text "［キャサリン］あっ・・・コールぅ！！")
     (wait)
     (text-reset 1)
     (exec-mem 14544 2 10)
     (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
     (text "俺は部屋に戻り、ベッドの中でこれでよかったのだと、自分に言い聞かせていた・・・。")
     (wait)
     (text-reset 1)
     (sound '|| 2)
     ((cmd 204) 100 899)
     (mes-jump "A:¥MES¥063.MES"))
    (/
     (text "［コール］悪いがやめとくよ・・・。キャサリンの気持ちは良く判　　　　　るけど、今の俺には君を抱く事はできないよ。")
     (wait)
     (text-reset 1)
     (text "［キャサリン］そう・・・。")
     (wait)
     (text-reset 1)
     (text "［コール］だからといって、キャサリンを嫌っている訳でもないん　　　　　だよ。")
     (wait)
     (text-reset 1)
     (text
      "［キャサリン］うん、分かってる・・・でも、もういいの。コール　　　　　　　にはシーラがいるって分かっているのに、私、どう　　　　　　　かしてたみたい・・・ごめんなさい。")
     (wait)
     (text-reset 1)
     (text "［コール］風が強くなってきたな。部屋に戻って今日は休もう。")
     (wait)
     (text-reset 1)
     (text "［キャサリン］うん。")
     (wait)
     (text-reset 1)
     (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
     (text "俺は部屋に戻り、ベッドの中でこれでよかったのだと、自分に言い聞かせていた・・・。")
     (wait)
     (text-reset 1)
     (sound '|| 2)
     ((cmd 204) 100 899)
     (mes-jump "A:¥MES¥063.MES")))))
 (seg*))