(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_10.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_10.USO"))))
  (sound '|| 1)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB104.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "Cole: It's a bit chilly up here, isn't it?")
  (wait)
  (text-reset 1)
  (text "Catherine: No, it's fine.")
  (wait)
  (text-reset 1)
  (text "Catherine: Cole, about Daniel...")
  (wait)
  (text-reset 1)
  (text "Cole: Hmm?")
  (wait)
  (text-reset 1)
  (text "Catherine: You know I ran away from home because I hated    Daniel, right?")
  (wait)
  (text-reset 1)
  (text "Cole: Yeah, you mentioned that.")
  (wait)
  (text-reset 1)
  (text "Catherine: But recently, I've been thinking that I want to  forgive him..")
  (wait)
  (text-reset 1)
  (text "Cole: ...")
  (wait)
  (text-reset 1)
  (text
   "Catherine: You know, my mother loved him with all her heart.No matter how despicable he could be, she trusted him         completely.")
  (wait)
  (text-reset 1)
  (text "Catherine: And since mom loved him so much, I started to    think that I should love Daniel too...")
  (wait)
  (text-reset 1)
  (text "Cole: ...But he assaulted you, didn't he?")
  (wait)
  (text-reset 1)
  (text "Catherine: Yes, he did. Even though he loved my mother, I   couldn't forgive him...")
  (wait)
  (text-reset 1)
  (text "Catherine: But since that day, Daniel hasn't come near me.")
  (wait)
  (text-reset 1)
  (text "Cole: Isn't that to be expected? After doing something like that, it's not like he's going to casually approach you.")
  (wait)
  (text-reset 1)
  (text "Catherine: That's right. He was remorseful about            it...repentant, even.")
  (wait)
  (text-reset 1)
  (text "Cole: Hold up. Aren't we talking about an abuser AND the    mastermind behind a horrific mass-casualty zombie incident?")
  (wait)
  (text-reset 1)
  (text "Catherine: I know...")
  (wait)
  (text-reset 1)
  (text "Cole: It's hard for me to sympathize with someone like him.")
  (wait)
  (text-reset 1)
  (text
   "Catherine: I intend to forgive Daniel for what he did to me.But if I were to forgive him for starting all of this, nobody  else would...")
  (wait)
  (text-reset 1)
  (text "Catherine: So even I can't forgive Daniel for taking so manylives in this incident.")
  (wait)
  (text-reset 1)
  (text "Cole: You're too kind as it is.")
  (wait)
  (text-reset 1)
  (text "Catherine: What about you, Cole?")
  (wait)
  (text-reset 1)
  (text
   "Cole: I can never forgive people like him. If I were in yourshoes, once I left home, I'd never go back.")
  (wait)
  (text-reset 1)
  (text "Catherine: Even if he repented.")
  (wait)
  (text-reset 1)
  (text "Cole: Yes.")
  (wait)
  (text-reset 1)
  (text "Catherine: Then I feel sorry for you.")
  (wait)
  (text-reset 1)
  (text "Cole: You may feel sorry for me, but since the incident two years ago, I can't trust anyone anymore.")
  (wait)
  (text-reset 1)
  (text "Catherine: The incident in the neighboring town?")
  (wait)
  (text-reset 1)
  (text "Cole: Yeah. Because I trusted Ghoul, the person who was     supposed to exterminate the zombies, I lost all my          comrades...")
  (wait)
  (text-reset 1)
  (text "Catherine: Cole...")
  (wait)
  (text-reset 1)
  (text "Cole: I'm sorry for telling you all this... I was out of my mind.")
  (wait)
  (text-reset 1)
  (text "Catherine: I see...")
  (wait)
  (text-reset 1)
  (text "Catherine: Cole...")
  (wait)
  (text-reset 1)
  (text "Cole: Yes?")
  (wait)
  (text-reset 1)
  (text "Catherine: I think Daniel's at Razovan Pharmaceuticals." 'br)
  (text "Cole: !?")
  (wait)
  (text-reset 1)
  (text "Catherine: There were two members of Bloody Fox who came to Shuffle Food to get me.")
  (wait)
  (text-reset 1)
  (text "Cole: Oh, that reminds me...there were two Bloody Fox gang  member corpses.")
  (wait)
  (text-reset 1)
  (text "Catherine: Yes. and one of them had said that I was being   too much trouble, and they should take me straight to       'Razo.'")
  (wait)
  (text-reset 1)
  (text "Cole: Why didn't you mention this back in the lab?")
  (wait)
  (text-reset 1)
  (text "Catherine: Because... Aren't you ultimately trying to kill  Daniel?")
  (wait)
  (text-reset 1)
  (text "Cole: ...")
  (wait)
  (text-reset 1)
  (text "Catherine: I thought that if Daniel died, it would destroy  my mother...")
  (wait)
  (text-reset 1)
  (text "Catherine: But now, it's different...because as long as     Daniel is alive, the undead will keep multiplying in number.")
  (wait)
  (text-reset 1)
  (text "Cole: ...")
  (wait)
  (text-reset 1)
  (text "Catherine: I feel so much better after having this talk,    Cole.")
  (wait)
  (text-reset 1)
  (text "Cole: Catherine...")
  (wait)
  (text-reset 1)
  (text "Catherine: More importantly, Cole.")
  (wait)
  (text-reset 1)
  (text "Cole: What is it?")
  (wait)
  (text-reset 1)
  (text "Catherine: Lately...have things been going well with Sheila?")
  (wait)
  (text-reset 1)
  (text "Cole: I wouldn't say 'well'... Normal, maybe? Why do you    ask?")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB105.GPC")
  (image-mem 0 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC")
  (image-mem 1 0)
  (image-file "B:¥GPC¥DB107C.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "Cole: What's with the sudden question? Is that your way of  saying good night?")
  (wait)
  (text-reset 1)
  (text "Catherine: I'll leave that up to your imagination...")
  (wait)
  (text-reset 1)
  (text "Cole: No... It would be cruel to Sheila.")
  (wait)
  (text-reset 1)
  (text "Catherine: Please...just this once?")
  (wait)
  (text-reset 1)
  (text "Cole: Wait a minute.")
  (wait)
  (text-reset 1)
  (text "Catherine: Cole, are you running away?")
  (wait)
  (text-reset 1)
  (text "Cole: No, that's not it. I just heard a car...")
  (wait)
  (text-reset 1)
  (text "Catherine: A car?")
  (wait)
  (text-reset 1)
  (text "Cole: Listen, do you hear it? It's coming from near the     entrance...")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 0 54 38,W 0,O 0")
  (text "Catherine: Who is it?")
  (wait)
  (text-reset 1)
  (text "Cole: It's Steve...")
  (wait)
  (text-reset 1)
  (text "Catherine: But Steve is--" 'br)
  (wait)
  (text-reset 1)
  (text "Cole: Shh!")
  (wait)
  (text-reset 1)
  (text "Cole: When I went to Steve's room earlier, he was too tired to let me in...")
  (wait)
  (text-reset 1)
  (text "Catherine: But where's he off to at this hour?")
  (wait)
  (text-reset 1)
  (text "Cole: I don't know. It looks like he's carrying something,  though.")
  (wait)
  (text-reset 1)
  (text "Catherine: He's leaving...")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 1 54 38,W 0,O 1")
  (exec-mem 912 "EXIT")
  (text "Catherine: I wonder where he's going?")
  (wait)
  (text-reset 1)
  (text "Cole: Well, you can ask him directly when he wakes up...")
  (wait)
  (text-reset 1)
  (text "Catherine: But seriously, Cole...")
  (wait)
  (text-reset 1)
  (text "Cole: ...")
  (wait)
  (text-reset 1)
  (text
   "Catherine: Please...hold me... I don't want to be alone.    Just for tonight... Please... Just tonight, okay?")
  (wait)
  (text-reset 1)
  (text "Cole: ...")
  (wait)
  (text-reset 1)
  (text "Catherine: Cole, answer me...")
  (wait)
  (text-reset 1)
  (text "Cole: Is someone like me really enough?")
  (wait)
  (text-reset 1)
  (text "Catherine: Please...")
  (wait)
  (text-reset 1)
  (text "Cole: How should I answer?")
  (menu1 25 337 45 337 (</> (/ (text "I'll do it. / No, I'll pass.")) (/ (text "I'll do it. / No, I'll pass."))))
  (text-reset 1)
  (branch-var
   S
   (</>
    (/
     (text "Cole: I understand... I'll erase all the fear from you      heart...")
     (wait)
     (text-reset 1)
     (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
     (image-file "B:¥GPC¥DB106.GPC")
     (image-mem 0 3)
     (exec-mem 15456 0)
     (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
     (text "Catherine: Ah... Cole!")
     (wait)
     (text-reset 1)
     (exec-mem 14544 2 10)
     (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
     (text "I go back to my room, lying on my bed telling myself this   was the right thing to do.")
     (wait)
     (text-reset 1)
     (sound '|| 2)
     ((cmd 204) 100 899)
     (mes-jump "A:¥MES¥063.MES"))
    (/
     (text "Cole: I'm sorry, Catherine... I understand how you feel, butwe can't do this.")
     (wait)
     (text-reset 1)
     (text "Catherine: I... I see...")
     (wait)
     (text-reset 1)
     (text "Cole: That doesn't mean I don't like you, Catherine.")
     (wait)
     (text-reset 1)
     (text
      "Catherine: I know... But that's enough. Even though I know  you have Sheila, I wasn't thinking... I'm sorry.")
     (wait)
     (text-reset 1)
     (text "Cole: The wind is picking up. Let's go back inside and get  some rest for the day.")
     (wait)
     (text-reset 1)
     (text "Catherine: Okay.")
     (wait)
     (text-reset 1)
     (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
     (text "I go back to my room, lying on my bed telling myself this   was the right thing to do.")
     (wait)
     (text-reset 1)
     (sound '|| 2)
     ((cmd 204) 100 899)
     (mes-jump "A:¥MES¥063.MES")))))
 (seg*))