(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB124.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 35 4 39 6)
  (exec-mem 3744 1 6 27 10 31 13)
  (exec-mem 3744 1 7 43 5 56 13)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB124.GPC")
  (image-mem 0 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 2 23 40 238 1 2 23")
  (exec-mem 912 "C 0 40 23 18 238 1 40 23")
  (exec-mem 912 "A 1")
  (image-file "B:¥GPC¥DB125.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 0 2 23 54 238")
  (image-file "B:¥GPC¥DB126.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 1 2 23 54 238")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 15456 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (if (</>
       (//
        (? (= 133 #f))
        (sound '|| 0)
        (if (</>
             (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
             (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
        (sound '|| 1))))
  (if (</>
       (//
        (? (= 164 #t))
        (str "Cole: Huh? Where is it? I definitely saw something ducking" 'br)
(str "into the restroom, but...")
        (wait)
        (text-reset 1))
       (//
        (? (= 150 #f))
        (str "Cole: From what I can see, there's no zombies in here," 'br)
(str "but...")
        (set-reg 150 #t)
        (wait)
        (text-reset 1))
       (// (str "Cole: Inside the restroom. But I only see myself reflected" 'br)
(str "in the mirror.") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 164 #t) (= 153 #f))
   (str "Cole: I only see myself in the mirror, but I'm sure I saw a" 'br)
(str "zombie come in here...")
   (set-reg 153 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 164 #t))
   (str "Cole: Huh? I heard something behind me...")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 0 2 23,W 0,O 0")
   (sound '|| 0)
   (if (</>
        (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_05.USO"))
        (// (sound '|| "A:¥USO_D¥BR2_05.USO"))))
   (sound '|| 1)
   (str "Cole: !?")
   (wait)
   (text-reset 1)
   (str "Cole: Dammit! Is it hiding?")
   (wait)
   (text-reset 1)
   (image-file "A:¥GPC¥COUNTER.GPC")
   (image-mem 0 0)
   (load-mem "A:¥CLM¥DB125.CLM" 32768)
   (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 3 2 0)
   (exec-mem 3744 1 1 80 0 0 0)
   (exec-mem 3744 1 5 41 5 44 6)
   (exec-mem 3744 1 6 80 0 0 0)
   (exec-mem 15728 0 0 0 5 0 1)
   (exec-mem 15728 1 0 0 0 0 "Z")
   (exec-mem 15728 2 1)
   (exec-mem 15456 0)
   (exec-mem 14544 2 0)
   (exec-mem 15728 3)
   (exec-mem 3744 3 "P" 32768)
   (exec-mem 15728 4)
   (image-file "A:¥GPC¥DB_FRM3.GPC")
   (image-mem 0 0)
   (if (</>
        (//
         (? (= Z 2) (= P 6))
         (str "Cole: I can't shoot whoever's behind me. I'll just slam that" 'br)
(str "zombie bastard into the wall instead!")
         (wait)
         (text-reset 1)
         (exec-mem 14544 2 2)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (str "Cole: *Huff huff* Well, that was anticlimactic.")
         (wait)
         (text-reset 1)
         (image-file "B:¥GPC¥DB127.GPC")
         (image-mem 0 3)
         ((cmd 193) 0 "B:¥GPA¥DB127.GPA")
         (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
         (sound '|| 0)
         (if (</>
              (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
              (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
         (sound '|| 1)
         (str "Cole: Another one of you Bloody Fox assholes?")
         (wait)
         (text-reset 1)
         (str "B.F.: *Pant pant*")
         (wait)
         (text-reset 1)
         (str "Cole: So it was you who busted the front door open, huh?")
         (wait)
         (text-reset 1)
         (text
          "Cole: Why did you attack me? Why are you here? Who sent you?" 'br)
"Was it Daniel?")
         (wait)
         (text-reset 1)
         (str "B.F.: *Pant pant*")
         (wait)
         (text-reset 1)
         (str "Cole: Answer me! Why did you come after us?")
         (wait)
         (text-reset 1)
         (str "B.F.: Heh...")
         (wait)
         (text-reset 1)
         (str "Cole: You bastard!")
         (wait)
         (text-reset 1)
         ((cmd 196) 0 0)
         ((cmd 196) 0 1)
         (delay 10 0)
         ((cmd 196) 0 2)
         (delay 6 0)
         ((cmd 196) 0 3)
         (delay 6 0)
         ((cmd 196) 0 4)
         (delay 6 0)
         ((cmd 196) 0 5)
         (delay 6 0)
         ((cmd 196) 0 6)
         (str "Cole: Wait, what the... What are you...")
         (wait)
         (text-reset 1)
         (str "B.F.: *Glorp*........")
         (wait)
         (text-reset 1)
         (str "Cole: Holy... Holy shit... He bit off his own tongue...")
         (wait)
         (text-reset 1)
         (str "Cole: ...")
         (wait)
         (text-reset 1)
         (str "Cole: I'm shaking... Me, of all people...")
         (wait)
         (text-reset 1)
         (text
          "Cole: I was never freaked out this bad when fighting" 'br)
"zombies, but now I can't stop shaking. This Bloody Fox" 'br)
"member came here prepared to die...")
         (wait)
         (text-reset 1)
         (text
          "Cole: We're on to something big here... Up until now my" 'br)
"enemies were only zombies, but now my fellow man... willing" 'br)
"to risk death...is coming at me...")
         (wait)
         (text-reset 1)
         (str "Cole: Anyway, I... I need to report this to Steve... Or at" 'br)
(str "this rate, we'll all end up dead.")
         (wait)
         (text-reset 1)
         (sound '|| 2)
         (exec-mem 912 "EXIT")
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         ((cmd 204) 100 899)
         (mes-jump "A:¥MES¥073.MES"))
        (//
         (? (= Z 2) (= P 5))
         (sound '|se | 13)
         (exec-mem 912 "PUT 1 2 23,W 0,O 0")
         (exec-mem 912 "EXIT")
         (str "Cole: At a dire time like this, doing something so" 'br)
(str "meaningless...")
         (wait)
         (text-reset 1)
         (str "Cole: Ahhhhhgh!")
         (wait)
         (text-reset 1)
         (exec-mem 14544 2 2))
        (//
         (exec-mem 14544 2 2)
         (str "Cole: My back is on fire... Like I've been stabbed...!")
         (wait)
         (text-reset 1)
         (str "Cole: I'm so sorry, everyone...")
         (wait)
         (text-reset 1))))
   (sound '|| 0)
   (sound '|se | 10)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (text "　　　　　　　　　　ＧＡＭＥ　ＯＶＥＲ")
   (menu1 32 337 48 337 (</> (/ (str "CONTINUE")) (/ (str "GAME END"))))
   (text-reset 1)
   (branch-var
    S
    (</>
     (/
      (exec-mem 9920 0 6 6 113 64 0)
      (nop@)
      (set-reg 133 #f)
      (mes-jump "A:¥MES¥071.MES"))
     (/
      (text "　　　　　ＮＩＧＨＴＭＡＲＥ　ＣＯＬＬＥＣＴＩＯＮ" 'br)
      (text "　　　　　　ＤＥＡＤ　ＯＦ　ＴＨＥ　ＢＲＡＩＮⅡ" 'br)
      (text "　　　　　　　　　　　ＧＡＭＥ　ＥＮＤ")
      (loop (wait))))))
 (seg (? (= P 5) (= 151 #f))
   (str "Cole: There's a big mirror in here. Holding my gun like" 'br)
(str "this, I sorta look like a gangster.")
   (set-reg 151 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 152 #f))
   (str "Cole: The mirror's just reflecting my image. If a zombie" 'br)
(str "comes at me from behind, I'll be able to see him coming.")
   (set-reg 152 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (str "Cole: It's been a long time since I've really looked at" 'br)
(str "myself in the mirror.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 164 #t))
   (str "Cole: I don't see any zombies around the toilets... But" 'br)
(str "there's gotta be one in here. Have to watch my back.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 154 #f))
   (str "Cole: There are several urinals lined up... I never thought" 'br)
(str "a zombie would be in a place like this.")
   (set-reg 154 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6)) (str "Cole: There aren't any zombies by the urinals.") (wait) (text-reset 1))
 (seg (? (= P 7) (= 164 #t))
   (str "Cole: This is weird... I can't see any signs of zombies... I" 'br)
(str "can't imagine one would hide in here, so where the hell is" 'br)
(str "it?")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 155 #f))
   (str "Cole: The entrance to the restroom is visible in the mirror.")
   (set-reg 155 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 156 #f))
   (text
    "Cole: The entrance is reflected in the mirror. If a zombie" 'br)
"lunges in here, I wouldn't have time to react. Gotta be on" 'br)
"my toes.")
   (set-reg 156 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (str "Cole: There aren't any fluorescent lights in here, so it's" 'br)
(str "dim and hard to see.")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 164 #t))
   (exec-mem 6064 2 1)
   (str "Cole: I definitely saw SOMEone head into the restroom. I" 'br)
(str "can't leave without confirming that.")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3))
 (seg (? (= P 1))
   (exec-mem 6064 2 1)
   (str "Cole: Okay, let's head outside for now.")
   (wait)
   (text-reset 1)
   (exec-mem 912 "EXIT")
   (exec-mem 6064 3)
   (nop@)
   (set-reg 127 #t)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥068.MES"))
 (seg (? (= P 2))
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (nop@) (set-reg 133 #f) (flag-save 1))
        (/ (nop@) (set-reg 133 #f) (flag-save 2))
        (/ (nop@) (set-reg 133 #f) (flag-save 3))
        (/ (nop@) (set-reg 133 #f) (flag-save 4))
        (/ (nop@) (set-reg 133 #f) (nop@) (set-reg 133 #f) (flag-save 5))
        (/ (nop@) (set-reg 133 #f) (flag-save 6))
        (/ (nop@) (set-reg 133 #f) (flag-save 7))
        (/ (nop@) (set-reg 133 #f) (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))