(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB043.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 16 3 21 7)
  (exec-mem 3744 1 6 38 2 44 6)
  (exec-mem 3744 1 7 25 2 34 7)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB043.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB044.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 100 #f))
        (text "Steve: Oh, there's Cole. You're just in time. How are things looking? Could you clean out the first floor?")
        (wait)
        (text-reset 1)
        (text "Cole: Steve, it's bad! Real bad!")
        (set-reg 100 #t)
        (wait)
        (text-reset 1))
       (// (text "Steve: Cole...") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 101 #f))
   (text "Lisle: Cole...")
   (wait)
   (text-reset 1)
   (text "Steve: Doctor Lisle, let's hear what Cole has to say.")
   (wait)
   (text-reset 1)
   (text "Cole: What is it?")
   (wait)
   (text-reset 1)
   (text "Steve: Give it to us straight.")
   (wait)
   (text-reset 1)
   (text "Cole: OK.")
   (wait)
   (text-reset 1)
   (text "Cole: Just now, I got jumped by Bloody Fox on the first floor.")
   (wait)
   (text-reset 1)
   (text "Steve: Bloody Fox!? How did they get here?")
   (wait)
   (text-reset 1)
   (text "Cole: I had assumed he was just a zombie. I started asking him questions, and...")
   (wait)
   (text-reset 1)
   (text "Steve: What happened?")
   (wait)
   (text-reset 1)
   (text "Cole: He bit his own tongue off!")
   (wait)
   (text-reset 1)
   (text "Steve: Good god. Did he die?")
   (wait)
   (text-reset 1)
   (text "Cole: Yeah... But before he did it, he SMILED at me.")
   (wait)
   (text-reset 1)
   (text "Steve: What a man... So, does that mean the person who broke open the entrance...")
   (wait)
   (text-reset 1)
   (text "Cole: Yeah, it must have been him.")
   (set-reg 101 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 102 #f))
   (text "Lisle: Who is Bloody Fox taking their orders from?")
   (wait)
   (text-reset 1)
   (text "Steve: Who indeed...")
   (wait)
   (text-reset 1)
   (text "Cole: Orders?")
   (wait)
   (text-reset 1)
   (text "Steve: You know as well as I do... Someone's pulling Bloody Fox's strings.")
   (wait)
   (text-reset 1)
   (text "Cole: You think Daniel...?")
   (wait)
   (text-reset 1)
   (text "Steve: I can only assume so.")
   (wait)
   (text-reset 1)
   (text "Cole: I'm not sure Daniel knows exactly who we are, though.")
   (wait)
   (text-reset 1)
   (text
    "Steve: Since Daniel has ties to Bloody Fox, they probably told him that we were investigating Purple Sky.")
   (wait)
   (text-reset 1)
   (text "Cole: I see...")
   (set-reg 102 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 103 #f))
   (text "Lisle: When it rains, it pours. From now on, it's not just zombies, but also Bloody Fox who's after us.")
   (wait)
   (text-reset 1)
   (text
    "Cole: We musta really gotten under Daniel's skin. He must know we're here at the Institute...")
   (wait)
   (text-reset 1)
   (text "Lisle: Well, we've locked down the shutters. They probably can't get to the second floor anytime soon.")
   (wait)
   (text-reset 1)
   (text "Steve: Doctor, don't let your guard down.")
   (wait)
   (text-reset 1)
   (text "Lisle: If my guard was down, I wouldn't be packing this gun all the time.")
   (set-reg 103 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "Steve: Doctor, don't let your guard down.")
   (wait)
   (text-reset 1)
   (text "Lisle: If my guard was down, I wouldn't be packing this gun all the time.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 103 #t) (= 105 #t) (= 106 #f))
   (text "Cole: So... What does Steve have to say?")
   (wait)
   (text-reset 1)
   (text "Steve: ...")
   (wait)
   (text-reset 1)
   (text "Cole: What is it...?")
   (wait)
   (text-reset 1)
   (text "Lisle: If it's about that, I can--")
   (wait)
   (text-reset 1)
   (text "Steve: I'm sorry.")
   (wait)
   (text-reset 1)
   (text "Lisle: It's about Sheila's blood test...")
   (wait)
   (text-reset 1)
   (text "Cole: Right, the blood test. Did you figure anything out?")
   (wait)
   (text-reset 1)
   (text "Lisle: We found a very slight DNV reaction in her blood.")
   (wait)
   (text-reset 1)
   (text "Cole: What!? Doesn't that mean...")
   (wait)
   (text-reset 1)
   (text "Lisle: ...")
   (wait)
   (text-reset 1)
   (text "Cole: What's going to happen to Sheila?")
   (wait)
   (text-reset 1)
   (text "Lisle: I can't say for sure yet... But now that we know there's DNV in her system, we can't just leave her as-is.")
   (set-reg 106 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 103 #t) (= 105 #t) (= 107 #f))
   (text "Cole: What do you mean?")
   (wait)
   (text-reset 1)
   (text "Steve: We need to move her to a...safe place.")
   (wait)
   (text-reset 1)
   (text "Cole: Sheila turning into a zombie? That's ridiculous!")
   (wait)
   (text-reset 1)
   (text "Lisle: We still don't know what will happen to her, but... Considering a worst-case scenario...")
   (wait)
   (text-reset 1)
   (text "Cole: No way, you've gotta be joking!")
   (wait)
   (text-reset 1)
   (text "Steve: Cole...")
   (wait)
   (text-reset 1)
   (text "Cole: ...")
   (wait)
   (text-reset 1)
   (text "Cole: ...So... What should we do about Sheila?")
   (wait)
   (text-reset 1)
   (text "Lisle: She's resting in her room, but we haven't given her the results yet.")
   (wait)
   (text-reset 1)
   (text "Cole: I see...")
   (wait)
   (text-reset 1)
   (text "Cole: I need to go.")
   (wait)
   (text-reset 1)
   (text "Lisle: She doesn't need to know about this, Cole.")
   (wait)
   (text-reset 1)
   (text "Cole: I get it... I'm just going to go check on her.")
   (set-reg 107 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 103 #t) (= 105 #t))
   (text "Lisle: I never thought Sheila would end up like this...")
   (wait)
   (text-reset 1)
   (text "Cole: ...")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 104 #f))
   (text "Steve: Things must have gotten pretty crazy on the first floor.")
   (wait)
   (text-reset 1)
   (text "Cole: Actually, it was relatively easy taking care of business...")
   (set-reg 104 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 105 #f))
   (text
    "Cole: In the first-floor office, I found the zombie that you'd taken out. As expected, a perfect shot right to the brain.")
   (wait)
   (text-reset 1)
   (text "Steve: Ah, at that range, even a toddler could have made the shot.")
   (set-reg 105 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6)) (text "Steve: So what happened on the first floor?") (wait) (text-reset 1))
 (seg (? (= P 7)) (text "Lisle: I'll be in the lab all day.") (wait) (text-reset 1))
 (seg (? (= P 1) (= 107 #t))
   (exec-mem 6064 2 1)
   (text "Cole: Let's get out of here for now.")
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥074.MES"))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))