(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB043.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 16 3 21 7)
  (exec-mem 3744 1 6 38 2 44 6)
  (exec-mem 3744 1 7 25 2 34 7)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB043.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB044.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 100 #f))
        (text "［スティーブ］あ、コールか。丁度良かった・・・どうだ、１階の　　　　　　　方は片付いたか？")
        (wait)
        (text-reset 1)
        (text "［コール］スティーブさん、大変なんです！！")
        (set-reg 100 #t)
        (wait)
        (text-reset 1))
       (// (text "［スティーブ］コールか・・・。") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 101 #f))
   (text "［ライル］コール・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ライル、まずコールの話を聞こう。")
   (wait)
   (text-reset 1)
   (text "［コール］何か？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］いや、話してくれ。")
   (wait)
   (text-reset 1)
   (text "［コール］ええ。")
   (wait)
   (text-reset 1)
   (text "［コール］ついさっき、１階でブラッディフォックスに襲われたん　　　　　です。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ブラッディフォックス！？　どうしてここに！？")
   (wait)
   (text-reset 1)
   (text "［コール］俺は死霊だとばかり思ってたのですが・・・。それで、　　　　　その男に聞いたら・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］どうした？")
   (wait)
   (text-reset 1)
   (text "［コール］自ら舌を噛み切って・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］舌を？　死んだのか？")
   (wait)
   (text-reset 1)
   (text "［コール］ええ・・・そいつ、舌を噛む前に俺に微笑んだんです。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］なんて男だ・・・。じゃあ、入口のドアが開いてい　　　　　　　たのも・・・？")
   (wait)
   (text-reset 1)
   (text "［コール］きっとその男でしょう。")
   (set-reg 101 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 102 #f))
   (text "［ライル］そのブラッディフォックス、誰かに操られているな。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］多分な・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］操る？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］コールにも判っているだろう？　ブラッディフォッ　　　　　　　クスにそんな事をやらせている人間だよ。")
   (wait)
   (text-reset 1)
   (text "［コール］ダニエルが・・・？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］そうとしか考えられない・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］だけど、ダニエルは直接俺達の事は知らないと思います　　　　　が・・・。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］ダニエルがブラッディフォックスと繋がっている以　　　　　　　上、我々がパープル・スカイを調べていたという事　　　　　　　は既に報告してあるだろう。")
   (wait)
   (text-reset 1)
   (text "［コール］なるほど・・・。")
   (set-reg 102 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 103 #f))
   (text "［ライル］厄介な事になってきたな・・・。これからは、死霊以外　　　　　にブラッディフォックスも敵となるのか・・。")
   (wait)
   (text-reset 1)
   (text
    "［コール］ダニエルは相当俺達を邪魔に思っているのでしょうね。　　　　　それに、この研究所に俺達が居るって事も、発覚してし　　　　　まったようですし・・・。")
   (wait)
   (text-reset 1)
   (text "［ライル］まあ、研究所のシャッターは全て閉めてあるんだ。早々　　　　　この２階に上がって来る事はできんだろう。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ライル、油断するなよ。")
   (wait)
   (text-reset 1)
   (text "［ライル］油断してるなら、常時銃なんて携帯していないよ。")
   (set-reg 103 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "［スティーブ］ライル、油断するなよ。")
   (wait)
   (text-reset 1)
   (text "［ライル］油断してるなら、常時銃なんて携帯していないよ。")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 103 #t) (= 105 #t) (= 106 #f))
   (text "［コール］それで・・・スティーブさんの話とは？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］・・・・・・・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］何か・・・？")
   (wait)
   (text-reset 1)
   (text "［ライル］その話なら私が・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］すまない・・・。")
   (wait)
   (text-reset 1)
   (text "［ライル］実はシーラの血液の事なんだが・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］血液検査ですね、分かったんですか？")
   (wait)
   (text-reset 1)
   (text "［ライル］彼女の血液中に、ほんのわずかだがＤＮＶ反応が確認さ　　　　　れたんだ・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］なんだって！？")
   (wait)
   (text-reset 1)
   (text "［ライル］・・・・・・・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］じゃあ、シーラはどうなるんですか！？")
   (wait)
   (text-reset 1)
   (text "［ライル］まだ何とも言えんが・・・ＤＮＶ反応が現れた以上は、　　　　　このまま放っておく訳にはいかない。")
   (set-reg 106 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 103 #t) (= 105 #t) (= 107 #f))
   (text "［コール］どういう事ですか！？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］どこか安全な場所に彼女を移した方が・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］シーラが死霊に！？　そんな馬鹿な！？")
   (wait)
   (text-reset 1)
   (text "［ライル］まだ、これから彼女がどうなるのかは判らない。だが、　　　　　もしもの時の事を考えて・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］嘘だ！？　嘘でしょ！？　ねえ、ライルさん！！")
   (wait)
   (text-reset 1)
   (text "［スティーブ］コール・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］・・・・・・・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］・・・それで、シーラは？")
   (wait)
   (text-reset 1)
   (text "［ライル］多分、部屋にいるだろう。だが、この事はまだ彼女には　　　　　話していない・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］そうですか・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］俺、ちょっと行ってきます。")
   (wait)
   (text-reset 1)
   (text "［ライル］この話は彼女には・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］判っています・・・様子を見に行くだけですから・・。")
   (set-reg 107 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 103 #t) (= 105 #t))
   (text "［ライル］シーラがこんな事になってしまうなんてな・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］・・・・・・・・・。")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 104 #f))
   (text "［スティーブ］１階では御苦労だったな・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］いや、意外と楽勝でしたから・・・。")
   (set-reg 104 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 105 #f))
   (text
    "［コール］１階の事務室に、スティーブさんの倒した死霊の死体が　　　　　ありました。さすが刑事ですね、ピタリと死霊の額を打　　　　　ち抜いていましたよ。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］あのぐらいの距離なら、赤ん坊でも当てる事ができ　　　　　　　るよ。")
   (set-reg 105 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6)) (text "［スティーブ］それで、１階で何かあったのか？") (wait) (text-reset 1))
 (seg (? (= P 7)) (text "［ライル］私は、今日はずっとこの研究室にいるよ。") (wait) (text-reset 1))
 (seg (? (= P 1) (= 107 #t))
   (exec-mem 6064 2 1)
   (text "［コール］とにかく、一旦ここを出よう。")
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥074.MES"))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))