(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB073.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 30 3 37 7)
  (exec-mem 3744 1 6 50 3 56 14)
  (exec-mem 3744 1 7 4 10 23 15)
  (exec-mem 3744 1 8 15 2 27 9)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB072.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB073.GPC")
  (image-mem 1 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 2 23 40 238 1 2 23")
  (exec-mem 912 "C 0 40 23 18 238 1 40 23")
  (exec-mem 912 "A 1")
  (image-file "B:¥GPC¥DB072.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB128.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 0 2 23 54 238")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 111 #f))
        (str "Cole: Sheila... You were awake?")
        (wait)
        (text-reset 1)
        (str "Sheila: Yeah. It sounded like something was going down on" 'br)
(str "the first floor.")
        (wait)
        (text-reset 1)
        (str "Cole: The front door got opened, but it's all fine now, I" 'br)
(str "took care of everything. There's nothing for you to worry" 'br)
(str "about.")
        (set-reg 111 #t)
        (wait)
        (text-reset 1))
       (// (str "Sheila: Cole...") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 112 #f))
   (str "Cole: How are you feeling?")
   (wait)
   (text-reset 1)
   (str "Sheila: ...")
   (wait)
   (text-reset 1)
   (str "Cole: What's wrong?")
   (wait)
   (text-reset 1)
   (str "Sheila: Ugh...")
   (set-reg 112 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 113 #f))
   (str "Sheila: Cole...")
   (wait)
   (text-reset 1)
   (str "Cole: Yeah?")
   (wait)
   (text-reset 1)
   (str "Sheila: I... I lied to you, Cole.")
   (wait)
   (text-reset 1)
   (str "Cole: Lied? What about?")
   (wait)
   (text-reset 1)
   (str "Sheila: The reason why I was investigating Purple Sky by" 'br)
(str "myself yesterday...")
   (wait)
   (text-reset 1)
   (str "Cole: Because you couldn't just stay at home?")
   (wait)
   (text-reset 1)
   (str "Sheila: No, it's not that... The truth is, ever since I was" 'br)
(str "injected with Purple Sky, my body has been changing...")
   (wait)
   (text-reset 1)
   (str "Cole: !?")
   (set-reg 113 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 114 #f))
   (str "Cole: No way, she couldn't have... Not already...")
   (wait)
   (text-reset 1)
   (str "Cole: What... What kind of change?")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 0 2 23,W 0,O 0")
   (exec-mem 912 "EXIT")
   (str "Sheila: Here, look...")
   (wait)
   (text-reset 1)
   (str "Cole: What the...!")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB121.GPC")
   (image-mem 0 3)
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (str "Cole: There's no mistaking it... That's exactly the same" 'br)
(str "skin blemishes that were on the chest of that woman zombie I" 'br)
(str "killed on the first floor...")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB072.GPC")
   (image-mem 0 3)
   (image-file "B:¥GPC¥DB073.GPC")
   (image-mem 1 3)
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (str "Sheila: I noticed this the day after I got the injection. I" 'br)
(str "went to the hospital, but since Purple Sky is a brand-new" 'br)
(str "drug, they said they didn't have anything for me...")
   (wait)
   (text-reset 1)
   (str "Sheila: They said that because Purple Sky is a cocktail of" 'br)
(str "various chemicals, if we figure out its composition, there" 'br)
(str "might be something we could do...")
   (wait)
   (text-reset 1)
   (str "Sheila: That's why I wanted to find out where Purple Sky" 'br)
(str "came from without telling you, Cole...")
   (wait)
   (text-reset 1)
   (str "Cole: That's... I can't believe it...")
   (set-reg 114 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 115 #f))
   (str "Cole: But why didn't you tell me until now?")
   (wait)
   (text-reset 1)
   (str "Sheila: I thought you'd worry, and if they didn't have a" 'br)
(str "cure for me , I...")
   (wait)
   (text-reset 1)
   (str "Cole: Then you really should have told me earlier!")
   (wait)
   (text-reset 1)
   (str "Sheila: I'm sorry...")
   (set-reg 115 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 116 #f))
   (str "Cole: Does it hurt?")
   (wait)
   (text-reset 1)
   (str "Sheila: No, it doesn't... But the spots have gotten bigger" 'br)
(str "since yesterday...")
   (wait)
   (text-reset 1)
   (str "Cole: I see... Anyway, you stay right there. I'm going to" 'br)
(str "talk to Lisle. He's the only person we can rely on now.")
   (wait)
   (text-reset 1)
   (str "Sheila: I understand.")
   (set-reg 116 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (str "Cole: I'm going to go consult with Lisle. He's the only one" 'br)
(str "we can depend on.")
   (wait)
   (text-reset 1)
   (str "Sheila: Cole...I...")
   (wait)
   (text-reset 1)
   (str "Cole: Don't worry. He'll get you fixed up.")
   (wait)
   (text-reset 1)
   (str "Sheila: Yeah...")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 117 #f))
   (str "Sheila: Cole, have you been taking proper showers?")
   (wait)
   (text-reset 1)
   (str "Cole: Yeah, but there's no doubt the zombies are gonna" 'br)
(str "contaminate me again.")
   (set-reg 117 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (str "Cole: This is the shower room... My room doesn't have one.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 118 #f))
   (str "Cole: Are you okay without sleep?")
   (wait)
   (text-reset 1)
   (str "Sheila: Yeah... I'm feeling a little better than before.")
   (set-reg 118 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (str "Cole: Maybe you should just sleep and take it easy.")
   (wait)
   (text-reset 1)
   (str "Sheila: Thanks, but I'm okay...")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 119 #f))
   (str "Cole: The curtains are closed. Since the temperature's been" 'br)
(str "dropping, best to keep them that way.")
   (set-reg 119 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8))
   (str "Cole: We're getting into the cold season. Better keep the" 'br)
(str "curtains drawn.")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 116 #t))
   (exec-mem 6064 2 1)
   (str "Cole: Okay, I'm off... Cheer up, if you can.")
   (wait)
   (text-reset 1)
   (str "Sheila: Yeah...")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥074.MES"))
 (seg (? (= P 1))
   (str "Cole: Sorry, I just remembered something I had to do.")
   (wait)
   (text-reset 1)
   (str "Cole: Okay... Got it,. I'll be back later.")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (mes-jump "A:¥MES¥074.MES"))
 (seg (? (= P 2))
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))