(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB043.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB044.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (text "［ライル］コール、シーラの様子はどうだった？")
  (wait)
  (text-reset 1)
  (text "［コール］それが・・・シーラは、自分の身体の変化を既に気付い　　　　　ていました・・・。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］身体の変化！？")
  (wait)
  (text-reset 1)
  (text "［コール］ええ、彼女の胸元に紫色の斑点がありました。これは、　　　　　俺が１階で戦った女の死霊にもついているものと同一で　　　　　す。")
  (wait)
  (text-reset 1)
  (text "［ライル］その斑点とやらを詳しく教えてくれないか？")
  (wait)
  (text-reset 1)
  (text
   "［コール］直径が１センチから２センチぐらいの紫色の斑点が、い　　　　　くつも皮膚の表面からシミのように現れていました。ま　　　　　るで蘇生薬が体内から出て来たように・・・。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text
   "［コール］彼女は、それを自分で治そうと次の日病院へ行ったんで　　　　　す。だけど、パープル・スカイの成分が判らないため、　　　　　病院も対応できません。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］それで自らパープル・スカイの調査を？")
  (wait)
  (text-reset 1)
  (text "［コール］そうです。")
  (wait)
  (text-reset 1)
  (text "［コール］ライルさん、お願いです！　何かシーラが助かる方法は　　　　　ないんですか！？")
  (wait)
  (text-reset 1)
  (text
   "［ライル］多分、紫色の斑点というのは血液の中で育ったＤＮＶが　　　　　溢れてしまい、血管を溶かして体内に放出してしまった　　　　　ものだろう。")
  (wait)
  (text-reset 1)
  (text
   "［ライル］既にシーラの身体には、大量のＤＮＶが繁殖している。　　　　　もう少し早く気付いていれば、少しは抑えられる事もで　　　　　きるが・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text "［ライル］今の私の力では、そこまで身体を侵しているＤＮＶを食　　　　　い止める事はできない。")
  (wait)
  (text-reset 1)
  (text "［コール］そんな・・・。")
  (wait)
  (text-reset 1)
  (text "［ライル］だが、たった一人だけシーラの身体からＤＮＶを消滅さ　　　　　せる事のできる人間がいる・・・だが・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］だ、誰？　その人は誰ですか！？")
  (wait)
  (text-reset 1)
  (text "［ライル］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］コール・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］教えて下さい、ライルさん！　スティーブさん！")
  (wait)
  (text-reset 1)
  (text "［ライル］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text "［ライル］シーラの身体を治せる事のできる人は、ＤＮＶを一番良　　　　　く知っている人間・・・。")
  (wait)
  (text-reset 1)
  (text "［ライル］そう、蘇生薬の生みの親であるクーガー・ハミルトンだ　　　　　けだ。")
  (sound '|| 0)
  (sound '|se | 3)
  (wait)
  (text-reset 1)
  (text "［コール］な、何をこんな時にそんな冗談を・・・！！")
  (wait)
  (text-reset 1)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
  (sound '|| 1)
  (text "［スティーブ］コール、ライルが冗談で言っていると思うか？")
  (wait)
  (text-reset 1)
  (text "［コール］当たり前だ！　現にドクは２年前、死霊に殺られて死ん　　　　　だんだぞ！！")
  (wait)
  (text-reset 1)
  (text "［ライル］そう、君の言うとおり彼は死んだ。だが、今でも彼の身　　　　　体は腐らずに残っているとしたら・・・。")
  (wait)
  (text-reset 1)
  (text
   "［コール］ドクは・・・クーガーは死霊に頭をかじられたんだ。そ　　　　　のため、彼自身も死霊になる事を恐れて俺にトリガーを　　　　　引かせたんだ・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］彼の脳は俺の撃った弾で完全に破壊されている・・・。")
  (wait)
  (text-reset 1)
  (text
   "［コール］彼はもう蘇生できない。それに、彼を人間らしく死なせ　　　　　てやりたかった・・・彼を死霊になんかにさせたくなか　　　　　った・・・。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］だが、現に彼の身体は生きているよ。")
  (wait)
  (text-reset 1)
  (text "［コール］そんな・・・まさか・・・！？")
  (wait)
  (text-reset 1)
  (text "［スティーブ］昨夜、私とライルはディスベル霊園に行ったんだ。")
  (wait)
  (text-reset 1)
  (text "［コール］ディスベル霊園に？　じゃあ、夜中に車で出て行ったと　　　　　いうのは・・・。")
  (wait)
  (text-reset 1)
  (text
   "［スティーブ］ああ、私達だ。２年前の事件が起きた時に、隣街で　　　　　　　発見された死体は全てディスベル霊園に埋葬された　　　　　　　んだ。勿論、クーガーの遺体もな・・・。")
  (wait)
  (text-reset 1)
  (text
   "［ライル］私達はクーガーの墓を探して彼の遺体を調べたんだ。彼　　　　　の心臓は完全に止まっていたが、身体の細胞は未だに生　　　　　き続けていた・・・。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］そして、ほんのわずかだが彼の脳波が確認されたん　　　　　　　だ。")
  (wait)
  (text-reset 1)
  (text "［コール］そんな・・・。")
  (wait)
  (text-reset 1)
  (text "［ライル］コール、こっちの部屋に来るんだ。君が入りたがってい　　　　　た実験室で、私は何をやっていたのかが判るだろう。")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB129.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB130.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC")
  (image-mem 1 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "［スティーブ］ここがライルの実験室だ。私も昨日初めてこの部屋　　　　　　　に入れてもらったんだ。")
  (wait)
  (text-reset 1)
  (text "［ライル］準備はできている。そこにある筒状のガラスケースを見　　　　　てくれ。")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB131.GPC")
  (image-mem 0 3)
  ((cmd 193) 0 "B:¥GPA¥DB131A.GPA")
  ((cmd 193) 1 "B:¥GPA¥DB131B.GPA")
  ((cmd 194)
   0
   "ｱ. ...ｲ..ｳ.ｴ.ｵ.ｶ.ｷ.ｸ.ｹ.ｺ.ｻ.ｼ.ｽ.ｾ.ｿ.ﾀ.ﾁ.ｱ. ..........................ｱ")
  ((cmd 194) 1 "ｱ. .........ｱ ...ｲ..ｳ.ｴ.ｵ.ｶ.ｷ.ｸ.ｹ.ｺ.ｻ.ｼ.ｽ.ｾ.ｿ.ﾀ.ﾁ..........")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "［コール］こ、これは・・・。")
  (wait)
  (text-reset 1)
  (text "［ライル］それは、１階でコールを襲って来たブラッディフォック　　　　　スの脳だ。既にトイレで舌を噛み切っていた・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］これが、あの男の脳・・・。")
  (wait)
  (text-reset 1)
  (text "［ライル］今からこの脳にアクセスする。")
  (wait)
  (text-reset 1)
  (text "［ライル］私の声が聞こえるか？")
  (wait)
  (text-reset 1)
  (text "［合成音］ガー・ガガー・・・。")
  (wait)
  (text-reset 1)
  (text "［ライル］聞こえるなら返事をするのだ！")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "［合成音］ダ・・・誰ダ・・・？　ココハ・・・ココハドコダ？")
  (sound '|| 0)
  (sound '|se | 4)
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "［コール］ま、まさか！？　こんな事が・・・！？")
  (wait)
  (text-reset 1)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
  (sound '|| 1)
  (text
   "［ライル］びっくりするのも無理はない。この実験はＤＮＡに関す　　　　　る様々な原因を追求するために、８年前からアメリカや　　　　　イギリスなどの医学界で行われている実験の一つだ。")
  (wait)
  (text-reset 1)
  (text "［ライル］もっとも、生きた脳の研究だけあって、どの国でも極秘　　　　　で行われているから、一般人には想像もつかない事だが　　　　　ね。")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "［合成音］ココハドコダ・・・俺ハドウシテ動ケナイ・・・？")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "［ライル］物が見えるのか？")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "［合成音］ボヤケテイル・・・男ガ二人、俺ヲ見テイル・・・。")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "［ライル］お前さんの名前は？")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "［合成音］キース・・・キース・ヘンダーソン。")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "［ライル］脳が新しいせいか、意識がハッキリしているようだな。")
  (wait)
  (text-reset 1)
  (text "［ライル］どうしてこの研究所に来た？")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "［合成音］・・・・ダメダ、言エナイ・・・俺ハ一人ノ男ヲ殺セト　　　　　頼マレタ・・・。")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "［ライル］誰に頼まれたんだ？")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "［合成音］・・・ダメダ、言エナイ・・・。")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "［コール］ダニエルか、ダニエルに頼まれたんだな！？")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "［合成音］ヤメロ・・・ヤメロ！　来ルナ！！")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 193) 0 "B:¥GPA¥DB131C.GPA")
  ((cmd 197) 1 0)
  (text "［ライル］マズい、禁断症状だ！！")
  (wait)
  (text-reset 1)
  ((cmd 197) 1 15)
  (text "［合成音］ガアアアア・・・！！")
  (wait)
  (text-reset 1)
  ((cmd 197) 1 0)
  ((cmd 196) 0 0)
  ((cmd 196) 0 1)
  (delay 4 0)
  ((cmd 196) 0 2)
  (delay 4 0)
  ((cmd 196) 0 1)
  (delay 4 0)
  ((cmd 196) 0 0)
  (delay 12 0)
  ((cmd 196) 0 1)
  (delay 12 0)
  ((cmd 196) 0 2)
  (delay 8 0)
  ((cmd 196) 0 1)
  (delay 4 0)
  ((cmd 196) 0 2)
  (delay 8 0)
  ((cmd 196) 0 1)
  (delay 10 0)
  ((cmd 196) 0 2)
  (delay 4 0)
  ((cmd 196) 0 3)
  (delay 4 0)
  ((cmd 196) 0 4)
  (delay 4 0)
  ((cmd 196) 0 5)
  (text "［コール］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB129.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB130.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC")
  (image-mem 1 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text
   "［ライル］これで判っただろう・・・あとはコール、君次第だ。　　　　　　シーラを治療するためには、蘇生薬を一番よく知ってい　　　　　るクーガー博士に聞くしかない。")
  (wait)
  (text-reset 1)
  (text
   "［ライル］だが、君の言ってた通りクーガー博士の脳には、君の撃　　　　　った弾丸の傷が入っている。ましてや、埋められてから　　　　　かなりの時間が経っている。")
  (wait)
  (text-reset 1)
  (text "［ライル］彼の意識はまだ残っているのかどうかも判らないが、私　　　　　の調べによると、彼の脳には今でも正常な脳波が感じら　　　　　れた。")
  (wait)
  (text-reset 1)
  (text "［ライル］うまく行く可能性の方が少ないが、やってみる価値はあ　　　　　ると思うのだ。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］こればかりは、コールを無視して我々の判断で実行　　　　　　　する訳にもいかない。")
  (wait)
  (text-reset 1)
  (text
   "［ライル］コールの言ったように、クーガー博士を人間らしく死な　　　　　せてやるのもいいだろう。我々は君のやりたいようにさ　　　　　せるつもりだ。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］コール、決断をしてくれ・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］しばらく考えさせてください・・・。いくら俺でも、こ　　　　　んな事を今すぐには決められない・・・。")
  (wait)
  (text-reset 1)
  (text "［ライル］いいだろう、だがシーラがあの様子だとそんなに時間は　　　　　ない。１時間以内に答えを出してくれ。")
  (wait)
  (text-reset 1)
  (text "［コール］判りました・・・。")
  (wait)
  (text-reset 1)
  (sound '|| 2)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (mes-jump "A:¥MES¥079.MES")))