(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB043.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB044.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (str "Lisle: Cole, how was Sheila looking?")
  (wait)
  (text-reset 1)
  (str "Cole: Well, she'd already noticed the changes to her body...")
  (wait)
  (text-reset 1)
  (str "Steve: What kind of changes?")
  (wait)
  (text-reset 1)
  (str "Cole: There were purple spots on her chest. Same as the ones" 'br)
(str "I saw on the zombie woman I killed downstairs.")
  (wait)
  (text-reset 1)
  (str "Lisle: Can you describe these spots?")
  (wait)
  (text-reset 1)
  (str "Cole: There were a bunch of them, maybe a quarter- to" 'br)
(str "half-inch in diameter, on her skin, like blemishes. It was" 'br)
(str "like the reanimation serum was coming out of her skin...")
  (wait)
  (text-reset 1)
  (str "Steve: ...")
  (wait)
  (text-reset 1)
  (str "Cole: She went to the hospital in hope of a treatment, but" 'br)
(str "since they don't know anything about Purple Sky's makeup," 'br)
(str "they couldn't help her.")
  (wait)
  (text-reset 1)
  (str "Steve: So she was looking into the Purple Sky by herself?")
  (wait)
  (text-reset 1)
  (str "Cole: That's right.")
  (wait)
  (text-reset 1)
  (str "Cole: Lisle, please... Is there any way to save Sheila?")
  (wait)
  (text-reset 1)
  (str "Lisle: I'm going to guess those purple spots are the" 'br)
(str "results of the DNV developing in her blood overflowing," 'br)
(str "dissolving in her blood vessels, and releasing into her body.")
  (wait)
  (text-reset 1)
  (str "Lisle: Her body's already teeming with DNV. If we'd noticed" 'br)
(str "it a little earlier, we might have been able to contain" 'br)
(str "things somewhat.")
  (wait)
  (text-reset 1)
  (str "Cole: ...")
  (wait)
  (text-reset 1)
  (str "Lisle: With my current skill set, I can't stop the DNV" 'br)
(str "that's taking over her body.")
  (wait)
  (text-reset 1)
  (str "Cole: That's... That means...")
  (wait)
  (text-reset 1)
  (str "Lisle: But there's one person who could completely eliminate" 'br)
(str "the DNV from Sheila's body.")
  (wait)
  (text-reset 1)
  (str "Cole: W-who?! Who can help her?")
  (wait)
  (text-reset 1)
  (str "Lisle: ...")
  (wait)
  (text-reset 1)
  (str "Steve: Cole...")
  (wait)
  (text-reset 1)
  (str "Cole: Please tell us, Lyle! Steve, back me up here!")
  (wait)
  (text-reset 1)
  (str "Lisle: ...")
  (wait)
  (text-reset 1)
  (str "Lisle: The only person who can cure Sheila...is the one who" 'br)
(str "knows DNV better than anyone else on the planet.")
  (wait)
  (text-reset 1)
  (str "Lisle: Yes. Doctor Hamilton Cooger, the creator of the" 'br)
(str "reanimation serum.")
  (sound '|| 0)
  (sound '|se | 3)
  (wait)
  (text-reset 1)
  (str "Cole: That's not funny, Lisle.")
  (wait)
  (text-reset 1)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
  (sound '|| 1)
  (str "Steve: Cole... I don't think Lisle is joking.")
  (wait)
  (text-reset 1)
  (str "Cole: You know well enough a zombie killed Doc two years" 'br)
(str "ago...")
  (wait)
  (text-reset 1)
  (str "Lisle: That's correct. Like you said, he died. But if his" 'br)
(str "body still remained, without decomposing...")
  (wait)
  (text-reset 1)
  (str "Cole: Doc Cooger got bitten on the head by a zombie. He" 'br)
(str "didn't want to turn, and made me pull the trigger...")
  (wait)
  (text-reset 1)
  (str "Cole: I saw the bullet go into his head. His brain was" 'br)
(str "destroyed.")
  (wait)
  (text-reset 1)
  (str "Cole: There was no bringing him back. Besides, I wanted him" 'br)
(str "to die as a man... Not a zombie.")
  (wait)
  (text-reset 1)
  (str "Steve: But... His body is actually still alive.")
  (wait)
  (text-reset 1)
  (str "Cole: No. No way. That can't be.")
  (wait)
  (text-reset 1)
  (str "Steve: Last night, Lisle and I went to Disbell Cemetery.")
  (wait)
  (text-reset 1)
  (str "Cole: Disbell Cemetery? That explains why you were going for" 'br)
(str "a drive in the middle of the night...")
  (wait)
  (text-reset 1)
  (str "Steve: Yeah, it was us. When the incident occurred two" 'br)
(str "years ago, all the bodies in the neighboring town were" 'br)
(str "buried at Disbell. Of course, Cooger's body is there too...")
  (wait)
  (text-reset 1)
  (str "Lisle: We searched for Cooger's grave and exhumed his body." 'br)
(str "His heart had stopped, but the cells in his body... They" 'br)
(str "were still alive.")
  (wait)
  (text-reset 1)
  (str "Steve: And we managed to confirm his brainwaves... Albeit" 'br)
(str "faintly.")
  (wait)
  (text-reset 1)
  (str "Cole: That's... That means...")
  (wait)
  (text-reset 1)
  (str "Lisle: Cole, you need to come with me. You wanted to see" 'br)
(str "what was inside this room... Once you do, you'll understand.")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB129.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB130.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC")
  (image-mem 1 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (str "Steve: This is Lisle's lab. I was only allowed in here for" 'br)
(str "the first time yesterday.")
  (wait)
  (text-reset 1)
  (str "Lisle: He's ready. Look at the cylindrical glass case.")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB131.GPC")
  (image-mem 0 3)
  ((cmd 193) 0 "B:¥GPA¥DB131A.GPA")
  ((cmd 193) 1 "B:¥GPA¥DB131B.GPA")
  ((cmd 194)
   0
   "A... E... I... O...U... A... B... C... D... E... A...")
  ((cmd 194) 1 "ｱ. .........ｱ ...ｲ..ｳ.ｴ.ｵ.ｶ.ｷ.ｸ.ｹ.ｺ.ｻ.ｼ.ｽ.ｾ.ｿ.ﾀ.ﾁ..........")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (str "Cole: No. Fucking. Way.")
  (wait)
  (text-reset 1)
  (str "Lisle: This is the brain of the Bloody Fox member who" 'br)
(str "attacked you on the first floor. He'd bitten his own tongue" 'br)
(str "off in the bathroom...")
  (wait)
  (text-reset 1)
  (str "Cole: His...brain...?")
  (wait)
  (text-reset 1)
  (str "Lisle: Yes, and I'll access it now...")
  (wait)
  (text-reset 1)
  (str "Lisle: Can you hear my voice?")
  (wait)
  (text-reset 1)
  (str "Synthetic Voice: GAAA... GA GA...")
  (wait)
  (text-reset 1)
  (str "Lisle: Answer if you hear me!")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Synthetic Voice: WH...WHO... WHO IS IT... WHERE IS THIS?")
  (sound '|| 0)
  (sound '|se | 4)
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: How in the hell is this possible!?")
  (wait)
  (text-reset 1)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
  (sound '|| 1)
  (str "Lisle: It's perfectly acceptable to be shocked. This is a" 'br)
(str "medical study being performed in America, the UK, and other" 'br)
(str "countries for eight years, revolving around DNA." 'br)
  (wait)
  (text-reset 1)
  (str "Lisle: Moreover, since it involves research on a living" 'br)
(str "brain, it's conducted in secrecy in each nation, as the" 'br)
(str "general public would find it...unimaginable.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Synthetic Voice: WHERE AM I... WHY CAN'T I MOVE?")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Lisle: Can you see anything?")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Synthetic Voice: ALL A BLUR. TWO MEN LOOKING AT ME.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Lisle: What is your name?")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Synthetic Voice: KEITH. KEITH HENDERSON.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Lisle: Since your brain is fresh, your consciousness still" 'br)
(str "remains active.")
  (wait)
  (text-reset 1)
  (str "Lisle: Why did you come to the institute?")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Synthetic Voice: ...NO, I CANNOT SAY. ORDERED TO KILL A" 'br)
(str "MAN. ALONE.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Lisle: Who sent you?")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Synthetic Voice: ...I CANNOT SAY.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: Daniel... It was Daniel, wasn't it?")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Synthetic Voice: ... STOP...STOP! GET AWAY!")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 193) 0 "B:¥GPA¥DB131C.GPA")
  ((cmd 197) 1 0)
  (str "Lisle: This isn't good, it's having withdrawal symptoms--")
  (wait)
  (text-reset 1)
  ((cmd 197) 1 15)
  (str "Synthetic Voice: GAAAAAAAAAAAAA!!!")
  (wait)
  (text-reset 1)
  ((cmd 197) 1 0)
  ((cmd 196) 0 0)
  ((cmd 196) 0 1)
  (delay 4 0)
  ((cmd 196) 0 2)
  (delay 4 0)
  ((cmd 196) 0 1)
  (delay 4 0)
  ((cmd 196) 0 0)
  (delay 12 0)
  ((cmd 196) 0 1)
  (delay 12 0)
  ((cmd 196) 0 2)
  (delay 8 0)
  ((cmd 196) 0 1)
  (delay 4 0)
  ((cmd 196) 0 2)
  (delay 8 0)
  ((cmd 196) 0 1)
  (delay 10 0)
  ((cmd 196) 0 2)
  (delay 4 0)
  ((cmd 196) 0 3)
  (delay 4 0)
  ((cmd 196) 0 4)
  (delay 4 0)
  ((cmd 196) 0 5)
  (str "Cole: ...")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB129.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB130.GPC")
  (image-mem 1 3)
  (image-file "B:¥GPC¥DB071.GPC")
  (image-mem 1 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (str "Lisle: Now you understand... It's up to you now, Cole. If" 'br)				; 4 lines, waiting on Geo's shortening
(str "we're going to cure Sheila, there's nobody better to ask" 'br)
(str "than Dr. Cooger... Who knows the reanimation serum better" 'br)
(str "than anyone else.")
  (wait)
  (text-reset 1)
  (str "Lisle: But like you said, the bullet you fired is still in" 'br)
(str "Dr. Cooger's brain. And he's been...out of commission for" 'br)
(str "quite a while.")
  (wait)
  (text-reset 1)
  (str "Lisle: We don't even know if his consciousness is still" 'br)
(str "present, but according to my scans, he's still exhibiting" 'br)
(str "normal brainwave activity.")
  (wait)
  (text-reset 1)
  (str "Lisle: The odds of success are slim, but it's worth a shot.")
  (wait)
  (text-reset 1)
  (str "Steve: We have to ask you, Cole. There's no way we could" 'br)
(str "make this call.")
  (wait)
  (text-reset 1)
  (str "Lisle: Like Cole said, maybe it would be better for the" 'br)
(str "good doctor to die a natural death... We'll support your" 'br)
(str "decision either way.")
  (wait)
  (text-reset 1)
  (str "Steve: Cole... It's time to choose.")
  (wait)
  (text-reset 1)
  (str "Cole: God... I need a minute to think. I can't decide on the" 'br)
(str "spot.")
  (wait)
  (text-reset 1)
  (str "Lisle: Fair enough. Just remember that with Sheila's" 'br)
(str "condition, time isn't on our side. I'll need to know within" 'br)
(str "one hour.")
  (wait)
  (text-reset 1)
  (str "Cole: I understand...")
  (wait)
  (text-reset 1)
  (sound '|| 2)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (mes-jump "A:¥MES¥079.MES")))