; Dead of the Brain 2 (PC-98) - 079.MES
; Translated by Geometrizer
; Edited by JackDBS, commented by trentsignia
; --Description:--
; Cole goes back to his room to find Sheila waiting for him there. (IPV counter: 1)
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB101A.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)			; Hotspots and buttons defined here...
  (exec-mem 3744 1 1 80 0 0 0)							; 	MOVE button
  (exec-mem 3744 1 2 80 0 0 0)							; 	SYSTEM button
  (exec-mem 3744 1 5 37 5 54 10)						; 	Lockers
  (exec-mem 3744 1 6 20 3 27 13)						; 	Door
  (exec-mem 3744 1 7 4 12 17 15)						; 	Desk
  (exec-mem 3744 1 8 30 3 37 7)							; 	Sheila
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB101.GPC") (image-mem 0 3)
  (image-file "B:¥GPC¥DB073.GPC") (image-mem 1 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 2 23 40 238 1 2 23")
  (exec-mem 912 "C 0 40 23 18 238 1 40 23")
  (exec-mem 912 "A 1")
  (exec-mem 912 "GET 0 2 23 54 238")
  (image-file "B:¥GPC¥DB132.GPC") (image-mem 1 3)
  (exec-mem 912 "GET 1 2 23 54 238")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 15456 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_10.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_10.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 127 #f))							; Lead-in from previous MES file
        (str "Cole: Sheila...!")
        (wait)
        (text-reset 1)
        (str "Sheila: What's happening? What did Lisle tell you?")
        (wait)
        (text-reset 1)
        (str "Cole: ...")
        (set-reg 127 #t)
        (wait)
        (text-reset 1))
       (//
        (str "Cole: Sheila...!")					; Lead-in from loading game
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 128 #f))						; Lockers #1
   (str "Sheila: Cole... Stop staring off into the distance like" 'br)
   (str "that.")
   (set-reg 128 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))							; Lockers #2
   (str "Sheila: Cole, stop staring at the lockers and look at me.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 129 #f))						; Door #1
   (str "Cole: Sheila, I didn't even realize you came in.")
   (wait)
   (text-reset 1)
   (str "Sheila: The door was unlocked, so I let myself in...")
   (set-reg 129 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))							; Door #2
   (str "Cole: Ah, yeah, the door doesn't have a lock, does it...")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 130 #f))						; Desk #1
   (str "Sheila: Cole, why won't you look me in the eye?")
   (wait)
   (text-reset 1)
   (str "Cole: No, it's not like that... I'm looking at you now.")
   (wait)
   (text-reset 1)
   (str "Sheila: You've been fidgeting for a while now.")
   (set-reg 130 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))							; Desk #2
   (str "Cole: I need to stop looking at the desk, or Sheila will" 'br)
   (str "call me out.")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 131 #f))						; Sheila #1
   (str "Sheila: What exactly did Lisle tell you?")
   (wait)
   (text-reset 1)
   (str "Cole: ...")
   (wait)
   (text-reset 1)
   (str "Sheila: Cole, would you please answer me?")
   (wait)
   (text-reset 1)
   (str "Cole: ...It's not like I could understand any of their" 'br)
   (str "complicated medical terms...")
   (wait)
   (text-reset 1)
   (str "Sheila: Why? Didn't they explain it so you could understand?")
   (wait)
   (text-reset 1)
   (str "Cole: ...")
   (set-reg 131 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 132 #f))						; Sheila #2
   (str "Sheila: Come on, Cole...")
   (wait)
   (text-reset 1)
   (str "Cole: Could you leave me alone for a minute? I have a lot" 'br)
   (str "to think about...")
   (wait)
   (text-reset 1)
   (str "Sheila: What's wrong? Did something happen?")
   (wait)
   (text-reset 1)
   (str "Cole: ...")
   (wait)
   (text-reset 1)
   (str "Sheila: Cole?")
   (wait)
   (text-reset 1)
   (str "Cole: God, would you just shut up for once! I told you to" 'br)
   (str "go!")
   (wait)
   (text-reset 1)
   (str "Sheila: ...")
   (set-reg 132 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 133 #f))						; Sheila #3
   (str "Sheila: Cole... Do you hate me now because I got...sick..." 'br)
   (str "Because I'm going to turn?")
   (wait)
   (text-reset 1)
   (str "Cole: No... No, it's not like that...")
   (wait)
   (text-reset 1)
   (str "Sheila: You're lying... You've never been this cold. Never.")
   (wait)
   (text-reset 1)
   (str "Cole: ...")
   (set-reg 133 #t)
   (wait)
   (text-reset 1))
;
; 	At this point, Cole is forced to make a decision that, spoiler alert, affects the rest of the game. 
; 	You will probably want to save the game here if you want to fully explore both paths.
; 	The game sets a special flag for this ocassion: look out for register 901 in the coming scripts.
;
 (seg (? (= P 8))							; Sheila #4
   (str "Cole: ...")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 1 2 23,W 0,O 0")
   (str "Sheila: So that's why. I get it now. Lisle told you he" 'br)
   (str "couldn't cure me, right?")
   (wait)
   (text-reset 1)
   (str "Cole: No, that's not it at all!")
   (wait)
   (text-reset 1)
   (str "Sheila: Yes it is! And when I turn, you're going to have to" 'br)
   (str "shoot me, right? No matter how much you love me, you have" 'br)
   (str "to put a bullet in me to stop the inevitable, don't you?")
   (wait)
   (text-reset 1)
   (str "Cole: I fucking told you to SHUT UP!")
   (wait)
   (text-reset 1)
   (exec-mem 14544 2 2)
   (exec-mem 912 "PUT 0 2 23,W 0,O 0")
   (exec-mem 912 "EXIT")
   (str "Cole: ...")
   (wait)
   (text-reset 1)
   (str "Sheila: ...I'm sorry.")
   (wait)
   (text-reset 1)
   (str "Sheila: I won't bother you anymore, Cole.")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB101.GPC") (image-mem 0 3)
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (str "Cole: God... This is just a mess... I'm a fucking mess...")
   (wait)
   (text-reset 1)
   (str "Cole: I get how you feel, Sheila... You know that if I" 'br)
   (str "could cure you, I would...")
   (wait)
   (text-reset 1)
   (str "Cole: ...But to do that, we have to revive Doc. And the" 'br)
   (str "chances aren't good that he's still all there...")
   (wait)
   (text-reset 1)
   (str "Cole: And if we can't revive him or something awful" 'br)
   (str "happens, I couldn't face you, or Doc, with a clear" 'br)
   (str "conscience...")
   (wait)
   (text-reset 1)
   (str "Cole: Even before, I never would have thought of doing" 'br)
   (str "something as cruel as reviving Doc...")
   (wait)
   (text-reset 1)
   (str "Cole: But if things keep going the way they are... Just" 'br)
   (str "like Sheila said, I might have to pull the trigger on her.")
   (wait)
   (text-reset 1)
   (str "Cole: I feel like Doc would forgive me if I revived him to" 'br)
   (str "save you, Sheila... But I'll regret it for the rest of my" 'br)
   (str "life.")
   (wait)
   (text-reset 1)
   (str "Cole: T")								; Trying something here; if Cole loops back to the start he should say "But the hour's [...]"
   (loop
    (str "he hour's almost up, I have to make my decision.")			; Choice loop starts here
    (menu1 20 337 44 337
     (</> (/ (str "Let Doc rest in peace.")) (/ (str "     Revive Doc...    "))))
    (text-reset 1)
    (str "Cole: ...I'm going to ")
    (branch-var S
     (</>
      (/ (str "let Doc rest in peace. I've made my" 'br) (set-reg 134 #t))
      (/ (str "revive Doc. I've made my ") (set-reg 135 #t))))
    (str "decision.")
    (wait)
    (text-reset 1)
    (str "Cole: ...Is this really the right path forward?")			; Confirm choice; saying no kicks you back to the start
    (menu1 25 337 37 337 (</> (/ (str "   Yes!   ")) (/ (str "   No...  "))))
    (text-reset 1)
    (if (</>
         (//
          (? (= S 1))
          (nop@)
          (set-reg 134 #f)
          (set-reg 135 #f)
          (set-var S 2))))
    (if (</>
         (//
          (? (= S 0) (= 134 #t))						; Don't revive
          (str "Cole: I can't revive Doc. We're not certain whether or not" 'br)
          (str "Sheila will become a zombie. I've got a heart, and it won't" 'br)
          (str "let me bring my best friend back from the dead.")
          (wait)
          (text-reset 1)
          (str "Cole: I'm going to go tell Lisle and the others.")
          (wait)
          (text-reset 1)
          (sound '|| 2)
          (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
          (nop@)
          (set-reg 901 #f)
          (mes-jump "A:¥MES¥080.MES"))
         (//
          (? (= S 0) (= 135 #t))						; Revive
          (str "Cole: I'm going to revive Doc's brain to help save Sheila." 'br)
          (str "Though I'll owe Doc more than I can ever repay, I need to" 'br)
          (str "save Sheila at any cost.")
          (wait)
          (text-reset 1)
          (str "Cole: And even if things go horribly wrong, what matters is" 'br)
          (str "we tried.")
          (wait)
          (text-reset 1)
          (str "Cole: I'm going to go tell Lisle and the others.")
          (wait)
          (text-reset 1)
          (sound '|| 2)
          (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
          (nop@)
          (set-reg 901 #t)
          (mes-jump "A:¥MES¥080.MES"))
         (//
          (? (= S 2))								; Unsure
          (str "Cole: No, no. I can't do it... I don't know if I can make" 'br)
          (str "that choice.")
          (wait)
          (text-reset 1)
	  (str "Cole: But t"))))))
 (seg (? (= P 2))								; SYSTEM
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25 317  39 317  53 317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))