(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB134.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 4 3 20 7)
  (exec-mem 3744 1 6 21 10 41 12)
  (exec-mem 3744 1 7 34 5 40 7)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB134.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (if (</>
       (//
        (? (= 108 #f))
        (sound '|| 0)
        (if (</>
             (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_13.USO"))
             (// (sound '|| "A:¥USO_D¥BR2_13.USO"))))
        (sound '|| 1))))
  (if (</>
       (// (? (= 109 #f)) (text "Cole: A graveyard at night is pretty creepy.") (set-reg 109 #t))
       (// (text "Steve: Doctor Cooger's grave is a bit further down the path."))))
  (wait)
  (text-reset 1)
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 110 #f))
   (text "Cole: This cemetery is unmaintained and overgrown, with weeds everywhere.")
   (set-reg 110 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 111 #f))
   (text "Cole: I don't see any undead hiding in the thickets.")
   (wait)
   (text-reset 1)
   (text "Steve: Well, if the undead were smart enough to set traps, I would have been eaten a long time ago.")
   (set-reg 111 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "Steve: I think we can rest easy. When we came here yesterday, we didn't see a single zombie.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 112 #f))
   (text "Steve: Doctor Cooger's grave is about a 10-minute walk from here.")
   (wait)
   (text-reset 1)
   (text "Cole: In the incident two years ago, I imagine there were a ton of casualties... Did they dig graves for all of them?")
   (wait)
   (text-reset 1)
   (text "Steve: Well, for the people they could identify, anyway.")
   (wait)
   (text-reset 1)
   (text "Cole: The government must have paid a pretty penny getting everyone in the ground, huh.")
   (wait)
   (text-reset 1)
   (text "Steve: It was all over the news. There was plenty of financial aid from other countries.")
   (wait)
   (text-reset 1)
   (text "Cole: I remember seeing that... But nobody was able to pinpoint who was ultimately responsible for the destruction.")
   (wait)
   (text-reset 1)
   (text "Steve: Although it was an unexplained catastrophe, a lot of countries were happy to have America owe them a favor.")
   (wait)
   (text-reset 1)
   (text "Cole: I see...")
   (set-reg 112 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 113 #f))
   (text "Cole: A graveyard at night is pretty creepy.")
   (wait)
   (text-reset 1)
   (text "Steve: Having seen actual undead people, I wouldn't be surprised at all if ghosts were flying around right now.")
   (set-reg 113 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "Cole: *Huff* *Puff* We've walked quite a while...")
   (wait)
   (text-reset 1)
   (text "Steve: We're almost at Dr. Cooger's grave.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 114 #f))
   (text "Cole: There are so many tombstones...")
   (wait)
   (text-reset 1)
   (text "Steve: Disbell Cemetery is one of the larger graveyards around, but after burying all the corpses from the incident, it's getting a little cramped.")
   (wait)
   (text-reset 1)
   (text "Cole: How many bodies were there total?")
   (wait)
   (text-reset 1)
   (text "Steve: About 600... And 800 couldn't be identified.")
   (set-reg 114 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 115 #f))
   (text "Cole: Even though there's no caretaker and the cemetery isn't maintained well, there are still some neat tombstones to see.")
   (wait)
   (text-reset 1)
   (text "Steve: People would come here to check out the historical graves.")
   (set-reg 115 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 116 #f))
   (text "Steve: The thought of everyone buried here being reanimated gives me the chills.")
   (wait)
   (text-reset 1)
   (text "Cole: Don't say that, man.")
   (wait)
   (text-reset 1)
   (text "Steve: Come on, Cole, you've fought enough zombies that that sorta talk shouldn't bother you.")
   (set-reg 116 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "Cole: You did a good job finding Doc's grave in this sea of markers.")
   (wait)
   (text-reset 1)
   (text "Steve: Yeah, it was hard to track him down.")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 113 #t) (= 114 #t))
   (exec-mem 6064 2 1)
   (text "Steve: Cole, we're here... Doc's grave is right there.")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (exec-mem 6064 3)
   (image-file "B:¥GPC¥DB135.GPC")
   (image-mem 0 3)
   (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
   (exec-mem 912 "C 0 2 23 40 238 1 2 23")
   (exec-mem 912 "C 0 40 23 18 238 1 40 23")
   (exec-mem 912 "A 1")
   (image-file "B:¥GPC¥DB135.GPC")
   (image-mem 0 3)
   (image-file "B:¥GPC¥DB136.GPC")
   (image-mem 1 3)
   (exec-mem 912 "GET 0 2 23 54 238")
   (exec-mem 912 "A 0,S 0")
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (text "Cole: Ahhh... We finally made it.")
   (wait)
   (text-reset 1)
   (text "Cole: 1933-1992, Hamilton Cooger.")
   (wait)
   (text-reset 1)
   (text "Cole: That's definitely Doc's grave... But I never thought he'd be buried in the cemetery in the town I moved to.")
   (wait)
   (text-reset 1)
   (text "Steve: Cole, you've got the shovel... Start digging.")
   (wait)
   (text-reset 1)
   (text "Cole: Huh? Me?")
   (wait)
   (text-reset 1)
   (text "Steve: If not you, who else?")
   (wait)
   (text-reset 1)
   (text "Cole: ...Understood.")
   (wait)
   (text-reset 1)
   (text "*Dig...dig...dig...dig...*")
   (wait)
   (text-reset 1)
   (text "*Dig...dig...dig...dig...*")
   (wait)
   (text-reset 1)
   (text "*Dig...dig...dig...dig...*")
   (wait)
   (text-reset 1)
   (text "Cole: Geez... Are we done yet?")
   (wait)
   (text-reset 1)
   (text "Steve: Halfway there.")
   (wait)
   (text-reset 1)
   (text "Cole: *Dig...dig...dig...dig...* Steve, you're really tough on your people...")
   (wait)
   (text-reset 1)
   (text "*Dig...dig...dig...dig...*")
   (wait)
   (text-reset 1)
   (text "*Dig...dig...dig...dig...*")
   (wait)
   (text-reset 1)
   (text "*Dig...dig...dig...dig...*")
   (wait)
   (text-reset 1)
   (text "*Dig...dig...dig...dig...*")
   (wait)
   (text-reset 1)
   (text "*Thunk*")
   (wait)
   (text-reset 1)
   (text "Cole: Ah, I hit something.")
   (wait)
   (text-reset 1)
   (text "Steve: Good work, let me pull it out.")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 0 2 23,W 0,O 0")
   (exec-mem 912 "EXIT")
   (text "Cole: So Doc's in there...")
   (wait)
   (text-reset 1)
   (text "Steve: Want to take a look? His lower body's charred black, though.")
   (wait)
   (text-reset 1)
   (text "Cole: His lower body?")
   (wait)
   (text-reset 1)
   (text "Cole: Oh, right... The hotel where Doc died had been blown up by one of Ghoul's subordinates...")
   (wait)
   (text-reset 1)
   (text "Steve: Hence the burn damage.")
   (wait)
   (text-reset 1)
   (text "Cole: Even with the charring... Is his brain okay?")
   (wait)
   (text-reset 1)
   (text "Steve: Well, that's up to Dr. Lisle to determine.")
   (wait)
   (text-reset 1)
   (text "Cole: If we reanimate Doc, we can get rid of the DNV in Sheila's body. But we've got to put our trust in Lisle first.")
   (wait)
   (text-reset 1)
   (text "Cole: Steve, we've gotta rush Doc's body back to the lab.")
   (wait)
   (text-reset 1)
   (text "Steve: ...")
   (wait)
   (text-reset 1)
   (text "Cole: Steve...")
   (wait)
   (text-reset 1)
   (text "Steve: Ack... Gack...")
   (wait)
   (text-reset 1)
   (sound '|| 2)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB137.GPC")
   (image-mem 0 3)
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (sound '|| 0)
   (if (</>
        (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_06.USO"))
        (// (sound '|| "A:¥USO_D¥BR2_06.USO"))))
   (sound '|| 1)
   (text "Cole: Steve!!!")
   (wait)
   (text-reset 1)
   (text "Zombie: GAAAAAA!!!!")
   (wait)
   (text-reset 1)
   (text "Cole: Fucker!")
   (wait)
   (text-reset 1)
   (text "Steve: Don't shoot! The gunfire might attract others!")
   (wait)
   (text-reset 1)
   (text "Cole: What should I do?")
   (wait)
   (text-reset 1)
   (text "Zombie: GYIIIIIAAAAAA!!!")
   (wait)
   (text-reset 1)
   (text "Steve: Sonofabitch...!")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB138.GPC")
   (image-mem 0 3)
   (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
   (exec-mem 912 "C 0 2 23 40 238 1 2 23")
   (exec-mem 912 "C 0 40 23 18 238 1 40 23")
   (exec-mem 912 "A 1")
   (image-file "B:¥GPC¥DB138.GPC")
   (image-mem 0 3)
   (exec-mem 912 "GET 0 2 23 54 238")
   (image-file "B:¥GPC¥DB138A.GPC")
   (image-mem 0 3)
   (exec-mem 912 "GET 1 2 23 54 238")
   (image-file "B:¥GPC¥DB138B.GPC")
   (image-mem 0 3)
   (exec-mem 912 "GET 2 2 23 54 238")
   (image-file "B:¥GPC¥DB138D.GPC")
   (image-mem 0 3)
   (exec-mem 912 "GET 3 2 23 54 238")
   (exec-mem 912 "A 0,S 0")
   (load-mem "A:¥CLM¥DB138.CLM" 32768)
   (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 3 2 0)
   (exec-mem 3744 1 5 32 8 36 13)
   (exec-mem 3744 1 6 15 5 19 7)
   (exec-mem 3744 1 7 19 3 22 5)
   (exec-mem 3744 1 8 22 6 29 9)
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (text "Steve: Cole...now!")
   (wait)
   (text-reset 1)
   (image-file "A:¥GPC¥COUNTER.GPC")
   (image-mem 0 0)
   (exec-mem 15728 0 0 1 5 0 1)
   (exec-mem 15728 1 0 0 0 0 "Z")
   (exec-mem 15728 2 1)
   (exec-mem 15456 0)
   (exec-mem 14544 2 0)
   (exec-mem 15728 3)
   (exec-mem 3744 3 "P" 32768)
   (exec-mem 15728 4)
   (image-file "A:¥GPC¥DB_FRM3.GPC")
   (image-mem 0 0)
   (if (</>
        (//
         (? (= P 5) (= Z 2))
         (text "Cole: Drop dead!")
         (wait)
         (text-reset 1)
         (exec-mem 912 "PUT 0 2 23,W 5,O 0")
         (exec-mem 912 "PUT 1 2 23,W 5,O 0")
         (exec-mem 912 "PUT 2 2 23,W 5,O 0")
         (sound '|se | 2)
         (exec-mem 912 "PUT 3 2 23,W 5,O 0")
         (exec-mem 912 "EXIT")
         (text "Zombie: GYAAAAAA...")
         (wait)
         (text-reset 1)
         (text "Steve: *Gasp* *Gasp* Well played.")
         (wait)
         (text-reset 1)
         (text "Cole: Ha...ha  ha ha ha...")
         (wait)
         (text-reset 1)
         (text "Steve: It's dangerous here. We've gotta get the body back to the lab.")
         (wait)
         (text-reset 1)
         (sound '|| 2)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (mes-jump "A:¥MES¥083.MES"))
        (//
         (text "Cole: Shit! No!")
         (wait)
         (text-reset 1)
         (text "Zombie: GURAAAAAAA!!!")
         (wait)
         (text-reset 1)
         (text "Steve: Cole, look out!")
         (wait)
         (text-reset 1)
         (text "Cole: Shit!!!! SHIT!!!! AAAGHHHHH!")
         (wait)
         (text-reset 1)
         (sound '|| 0)
         (sound '|se | 10)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (text "　　　　　　　　　　ＧＡＭＥ　ＯＶＥＲ")
         (menu1 32 337 48 337 (</> (/ (str "CONTINUE")) (/ (str "GAME END"))))
         (text-reset 1)
         (branch-var
          S
          (</>
           (/
            (exec-mem 9920 0 6 6 113 64 0)
            (nop@)
            (set-reg 108 #f)
            (mes-jump "A:¥MES¥082.MES"))
           (/
            (text "　　　　　ＮＩＧＨＴＭＡＲＥ　ＣＯＬＬＥＣＴＩＯＮ" 'br)
            (text "　　　　　　ＤＥＡＤ　ＯＦ　ＴＨＥ　ＢＲＡＩＮⅡ" 'br)
            (text "　　　　　　　　　　　ＧＡＭＥ　ＥＮＤ")
            (loop (wait)))))))))
 (seg (? (= P 2))
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (nop@) (set-reg 108 #f) (flag-save 1))
        (/ (nop@) (set-reg 108 #f) (flag-save 2))
        (/ (nop@) (set-reg 108 #f) (flag-save 3))
        (/ (nop@) (set-reg 108 #f) (flag-save 4))
        (/ (nop@) (set-reg 108 #f) (flag-save 5))
        (/ (nop@) (set-reg 108 #f) (flag-save 6))
        (/ (nop@) (set-reg 108 #f) (flag-save 7))
        (/ (nop@) (set-reg 108 #f) (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))