(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  ((cmd 209) 0 5)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (image-file "B:¥GPC¥DB139.GPC")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_10.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_10.USO"))))
  (sound '|| 1)
  (text "Sheila: Cole... I'm sorry I said what I did...")
  (wait)
  (text-reset 1)
  (text "Sheila: I've seen so many people become zombies, and when it was my turn, I got scared...")
  (wait)
  (text-reset 1)
  (text "Sheila: And I wound up saying that to Cole, even though I knew he was worried about me...")
  (wait)
  (text-reset 1)
  (text "Sheila: My body reacted to the Purple Sky, and suddenly I felt like I was alone in the world...")
  (wait)
  (text-reset 1)
  (text "Sheila: Everyone was trying so hard to stay alive, and I was the only one. Thinking about that, I felt lonely...")
  (wait)
  (text-reset 1)
  (text "Sheila: I'm sure Cole knows how I feel. But I did such a terrible thing to him.")
  (wait)
  (text-reset 1)
  (text "Sheila: But I won't say anything else to you, Cole, so you won't worry about me...")
  (wait)
  (text-reset 1)
  (text "Sheila: Save this world with your own hands, Cole...")
  (wait)
  (text-reset 1)
  (text "Sheila: I won't get in your way anymore.")
  (wait)
  (text-reset 1)
  (text "Sheila: And then finally...")
  (wait)
  (text-reset 1)
  (text "Sheila: Once this incident is resolved, I'll keep apologizing...")
  (wait)
  (text-reset 1)
  (text "Sheila: Until Cole finally forgives me...")
  (wait)
  (text-reset 1)
  ((cmd 209) 0 5)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  ((cmd 209) 1 5)
  (mes-jump "A:¥MES¥084.MES"))
 (seg*))