(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  ((cmd 209) 0 5)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (image-file "B:¥GPC¥DB139.GPC")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_10.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_10.USO"))))
  (sound '|| 1)
  (text "［シーラ］コール・・・あんな事言ってごめんなさい・・・")
  (wait)
  (text-reset 1)
  (text "［シーラ］私、今までたくさんの人間が死霊になる所を見てきて、　　　　　実際に自分の番が来てみたら急に怖くなった・・・")
  (wait)
  (text-reset 1)
  (text "［シーラ］・・・コールが私の事で悩んでいるのを知っているのに　　　　　私はあんな事言ってしまった・・・")
  (wait)
  (text-reset 1)
  (text "［シーラ］私、身体にパープル・スカイの反応が出て来て、急に独　　　　　りぼっちになってしまったような気がしたの・・・")
  (wait)
  (text-reset 1)
  (text "［シーラ］皆、生きようと頑張っているのに私だけ・・・そんな事　　　　　を考えてたら、急に寂しくなったの・・・")
  (wait)
  (text-reset 1)
  (text "［シーラ］コールは私の気持ちを判ってくれているはず・・なのに　　　　　私はそんなコールに酷い事を・・・")
  (wait)
  (text-reset 1)
  (text "［シーラ］もうコールには何も言わないから、私の事は心配しない　　　　　で・・・")
  (wait)
  (text-reset 1)
  (text "［シーラ］コールの手でこの世界を死霊から救って・・・")
  (wait)
  (text-reset 1)
  (text "［シーラ］もうコールの邪魔はしないから・・・")
  (wait)
  (text-reset 1)
  (text "［シーラ］・・・そして・・・")
  (wait)
  (text-reset 1)
  (text "［シーラ］この事件が解決したら・・・私はずっとコールに謝り続　　　　　けるから・・・")
  (wait)
  (text-reset 1)
  (text "［シーラ］コールが許してくれるまで・・・ずっと・・・")
  (wait)
  (text-reset 1)
  ((cmd 209) 0 5)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  ((cmd 209) 1 5)
  (mes-jump "A:¥MES¥084.MES"))
 (seg*))