(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB140.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 7 10 18 14)
  (exec-mem 3744 1 6 17 2 23 9)
  (exec-mem 3744 1 7 51 4 54 7)
  (exec-mem 3744 1 8 25 4 37 10)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB108.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB140.GPC")
  (image-mem 1 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 121 #t) (= 149 #t) (= 137 #t))
        (text "［キャサリン］コール・・・。")
        (wait)
        (text-reset 1)
        (text "［コール］どうした？")
        (wait)
        (text-reset 1)
        (text "［キャサリン］そういえば廊下で私とすれちがった時、いつもは明　　　　　　　るく微笑んでくれてたのに、少し違って見えたの。")
        (wait)
        (text-reset 1)
        (text "［コール］どんな風に？")
        (wait)
        (text-reset 1)
        (text "［キャサリン］なんだか険しい表情で・・・私が挨拶しても何も言　　　　　　　わないで出て行ったのよ。")
        (wait)
        (text-reset 1)
        (text "［コール］ライルさんに聞いたんだが、スティーブさんは多分また　　　　　街にでも行ったんじゃないかって・・・。")
        (wait)
        (text-reset 1)
        (text "［キャサリン］街へ行く様子とは違ってたわ。")
        (wait)
        (text-reset 1)
        (text "［コール］じゃあ、どこに行ったんだ？")
        (wait)
        (text-reset 1)
        (text "［キャサリン］コール、スティーブさんの様子はどうだったの？")
        (wait)
        (text-reset 1)
        (text "［コール］様子と言ってもなぁ・・・普段と同じだったし・・。")
        (wait)
        (text-reset 1)
        (text "［キャサリン］何か思い出して。")
        (wait)
        (text-reset 1)
        (text "［コール］そう・・・そういえば、研究所で３人で話している時に　　　　　一時、言葉がつまっていた事があったな・・・。")
        (wait)
        (text-reset 1)
        (loop
         (text "［キャサリン］スティーブさんの様子が変だったのは、どんな話題　　　　　　　で？")
         (wait)
         (text-reset 1)
         (menu1
          22
          298
          46
          298
          22
          318
          46
          318
          22
          338
          46
          338
          (</>
           (/ (text "脳の蘇生についての話題"))
           (/ (text "俺の射撃についての話題"))
           (/ (text "パープル・スカイの話題"))
           (/ (text "ダニエルについての話題"))
           (/ (text "女の死体についての話題"))
           (/ (text "シーラの体の変化の話題"))))
         (text-reset 1)
         (text "［コール］確か")
         (branch-var
          S
          (</>
           (/ (text "脳の蘇生についての話題"))
           (/ (text "俺の射撃についての話題"))
           (/ (text "パープル・スカイの話題"))
           (/ (text "ダニエルについての話題") (set-reg 151 #t))
           (/ (text "女の死体についての話題"))
           (/ (text "シーラの体の変化の話題"))))
         (text "が出た時だったな。")
         (wait)
         (text-reset 1)
         (text "［キャサリン］それで、スティーブさんはどんな感じだった？")
         (wait)
         (text-reset 1)
         (menu1
          22
          298
          46
          298
          22
          318
          46
          318
          22
          338
          46
          338
          (</>
           (/ (text "何か、落ち着かなかった"))
           (/ (text "急に口数が少なくなった"))
           (/ (text "呆れて物を言わなかった"))
           (/ (text "驚いて慌てて出て行った"))
           (/ (text "一言もしゃべらなかった"))
           (/ (text "怒って部屋を出て行った"))))
         (text-reset 1)
         (text "［コール］")
         (branch-var
          S
          (</>
           (/ (text "何か、落ち着かなかった") (set-reg 152 #t))
           (/ (text "急に口数が少なくなった") (set-reg 152 #t))
           (/ (text "呆れて物を言わなかった"))
           (/ (text "驚いて慌てて出て行った"))
           (/ (text "一言もしゃべらなかった"))
           (/ (text "怒って部屋を出て行った"))))
         (text "ようだったな・・・。")
         (wait)
         (text-reset 1)
         (if (</>
              (//
               (? (= 151 #t) (= 152 #t))
               (text "［キャサリン］じゃあ、彼はダニエルを？")
               (wait)
               (text-reset 1)
               (text "［コール］そんな・・・まさか・・・。")
               (wait)
               (text-reset 1)
               (text
                "［コール］たった一人で、ラゾバン製薬に行くなんて考えられない　　　　　よ・・・。それに、俺を残して行く訳がないだろ。")
               (wait)
               (text-reset 1)
               (text
                "［キャサリン］だけど、スティーブさんは自分の手で兄の敵討ちを　　　　　　　したいって前から口癖のように言ってたわ。")
               (wait)
               (text-reset 1)
               (text "［コール］危険すぎるよ、たった一人でなんて！")
               (wait)
               (text-reset 1)
               (text "［キャサリン］コール、行ってあげて！！　スティーブさん、一人　　　　　　　では無理よ！！")
               (wait)
               (text-reset 1)
               (text "［コール］わ、判った！！")
               (wait)
               (text-reset 1)
               (text "［キャサリン］待って！！")
               (wait)
               (text-reset 1)
               (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
               (image-file "B:¥GPC¥DB108.GPC")
               (image-mem 0 3)
               (image-file "B:¥GPC¥DB141.GPC")
               (image-mem 1 3)
               (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
               (text "［コール］おい、キャサ・・・")
               (wait)
               (text-reset 1)
               (text "［キャサリン］コール・・・死なないで・・・。")
               (wait)
               (text-reset 1)
               (text "［コール］・・・・・・・・・。")
               (wait)
               (text-reset 1)
               (text "［キャサリン］お願い・・・。")
               (wait)
               (text-reset 1)
               (text "［コール］キャサリン・・・。")
               (wait)
               (text-reset 1)
               (text "［コール］安心しろ、必ず戻ってくるよ。そして、蘇生薬の最後の　　　　　決着をつけてやるんだ。")
               (wait)
               (text-reset 1)
               (text "［キャサリン］約束・・・・。")
               (wait)
               (text-reset 1)
               (text "［コール］ああ・・・約束しよう。")
               (wait)
               (text-reset 1)
               (text "［キャサリン］シーラのためにも・・・")
               (wait)
               (text-reset 1)
               (text "［コール］お、おいキャサリ・・・")
               (wait)
               (text-reset 1)
               (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
               (image-file "B:¥GPC¥DB070.GPC")
               (image-mem 1 3)
               (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
               (text "［コール］キャサリンの奴、シーラの身体の事を知っていたのか？")
               (wait)
               (text-reset 1)
               (text "［コール］・・・・・・・・・。")
               (wait)
               (text-reset 1)
               (text "［コール］よし、最後の戦いだ。必ずダニエルを仕留めてやる！！")
               (wait)
               (text-reset 1)
               (sound '|| 2)
               (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
               (mes-jump "A:¥MES¥089.MES"))
              (//
               (text "［コール］ちょっと違うかな・・・。")
               (wait)
               (text-reset 1)
               (text "［キャサリン］コール、よく思い出して。")
               (wait)
               (text-reset 1)
               (text "［コール］もう一度、聞いてくれるか？")
               (set-reg 151 #f)
               (set-reg 152 #f)
               (wait)
               (text-reset 1))))))
       (//
        (? (= 139 #f))
        (text "［キャサリン］コール、シーラと喧嘩したの？")
        (wait)
        (text-reset 1)
        (text "［コール］あ、ああ・・・ちょっとね。")
        (set-reg 139 #t)
        (wait)
        (text-reset 1))
       (// (text "［キャサリン］いらっしゃい、コール。") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 140 #f))
   (text "［キャサリン］コール、疲れているの？")
   (wait)
   (text-reset 1)
   (text "［コール］え？")
   (wait)
   (text-reset 1)
   (text "［キャサリン］ベッドばかり見てるから・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］いや、俺の部屋のベッドは寝心地が悪いからね。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］このベッド使っていいわよ。")
   (wait)
   (text-reset 1)
   (text "［コール］いや、いいんだ。まだ眠くないしね。")
   (set-reg 140 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 141 #f))
   (text "［キャサリン］ここのベッドはよく眠れるわ。")
   (wait)
   (text-reset 1)
   (text "［コール］俺の部屋のベッドにはトラップが仕掛けてあるからな。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］トラップ？")
   (wait)
   (text-reset 1)
   (text "［コール］寝返りをうつと机の角に頭をぶつけるんだよ。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］フフフ、コールは寝相が悪いのね。")
   (set-reg 141 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "［キャサリン］コール、ベッドばかり見て疲れてるんじゃないの？")
   (wait)
   (text-reset 1)
   (text "［コール］いや、そんな事はないと思うけど・・・。")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 142 #f))
   (text "［コール］窓は開けないの？")
   (wait)
   (text-reset 1)
   (text "［キャサリン］え？　寒くないの？")
   (wait)
   (text-reset 1)
   (text "［コール］いや、たまには空気を入れ換えた方がいいと思ってさ。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］空気の入れ換えは、起きた時にやったわ。")
   (set-reg 142 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 143 #f))
   (text "［キャサリン］街の方では、まだ燃えている所があるみたいね。")
   (wait)
   (text-reset 1)
   (text "［コール］ガソリンスタンドのような燃料を扱うところは、一度で　　　　　も火が点いたらなかなか消えないだろうな。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］消防車呼ぶ？")
   (wait)
   (text-reset 1)
   (text "［コール］その前に電話が通じないよ。")
   (set-reg 143 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "［コール］街の方では、未だに点々と白い煙が上がっている所があ　　　　　るな。")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 144 #f))
   (text "［キャサリン］新年はどこで過ごす？")
   (wait)
   (text-reset 1)
   (text "［コール］そうだなあ・・・カナダにでも行きたいね。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］いいなぁ・・・。")
   (set-reg 144 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 145 #f))
   (text "［コール］もう今年も終わりなんだよな・・・。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］ねえ・・・来年になったら、シーラと正式に結婚す　　　　　　　るんでしょ？")
   (wait)
   (text-reset 1)
   (text "［コール］そうだな・・・。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］・・・・・・・・・。")
   (set-reg 145 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "［コール］なんかマズい雰囲気だな。あまりカレンダーは見ないよ　　　　　うにしよう。")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 146 #f))
   (text "［キャサリン］シーラとどうして喧嘩したの？")
   (wait)
   (text-reset 1)
   (text "［コール］いや、大した事じゃないよ。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］言えない？")
   (wait)
   (text-reset 1)
   (text "［コール］まあね・・・。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］なによ・・・つめたいのね。")
   (set-reg 146 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 147 #f))
   (text "［キャサリン］教えて。")
   (wait)
   (text-reset 1)
   (text "［コール］何を？")
   (wait)
   (text-reset 1)
   (text "［キャサリン］もう！　シーラとの喧嘩の原因よ。")
   (wait)
   (text-reset 1)
   (text "［コール］そうだなぁ・・・意見の食い違いというか・・・。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］意見の食い違いね・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］何だよ。本当の事を言ったんだぞ。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］何故、意見の食い違いが起こるか知ってる？")
   (wait)
   (text-reset 1)
   (text "［コール］何故って・・・言われても・・・。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］どっちかがね、自分の気持ちを相手に伝えきれてい　　　　　　　ないのよ。")
   (wait)
   (text-reset 1)
   (text "［コール］伝えているつもりだけどなぁ・・・。")
   (wait)
   (text-reset 1)
   (text
    "［キャサリン］そのくらい、言わなくても判るだろうって思ってる　　　　　　　と駄目よ。それは、いくら相手の事を理解してても　　　　　　　避ける事はできないからね。")
   (wait)
   (text-reset 1)
   (text "［コール］なるほどね・・・それも一理あるよな。")
   (set-reg 147 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 148 #f))
   (text "［コール］でも、俺そんな事を今まで真剣に考えた事はないよ。")
   (wait)
   (text-reset 1)
   (text
    "［キャサリン］私はいろんな所で接客をしていたから、人間関係に　　　　　　　ついてはいろいろと学んできたわ。信じれる人か信　　　　　　　じれない人か、自分で判るまでが大変だけどね。")
   (wait)
   (text-reset 1)
   (text "［コール］人間不信になりそうな話しだな。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］コールはどうなの？")
   (wait)
   (text-reset 1)
   (text "［コール］何が？")
   (wait)
   (text-reset 1)
   (text "［キャサリン］信じれる人？")
   (wait)
   (text-reset 1)
   (text "［コール］さあね・・・。")
   (set-reg 148 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 149 #f))
   (text "［コール］ごめん、話が変わるけど・・・。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］うん、なに？")
   (wait)
   (text-reset 1)
   (text "［コール］昨日、死霊がこの研究所に来たのは知ってるよね。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］ええ。")
   (wait)
   (text-reset 1)
   (text "［コール］敵さんは俺達がここに居る事を知っているから、明日の　　　　　夜にでも場所を移した方がいいと思うんだよ。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］そうね、その方が安心よね。")
   (wait)
   (text-reset 1)
   (text "［コール］それで、今夜ミーティングをやりたいんだ。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］ミーティング？")
   (wait)
   (text-reset 1)
   (text "［コール］うん、移動するにあたってのルートとか・・・ね。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］私はいいけど・・・スティーブさんとシーラがいな　　　　　　　いわよ。")
   (wait)
   (text-reset 1)
   (if (</>
        (//
         (? (= 150 #t))
         (text "［コール］うん、シーラはどこかに居る筈なんだが、スティーブさ　　　　　んはどこかに出かけたらしいんだよな。")
         (wait)
         (text-reset 1))
        (//
         (text "［コール］え？　スティーブさんは研究室に居ると思ったけど。")
         (wait)
         (text-reset 1)
         (text "［キャサリン］ついさっき、廊下ですれ違ったわ。")
         (wait)
         (text-reset 1)
         (text "［コール］そうなんだ・・・どこに行ったんだろう。")
         (wait)
         (text-reset 1))))
   (set-reg 149 #t))
 (seg (? (= P 8) (= 150 #t))
   (text "［コール］スティーブさんが居なければ、ミーティングなんてでき　　　　　ないな。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］どこに行ったか判らないの？")
   (wait)
   (text-reset 1))
 (seg (? (= P 8))
   (text "［キャサリン］どう？　スティーブさん、研究室に居た？")
   (wait)
   (text-reset 1)
   (text "［コール］あ、まだ行ってないや・・・。")
   (wait)
   (text-reset 1))
 (seg (? (= P 1))
   (exec-mem 6064 2 1)
   (text "［コール］じゃ、これで失礼するよ。")
   (wait)
   (text-reset 1)
   (text "［キャサリン］うん、また来てね。")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (exec-mem 6064 3)
   (mes-jump "A:¥MES¥085.MES"))
 (seg (? (= P 2))
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))