(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB140.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 7 10 18 14)
  (exec-mem 3744 1 6 17 2 23 9)
  (exec-mem 3744 1 7 51 4 54 7)
  (exec-mem 3744 1 8 25 4 37 10)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB108.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB140.GPC")
  (image-mem 1 0)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 121 #t) (= 149 #t) (= 137 #t))
        (text "Catherine: Cole...")
        (wait)
        (text-reset 1)
        (text "Cole: What is it?")
        (wait)
        (text-reset 1)
        (text "Catherine: Well, Steve usually gives me a smile when he     passes by in the hallway, but this time he looked different.")
        (wait)
        (text-reset 1)
        (text "Cole: Howso?")
        (wait)
        (text-reset 1)
        (text "Catherine: He was looking pretty grim... Even when I said   hello, he left without a word.")
        (wait)
        (text-reset 1)
        (text "Cole: Lisle said Steve might have gone into town...")
        (wait)
        (text-reset 1)
        (text "Catherine: But where would he need to go?")
        (wait)
        (text-reset 1)
        (text "Cole: Catherine... How was Steve acting?")
        (wait)
        (text-reset 1)
        (text "Catherine: Well, he looked like he usually does...")
        (wait)
        (text-reset 1)
        (text "Cole: But can you remember anything strange?")
        (wait)
        (text-reset 1)
        (text "Catherine: No, nothing.")
        (wait)
        (text-reset 1)
        (text "Cole: Actually, when you mention it, when the three of us got talking at  the lab, he got tongue-tied for a moment.")
        (wait)
        (text-reset 1)
        (loop
         (text "Catherine: What topic could have spooked Steve?")
         (wait)
         (text-reset 1)
         (menu1
          22
          298
          46
          298
          22
          318
          46
          318
          22
          338
          46
          338
          (</>
           (/ (text "Doc's brain revival"))
           (/ (text "My shooting skills"))
           (/ (text "Purple Sky"))
           (/ (text "Daniel"))
           (/ (text "The woman's corpse"))
           (/ (text "Sheila's physical change"))))
         (text-reset 1)
         (text "Cole: I think ")
         (branch-var
          S
          (</>
           (/ (text "Doc's brain revival"))
           (/ (text "My shooting skills"))
           (/ (text "Purple Sky"))
           (/ (text "going after Daniel") (set-reg 151 #t))
           (/ (text "The woman's corpse"))
           (/ (text "Sheila's physical change"))))
         (text "was the topic at hand.")
         (wait)
         (text-reset 1)
         (text "Catherine: At that point, how did Steve react?")
         (wait)
         (text-reset 1)
         (menu1
          22
          298
          46
          298
          22
          318
          46
          318
          22
          338
          46
          338
          (</>
           (/ (text "He seemed uneasy."))
           (/ (text "He suddenly became quiet."))
           (/ (text "He was shocked and didn't say a word."))
           (/ (text "He was shocked and left immediately."))
           (/ (text "He didn't say a word."))
           (/ (text "He left the room angrily."))))
         (text-reset 1)
         (text "［コール］")
         (branch-var
          S
          (</>
           (/ (text "He seemed uneasy.") (set-reg 152 #t))
           (/ (text "He suddenly became quiet.") (set-reg 152 #t))
           (/ (text "He was shocked and didn't say a word."))
           (/ (text "He was shocked and left immediately."))
           (/ (text "He didn't say a word."))
           (/ (text "He left the room angrily."))))
         (text "That's what happened...")
         (wait)
         (text-reset 1)
         (if (</>
              (//
               (? (= 151 #t) (= 152 #t))
               (text "Catherine: Do you think he was going to go after Daniel?")
               (wait)
               (text-reset 1)
               (text "Cole: No... No way!")
               (wait)
               (text-reset 1)
               (text
                "Cole: I couldn't imagine him going to Razovan               Pharmaceuticals all by himself... There's no way he'd leave me behind.")
               (wait)
               (text-reset 1)
               (text
                "Catherine: But Steve's been saying all along that he needs  to avenge his brother himself! It's like his catchphrase.")
               (wait)
               (text-reset 1)
               (text "Cole: It's way too dangerous for him to go alone!")
               (wait)
               (text-reset 1)
               (text "Catherine: Cole, you've gotta catch up with him! He can't doit alone!")
               (wait)
               (text-reset 1)
               (text "Cole: O-okay! I gotta go...")
               (wait)
               (text-reset 1)
               (text "Catherine: Wait!")
               (wait)
               (text-reset 1)
               (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
               (image-file "B:¥GPC¥DB108.GPC")
               (image-mem 0 3)
               (image-file "B:¥GPC¥DB141.GPC")
               (image-mem 1 3)
               (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
               (text "Cole: What is it, Cath--")
               (wait)
               (text-reset 1)
               (text "Catherine: Cole... Don't you die on me.")
               (wait)
               (text-reset 1)
               (text "Cole: ...")
               (wait)
               (text-reset 1)
               (text "Catherine: Please...")
               (wait)
               (text-reset 1)
               (text "Cole: Catherine...")
               (wait)
               (text-reset 1)
               (text "Cole: Don't worry, I'll be back in one piece. And I'll stop the reanimation serum once and for all.")
               (wait)
               (text-reset 1)
               (text "Catherine: Promise me.")
               (wait)
               (text-reset 1)
               (text "Cole: I promise.")
               (wait)
               (text-reset 1)
               (text "Catherine: And promise for Sheila.")
               (wait)
               (text-reset 1)
               (text "Cole: Hey, Cathy...")
               (wait)
               (text-reset 1)
               (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
               (image-file "B:¥GPC¥DB070.GPC")
               (image-mem 1 3)
               (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
               (text "Cole: Did you know about Sheila's condition?")
               (wait)
               (text-reset 1)
               (text "Cole: ...")
               (wait)
               (text-reset 1)
               (text "Cole: Okay, this is where it comes to an end. I'm taking    down Daniel!")
               (wait)
               (text-reset 1)
               (sound '|| 2)
               (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
               (mes-jump "A:¥MES¥089.MES"))
              (//
               (text "Cole: Maybe... Maybe that's not quite right...")
               (wait)
               (text-reset 1)
               (text "Catherine: Cole, remember for me.")
               (wait)
               (text-reset 1)
               (text "Cole: Will you listen to me again?")
               (set-reg 151 #f)
               (set-reg 152 #f)
               (wait)
               (text-reset 1))))))
       (//
        (? (= 139 #f))
        (text "Catherine: Cole, did you have a fight with Sheila?")
        (wait)
        (text-reset 1)
        (text "Cole: Ah... Yeah, a little one.")
        (set-reg 139 #t)
        (wait)
        (text-reset 1))
       (// (text "Catherine: Welcome, Cole.") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (seg-call)))
 (seg (? (= P 5) (= 140 #f))
   (text "Catherine: Cole, are you tired?")
   (wait)
   (text-reset 1)
   (text "Cole: Whuh?")
   (wait)
   (text-reset 1)
   (text "Catherine: It's because you keep looking at my bed.")
   (wait)
   (text-reset 1)
   (text "Cole: No, it's just that the bed in MY room sucks.")
   (wait)
   (text-reset 1)
   (text "Catherine: You can use this one.")
   (wait)
   (text-reset 1)
   (text "Cole: Nah, it's fine. I'm not sleepy at all.")
   (set-reg 140 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 141 #f))
   (text "Catherine: You'll sleep real well in this bed.")
   (wait)
   (text-reset 1)
   (text "Cole: The bed in my room has traps around it.")
   (wait)
   (text-reset 1)
   (text "Catherine: Traps?")
   (wait)
   (text-reset 1)
   (text "Cole: When I roll over, I bonk my head on the edge of the   desk.")
   (wait)
   (text-reset 1)
   (text "Catherine: Cole, you really do toss and turn.")
   (set-reg 141 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "Catherine: Cole, aren't you getting worn out from all this  constant bed examination?")
   (wait)
   (text-reset 1)
   (text "Cole: No no, it's not like that...")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 142 #f))
   (text "Cole: Aren't you going to open the window?")
   (wait)
   (text-reset 1)
   (text "Catherine: Huh? Isn't it cold?")
   (wait)
   (text-reset 1)
   (text "Cole: No, I just think it's good to get some fresh air once in a while.")
   (wait)
   (text-reset 1)
   (text "Catherine: I already aired out the room when I woke up.")
   (set-reg 142 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 143 #f))
   (text "Catherine: It still smells like there are places burning    downtown.")
   (wait)
   (text-reset 1)
   (text "Cole: Flammable places like gas stations are hard to        extinguish once they go up.")
   (wait)
   (text-reset 1)
   (text "Catherine: Should we call the fire department?")
   (wait)
   (text-reset 1)
   (text "Cole: I don't think calls are going through.")
   (set-reg 143 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "Cole: Downtown, I can see spots where white smoke is        billowing.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 144 #f))
   (text "Catherine: Where do you want to spend the new year?")
   (wait)
   (text-reset 1)
   (text "Cole: Hmm... I'd like to go to Canada.")
   (wait)
   (text-reset 1)
   (text "Catherine: That sounds nice, eh?")
   (set-reg 144 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 145 #f))
   (text "Cole: The year's almost over, huh.")
   (wait)
   (text-reset 1)
   (text "Catherine: Hey, when you ring in the new year, you're gonna marry Sheila officially, right?")
   (wait)
   (text-reset 1)
   (text "Cole: Yeah, that's right.")
   (wait)
   (text-reset 1)
   (text "Catherine: ...")
   (set-reg 145 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "Cole: I don't like this vibe, I'd better stop staring at thecalendar.")
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 146 #f))
   (text "Catherine: Why did you fight with Sheila?")
   (wait)
   (text-reset 1)
   (text "Cole: I wasn't... Well, it wasn't anything serious.")
   (wait)
   (text-reset 1)
   (text "Catherine: Won't you tell me?")
   (wait)
   (text-reset 1)
   (text "Cole: No...?")
   (wait)
   (text-reset 1)
   (text "Catherine: Man, you're cold, Cole.")
   (set-reg 146 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 147 #f))
   (text "Catherine: Tell me.")
   (wait)
   (text-reset 1)
   (text "Cole: Tell you what?")
   (wait)
   (text-reset 1)
   (text "Catherine: Fucking come on! I'm asking why you were fightingwith Sheila!")
   (wait)
   (text-reset 1)
   (text "Cole: Well... I guess it was a difference of opinion.")
   (wait)
   (text-reset 1)
   (text "Catherine: A difference of opinion.")
   (wait)
   (text-reset 1)
   (text "Cole: Is that enough? I'm telling you the truth.")
   (wait)
   (text-reset 1)
   (text "Catherine: Do you know why people have differences of       opinion?")
   (wait)
   (text-reset 1)
   (text "Cole: Fine. Why don't you tell me?")
   (wait)
   (text-reset 1)
   (text "Catherine: It's because one of the two didn't communicate   their feelings.")
   (wait)
   (text-reset 1)
   (text "Cole: Maybe they think they are, though--")
   (wait)
   (text-reset 1)
   (text
    "Catherine: You just assume the other person understands you without having to say it. You assume that, no matter how    much you think you know them.")
   (wait)
   (text-reset 1)
   (text "Cole: Okay, okay. It's a valid point.")
   (set-reg 147 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 148 #f))
   (text "Cole: But I've never thought about it that seriously before.")
   (wait)
   (text-reset 1)
   (text
    "Catherine: I've worked in a ton of different jobs, so I knowa lot about how people communicate. It's hard to know for   yourself if you can trust someone.")
   (wait)
   (text-reset 1)
   (text "Cole: That's the kind of thing that makes me not want to    trust people.")
   (wait)
   (text-reset 1)
   (text "Catherine: What about you, Cole?")
   (wait)
   (text-reset 1)
   (text "Cole: What about me?")
   (wait)
   (text-reset 1)
   (text "Catherine: Who can you trust?")
   (wait)
   (text-reset 1)
   (text "Cole: I...don't know.")
   (set-reg 148 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 8) (= 149 #f))
   (text "Cole: Sorry, not to change the topic, but...")
   (wait)
   (text-reset 1)
   (text "Catherine: Go ahead and change it.")
   (wait)
   (text-reset 1)
   (text "Cole: You know that a zombie got into the lab yesterday,    right?")
   (wait)
   (text-reset 1)
   (text "Catherine: Yeah.")
   (wait)
   (text-reset 1)
   (text "Cole: Since our enemies know that we're in here, I think we should relocate... Maybe as soon as tomorrow night.")
   (wait)
   (text-reset 1)
   (text "Catherine: We'd be better off.")
   (wait)
   (text-reset 1)
   (text "Cole: We should have a meeting tonight.")
   (wait)
   (text-reset 1)
   (text "Catherine: A meeting?")
   (wait)
   (text-reset 1)
   (text "Cole: Yeah, about where we should relocate to.")
   (wait)
   (text-reset 1)
   (text "Catherine: I'm okay with that, but you Steve and Sheila     aren't here.")
   (wait)
   (text-reset 1)
   (if (</>
        (//
         (? (= 150 #t))
         (text "Cole: Well, we can find Sheila, but Steve's out.")
         (wait)
         (text-reset 1))
        (//
         (text "Cole: Huh? I thought Steve was in the lab.")
         (wait)
         (text-reset 1)
         (text "Catherine: I just passed by him in the hallway.")
         (wait)
         (text-reset 1)
         (text "Cole: Is that so... I wonder where he was off to.")
         (wait)
         (text-reset 1))))
   (set-reg 149 #t))
 (seg (? (= P 8) (= 150 #t))
   (text "Cole: Without Steve we can't have a meeting...")
   (wait)
   (text-reset 1)
   (text "Catherine: Do you know where he went?")
   (wait)
   (text-reset 1))
 (seg (? (= P 8))
   (text "Catherine: Hmm, was Steve in the lab?")
   (wait)
   (text-reset 1)
   (text "Cole: Oh, I haven't checked there yet.")
   (wait)
   (text-reset 1))
 (seg (? (= P 1))
   (exec-mem 6064 2 1)
   (text "Cole: Okay, I've got to get going.")
   (wait)
   (text-reset 1)
   (text "Catherine: Okay, don't be a stranger.")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (exec-mem 6064 3)
   (mes-jump "A:¥MES¥085.MES"))
 (seg (? (= P 2))
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))