(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB150.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 7 7 14 13)
  (exec-mem 3744 1 6 33 11 40 14)
  (exec-mem 3744 1 7 20 5 33 8)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB150.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (if (</>
       (//
        (? (= 158 #f))
        (sound '|| 0)
        (if (</>
             (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
             (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
        (sound '|| 1))))
  (if (</>
       (//
        (? (= 190 #t) (= 185 #t) (= 170 #t))
        (text "［　男　］ようこそ、ラゾバンへ。")
        (wait)
        (text-reset 1)
        (text "［コール］！？")
        (wait)
        (text-reset 1)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (image-file "B:¥GPC¥DB151.GPC")
        (image-mem 0 3)
        (sound '|| 0)
        (if (</>
             (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_04.USO"))
             (// (sound '|| "A:¥USO_D¥BR2_04.USO"))))
        (sound '|| 1)
        (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
        (text "［コール］ダニエルか！？")
        (wait)
        (text-reset 1)
        (text "［ダニエル］コール、お前と会うのは２回目になるかな。")
        (wait)
        (text-reset 1)
        (text "［コール］２回目だと？　冗談じゃないぜ、お前と会うのはこれで　　　　　最初で最後だ！！")
        (wait)
        (text-reset 1)
        (text "［ダニエル］おっと、１歩でも動けば身体が蜂の巣になるぞ。")
        (wait)
        (text-reset 1)
        (text "［ダニエル］それに、私はお前の女のマンションで一度会っている　　　　　　のだよ。覚えているかな・・・。")
        (wait)
        (text-reset 1)
        (text "［コール］シーラのマンションだと！？")
        (wait)
        (text-reset 1)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (image-file "B:¥GPC¥DB047.GPC")
        (image-mem 0 3)
        (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
        (text "［コール］そうか、あの時すれ違ったのは貴様だったのか！？")
        (wait)
        (text-reset 1)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (image-file "B:¥GPC¥DB151.GPC")
        (image-mem 0 3)
        (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
        (exec-mem 912 "C 0 2 23 40 238 1 2 23")
        (exec-mem 912 "C 0 40 23 18 238 1 40 23")
        (exec-mem 912 "A 1")
        (image-file "B:¥GPC¥DB152.GPC")
        (image-mem 0 3)
        (exec-mem 912 "GET 0 2 23 54 238")
        (exec-mem 912 "A 0,S 0")
        (exec-mem 15456 0)
        ((cmd 193) 0 "B:¥GPA¥DB152A.GPA")
        ((cmd 193) 1 "B:¥GPA¥DB152B.GPA")
        (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
        (text "［コール］パープル・スカイを作ったのはお前か！？")
        (wait)
        (text-reset 1)
        (text "［ダニエル］その通り、パープル・スカイは数々の実験をくり返し　　　　　　て作り上げたドラッグだ。")
        (wait)
        (text-reset 1)
        (text "［コール］隣の部屋にあった死体もその実験に使ったんだな！？")
        (wait)
        (text-reset 1)
        (text "［ダニエル］そうだ、蘇生薬の実験には人体実験は欠かせないので　　　　　　な。")
        (wait)
        (text-reset 1)
        (text "［コール］蘇生薬をどこで手に入れたんだ！？")
        (wait)
        (text-reset 1)
        (text "［ダニエル］蘇生薬を直に発見したのは私ではない。")
        (wait)
        (text-reset 1)
        (text "［コール］何！？　じゃあ、一体誰が！？")
        (wait)
        (text-reset 1)
        (text "［ダニエル］蘇生薬に直接関っているのはジル様だ。")
        (wait)
        (text-reset 1)
        (text "［コール］ジル！？　ジルとは誰だ！？")
        (wait)
        (text-reset 1)
        (text
         "［ダニエル］ジル様を知らないのか？　これは驚いたな。まあ、ピ　　　　　　レインのライルに聞いてみれば判るだろうが、些か遅　　　　　　かったようだがな・・・。")
        (wait)
        (text-reset 1)
        (text "［コール］どういう意味だ！？")
        (wait)
        (text-reset 1)
        (text
         "［ダニエル］今頃は、あの研究所にいる人間は一人も残っていない　　　　　　という事だ。何百体もの死霊の餌食になっているだろ　　　　　　う。")
        (wait)
        (text-reset 1)
        (text "［コール］なんだと！？　研究所にはシーラの他にもキャサリンが　　　　　いるんだぞ！！")
        (wait)
        (text-reset 1)
        (text "［ダニエル］ほう・・・もうとっくに死霊に喰われたと思っていた　　　　　　が、お前達の所に居たのか。")
        (wait)
        (text-reset 1)
        (text "［コール］なに！？")
        (wait)
        (text-reset 1)
        (text "［ダニエル］なら、私とあの女の事はもう聞いているだろう。")
        (wait)
        (text-reset 1)
        (text "［コール］ああ、お前が義父だったという話しだな。それにお前は　　　　　キャサリンに暴行を・・・。")
        (wait)
        (text-reset 1)
        (text
         "［ダニエル］あの女、なかなかいい身体をしているだろう？　今で　　　　　　も忘れられなくてな。私はあの女が死霊に喰われる前　　　　　　に、ブラッディフォックスにさらわせようとした。")
        (wait)
        (text-reset 1)
        (text
         "［ダニエル］だが、意外にも死霊の繁殖が早かったためか、連中は　　　　　　ここには戻って来なかった。まあ、そんな事は私にす　　　　　　れば、小さな楽しみが一つ減ったようなものだよ。")
        (wait)
        (text-reset 1)
        (text "［ダニエル］おとなしくピレインに居ればいいものを、スティーブ　　　　　　の後を追ってここに来たのは失敗だったようだな。")
        (wait)
        (text-reset 1)
        (text "［コール］スティーブさんをどうした！？")
        (wait)
        (text-reset 1)
        (text
         "［ダニエル］フフフ、心配しなくともまだ椅子に縛り付けてある。　　　　　　もっとも、お前を殺した後に増殖したＤＮＶを打ち込　　　　　　んでやるがな。")
        (wait)
        (text-reset 1)
        (text "［コール］待て、どうして俺達が研究所にいると・・・？")
        (wait)
        (text-reset 1)
        (text
         "［ダニエル］お前達の行動は、ブラッディフォックスを通じて全て　　　　　　判っているよ。既に一人送り込んであるが、どうやら　　　　　　お前達に始末されたようだがな。")
        (wait)
        (text-reset 1)
        (text
         "［ダニエル］君の恋人であるシーラにも困ったものだ。薬を打たれ　　　　　　たのにも関らず、パープル・スカイの秘密を探ろうと　　　　　　ノコノコここに向かおうとしていたんだからな。")
        (wait)
        (text-reset 1)
        (text "［コール］シーラの部屋を荒らしたのも・・・。")
        (wait)
        (text-reset 1)
        (text
         "［ダニエル］そう、私だよ。そして、ブラッディフォックスに１０　　　　　　日あまり保存しておいたパープル・スカイを打たせた　　　　　　のもな。")
        (wait)
        (text-reset 1)
        (text "［ダニエル］だが、あの女は自分の身体の変化に気付き、パープル　　　　　　スカイの情報を色々な所から聞き出していた。")
        (wait)
        (text-reset 1)
        (text
         "［ダニエル］私は自分の身を恐れてあの女の部屋を荒らし、手を引　　　　　　かせようと思った。だが、手を引かすどころか、あの　　　　　　女はここラゾバン製薬へ来ようとしていた。")
        (wait)
        (text-reset 1)
        (text
         "［ダニエル］だから私は余計な事は後にまわし、街に死霊を放した　　　　　　のだ。少し時期が早かったが、それも邪魔なお前達を　　　　　　追い込むために仕組んだものだ。")
        (wait)
        (text-reset 1)
        (text "［コール］追い込むだと！？")
        (wait)
        (text-reset 1)
        (text
         "［ダニエル］街に死霊を放す事で、お前達を一ヶ所に集める事がで　　　　　　きる。必ずお前達が安全な場所に避難するという事を　　　　　　最初から読んでいたのだよ。")
        (wait)
        (text-reset 1)
        (text "［コール］最初から俺達を殺すつもりで・・・。")
        (wait)
        (text-reset 1)
        (text
         "［ダニエル］やっと気付いたか。蘇生薬の秘密を知っている君達が　　　　　　生きていると、この先、必ず私の邪魔をすると判って　　　　　　いたからな。")
        (wait)
        (text-reset 1)
        (text "［コール］ブラッディフォックスに、パープル・スカイを流したの　　　　　も俺をおびき寄せるためか！？")
        (wait)
        (text-reset 1)
        (text
         "［ダニエル］ああ。そうすれば、あの女はともかくお前だけでも飛　　　　　　び付いてくると睨んでいた。だが、お前の見ていない　　　　　　所でただパープル・スカイを流しただけではだめだ。")
        (wait)
        (text-reset 1)
        (text "［ダニエル］だから、その着火点としてお前のアパートの前で、友　　　　　　達２人に犠牲になってもらったという訳だよ。")
        (wait)
        (text-reset 1)
        (text "［コール］テリーとリンを殺したのがこいつだったのか・・・。")
        (wait)
        (text-reset 1)
        (text "［ダニエル］フフフフ・・・今頃気付いても遅いがね。")
        (wait)
        (text-reset 1)
        (text "［コール］くっそぉ・・・。")
        (wait)
        (text-reset 1)
        (text
         "［ダニエル］お前達が死ねば、私は気ままに研究に打ち込める。次　　　　　　のターゲットはモンタナ州だ。モンタナは広いからな　　　　　　・・・どのくらい死霊が繁殖するか楽しみだよ。")
        (wait)
        (text-reset 1)
        (text "［ダニエル］聞いているだろう？　モンタナに何があるか。")
        (wait)
        (text-reset 1)
        (text "［コール］貴様・・・。")
        (wait)
        (text-reset 1)
        (text
         "［ダニエル］おっと・・・少し長話しをしてしまったようだ。そろ　　　　　　そろ死んでもらうよ。クーガーがあの世でお前を待っ　　　　　　ているぞ。")
        (wait)
        (text-reset 1)
        (text "［コール］くそぉ！！")
        (wait)
        (text-reset 1)
        (exec-mem 912 "PUT 0 2 23,W 0,O 0")
        (exec-mem 14544 2 0)
        (exec-mem 912 "EXIT")
        (sound '|| 0)
        (if (</>
             (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_05.USO"))
             (// (sound '|| "A:¥USO_D¥BR2_05.USO"))))
        (sound '|| 1)
        (text "［コール］！！")
        (wait)
        (text-reset 1)
        (text "［スティーブ］コール！！")
        (wait)
        (text-reset 1)
        (load-mem "A:¥CLM¥DB152.CLM" 32768)
        (image-file "A:¥GPC¥COUNTER.GPC")
        (image-mem 0 0)
        (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 3 2 0)
        (exec-mem 3744 1 1 80 0 0 0)
        (exec-mem 3744 1 5 33 8 38 10)
        (exec-mem 15728 0 0 0 3 0 1)
        (exec-mem 15728 1 0 0 0 0 "Z")
        (exec-mem 15728 2 0)
        (exec-mem 15456 0)
        (exec-mem 14544 2 0)
        (exec-mem 15728 3)
        (exec-mem 3744 3 "P" 32768)
        (exec-mem 15728 4)
        (image-file "A:¥GPC¥DB_FRM3.GPC")
        (image-mem 0 0)
        (if (</>
             (//
              (? (= Z 2) (= P 5))
              (text "［コール］くたばれっ！！")
              (wait)
              (text-reset 1)
              ((cmd 196) 1 0)
              ((cmd 196) 1 1)
              (delay 4 0)
              (sound '|se | 13)
              ((cmd 196) 1 2)
              (delay 4 0)
              ((cmd 196) 1 3)
              (delay 4 0)
              ((cmd 196) 1 4)
              (sound '|| 2)
              (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
              (image-file "B:¥GPC¥DB153.GPC")
              (image-mem 0 3)
              ((cmd 193) 0 "B:¥GPA¥DB153.GPA")
              (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
              (if (</>
                   (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_09.USO"))
                   (// (sound '|| "A:¥USO_D¥BR2_09.USO"))))
              (sound '|| 1)
              (text "［スティーブ］長話しがすぎたようだな、ダニエル。")
              (wait)
              (text-reset 1)
              (text "［コール］スティーブさん！！")
              (wait)
              (text-reset 1)
              (text "［ダニエル］あれだけ固く縛って椅子に括り付けたのに、どうして　　　　　　脱出が！？")
              (wait)
              (text-reset 1)
              (text "［スティーブ］後ろのポケットをよく調べるんだったな。あんな縄　　　　　　　ぐらい、ライター１つでどうにでもなる。")
              (wait)
              (text-reset 1)
              (text "［ダニエル］クッ・・・・・・。")
              (wait)
              (text-reset 1)
              (text "［コール］スティーブさん、こいつも蘇生薬を・・・。")
              (wait)
              (text-reset 1)
              (text "［スティーブ］・・・らしいな。コールの撃った弾丸は心臓を直撃　　　　　　　している筈だ。")
              (wait)
              (text-reset 1)
              (text "［ダニエル］フッ・・・お前達にしてみれば、俺を殺す事は簡単だ　　　　　　ろう。")
              (wait)
              (text-reset 1)
              (text "［コール］ああ、その頭をフッ飛ばせばいいんだからな。そして、　　　　　パープル・スカイともおさらばだ。")
              (wait)
              (text-reset 1)
              (text
               "［ダニエル］フフフフ・・・私が居なくなればパープル・スカイを　　　　　　製造する人間は居なくなる。だが、私が居なくとも、　　　　　　蘇生薬だけは製造され続けているのだ。")
              (wait)
              (text-reset 1)
              (sound '|| 0)
              (if (</>
                   (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_13.USO"))
                   (// (sound '|| "A:¥USO_D¥BR2_13.USO"))))
              (sound '|| 1)
              (text "［コール］！？")
              (wait)
              (text-reset 1)
              (text "［ダニエル］今、こうして話しているだけでも何百ｃｃの蘇生薬が　　　　　　生まれているのだ。")
              (wait)
              (text-reset 1)
              (text "［スティーブ］なんだと！？")
              (wait)
              (text-reset 1)
              (text "［コール］蘇生薬はドク以外の人間には作れない筈だ！！　そんな　　　　　事があるわけがないっ！！")
              (wait)
              (text-reset 1)
              (text "［ダニエル］ジル様は天才だ・・・クーガーなど足元にも及ばん。")
              (wait)
              (text-reset 1)
              (text "［コール］ジルとは何者だ！？")
              (wait)
              (text-reset 1)
              (text "［ダニエル］お前達の息の根を止められるのはジル様達だけ")
              ((cmd 196) 0 0)
              ((cmd 196) 0 1)
              (delay 2 0)
              (sound '|se | 13)
              ((cmd 196) 0 2)
              (delay 2 0)
              ((cmd 196) 0 3)
              (delay 4 0)
              ((cmd 196) 0 4)
              (delay 8 0)
              ((cmd 196) 0 5)
              (delay 8 0)
              ((cmd 196) 0 6)
              (text "・・。")
              (wait)
              (text-reset 1)
              (text "［コール］スティーブさん！！")
              (wait)
              (text-reset 1)
              (text
               "［スティーブ］こいつの脳は完全に侵されている。これ以上、こい　　　　　　　つに付き合ったところで、ジルという奴の事は話さ　　　　　　　んだろう。")
              (wait)
              (text-reset 1)
              (text
               "［スティーブ］それと、パープル・スカイを二度と作る事ができな　　　　　　　いよう、私はこの建物の階ごとに時限爆弾をセット　　　　　　　してある。")
              (wait)
              (text-reset 1)
              (text "［コール］爆薬を！？")
              (wait)
              (text-reset 1)
              (text "［スティーブ］ああ、だから早めに脱出するんだ。")
              (wait)
              (text-reset 1)
              (text "［コール］スティーブさん、ダニエルが研究所に死霊を送り込んだ　　　　　そうです。")
              (wait)
              (text-reset 1)
              (text "［スティーブ］なに！？　だが、研究所にはシャッターが・・・。")
              (wait)
              (text-reset 1)
              (text "［コール］俺達を一気に殺そうと、何百体もの死霊を研究所に送り　　　　　込んだって・・・。")
              (wait)
              (text-reset 1)
              (text "［スティーブ］クソッ！！　なんて事だ！！")
              (wait)
              (text-reset 1)
              (text "［スティーブ］こんな所でグズグズしてられないぞ！！　早く研究　　　　　　　所に戻るんだ！！")
              (wait)
              (text-reset 1)
              (text "［コール］急ぎましょう！！")
              (wait)
              (text-reset 1)
              (sound '|| 2)
              (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
              (sound '|| 0)
              (sound '|se | 11)
              (delay 50 0)
              (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
              (image-file "B:¥GPC¥DB042.GPC")
              (image-mem 0 3)
              (image-file "B:¥GPC¥DB154.GPC")
              (image-mem 1 3)
              (exec-mem 256 0 4 2 3)
              (exec-mem 256 1 0 0 0)
              (exec-mem 256 2 6 4 5)
              (exec-mem 256 3 0 11 0)
              (exec-mem 256 4 0 7 0)
              (exec-mem 256 5 2 0 1)
              (exec-mem 256 6 5 1 3)
              (exec-mem 256 7 4 0 0)
              (exec-mem 256 8 7 1 5)
              (exec-mem 256 9 8 4 5)
              (exec-mem 256 10 9 0 0)
              (exec-mem 256 11 5 0 0)
              (exec-mem 256 12 3 0 0)
              (exec-mem 256 13 8 0 5)
              (exec-mem 256 14 4 0 3)
              (exec-mem 256 15 12 8 9)
              (sound '|| 0)
              (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
              (text "［コール］スティーブさん！！　研究所の入口が！！")
              (wait)
              (text-reset 1)
              (text "［スティーブ］クソッ、シャッターが壊されてる！！")
              (wait)
              (text-reset 1)
              (text "［コール］２階に行きましょう！！")
              (wait)
              (text-reset 1)
              (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
              (mes-jump "A:¥MES¥094.MES"))
             (//
              (text "［コール］くたばれっ！！")
              (wait)
              (text-reset 1)
              ((cmd 196) 0 0)
              (sound '|se | 13)
              (delay 3)
              ((cmd 196) 0 1)
              (sound '|se | 13)
              (delay 1)
              ((cmd 196) 0 2)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 1)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 2)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 1)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 2)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 1)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 2)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 1)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 0)
              (exec-mem 14544 2 2)
              (text "［コール］ぐあああああっ！！")
              (wait)
              (text-reset 1)
              (text "［スティーブ］コール！！")
              (wait)
              (text-reset 1)
              (sound '|| 0)
              (sound '|se | 10)
              (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
              (text "　　　　　　　　　　ＧＡＭＥ　ＯＶＥＲ")
              (menu1
               32
               337
               48
               337
               (</> (/ (str "CONTINUE")) (/ (str "GAME END"))))
              (text-reset 1)
              (branch-var
               S
               (</>
                (/
                 (exec-mem 9920 0 6 6 113 64 0)
                 (nop@)
                 (set-reg 158 #f)
                 (mes-jump "A:¥MES¥091.MES"))
                (/
                 (text "　　　　　ＮＩＧＨＴＭＡＲＥ　ＣＯＬＬＥＣＴＩＯＮ" 'br)
                 (text "　　　　　　ＤＥＡＤ　ＯＦ　ＴＨＥ　ＢＲＡＩＮⅡ" 'br)
                 (text "　　　　　　　　　　　ＧＡＭＥ　ＥＮＤ")
                 (loop (wait)))))))))
       (//
        (? (= 186 #f))
        (text "［コール］ダンボールがたくさん転がっている。ここは倉庫のよう　　　　　だな。")
        (set-reg 186 #t)
        (wait)
        (text-reset 1))
       (//
        (text "［コール］相変わらず、この部屋は薄暗い。目が慣れるまでに少し　　　　　時間がかかるな。")
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (text-reset 1) (seg-call)))
 (seg (? (= P 5) (= 187 #f))
   (text "［コール］ダンボールが積まれているな。どれも空っぽのようだ。")
   (set-reg 187 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5)) (text "［コール］空っぽのダンボールだ。他の物と変わりはない。") (wait) (text-reset 1))
 (seg (? (= P 6) (= 188 #f))
   (text "［コール］ダンボールがたくさん転がっているな。どれを調べても　　　　　中身の入っているものはない。")
   (set-reg 188 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 189 #f))
   (text "［コール］箱の表面には何も書かれていないな。")
   (set-reg 189 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "［コール］多分、何かの薬品が送られて来た時に使用されていたダ　　　　　ンボールだろう。")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 190 #f))
   (text "［コール］見回したところ、この部屋に人の姿はないようだな。")
   (set-reg 190 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 191 #f))
   (text "［コール］奥の壁は暗くて見えないな。")
   (set-reg 191 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "［コール］コンクリ打ちぱなしの壁だ。この部屋は、ただの倉庫に　　　　　使われているようだな。")
   (wait)
   (text-reset 1))
 (seg (? (= P 1))
   (exec-mem 6064 2 1)
   (text "［コール］よし、廊下に出よう。")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (exec-mem 6064 3)
   (nop@)
   (set-reg 158 #t)
   (mes-jump "A:¥MES¥091.MES"))
 (seg (? (= P 2))
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (nop@) (set-reg 158 #f) (flag-save 1))
        (/ (nop@) (set-reg 158 #f) (flag-save 2))
        (/ (nop@) (set-reg 158 #f) (flag-save 3))
        (/ (nop@) (set-reg 158 #f) (flag-save 4))
        (/ (nop@) (set-reg 158 #f) (flag-save 5))
        (/ (nop@) (set-reg 158 #f) (flag-save 6))
        (/ (nop@) (set-reg 158 #f) (flag-save 7))
        (/ (nop@) (set-reg 158 #f) (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))