(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB150.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 7 7 14 13)
  (exec-mem 3744 1 6 33 11 40 14)
  (exec-mem 3744 1 7 20 5 33 8)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB150.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (if (</>
       (//
        (? (= 158 #f))
        (sound '|| 0)
        (if (</>
             (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
             (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
        (sound '|| 1))))
  (if (</>
       (//
        (? (= 190 #t) (= 185 #t) (= 170 #t))
        (text "Man: Welcome...to Razovan.")
        (wait)
        (text-reset 1)
        (text "Cole: !?!")
        (wait)
        (text-reset 1)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (image-file "B:¥GPC¥DB151.GPC")
        (image-mem 0 3)
        (sound '|| 0)
        (if (</>
             (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_04.USO"))
             (// (sound '|| "A:¥USO_D¥BR2_04.USO"))))
        (sound '|| 1)
        (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
        (text "Cole: Daniel!?")
        (wait)
        (text-reset 1)
        (text "Daniel: Cole, I believe this is our second meeting...")
        (wait)
        (text-reset 1)
        (text "Cole: The second? Like hell... This is gonna be the first   and last time we meet.")
        (wait)
        (text-reset 1)
        (text "Daniel: Ah-ah-ah. Take one step, and I'll ventilate you.")
        (wait)
        (text-reset 1)
        (text "Daniel: Come to think of it, I already met your woman at    your apartment. Do you remember?")
        (wait)
        (text-reset 1)
        (text "Cole: Wait, at Sheila's apartment?")
        (wait)
        (text-reset 1)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (image-file "B:¥GPC¥DB047.GPC")
        (image-mem 0 3)
        (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
        (text "Cole: So it was you who walked by...")
        (wait)
        (text-reset 1)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (image-file "B:¥GPC¥DB151.GPC")
        (image-mem 0 3)
        (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
        (exec-mem 912 "C 0 2 23 40 238 1 2 23")
        (exec-mem 912 "C 0 40 23 18 238 1 40 23")
        (exec-mem 912 "A 1")
        (image-file "B:¥GPC¥DB152.GPC")
        (image-mem 0 3)
        (exec-mem 912 "GET 0 2 23 54 238")
        (exec-mem 912 "A 0,S 0")
        (exec-mem 15456 0)
        ((cmd 193) 0 "B:¥GPA¥DB152A.GPA")
        ((cmd 193) 1 "B:¥GPA¥DB152B.GPA")
        (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
        (text "Cole: Are you the one who made Purple Sky!?")
        (wait)
        (text-reset 1)
        (text "Daniel: Precisely. I developed Purple Sky over countless    experiments.")
        (wait)
        (text-reset 1)
        (text "Cole: I bet you used the corpse in the room next door for   your experimentation too, didn't you?")
        (wait)
        (text-reset 1)
        (text "Daniel: I certainly did. Human testing is a necessity for   reanimation serum experiments.")
        (wait)
        (text-reset 1)
        (text "Cole: But the serum... Where did you get it?")
        (wait)
        (text-reset 1)
        (text "Daniel: Well, it certainly wasn't me who found it, but...")
        (wait)
        (text-reset 1)
        (text "Cole: What!? Then who did?")
        (wait)
        (text-reset 1)
        (text "Daniel: If you're looking for the person directly involved  with the serum, that would be Jill.")
        (wait)
        (text-reset 1)
        (text "Cole: Jill? Who the hell is Jill!?")
        (wait)
        (text-reset 1)
        (text
         "Daniel: Oh, you haven't heard of Jill? That's a surprise. Ifonly you'd thought to ask Dr. Lisle... But it's a little late   for that now.")
        (wait)
        (text-reset 1)
        (text "Cole: What's that supposed to mean?")
        (wait)
        (text-reset 1)
        (text
         "Daniel: By now, there isn't a single soul left in that lab. They've all become zombie fodder.")
        (wait)
        (text-reset 1)
        (text "Cole: What!? It's not just Sheila in that lab... Catherine  is in there too!")
        (wait)
        (text-reset 1)
        (text "Daniel: Oho, interesting. I figured the zombies had killed  her, but she managed to join your little party.")
        (wait)
        (text-reset 1)
        (text "Cole: What!?")
        (wait)
        (text-reset 1)
        (text "Daniel: I suppose you've already heard about a certain      matter between that girl and myself.")
        (wait)
        (text-reset 1)
        (text "Cole: A matter involving Catherine being assaulted by her   stepfather?")
        (wait)
        (text-reset 1)
        (text
         "Daniel: A fine figure of a woman, wasn't she? I still can't forget her, even now. I tried to get Bloody Fox to abduct   her before the zombies arrived, but...")
        (wait)
        (text-reset 1)
        (text
         "Daniel: The zombies multiplied faster than I assumed. That'sone less pleasure in life, I suppose...")
        (wait)
        (text-reset 1)
        (text "Daniel: You should have stayed at Perain and waited for the inevitable. Following Steve here was a mistake.")
        (wait)
        (text-reset 1)
        (text "Cole: What did you do to him?")
        (wait)
        (text-reset 1)
        (text
         "Daniel: Oh, don't you worry, he's still tied up to his      chair. But once I kill you, I'll inject him with fine, aged DNV.")
        (wait)
        (text-reset 1)
        (text "Cole: Wait... How did you know we were at the lab?")
        (wait)
        (text-reset 1)
        (text
         "Daniel: Bloody Fox keeps me informed of your every move. I  sent in one foot soldier, but alas, you took care of him...")
        (wait)
        (text-reset 1)
        (text
         "Daniel: And your beloved Sheila is another problem. Even    after being dosed with Purple Sky, she headed there, trying to uncover its secrets...")
        (wait)
        (text-reset 1)
        (text "Cole: So you were the one who ransacked her room?")
        (wait)
        (text-reset 1)
        (text
         "Daniel: Of course it was me. And I was the one who had      Bloody Fox inject her with the Purple Sky that I'd matured  for over ten days.")
        (wait)
        (text-reset 1)
        (text "Daniel: But then she started seeing the changes to her body,and started prying for information on Purple Sky from any and  all sources...")
        (wait)
        (text-reset 1)
        (text
         "Daniel: I was worried she might find out about my           involvement, so I broke into her room to make her back off. But instead, she headed to Razovan.")
        (wait)
        (text-reset 1)
        (text
         "Daniel: That's why I put a halt to any further intervention and loosed the zombies on the city. Perhaps hasty, but      orchestrated to drive you fools into a corner.")
        (wait)
        (text-reset 1)
        (text "Cole: A corner, huh?")
        (wait)
        (text-reset 1)
        (text
         "Daniel: By unleashing the undead into the city, I was able  to force you all into one place. I knew right from the startthat you’d all seek refuge in a safe spot.")
        (wait)
        (text-reset 1)
        (text "Cole: So you planned on killing us from the start.")
        (wait)
        (text-reset 1)
        (text
         "Daniel: Very adept. I realized that as long as anyone who   knew the secret of the reanimation serum survived, they'd bein my way.")
        (wait)
        (text-reset 1)
        (text "Cole: So you released Purple Sky through Bloody Fox just to lure us in?")
        (wait)
        (text-reset 1)
        (text
         "Daniel: Very perceptive. I figured that you'd come running, even if the girl didn't. But merely getting Purple Sky out  there wouldn't be enough...")
        (wait)
        (text-reset 1)
        (text "Daniel: I figured there'd need to be a spark. Like your two friends, brutally murdered outside your apartment!")
        (wait)
        (text-reset 1)
        (text "Cole: You! You're the one who killed Terry and Lynn...?")
        (wait)
        (text-reset 1)
        (text "Daniel: Haw haw haw! Cole makes another deduction hours     after the train's left the station.")
        (wait)
        (text-reset 1)
        (text "Cole: God damn you...")
        (wait)
        (text-reset 1)
        (text
         "Daniel: Once you're all dead, I can fully devote myself to  my research. My next target is Montana. A vast, open land...I can't wait to see how quickly the zombies multiply there.")
        (wait)
        (text-reset 1)
        (text "Daniel: You've heard about Montana, haven't you? What it    holds...")
        (wait)
        (text-reset 1)
        (text "Cole: You bastard!")
        (wait)
        (text-reset 1)
        (text
         "Daniel: Ah, I do seem to have gone on far too long. It's    about time you met your end. When you see Doc Cooger in     hell, say hello for me.")
        (wait)
        (text-reset 1)
        (text "Cole: Shit!")
        (wait)
        (text-reset 1)
        (exec-mem 912 "PUT 0 2 23,W 0,O 0")
        (exec-mem 14544 2 0)
        (exec-mem 912 "EXIT")
        (sound '|| 0)
        (if (</>
             (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_05.USO"))
             (// (sound '|| "A:¥USO_D¥BR2_05.USO"))))
        (sound '|| 1)
        (text "Cole: !!")
        (wait)
        (text-reset 1)
        (text "Steve: Cole, now!")
        (wait)
        (text-reset 1)
        (load-mem "A:¥CLM¥DB152.CLM" 32768)
        (image-file "A:¥GPC¥COUNTER.GPC")
        (image-mem 0 0)
        (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 3 2 0)
        (exec-mem 3744 1 1 80 0 0 0)
        (exec-mem 3744 1 5 33 8 38 10)
        (exec-mem 15728 0 0 0 3 0 1)
        (exec-mem 15728 1 0 0 0 0 "Z")
        (exec-mem 15728 2 0)
        (exec-mem 15456 0)
        (exec-mem 14544 2 0)
        (exec-mem 15728 3)
        (exec-mem 3744 3 "P" 32768)
        (exec-mem 15728 4)
        (image-file "A:¥GPC¥DB_FRM3.GPC")
        (image-mem 0 0)
        (if (</>
             (//
              (? (= Z 2) (= P 5))
              (text "Cole: Die!")
              (wait)
              (text-reset 1)
              ((cmd 196) 1 0)
              ((cmd 196) 1 1)
              (delay 4 0)
              (sound '|se | 13)
              ((cmd 196) 1 2)
              (delay 4 0)
              ((cmd 196) 1 3)
              (delay 4 0)
              ((cmd 196) 1 4)
              (sound '|| 2)
              (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
              (image-file "B:¥GPC¥DB153.GPC")
              (image-mem 0 3)
              ((cmd 193) 0 "B:¥GPA¥DB153.GPA")
              (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
              (if (</>
                   (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_09.USO"))
                   (// (sound '|| "A:¥USO_D¥BR2_09.USO"))))
              (sound '|| 1)
              (text "Steve: Maybe next time you can monologue a little less,     Daniel.")
              (wait)
              (text-reset 1)
              (text "Cole: Steve!")
              (wait)
              (text-reset 1)
              (text "Daniel: I strapped you to that chair myself... How did you  escape?")
              (wait)
              (text-reset 1)
              (text "Steve: Shoulda patted me down. The lighter in my back pocketmade short work of those ropes.")
              (wait)
              (text-reset 1)
              (text "Daniel: Damnation...!")
              (wait)
              (text-reset 1)
              (text "Cole: Steve, this guy's taken the reanimation serum too...")
              (wait)
              (text-reset 1)
              (text "Steve: Sure looks like it. You shot him in the heart, and   he's still going.")
              (wait)
              (text-reset 1)
              (text "Daniel: Heh... I guess you won't have any trouble killing mefor real.")
              (wait)
              (text-reset 1)
              (text "Cole: You know it. We shoot you in the head, and that's the end of Purple Sky.")
              (wait)
              (text-reset 1)
              (text
               "Daniel: Heh heh... Once I'm gone, there won't be anyone elseto make Purple Sky. But even when I'm gone, the reanimation   serum will survive.")
              (wait)
              (text-reset 1)
              (sound '|| 0)
              (if (</>
                   (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_13.USO"))
                   (// (sound '|| "A:¥USO_D¥BR2_13.USO"))))
              (sound '|| 1)
              (text "Cole: !?!")
              (wait)
              (text-reset 1)
              (text "Daniel: Even as we speak, hundreds of cc's of the serum are being produced.")
              (wait)
              (text-reset 1)
              (text "Steve: What!? How!?")
              (wait)
              (text-reset 1)
              (text "Cole: That's impossible! The serum is something that only   Doc can make!")
              (wait)
              (text-reset 1)
              (text "Daniel: Jill is a genius. Far and away beyond Cooger, even.")
              (wait)
              (text-reset 1)
              (text "Cole: Who the hell is Jill!?")
              (wait)
              (text-reset 1)
              (text "Daniel: ...Jill and his people will put an end to your      miserable...lives...")
              ((cmd 196) 0 0)
              ((cmd 196) 0 1)
              (delay 2 0)
              (sound '|se | 13)
              ((cmd 196) 0 2)
              (delay 2 0)
              ((cmd 196) 0 3)
              (delay 4 0)
              ((cmd 196) 0 4)
              (delay 8 0)
              ((cmd 196) 0 5)
              (delay 8 0)
              ((cmd 196) 0 6)
              (text "...")
              (wait)
              (text-reset 1)
              (text "Cole: Steve!")
              (wait)
              (text-reset 1)
              (text
               "Steve: His brain had checked out. He wasn't going to tell uswho or where Jill is.")
              (wait)
              (text-reset 1)
              (text
               "Steve: And more importantly, to sabotage any further Purple Sky production, I've set time bombs on each floor of the    building.")
              (wait)
              (text-reset 1)
              (text "Cole: Time bombs!?")
              (wait)
              (text-reset 1)
              (text "Steve: Yeah, which is why we need to make our exit right    now.")
              (wait)
              (text-reset 1)
              (text "Cole: Steve, Daniel told me he sent zombies to Perain!")
              (wait)
              (text-reset 1)
              (text "Steve: What!? But the shutters should still be in place...")
              (wait)
              (text-reset 1)
              (text "Cole: Yeah, but he literally sent hundreds of zombies!      They'll be overrun in no time!")
              (wait)
              (text-reset 1)
              (text "Steve: Shit!")
              (wait)
              (text-reset 1)
              (text "Steve: We can't stay here a second longer! Back to the lab, now!")
              (wait)
              (text-reset 1)
              (text "Cole: Let's move!")
              (wait)
              (text-reset 1)
              (sound '|| 2)
              (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
              (sound '|| 0)
              (sound '|se | 11)
              (delay 50 0)
              (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
              (image-file "B:¥GPC¥DB042.GPC")
              (image-mem 0 3)
              (image-file "B:¥GPC¥DB154.GPC")
              (image-mem 1 3)
              (exec-mem 256 0 4 2 3)
              (exec-mem 256 1 0 0 0)
              (exec-mem 256 2 6 4 5)
              (exec-mem 256 3 0 11 0)
              (exec-mem 256 4 0 7 0)
              (exec-mem 256 5 2 0 1)
              (exec-mem 256 6 5 1 3)
              (exec-mem 256 7 4 0 0)
              (exec-mem 256 8 7 1 5)
              (exec-mem 256 9 8 4 5)
              (exec-mem 256 10 9 0 0)
              (exec-mem 256 11 5 0 0)
              (exec-mem 256 12 3 0 0)
              (exec-mem 256 13 8 0 5)
              (exec-mem 256 14 4 0 3)
              (exec-mem 256 15 12 8 9)
              (sound '|| 0)
              (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
              (text "Cole: Steve! The lab entrance!")
              (wait)
              (text-reset 1)
              (text "Steve: Shit! The shutters are gone!")
              (wait)
              (text-reset 1)
              (text "Cole: To the second floor!")
              (wait)
              (text-reset 1)
              (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
              (mes-jump "A:¥MES¥094.MES"))
             (//
              (text "Cole: Die!")
              (wait)
              (text-reset 1)
              ((cmd 196) 0 0)
              (sound '|se | 13)
              (delay 3)
              ((cmd 196) 0 1)
              (sound '|se | 13)
              (delay 1)
              ((cmd 196) 0 2)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 1)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 2)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 1)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 2)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 1)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 2)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 1)
              (sound '|se | 13)
              (delay 2)
              ((cmd 196) 0 0)
              (exec-mem 14544 2 2)
              (text "Cole: Arrrrrgh!")
              (wait)
              (text-reset 1)
              (text "Steve: Cole, now!")
              (wait)
              (text-reset 1)
              (sound '|| 0)
              (sound '|se | 10)
              (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
              (text "　　　　　　　　　　ＧＡＭＥ　ＯＶＥＲ")
              (menu1
               32
               337
               48
               337
               (</> (/ (str "CONTINUE")) (/ (str "GAME END"))))
              (text-reset 1)
              (branch-var
               S
               (</>
                (/
                 (exec-mem 9920 0 6 6 113 64 0)
                 (nop@)
                 (set-reg 158 #f)
                 (mes-jump "A:¥MES¥091.MES"))
                (/
                 (text "　　　　　ＮＩＧＨＴＭＡＲＥ　ＣＯＬＬＥＣＴＩＯＮ" 'br)
                 (text "　　　　　　ＤＥＡＤ　ＯＦ　ＴＨＥ　ＢＲＡＩＮⅡ" 'br)
                 (text "　　　　　　　　　　　ＧＡＭＥ　ＥＮＤ")
                 (loop (wait)))))))))
       (//
        (? (= 186 #f))
        (text "Cole: Lots of cardboard boxes scattered about. This place   looks like a warehouse.")
        (set-reg 186 #t)
        (wait)
        (text-reset 1))
       (//
        (text "Cole: It's dim in here... It's taking a bit of time for my  eyes to adjust.")
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (text-reset 1) (seg-call)))
 (seg (? (= P 5) (= 187 #f))
   (text "Cole: There are boxes piled up, and they all look empty.")
   (set-reg 187 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5)) (text "Cole: It's an empty cardboard box, no different from the    others.") (wait) (text-reset 1))
 (seg (? (= P 6) (= 188 #f))
   (text "Cole: There's lots of cardboard boxes scattered about.      Nothing to be found in any of them.")
   (set-reg 188 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 189 #f))
   (text "Cole: There's nothing written on these boxes.")
   (set-reg 189 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (text "Cole: Maybe these boxes were used for shipping chemicals?")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 190 #f))
   (text "Cole: There's not a soul in this room.")
   (set-reg 190 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 191 #f))
   (text "Cole: The far wall is so dark that I can't see it.")
   (set-reg 191 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (text "Cole: Just a concrete wall. This room's being used as a     warehouse.")
   (wait)
   (text-reset 1))
 (seg (? (= P 1))
   (exec-mem 6064 2 1)
   (text "Cole: Back to the hallway, I guess.")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (exec-mem 6064 3)
   (nop@)
   (set-reg 158 #t)
   (mes-jump "A:¥MES¥091.MES"))
 (seg (? (= P 2))
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (nop@) (set-reg 158 #f) (flag-save 1))
        (/ (nop@) (set-reg 158 #f) (flag-save 2))
        (/ (nop@) (set-reg 158 #f) (flag-save 3))
        (/ (nop@) (set-reg 158 #f) (flag-save 4))
        (/ (nop@) (set-reg 158 #f) (flag-save 5))
        (/ (nop@) (set-reg 158 #f) (flag-save 6))
        (/ (nop@) (set-reg 158 #f) (flag-save 7))
        (/ (nop@) (set-reg 158 #f) (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 912 "EXIT") (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))