(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (mes-load? "A:¥MES¥096A.MES" 0)
  (mes-load? "A:¥MES¥096B.MES" 4096)
  (load-mem "A:¥CLM¥DB162.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 36 3 42 6)
  (exec-mem 3744 1 6 18 5 23 8)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB129.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB162.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 205 #f))
        (text "［コール］シーラ！！")
        (wait)
        (text-reset 1)
        (text "［シーラ］コール！！　私・・・私・・・。")
        (set-reg 205 #t)
        (wait)
        (text-reset 1))
       (// (text "［スティーブ］とにかく、シーラが無事で良かったよ。") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (text-reset 1) (seg-call)))
 (seg (? (= P 5) (= 206 #f))
   (text "［スティーブ］良かった・・・シーラは無事だったようだな。")
   (wait)
   (text-reset 1)
   (text "［コール］さすがの死霊も、分厚い扉のある実験室には入ってこれ　　　　　なかったようですね。")
   (set-reg 206 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 207 #f))
   (text
    "［スティーブ］この部屋は分厚い壁で固められているため、中にシ　　　　　　　ーラが居る事を、死霊に感知されずに済んだのだろ　　　　　　　うな。")
   (set-reg 207 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "［スティーブ］この実験室がなかったら、今頃シーラも死霊に殺ら　　　　　　　れていただろう。ライルに感謝しないとな。")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 210 #t) (= 207 #t) (= 901 #t))
   (text "［コール］ライルさんが居なけりゃ、ドクを生き返らせる事ができ　　　　　ないじゃないか・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］え！？　クーガーさんを！？")
   (wait)
   (text-reset 1)
   (text
    "［コール］シーラ、お前の身体の中にあるＤＮＶという細菌を取り　　　　　除くには、蘇生薬を作ったドクに直接聞くしかなかった　　　　　んだよ・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］クーガーさんを・・・生き返らせる・・・。")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］そうだ、コールにとってクーガー博士を蘇生させる　　　　　　　のはとても残酷な事だ。だが、それもシーラの身体　　　　　　　を思った上で決心した事だったんだ。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］だが、それももう・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］そう・・・それをライルさんに頼んだの・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］！？")
   (wait)
   (text-reset 1)
   (text "［シーラ］ライルさん、最後に言ってたわ・・・準備は出来ている　　　　　からって二人に伝えてくれと・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］準備が！？")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB131.GPC")
   (image-mem 0 3)
   (image-file "B:¥GPC¥DB164.GPC")
   (image-mem 0 3)
   (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
   (exec-mem 912 "C 0 40 0 40 400 1 40 0")
   (exec-mem 912 "A 1")
   (image-file "A:¥GPC¥DB_FRM2.GPC")
   (image-mem 1 0)
   (exec-mem 912 "GET 0 54 38 23 134")
   (exec-mem 912 "A 0")
   (exec-mem 912 "GET 1 54 38 23 172")
   (exec-mem 912 "A 0,S 0")
   ((cmd 193) 0 "B:¥GPA¥DB163C.GPA")
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (sound '|| 0)
   (sound '|se | 3)
   (text-frame 15 298 74 356)
   (text "［コール］こ、これは！？")
   (wait)
   (text-reset 1)
   (sound '|| 0)
   (if (</>
        (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
        (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
   (sound '|| 1)
   (text "［スティーブ］ライルは、既にクーガー博士の脳をセットしていた　　　　　　　のか・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］そう、これがクーガーさんだったの・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］ドク・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］コール、コンピューターの電源は既に入ってる。脳　　　　　　　のアクセスする準備もできているようだ。")
   (wait)
   (text-reset 1)
   (text "［コール］俺にやらせてください。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ああ・・・。")
   (wait)
   (text-reset 1)
   (sound '|| 2)
   (exec-mem 912 "PUT 0 54 38,W 0,O 0")
   (sound '|| 0)
   ((cmd 196) 0 0)
   (delay 100 0)
   ((cmd 196) 0 0)
   (delay 20 0)
   ((cmd 196) 0 1)
   (delay 10 0)
   ((cmd 196) 0 2)
   (delay 10 0)
   ((cmd 196) 0 3)
   (delay 10 0)
   ((cmd 196) 0 4)
   (delay 10 0)
   ((cmd 196) 0 5)
   (delay 10 0)
   ((cmd 196) 0 6)
   (delay 10 0)
   ((cmd 196) 0 7)
   (delay 10 0)
   ((cmd 196) 0 8)
   (delay 10 0)
   ((cmd 196) 0 9)
   (delay 10 0)
   ((cmd 196) 0 10)
   (delay 10 0)
   ((cmd 196) 0 11)
   (delay 10 0)
   ((cmd 196) 0 12)
   (delay 10 0)
   ((cmd 196) 0 13)
   (delay 10 0)
   ((cmd 196) 0 14)
   (delay 10 0)
   ((cmd 196) 0 15)
   (delay 10 0)
   ((cmd 196) 0 16)
   (delay 10 0)
   ((cmd 196) 0 17)
   (delay 10 0)
   ((cmd 196) 0 18)
   (delay 20 0)
   (exec-mem 912 "PUT 1 54 38,W 0,O 1")
   (exec-mem 912 "EXIT")
   ((cmd 193) 0 "B:¥GPA¥DB164A.GPA")
   ((cmd 193) 1 "B:¥GPA¥DB164B.GPA")
   ((cmd 194)
    0
    "ｱ............ｲ.ｳ.ｴ.ｵ.ｶ.ｷ.ｸ.ｹ.ｺ.ｻ.ｼ.ｽ.ｾ.ｿ.ﾀ.ﾁ....................")
   ((cmd 194) 1 "ｱ............ｲ.ｳ.ｴ.ｵ.ｶ.ｷ.ｸ.ｹ.ｺ.ｻ.ｼ.ｽ.ｱ....................")
   (mes-load? 0)
   (mes-load? 4096)
   (sound '|| 2)
   ((cmd 209) 0 5)
   (exec-mem 9920 0 6 6 113 64 0)
   ((cmd 209) 1 5)
   (sound '|| 0)
   ((cmd 204) 100 899)
   (mes-jump "A:¥MES¥097.MES"))
 (seg (? (= P 6) (= 210 #t) (= 207 #t))
   (text "［シーラ］ライルさん、最後に一言言ってたわ・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］何を？")
   (wait)
   (text-reset 1)
   (text
    "［シーラ］蘇生薬に入っている混合物の一つに、ジルガニロンとい　　　　　う薬が入っていたって・・・。詳しい事は私には判らな　　　　　いけど、昔、その薬を作った人がいたらしいわ。")
   (wait)
   (text-reset 1)
   (text "［コール］ジルガニロン？")
   (wait)
   (text-reset 1)
   (text "［シーラ］その薬を作った人が、ラスニュービルに居るっていう事　　　　　をコール達に教えて欲しいって・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ジルガニロン・・・！？")
   (wait)
   (text-reset 1)
   (text
    "［コール］スティーブさん！　ジルガニロンのジルって、もしかし　　　　　たら、ダニエルが言っていた蘇生薬を作っている奴の名　　　　　前ではないでしょうか！？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ジル・・・ガニ・・・！？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］そうだったのか！！　ジル・ガニーロだ！！")
   (wait)
   (text-reset 1)
   (text "［コール］ジル・ガニーロ？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］思い出したぞ！！　そうか、ジル・Ｊ・ガニーロと　　　　　　　いう男だ！！")
   (wait)
   (text-reset 1)
   (text "［コール］誰ですか、ジル・Ｊ・ガニーロとは！？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］驚くなよ、コール。ジルはベイサイド研究所の所長　　　　　　　の名だよ。")
   (wait)
   (text-reset 1)
   (text
    "［コール］ベイサイドの！？　そんな・・・だって、あそこの所長　　　　　はスティーブさんの兄であるグールに殺されているんで　　　　　すよ！？")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］だが、あのダニエルの口調からして、ジルはまだ生　　　　　　　きている・・・。あの状態でダニエルがハッタリを　　　　　　　言うとは思えないからな。")
   (wait)
   (text-reset 1)
   (text "［コール］そんな・・・という事は、２年前の事件でグールを操っ　　　　　ていたのもジルだったという事か・・・！？")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］やはりそうか・・・兄はジルに操られていたのだ。　　　　　　　これではっきりしたぞ、事件は全てジルの仕込んだ　　　　　　　ものだったのだ。")
   (wait)
   (text-reset 1)
   (text
    "［コール］クソッ！！　なんて奴だ！！　ドクの蘇生薬を最初から　　　　　狙っていたのもジルだったんだ！！　スティーブさん、　　　　　ラスニュービルに行きましょう！！")
   (wait)
   (text-reset 1)
   (text
    "［スティーブ］だがコール、危険だぞ。ラスニュービルといえば、　　　　　　　第三地区の荒廃した工場地帯にあるブラッディフォ　　　　　　　ックスの拠点でもあるんだ。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］あの一帯は無法地帯と恐れられ、我々ポリスでさえ　　　　　　　近づくのは危険な所なんだ。")
   (wait)
   (text-reset 1)
   (text "［コール］だけど、ここまで来て引き下がれません。相手が何だろ　　　　　うと、俺はジルという奴を仕留めます。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］判った、二人で行こう。私も兄を散々苦しめたジル　　　　　　　を許せない、この手でブチ殺してやる。")
   (wait)
   (text-reset 1)
   (text "［コール］シーラ・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］ううん、何も言わないで・・・。私はコールを信じてる　　　　　から・・・必ず戻って来ると信じてるから・・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］シーラ、心配する事はない。コールは私より、ずっ　　　　　　　としっかりしているよ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］スティーブさん、コールをお願いします。")
   (wait)
   (text-reset 1)
   (text "［コール］じゃあ、行ってくる！")
   (wait)
   (text-reset 1)
   (text "［シーラ］お願い・・・気を付けて・・・。")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   ((cmd 204) 100 899)
   ((cmd 206) 1 3)
   (mes-jump "A:¥MES¥104.MES"))
 (seg (? (= P 6) (= 208 #f))
   (text "［シーラ］コール・・・！！")
   (wait)
   (text-reset 1)
   (text "［コール］シーラ、良かった・・・無事だったんだな。")
   (wait)
   (text-reset 1)
   (text "［シーラ］ライルさんは・・・ライルさんは？")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ライルは残念ながら死霊に・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］そんな・・・。")
   (set-reg 208 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 209 #f))
   (text "［コール］シーラ、どうなったのか話してくれないか？")
   (wait)
   (text-reset 1)
   (text "［シーラ］私・・・屋上にいて・・・街の方からたくさんの死霊が　　　　　この研究所に向かっているのを見たの・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］数は？")
   (wait)
   (text-reset 1)
   (text "［シーラ］数え切れなかった・・・私、とても怖くてコールを捜し　　　　　てたの・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］ごめんよ・・・俺とスティーブさんは、ダニエルを始末　　　　　するためにラゾバン製薬に行っていたんだ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］そうだったの・・・コール達が無事で安心した・・・。")
   (set-reg 209 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 210 #f))
   (text "［コール］それで、どうしたんだ？")
   (wait)
   (text-reset 1)
   (text "［シーラ］ライルさんにその事を伝えたわ。そしてキャサリンを捜　　　　　そうと・・・。")
   (wait)
   (text-reset 1)
   (text "［シーラ］コール・・・キャサリンが・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］あ、ああ・・・キャサリンは殺られてしまった・・・。")
   (wait)
   (text-reset 1)
   (text
    "［シーラ］キャサリンが叫んですぐに、ライルさんは私をこの実験　　　　　室に入れたの。私、ライルさんも一緒だと思っていたの　　　　　に・・・。")
   (wait)
   (text-reset 1)
   (text "［コール］ライルさんは、シーラをこの部屋に入れてドアをロック　　　　　したんだ。")
   (wait)
   (text-reset 1)
   (text "［シーラ］『キャサリンを守る事ができなかった・・・男として、　　　　　　このまま死霊から逃げる訳にはいかない』って・・。")
   (wait)
   (text-reset 1)
   (text "［スティーブ］ライルの奴・・・格好つけやがって・・・。")
   (set-reg 210 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6)) (text "［スティーブ］ライルの奴・・・格好つけやがって・・・。") (wait) (text-reset 1))
 (seg (? (= P 2))
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))