(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (mes-load? "A:¥MES¥096A.MES" 0)
  (mes-load? "A:¥MES¥096B.MES" 4096)
  (load-mem "A:¥CLM¥DB162.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 36 3 42 6)
  (exec-mem 3744 1 6 18 5 23 8)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB129.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB162.GPC")
  (image-mem 1 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 205 #f))
        (text "Cole: Sheila!!!")
        (wait)
        (text-reset 1)
        (text "Sheila: Oh my god, Cole! I...")
        (set-reg 205 #t)
        (wait)
        (text-reset 1))
       (// (text "Steve: Thank god Sheila's safe.") (wait) (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (text-reset 1) (seg-call)))
 (seg (? (= P 5) (= 206 #f))
   (text "Steve: Saints be praised... Sheila's unharmed.")
   (wait)
   (text-reset 1)
   (text "Cole: So the zombies weren't able to bust open the lab's" 'br)
(text "reinforced door!")
   (set-reg 206 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 207 #f))
   (text
    "Steve: And since the walls are reinforced, the undead" 'br)
"weren't able to tell Sheila was inside.")
   (set-reg 207 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (text "Steve: Sheila would have met her fate if it weren't for this" 'br)
(text "room. I really owe Lisle my thanks.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 210 #t) (= 207 #t) (= 901 #t))
   (text "Cole: But without Lisle, there's no way to revive Doc...")
   (wait)
   (text-reset 1)
   (text "Sheila: What? Doc Cooger?")
   (wait)
   (text-reset 1)
   (text
    "Cole: Sheila... To remove the DNV bacterium from your body," 'br)
"we had no other choice but to consult with Doc... The one" 'br)
"who made the serum... Directly.")
   (wait)
   (text-reset 1)
   (text "Sheila: No... You were going to...revive Doc!?")
   (wait)
   (text-reset 1)
   (text
    "Steve: That's right. For Cole, reviving Dr. Cooger was an" 'br)
"act of cruelty beyond measure... But the decision was made" 'br)
"with your survival in mind.")
   (wait)
   (text-reset 1)
   (text "Steve: But now, that's impossible...")
   (wait)
   (text-reset 1)
   (text "Sheila: So you asked Lisle to do it...")
   (wait)
   (text-reset 1)
   (text "Cole: !?")
   (wait)
   (text-reset 1)
   (text "Sheila: Lisle's last words... Were to let you know that he" 'br)
(text "was ready.")
   (wait)
   (text-reset 1)
   (text "Cole: Ready to--")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB131.GPC")
   (image-mem 0 3)
   (image-file "B:¥GPC¥DB164.GPC")
   (image-mem 0 3)
   (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
   (exec-mem 912 "C 0 40 0 40 400 1 40 0")
   (exec-mem 912 "A 1")
   (image-file "A:¥GPC¥DB_FRM2.GPC")
   (image-mem 1 0)
   (exec-mem 912 "GET 0 54 38 23 134")
   (exec-mem 912 "A 0")
   (exec-mem 912 "GET 1 54 38 23 172")
   (exec-mem 912 "A 0,S 0")
   ((cmd 193) 0 "B:¥GPA¥DB163C.GPA")
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (sound '|| 0)
   (sound '|se | 3)
   (text-frame 15 298 74 356)
   (text "Cole: No way... For real?")
   (wait)
   (text-reset 1)
   (sound '|| 0)
   (if (</>
        (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_02.USO"))
        (// (sound '|| "A:¥USO_D¥BR2_02.USO"))))
   (sound '|| 1)
   (text "Steve: Lisle had already set up Dr. Cooger's brain for" 'br)
(text "revival.")
   (wait)
   (text-reset 1)
   (text "Sheila: So this was Doc Cooger's...")
   (wait)
   (text-reset 1)
   (text "Cole: Doc...")
   (wait)
   (text-reset 1)
   (text "Steve: Cole, the computer's already been powered on." 'br)
(text "Everything's set to access his brain.")
   (wait)
   (text-reset 1)
   (text "Cole: Let me handle this.")
   (wait)
   (text-reset 1)
   (text "Steve: Yeah...")
   (wait)
   (text-reset 1)
   (sound '|| 2)
   (exec-mem 912 "PUT 0 54 38,W 0,O 0")
   (sound '|| 0)
   ((cmd 196) 0 0)
   (delay 100 0)
   ((cmd 196) 0 0)
   (delay 20 0)
   ((cmd 196) 0 1)
   (delay 10 0)
   ((cmd 196) 0 2)
   (delay 10 0)
   ((cmd 196) 0 3)
   (delay 10 0)
   ((cmd 196) 0 4)
   (delay 10 0)
   ((cmd 196) 0 5)
   (delay 10 0)
   ((cmd 196) 0 6)
   (delay 10 0)
   ((cmd 196) 0 7)
   (delay 10 0)
   ((cmd 196) 0 8)
   (delay 10 0)
   ((cmd 196) 0 9)
   (delay 10 0)
   ((cmd 196) 0 10)
   (delay 10 0)
   ((cmd 196) 0 11)
   (delay 10 0)
   ((cmd 196) 0 12)
   (delay 10 0)
   ((cmd 196) 0 13)
   (delay 10 0)
   ((cmd 196) 0 14)
   (delay 10 0)
   ((cmd 196) 0 15)
   (delay 10 0)
   ((cmd 196) 0 16)
   (delay 10 0)
   ((cmd 196) 0 17)
   (delay 10 0)
   ((cmd 196) 0 18)
   (delay 20 0)
   (exec-mem 912 "PUT 1 54 38,W 0,O 1")
   (exec-mem 912 "EXIT")
   ((cmd 193) 0 "B:¥GPA¥DB164A.GPA")
   ((cmd 193) 1 "B:¥GPA¥DB164B.GPA")
   ((cmd 194)
    0
    "A... E I O U...")
   ((cmd 194) 1 "ｱ............ｲ.ｳ.ｴ.ｵ.ｶ.ｷ.ｸ.ｹ.ｺ.ｻ.ｼ.ｽ.ｱ....................")
   (mes-load? 0)
   (mes-load? 4096)
   (sound '|| 2)
   ((cmd 209) 0 5)
   (exec-mem 9920 0 6 6 113 64 0)
   ((cmd 209) 1 5)
   (sound '|| 0)
   ((cmd 204) 100 899)
   (mes-jump "A:¥MES¥097.MES"))
 (seg (? (= P 6) (= 210 #t) (= 207 #t))
   (text "Sheila: Lisle had mentioned one last thing...")
   (wait)
   (text-reset 1)
   (text "Cole: What?")
   (wait)
   (text-reset 1)
   (text
    "Sheila: He mentioned that one of the compounds in the" 'br)
"reanimation serum contains a substance named Jilgananiron. I" 'br)
"don't know all the details, but...")
   (wait)
   (text-reset 1)
   (text "Cole: Jilganiron? What now?")
   (wait)
   (text-reset 1)
   (text "Sheila: He wanted us to know that the person who came up" 'br)
(text "with that medicine is in the Lasnew Building.")
   (wait)
   (text-reset 1)
   (text "Steve: Jilganiron...!?")
   (wait)
   (text-reset 1)
   (text
    "Cole: Steve, do you think that the 'Jil' in 'Jilganiron' is" 'br)
"the same person Daniel mentioned...the one who made the" 'br)
"serum component?")
   (wait)
   (text-reset 1)
   (text "Steve: Jill.. Gani...")
   (wait)
   (text-reset 1)
   (text "Steve: That's it! It's Jill Ganiro!")
   (wait)
   (text-reset 1)
   (text "Cole: Jill Ganiro?")
   (wait)
   (text-reset 1)
   (text "Steve: I remember now! Yes, it's him -- Jill J. Ganiro!")
   (wait)
   (text-reset 1)
   (text "Cole: Who the hell is Jill J. Ganiro?")
   (wait)
   (text-reset 1)
   (text "Steve: It's not a surprise, Cole. Jill is the director of" 'br)
(text "the Bayside Research Institute.")
   (wait)
   (text-reset 1)
   (text
    "Cole: Bayside!? No way... The director there was killed by" 'br)
"your brother Ghoul, wasn't he?")
   (wait)
   (text-reset 1)
   (text
    "Steve: But according to Daniel, Jill is alive... I don't" 'br)
"think Daniel would have been bluffing.")
   (wait)
   (text-reset 1)
   (text "Cole: Damn... Does that mean that Jill was controlling Ghoul" 'br)
(text "during the incident two years ago?")
   (wait)
   (text-reset 1)
   (text
    "Steve: It figures... Jill was manipulating my brother. Now" 'br)
"it's clear to me. The entire incident was orchestrated by" 'br)
"him.")
   (wait)
   (text-reset 1)
   (text
    "Cole: What a sack of shit! He was after Doc's reanimation" 'br)
"serum from the very start! Steve, we need to go to the" 'br)
"Lasnew Building!")
   (wait)
   (text-reset 1)
   (text
    "Steve: Cole, that place is no joke. It's Bloody Fox's" 'br)
"headquarters in the ruined industrial zone of District" 'br)
"Three.")
   (wait)
   (text-reset 1)
   (text "Steve: It's known as a lawless zone... So dangerous that" 'br)
(text "cops like me are hesitant to go near it.")
   (wait)
   (text-reset 1)
   (text "Cole: But we've come this far... There's no way to back down" 'br)
(text "now. I don't care who I have to go up against, I'm taking" 'br)
(text "Jill down.")
   (wait)
   (text-reset 1)
   (text "Steve: Then so be it... We'll go together. I can't forgive" 'br)
(text "Jill for everything he put my brother through. I'm gonna" 'br)
(text "kill him with my own two hands.")
   (wait)
   (text-reset 1)
   (text "Cole: Sheila...")
   (wait)
   (text-reset 1)
   (text "Sheila: No, please... Don't say anything. I believe in you," 'br)
(text "Cole... And I trust you'll come back, no matter what.")
   (wait)
   (text-reset 1)
   (text "Steve: Sheila, you've got nothing to worry about. Cole is" 'br)
(text "far more reliable than me.")
   (wait)
   (text-reset 1)
   (text "Sheila: Steve, please look after Cole.")
   (wait)
   (text-reset 1)
   (text "Cole: Okay, we're going.")
   (wait)
   (text-reset 1)
   (text "Sheila: Please, be careful...")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   ((cmd 204) 100 899)
   ((cmd 206) 1 3)
   (mes-jump "A:¥MES¥104.MES"))
 (seg (? (= P 6) (= 208 #f))
   (text "Sheila: Cole...!")
   (wait)
   (text-reset 1)
   (text "Cole: Sheila, thank god! You're okay!")
   (wait)
   (text-reset 1)
   (text "Sheila: But Lisle... What about Lisle?")
   (wait)
   (text-reset 1)
   (text "Steve: Lisle...was taken by the undead...")
   (wait)
   (text-reset 1)
   (text "Sheila: No!")
   (set-reg 208 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 209 #f))
   (text "Cole: Sheila, can you tell us what happened?")
   (wait)
   (text-reset 1)
   (text "Sheila: I was on the rooftop, and I saw so many zombies" 'br)
(text "coming from the city, converging on us...")
   (wait)
   (text-reset 1)
   (text "Cole: How many?")
   (wait)
   (text-reset 1)
   (text "Sheila: I lost count... I was so scared that I went looking" 'br)
(text "for you, Cole...")
   (wait)
   (text-reset 1)
   (text "Cole: I'm sorry... Steve and I went to Razovan" 'br)
(text "Pharmaceuticals to kill Daniel.")
   (wait)
   (text-reset 1)
   (text "Sheila: I see... I'm so glad you and Steve are safe.")
   (set-reg 209 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 210 #f))
   (text "Cole: So what happened?")
   (wait)
   (text-reset 1)
   (text "Sheila: I told Lisle about the zombies and tried to find" 'br)
(text "Catherine...")
   (wait)
   (text-reset 1)
   (text "Sheila: Cole... Catherine was...")
   (wait)
   (text-reset 1)
   (text "Cole: Yes... Yes, Catherine was killed.")
   (wait)
   (text-reset 1)
   (text
    "Sheila: After I heard Catherine scream, Lisle put me in the" 'br)
"lab. I thought he was going to come in with me...")
   (wait)
   (text-reset 1)
   (text "Cole: Lisle put Sheila in the room and locked the door.")
   (wait)
   (text-reset 1)
   (text "Sheila: He told me 'I couldn't protect Catherine... As a" 'br)
(text "man, I can't just run away from the undead like this...'")
   (wait)
   (text-reset 1)
   (text "Steve: That's Lisle, always trying to act cool...")
   (set-reg 210 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6)) (text "Steve: That's Lisle, always trying to act cool...") (wait) (text-reset 1))
 (seg (? (= P 2))
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))