(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (text "Cole: Doc...")
  (wait)
  (text-reset 1)
  (text "合成音: ...")
  (wait)
  (text-reset 1)
  (text "Cole: Please, Doc... Answer me.")
  (wait)
  (text-reset 1)
  (text "合成音: ...")
  (wait)
  (text-reset 1)
  (text "Cole: It's me, Cole.")
  (wait)
  (text-reset 1)
  (text "合成音: ...")
  (wait)
  (text-reset 1)
  (text "Cole: You're all I've got left, Doc. Please.")
  (wait)
  (text-reset 1)
  (text "合成音: ...")
  (wait)
  (text-reset 1)
  (text "Steve: Well, he's sustained a brain injury... It may be hopeless.")
  (wait)
  (text-reset 1)
  (text "Cole: Doc! Talk to me, man!")
  (wait)
  (text-reset 1)
  (text "合成音: ...")
  (wait)
  (text-reset 1)
  (text "Cole: Can't you hear me? It's Cole! Doc, come on!")
  (wait)
  (text-reset 1)
  (text "Sheila: Cole, that's enough! Please, don't torture him any more...")
  (wait)
  (text-reset 1)
  (text "Cole: What choice do I have? Without Doc's mind, Sheila's body is going to--")
  (wait)
  (text-reset 1)
  (sound '|| 0)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (sound '|se | 3)
  (text "合成音: I can hear you all, Cole...")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "Steve: !!" 'br)
  (text "Sheila: !?")
  (wait)
  (text-reset 1)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_11.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_11.USO"))))
  (sound '|| 1)
  (text "Cole: Doc!? Can you hear us?")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "Cooger: So it is you... I can barely see... And I feel...ill.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "Steve: That's not a synthesized voice. Is that the doctor's real voice?")
  (wait)
  (text-reset 1)
  (text "Sheila: Y-yes... That's him... Hearing him again like this, it's...")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "Cooger: I can't move my limbs... Cole, where are we?")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "Cole: Doc, we've revived your consciousness in Dr. Lisle's laboratory.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text
   "Cooger: Lisle, eh? That brings back memories. He was my assistant once. So... Lisle is the one who revived me...")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "Cole: Doc, the zombies got Lisle. He's dead.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "Cooger: ...I see. That's unfortunate.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "Cole: It's been two years since you died. I didn't want to go through with this, but we need your help more than ever.")
  (wait)
  (text-reset 1)
  (text "Cooger: ...")
  (wait)
  (text-reset 1)
  (text "Cole: Please, Doc... Help us.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "Cooger: Cole, I want to know everything that's happened to you for these past two years.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "Cole: I can tell you.")
  (wait)
  (text-reset 1)
  (text
   "I recounted everything I could since he died. About Ghoul, Steve, Catherine, Daniel, and Jill.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "Cooger: I see. So much happened after I died...")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "Steve: I'm sorry. I never intended for you to suffer because of my brother.")
  (wait)
  (text-reset 1)
  (text "Cooger: No, I deserved everything that happened to me. You bear no responsibility.")
  (wait)
  (text-reset 1)
  (text "Sheila: Doctor Cooger... Can you hear me?")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "Cooger: Ah, there's Sheila... You've been through quite a few frights, but you'll be safe with Cole by your side.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "Cole: Doc... That's not really the case. The main reason I revived you was because I needed your help with Sheila.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "Cooger: What do you mean?")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "Cole: Sheila was infected with a bacteria called DNV after being injected with Purple Sky.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "Cooger: DNV... That sounds familiar. A most troublesome bacteria when it came to making the serum.")
  (wait)
  (text-reset 1)
  (text
   "Cooger: But there's not just one DNV, there's multiple strains. Sheila, what happened to you since you were injected?")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (text "Sheila: Well, my body went limp, and Cole helped me rest...")
  (wait)
  (text-reset 1)
  (text "Sheila: The next day, my chest was covered with red spots, like insect bites.")
  (wait)
  (text-reset 1)
  (text
   "Sheila: Those red spots turned purple, and I felt more and more drained... And no matter how much water I drank, I was parched.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (text "Cooger: Judging by that description, it's likely number 16.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  ((cmd 212))))