(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (str "Cole: Doc...")
  (wait)
  (text-reset 1)
  (str "Voice: ...")
  (wait)
  (text-reset 1)
  (str "Cole: Please, Doc... Answer me.")
  (wait)
  (text-reset 1)
  (str "Voice: ...")
  (wait)
  (text-reset 1)
  (str "Cole: It's me, Cole.")
  (wait)
  (text-reset 1)
  (str "Voice: ...")
  (wait)
  (text-reset 1)
  (str "Cole: You're all I've got left, Doc. Please.")
  (wait)
  (text-reset 1)
  (str "Voice: ...")
  (wait)
  (text-reset 1)
  (str "Steve: Well, he's sustained a brain injury... It may be" 'br)
  (str "hopeless.")
  (wait)
  (text-reset 1)
  (str "Cole: Doc! Talk to me, man!")
  (wait)
  (text-reset 1)
  (str "Voice: ...")
  (wait)
  (text-reset 1)
  (str "Cole: Can't you hear me? It's Cole! Doc, come on!")
  (wait)
  (text-reset 1)
  (str "Sheila: Cole, that's enough! Please, don't torture him any" 'br)
  (str "more...")
  (wait)
  (text-reset 1)
  (str "Cole: What choice do I have? Without Doc's mind, Sheila's" 'br)
  (str "body is going to--")
  (wait)
  (text-reset 1)
  (sound '|| 0)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (sound '|se | 3)
  (str "Voice: I can hear you all, Cole...")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Steve: !!" 'br)
  (str "Sheila: !?")
  (wait)
  (text-reset 1)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_11.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_11.USO"))))
  (sound '|| 1)
  (str "Cole: Doc!? Can you hear us?")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: So it is you... I can barely see... And I" 'br)
  (str "feel...ill.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Steve: That's not a synthesized voice. Is that the doctor's" 'br)
  (str "real voice?")
  (wait)
  (text-reset 1)
  (str "Sheila: Y-yes... That's him... Hearing him again like this," 'br)
  (str "it's...")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: I can't move my limbs... Cole, where are we?")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: Doc, we've revived your consciousness in Dr. Lisle's" 'br)
  (str "laboratory.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: Lisle, eh? That brings back memories. He was my" 'br)
  (str "assistant once. So... Lisle is the one who revived me...")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: Doc, the zombies got Lisle. He's dead.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: ...I see. That's unfortunate.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: It's been two years since you died. I didn't want to" 'br)
  (str "go through with this, but we need your help more than ever.")
  (wait)
  (text-reset 1)
  (str "Cooger: ...")
  (wait)
  (text-reset 1)
  (str "Cole: Please, Doc... Help us.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: Cole, I want to know everything that's happened to" 'br)
  (str "you for these past two years.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: I can tell you.")
  (wait)
  (text-reset 1)
  (str "I recounted everything I could since he died. About Ghoul," 'br)
  (str "Steve, Catherine, Daniel, and Jill.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: I see. So much happened after I died...")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Steve: I'm sorry. I never intended for you to suffer because" 'br)
  (str "of my brother.")
  (wait)
  (text-reset 1)
  (str "Cooger: No, I deserved everything that happened to me. You" 'br)
  (str "bear no responsibility.")
  (wait)
  (text-reset 1)
  (str "Sheila: Doctor Cooger... Can you hear me?")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: Ah, there's Sheila... You've been through quite a" 'br)
  (str "few frights, but you'll be safe with Cole by your side.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: Doc... That's not really the case. The main reason I" 'br)
  (str "revived you was because I needed your help with Sheila.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: What do you mean?")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: Sheila was infected with a bacteria called DNV after" 'br)
  (str "being injected with Purple Sky.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: DNV... That sounds familiar. A most troublesome" 'br)
  (str "bacteria when it came to making the serum.")
  (wait)
  (text-reset 1)
  (str "Cooger: But there's not just one DNV, there's multiple" 'br)
  (str "strains. Sheila, what happened to you since you were" 'br)
  (str "injected?")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Sheila: Well, my body went limp, and Cole helped me rest...")
  (wait)
  (text-reset 1)
  (str "Sheila: The next day, my chest was covered with red spots," 'br)
  (str "like insect bites.")
  (wait)
  (text-reset 1)
  (str "Sheila: Those red spots turned purple, and I felt more and" 'br)
  (str "more drained... And no matter how much water I drank, I was" 'br)
  (str "parched.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: Judging by that description, it's likely number 16.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  ((cmd 212))))