; Dead of the Brain 2 (PC-98) - 096B.MES
; Translated by Geometrizer
; Edited by JackDBS, commented by trentsignia
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (str "Cole: Number 16?")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: That pesky bacterium made me want to give up on my" 'br)
  (str "serum research more than once...")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: Doc, can you cure her?")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: Yes. Don't worry. I'd prepared a serum to" 'br)
  (str "specifically kill DNV. But after two years, its viability" 'br)
  (str "is...ah, questionable...")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: Where is it?")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: Cole, do you remember the first night I showed you" 'br)
  (str "the serum? We got chased by a policeman named Jack and ran" 'br)
  (str "through the cemetery...")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: Yes, I remember.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: I was carrying a bag with the DNV cure in it.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: But Doc, you had tripped and dropped the bag...")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: The cure's potency doesn't fade with time, but if" 'br)
  (str "it was broken, like the flask with the reanimation serum...")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: ...There's no way to make another batch?")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: I... Don't think my brain could manage such a thing" 'br)
  (str "now.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: I understand. I'll find it no matter what.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: Cole, my mind can't hold on much longer. Before" 'br)
  (str "this all fades away, I have one request.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: Anything, Doc.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: I'd like to speak to you alone, Cole.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Steve: I understand. Sheila and I will duck out for a bit.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: I'm sorry.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: They've left, Doc.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: Cole, my reanimation serum has caused so much" 'br)
  (str "suffering.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: Doc, it wouldn't have happened if it had been" 'br)
  (str "presented to the world in a better way, if it'd been" 'br)
  (str "officially released--")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: Thanks for your kind words, but even if the serum" 'br)
  (str "hadn't been stolen, a mass casualty incident was bound to" 'br)
  (str "happen.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: ...")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: In the end, I wound up doing...inhuman things. What" 'br)
  (str "matters in a human's short life is how earnestly they live" 'br)
  (str "it.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: ...")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: I believe that's the very reason God gave us such a" 'br)
  (str "short amount of time on Earth...")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: Doc, I...")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: Cole, I know the serum's burdened you with" 'br)
  (str "countless troubles, and you've lost so much.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: That's not true. I've lost things, but I've gained so" 'br)
  (str "much more.")
  (wait)
  (text-reset 1)
  (str "Cooger: ...")
  (wait)
  (text-reset 1)
  (str "Cole: Doc...")
  (wait)
  (text-reset 1)
  (str "Cole: Honestly, I didn't want to bring you back. But right" 'br)
  (str "now, there's no other way to save Sheila. Talking to you" 'br)
  (str "was the only option.")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: I'm glad you still have me in your thoughts, Cole." 'br)
  (str "You truly care for Sheila, and that's why you didn't" 'br)
  (str "hesitate to revive me.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: ...")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: You care for me as earnestly as you do for Sheila." 'br)
  (str "Otherwise, after I got infected by the undead two years" 'br)
  (str "ago, you wouldn't have shot me.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: ...")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: Cole, I don't have much time left. I see the" 'br)
  (str "darkness one step ahead of me.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: Doc... Thank you, Doc...")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 15)
  ((cmd 197) 1 15)
  (str "Cooger: And Cole... Congratulations on your engagement.")
  (wait)
  (text-reset 1)
  ((cmd 196) 0 0)
  ((cmd 196) 1 0)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (str "Cole: !?")
  (wait)
  (text-reset 1)
  (str "Cole: So you could see my ring after all...")
  (wait)
  (text-reset 1)
  ((cmd 212))))