(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB166.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 2 80 0 0 0)
  (exec-mem 3744 1 5 40 7 56 11)
  (exec-mem 3744 1 6 18 11 38 15)
  (exec-mem 3744 1 7 28 7 34 8)
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB166.GPC")
  (image-mem 0 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (if (</>
       (//
        (? (= 114 #f))
        (sound '|| 0)
        (if (</>
             (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_13.USO"))
             (// (sound '|| "A:¥USO_D¥BR2_13.USO"))))
        (sound '|| 1))))
  (if (</>
       (//
        (? (= 115 #f))
        (str "Cole: Cemeteries at night always give me the heebie-jeebies.")
        (set-reg 115 #t))
       (// (str "Cole: I need to find the cure quickly."))))
  (wait)
  (text-reset 1)
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (text-reset 1) (seg-call)))
 (seg (? (= P 5) (= 116 #f))
   (str "Cole: There are so many tombstones lining the side of the" 'br)
   (str "path. It feels like they're watching me... Brrrr.")
   (set-reg 116 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 117 #f))
   (str "Cole: It's been two years since the town fell to the undead." 'br)
   (str "I can't imagine there are any zombies left.")
   (wait)
   (text-reset 1)
   (str "Cole: And yet... Even though they shouldn't be there... I've" 'br)
   (str "got a weird foreboding...")
   (set-reg 117 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))
   (str "Cole: On this tombstone, the name ")
   (branch-random
    (</>
     (/ (str "'Stella Treshil'"))
     (/ (str "'Seed Relics'"))
     (/ (str "'Merini Nanets'"))
     (/ (str "'Robert Gibson'"))
     (/ (str "'Jonathan Long'"))))
   (str " " 'br)
   (str "is enscribed.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 118 #f))
   (str "Cole: This path just goes on and on... I remember this from" 'br)
   (str "back when we were on the run from Jack.")
   (set-reg 118 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 119 #f))
   (str "Cole: Even though it's cloudy, the moon's still out, so I" 'br)
   (str "can see the path.")
   (set-reg 119 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 120 #f))
   (str "Cole: I just hope the cure Doc mentioned still exists after" 'br)
   (str "two years...")
   (set-reg 120 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6) (= 121 #f))
   (str "Cole: I'm getting tired from walking so much. But back when" 'br)
   (str "Jack was after us, we were running for our lives.")
   (set-reg 121 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 6))
   (str "Cole: *Pant pant* Even if I manage to grab the serum," 'br)
   (str "retracing my steps is going to be a challenge. I came by" 'br)
   (str "car, so I'll need to walk back to the gate.")
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 122 #f))
   (str "Cole: The path stretches far into the horizon... Hard to see" 'br)
   (str "what's up ahead.")
   (set-reg 122 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7) (= 123 #f))
   (str "Cole: Doc tripped and fell a bit further on... Now that I" 'br)
   (str "think about it, we escaped through the back exit and headed" 'br)
   (str "to my apartment.")
   (wait)
   (text-reset 1)
   (str "Cole: I should have entered the cemetery through the back" 'br)
   (str "exit from the start... I messed that up.")
   (set-reg 123 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 7))
   (str "Cole: The spot where Doc tripped was a bit further ahead...")
   (wait)
   (text-reset 1))
 (seg (? (= P 1) (= 117 #t) (= 121 #t) (= 123 #t) (= 126 #t))
   (exec-mem 6064 2 1)
   (str "Cole: Wait, what's that ahead...")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (exec-mem 6064 3)
   (image-file "B:¥GPC¥DB168.GPC")
   (image-mem 0 3)
   (image-file "B:¥GPC¥DB168B.GPC")
   (image-mem 1 3)
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (str "Cole: A dead end? Did I take a wrong turn?")
   (wait)
   (text-reset 1)
   (str "Cole: Damn, maybe I should backtrack--")
   (wait)
   (text-reset 1)
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (image-file "B:¥GPC¥DB167.GPC")
   (image-mem 0 3)
   ((cmd 193) 0 "B:¥GPA¥DB167.GPA")
   (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
   (sound '|| 0)
   (if (</>
        (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_05.USO"))
        (// (sound '|| "A:¥USO_D¥BR2_05.USO"))))
   (sound '|| 1)
   (str "Cole: Shit! Zombie!")
   (wait)
   (text-reset 1)
   (str "Zombie: GUUUUUU…")
   (wait)
   (text-reset 1)
   (image-file "A:¥GPC¥COUNTER.GPC")
   (image-mem 0 0)
   (load-mem "A:¥CLM¥DB167.CLM" 32768)
   (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 3 2 0)
   (exec-mem 3744 1 1 80 0 0 0)
   (exec-mem 3744 1 5 29 5 35 8)
   (exec-mem 15728 0 0 1 0 0 1)
   (exec-mem 15728 1 0 0 0 0 "Z")
   (exec-mem 15728 2 1)
   (exec-mem 15456 0)
   (exec-mem 14544 2 0)
   (exec-mem 15728 3)
   (exec-mem 3744 3 "P" 32768)
   (exec-mem 15728 4)
   (image-file "A:¥GPC¥DB_FRM3.GPC")
   (image-mem 0 0)
   (if (</>
        (//
         (? (= Z 2) (= P 5))
         ((cmd 196) 0 0)
         ((cmd 196) 0 1)
         (delay 2 0)
         (sound '|se | 13)
         ((cmd 196) 0 2)
         (delay 2 0)
         ((cmd 196) 0 3)
         (delay 8 0)
         ((cmd 196) 0 4)
         (delay 4 0)
         ((cmd 196) 0 5)
         (delay 8 0)
         ((cmd 196) 0 6)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (str "Zombie: GAAAAAAA!!!")
         (wait)
         (text-reset 1)
         (str "Cole: What the hell... Is this guy immortal?")
         (wait)
         (text-reset 1)
         (str "Zombie: GUAAAAAAA!!!")
         (wait)
         (text-reset 1)
         (str "Cole: Agh! AAAAAAAAAGH!")
         (wait)
         (text-reset 1)
         (sound '|| 0)
         (sound '|se | 10)
         (text "　　　　　　　　　　ＧＡＭＥ　ＯＶＥＲ")
         (menu1 32 337 48 337 (</> (/ (str "CONTINUE")) (/ (str "GAME END"))))
         (text-reset 1)
         (branch-var
          S
          (</>
           (/
            (exec-mem 9920 0 6 6 113 64 0)
            (nop@)
            (set-reg 114 #f)
            (mes-jump "A:¥MES¥099.MES"))
           (/
            (text "　　　　　ＮＩＧＨＴＭＡＲＥ　ＣＯＬＬＥＣＴＩＯＮ" 'br)
            (text "　　　　　　ＤＥＡＤ　ＯＦ　ＴＨＥ　ＢＲＡＩＮⅡ" 'br)
            (text "　　　　　　　　　　　ＧＡＭＥ　ＥＮＤ")
            (loop (wait))))))
        (//
         (? (= Z 2))
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (str "Zombie: GAAAAAAA!!!")
         (wait)
         (text-reset 1)
         (str "Cole: Shit, I missed!")
         (wait)
         (text-reset 1)
         (str "Zombie: GUAAAAAAA!!!")
         (wait)
         (text-reset 1)
         (str "Cole: Agh! AAAAAAAAAGH!")
         (wait)
         (text-reset 1)
         (sound '|| 0)
         (sound '|se | 10)
         (text "　　　　　　　　　　ＧＡＭＥ　ＯＶＥＲ")
         (menu1 32 337 48 337 (</> (/ (str "CONTINUE")) (/ (str "GAME END"))))
         (text-reset 1)
         (branch-var
          S
          (</>
           (/
            (exec-mem 9920 0 6 6 113 64 0)
            (nop@)
            (set-reg 114 #f)
            (mes-jump "A:¥MES¥099.MES"))
           (/
            (text "　　　　　ＮＩＧＨＴＭＡＲＥ　ＣＯＬＬＥＣＴＩＯＮ" 'br)
            (text "　　　　　　ＤＥＡＤ　ＯＦ　ＴＨＥ　ＢＲＡＩＮⅡ" 'br)
            (text "　　　　　　　　　　　ＧＡＭＥ　ＥＮＤ")
            (loop (wait))))))
        (//
         (str "Cole: Hold on a second. This isn't right...")
         (wait)
         (text-reset 1)
         (str "Zombie: GUUUUUU…")
         (wait)
         (text-reset 1)
         (str "Cole: Huh?")
         (wait)
         (text-reset 1)
         (sound '|| 2)
         (str "Zombie: ...")
         (wait)
         (text-reset 1)
         (str "Cole: What is it with this guy...")
         (wait)
         (text-reset 1)
         (sound '|| 0)
         (str "Cole: It isn't aggressive. It isn't attacking me at all...  What's the deal?")
         (wait)
         (text-reset 1)
         (str "Cole: Has it noticed me? Even if it can't see, it should be" 'br)
         (str "able to sense where a human is...")
         (wait)
         (text-reset 1)
         (str "Zombie: GUUUUUU…")
         (wait)
         (text-reset 1)
         (str "Cole: ...To keep this thing from hurting anyone else, I'd" 'br)
         (str "better put it out of its misery.")
         (wait)
         (text-reset 1)
         ((cmd 196) 0 0)
         ((cmd 196) 0 1)
         (delay 2 0)
         (sound '|se | 13)
         ((cmd 196) 0 2)
         (delay 2 0)
         ((cmd 196) 0 3)
         (delay 8 0)
         ((cmd 196) 0 4)
         (delay 4 0)
         ((cmd 196) 0 5)
         (delay 8 0)
         ((cmd 196) 0 6)
         (str "Cole: All right, I can't afford to sit around. I need to" 'br)
         (str "find the cure fast.")
         (wait)
         (text-reset 1)
         (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
         (mes-jump "A:¥MES¥100.MES")))))
 (seg (? (= P 1) (= 124 #f))
   (exec-mem 6064 2 1)
   (str "Cole: *Pant pant*")
   (set-reg 124 #t)
   (wait)
   (text-reset 1)
   (exec-mem 6064 3))
 (seg (? (= P 1) (= 125 #f))
   (exec-mem 6064 2 1)
   (str "Cole: I've been walking forever, and I'm still not there...")
   (set-reg 125 #t)
   (wait)
   (text-reset 1)
   (exec-mem 6064 3))
 (seg (? (= P 1) (= 126 #f))
   (exec-mem 6064 2 1)
   (if (</> (// (? (= X 4)) (nop@) (set-reg 126 #t))))
   (str "Cole: *Pant pant*")
   (inc-var X 1)
   (wait)
   (text-reset 1)
   (exec-mem 6064 3))
 (seg (? (= P 1))
   (exec-mem 6064 2 1)
   (str "Cole: *Pant pant*")
   (wait)
   (text-reset 1)
   (exec-mem 6064 3))
 (seg (? (= P 2))
   (exec-mem 6064 2 2)
   (menu1
    25
    317
    39
    317
    53
    317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var
    S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var
       S
       (</>
        (/ (nop@) (set-reg 114 #f) (flag-save 1))
        (/ (nop@) (set-reg 114 #f) (flag-save 2))
        (/ (nop@) (set-reg 114 #f) (flag-save 3))
        (/ (nop@) (set-reg 114 #f) (flag-save 4))
        (/ (nop@) (set-reg 114 #f) (flag-save 5))
        (/ (nop@) (set-reg 114 #f) (flag-save 6))
        (/ (nop@) (set-reg 114 #f) (flag-save 7))
        (/ (nop@) (set-reg 114 #f) (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18
       317
       32
       317
       46
       317
       60
       317
       18
       337
       32
       337
       46
       337
       60
       337
       66
       298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var
       S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))