(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB101.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB177.GPC")
  (image-mem 1 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC")
  (image-mem 1 0)
  (image-file "B:¥GPC¥DB178C.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "［スティーブ］何があったんだ？")
  (wait)
  (text-reset 1)
  (text "［コール］血清の入っていたバッグの中に、こんな物が入っていた　　　　　んです。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］手帳・・・？")
  (wait)
  (text-reset 1)
  (text "［コール］はい、中を見てください。")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 0 54 38,W 0,O 0")
  (text "［スティーブ］こ、これは！？")
  (wait)
  (text-reset 1)
  (text "［スティーブ］本物か？")
  (wait)
  (text-reset 1)
  (text
   "［コール］ええ、確かにドクの筆跡です。その手帳には、蘇生薬を　　　　　作る過程が細かく記されています。俺も、帰りの車の中　　　　　で見て驚きました。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］クーガー博士が、こんな物を残していたなんてな。")
  (wait)
  (text-reset 1)
  (text "［コール］その手帳は、ずっとバッグの中に入っていたようです。　　　　　誰の手にも触れられてはいません。")
  (wait)
  (text-reset 1)
  (text "［コール］だけど、ジルは蘇生薬を作っています。きっと、その手　　　　　帳のコピーか何かを参考に・・・。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］ちょっと待て。")
  (wait)
  (text-reset 1)
  (text "［コール］何か？")
  (wait)
  (text-reset 1)
  (text "［スティーブ］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］どうしたんですか？")
  (wait)
  (text-reset 1)
  (text "［スティーブ］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］・・残念ながら、コールの推測は違ったようだな。")
  (wait)
  (text-reset 1)
  (text "［コール］えっ？")
  (wait)
  (text-reset 1)
  (text "［スティーブ］手帳の最後のページを読んでみろ。")
  (wait)
  (text-reset 1)
  (text "［コール］最後のページ？")
  (wait)
  (text-reset 1)
  (text "［コール］・・・・・・これは！？")
  (wait)
  (text-reset 1)
  (text
   "『この手帳には、蘇生薬の製作過程について後半の半分だけ書かれ　ている。前半の載っている手帳が無いと、完全なる蘇生薬は完成　する事はまず不可能だろう』")
  (wait)
  (text-reset 1)
  (text "［コール］前半と後半！？")
  (wait)
  (text-reset 1)
  (text "［スティーブ］どうやら、その手帳は後半だけのようだな。")
  (wait)
  (text-reset 1)
  (text "『しかし２月２２日に、私の研究材料と一緒に前半の手帳を何者か　に盗まれてしまった。犯人は大体見当がついている』")
  (wait)
  (text-reset 1)
  (text
   "『その男は、学会でも人の研究を盗んでいるという不評がある男、　ドクタージルであろう。確信はないが、こんな事をするのは私の　周りには奴しかいない』")
  (wait)
  (text-reset 1)
  (text "［コール］ジルの事が載っている！？　ドクは何も言ってなかった　　　　　のに・・・。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］クーガー博士は、コールがこの手帳を見つけて読む　　　　　　　事を予測していたのだな・・・。")
  (wait)
  (text-reset 1)
  (text
   "『万が一、奴が前半の手帳に書かれているものだけで薬を作った場　合、決して死ぬ事のない狂暴な死霊が生まれるだろう。それだけ　は何としても食い止めなければならない』")
  (wait)
  (text-reset 1)
  (text "［コール］そうだ、墓地にいた死霊の事だ・・・。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］その死霊がどうした？")
  (wait)
  (text-reset 1)
  (text "［コール］脳を撃っても死ななかった・・・。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］なに！？")
  (wait)
  (text-reset 1)
  (text "［コール］そうか・・・前半の手帳を持っているジルが造った死霊　　　　　だったんだ・・・。")
  (wait)
  (text-reset 1)
  (text
   "［スティーブ］ちょっと待ってくれ・・・その前に、脳を破壊して　　　　　　　も死なない死霊を、コールは一体どうやって倒した　　　　　　　んだ？")
  (wait)
  (text-reset 1)
  (text "［コール］助けられました・・・何者かに。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］助けられたって・・・誰か判らないのか？")
  (wait)
  (text-reset 1)
  (text "［コール］死霊に襲われて、俺は崖に追い詰められました。もう、　　　　　殆ど諦めていた俺の目に、青白い閃光が見えたんです。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］閃光！？")
  (wait)
  (text-reset 1)
  (text "［コール］ええ、グールと同じタイプの物だと直感しました。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］！？")
  (wait)
  (text-reset 1)
  (text "［コール］そして、地面には明らかにアンドロイドの足跡が残って　　　　　いたんです。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］じゃあ、兄が・・・？")
  (wait)
  (text-reset 1)
  (text
   "［コール］いえ、俺も最初はそう考えたんですが、グールは２年前　　　　　に俺の目の前でフッ飛んでいます。スティーブさんも、　　　　　グールの頭部を持っています。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］なるほど・・・。")
  (wait)
  (text-reset 1)
  (text
   "［コール］それに、殺人機と化しているグールが俺を助けるなんて　　　　　事は絶対にしません。それは、彼と戦った俺が一番判っ　　　　　ている事です。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］・・・そうだったな。")
  (wait)
  (text-reset 1)
  (text "［コール］俺は多分、同タイプのアンドロイドではないかと・・。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］兄の他にもアンドロイドがいると？")
  (wait)
  (text-reset 1)
  (text "［コール］ええ、それも味方のね。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］味方なら、なぜ姿を現さなかったんだ？")
  (wait)
  (text-reset 1)
  (text "［コール］・・・判りません。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］それに、グールを造ったのはジルだ。あんな物を、　　　　　　　ジル以外の人間がそう簡単に造れるとは思えない。")
  (wait)
  (text-reset 1)
  (text "［コール］ジルの造ったアンドロイドが、俺を助ける筈はないし、　　　　　・・・じゃあ、あの閃光と足跡は一体なんなんだ？")
  (wait)
  (text-reset 1)
  (text "［スティーブ］直接ジルの所に行ってみた方がよさそうだな。")
  (wait)
  (text-reset 1)
  (text "［コール］だけど、ジルの居場所が・・・。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］コール、一番最後の行を読んでみろ。")
  (wait)
  (text-reset 1)
  (text "『一度、私もラスニュー・ビルに行かなければならないようだ』")
  (wait)
  (text-reset 1)
  (text "［コール］ラスニュービル！？")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 1 54 38,W 0,O 1")
  (exec-mem 912 "EXIT")
  (text "［コール］じゃあ、ドクは直接ジルに会いに行こうと・・・。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］・・・らしいな。")
  (wait)
  (text-reset 1)
  (text "［コール］ラスニュービルというのは？")
  (wait)
  (text-reset 1)
  (text
   "［スティーブ］第三地区にある荒廃した工場地帯にあるビルだよ。　　　　　　　世間では、ブラッディフォックスの拠点と恐れられ　　　　　　　警察ですら危険で近づく事はできなかった。")
  (wait)
  (text-reset 1)
  (text "［コール］ブラッディフォックスのアジトって訳か・・・。だけど　　　　　相手がどこにいようと、俺はジルを必ず仕留めますよ。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］今回ばかりはコールが頼りになるよ。")
  (wait)
  (text-reset 1)
  (text "［コール］だけどその前にシーラに血清を・・・。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］ああ、そうだな。")
  (wait)
  (text-reset 1)
  (sound '|| 2)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB113.GPC")
  (image-mem 0 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC")
  (image-mem 1 0)
  (image-file "B:¥GPC¥DB175C.GPC")
  (image-mem 1 0)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "［コール］シーラ、具合はどうだ？")
  (wait)
  (text-reset 1)
  (text "［シーラ］コール・・・私、なんだか全身に力が入らなくて・・。")
  (wait)
  (text-reset 1)
  (text "［コール］そうか・・・とにかく、この血清を打てば体内のＤＮＶ　　　　　が消滅する筈だよ。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］私がやろう。")
  (wait)
  (text-reset 1)
  (text "［コール］お願いします。シーラ、腕を出して。")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 0 54 38,W 0,O 0")
  (text "［コール］痛いか？")
  (wait)
  (text-reset 1)
  (text "［シーラ］ううん・・・感覚がない・・・。")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 1 54 38,W 0,O 1")
  (exec-mem 912 "EXIT")
  (text "［スティーブ］これでシーラが治ってくれればいいが・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text "［シーラ］コール、怖い顔してる・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］・・・・シーラ、俺達は少し研究所を空けるよ。")
  (wait)
  (text-reset 1)
  (text "［シーラ］どうして？")
  (wait)
  (text-reset 1)
  (text "［スティーブ］この事件の黒幕である男の所へ決着をつけに行って　　　　　　　くるんだよ。")
  (wait)
  (text-reset 1)
  (text "［シーラ］そう・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］だから、俺達が帰って来るまでゆっくり休んでろよ。")
  (wait)
  (text-reset 1)
  (text "［シーラ］私が死霊になる事を恐れて離れるのかと思った・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］馬鹿いうな・・・。")
  (wait)
  (text-reset 1)
  (text "［シーラ］コールとスティーブさんが、こんなに頑張っているのに　　　　　私は何もできないでベッドに寝てるなんて・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］いいんだよ。今はゆっくり休んで早く元気になってくれ　　　　　よ。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］さあ、そろそろ行こうか。")
  (wait)
  (text-reset 1)
  (text "［コール］はい。")
  (wait)
  (text-reset 1)
  (text "［シーラ］コール、スティーブさん・・・二人とも、死なないで。")
  (wait)
  (text-reset 1)
  (text "［スティーブ］ハハハ、俺達が死ぬ訳ないだろ。")
  (wait)
  (text-reset 1)
  (text "［コール］ジルごときに殺られてたまるかよ。")
  (wait)
  (text-reset 1)
  (text "［シーラ］・・・・・・・・・。")
  (wait)
  (text-reset 1)
  (text "［コール］じゃあな。")
  (wait)
  (text-reset 1)
  (sound '|| 2)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  ((cmd 204) 100 899)
  (mes-jump "A:¥MES¥104.MES"))
 (seg*))