(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB101.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB177.GPC")
  (image-mem 1 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC")
  (image-mem 1 0)
  (image-file "B:¥GPC¥DB178C.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "Steve: What's wrong?")
  (wait)
  (text-reset 1)
  (text "Cole: This was in the bag, alongside the serum.")
  (wait)
  (text-reset 1)
  (text "Steve: A notebook?")
  (wait)
  (text-reset 1)
  (text "Cole: Yeah. Take a look inside.")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 0 54 38,W 0,O 0")
  (text "Steve: What is this!?")
  (wait)
  (text-reset 1)
  (text "Steve: Is this for real?")
  (wait)
  (text-reset 1)
  (text
   "Cole: Yeah, that's Doc's handwriting. The notebook contains detailed instructions for making the reanimation serum. I saw it when I was driving back... I was shocked.")
  (wait)
  (text-reset 1)
  (text "Steve: I can't believe Dr. Cooger left something like this behind.")
  (wait)
  (text-reset 1)
  (text "Cole: It looks like the notebook's been in there all this time. Nobody's touched it.")
  (wait)
  (text-reset 1)
  (text "Cole: But Jill's making reanimation serum. You'd have thought he would have had a copy of this notebook or something for reference...")
  (wait)
  (text-reset 1)
  (text "Steve: Uh oh.")
  (wait)
  (text-reset 1)
  (text "Cole: What is it?")
  (wait)
  (text-reset 1)
  (text "Steve: ...")
  (wait)
  (text-reset 1)
  (text "Cole: What's wrong?")
  (wait)
  (text-reset 1)
  (text "Steve: ...")
  (wait)
  (text-reset 1)
  (text "Steve: ...")
  (wait)
  (text-reset 1)
  (text "Steve: Cole, I think your deduction is slightly off.")
  (wait)
  (text-reset 1)
  (text "Cole: What do you mean?")
  (wait)
  (text-reset 1)
  (text "Steve: Read the last page of the notebook.")
  (wait)
  (text-reset 1)
  (text "Cole: ...What the...")
  (wait)
  (text-reset 1)
  (text "Cole: ...Oh, shit.")
  (wait)
  (text-reset 1)
  (text
   "...'This notebook only contains the second half of the process for creating the serum. It would be almost impossible to create without the first notebook.'")
  (wait)
  (text-reset 1)
  (text "Cole: You mean to tell me there are TWO notebooks!?")
  (wait)
  (text-reset 1)
  (text "Steve: Yeah, and we've only got the second one.")
  (wait)
  (text-reset 1)
  (text "...'However, on Feb 22, someone stole the first half of the notebook along with my research materials, but I have a good idea who it was.'")
  (wait)
  (text-reset 1)
  (text
   "...'It's likely Dr. Jill, who has a poor reputation in the academic field for pilfering others' research. He's the only one in my circle who'd pull that kind of stunt.'")
  (wait)
  (text-reset 1)
  (text "Cole: It's all about Jill! Doc never mentioned him to me, though...")
  (wait)
  (text-reset 1)
  (text "Steve: Maybe Dr. Cooger predicted that you'd find and read the notebook...")
  (wait)
  (text-reset 1)
  (text
   "...'If you were to make a serum using only the instructions in the first half, it would create a virtually unkillable zombie. We must stop that at all costs.'")
  (wait)
  (text-reset 1)
  (text "Cole: Oh, shit. That's the super-zombie I saw in the cemetery.")
  (wait)
  (text-reset 1)
  (text "Steve: The WHAT?")
  (wait)
  (text-reset 1)
  (text "Cole: Even though I shot it in the brain, it kept coming.")
  (wait)
  (text-reset 1)
  (text "Steve: Headshots didn't work? That's a thing now!?")
  (wait)
  (text-reset 1)
  (text "Cole: Damn... So Jill made that zombie using only the first half of the notebooks...")
  (wait)
  (text-reset 1)
  (text
   "Steve: Wait a minute. If that zombie was unkillable, how'd you...uh, kill it?")
  (wait)
  (text-reset 1)
  (text "Cole: I didn't kill it. Someone else saved me.")
  (wait)
  (text-reset 1)
  (text "Steve: Who saved you?")
  (wait)
  (text-reset 1)
  (text "Cole: A zombie cornered me on the edge of a cliff. I'd almost given up, but then I saw a red flash.")
  (wait)
  (text-reset 1)
  (text "Steve: A flash?")
  (wait)
  (text-reset 1)
  (text "Cole: Yeah... The same type of thing as Ghoul.")
  (wait)
  (text-reset 1)
  (text "Steve: !?")
  (wait)
  (text-reset 1)
  (text "Cole: And there were clearly android footprints on the ground.")
  (wait)
  (text-reset 1)
  (text "Steve: Damn... My brother...?")
  (wait)
  (text-reset 1)
  (text
   "Cole: I thought the same thing, but I swear I saw Ghoul blown apart right in front of me. And you have part of his skull, for godsakes.")
  (wait)
  (text-reset 1)
  (text "Steve: I see...")
  (wait)
  (text-reset 1)
  (text
   "Cole: And there's no way a killing machine like Ghoul would ever save me. He's proven that in the past.")
  (wait)
  (text-reset 1)
  (text "Steve: That's true...")
  (wait)
  (text-reset 1)
  (text "Cole: So I suspect it's another android, but the same type.")
  (wait)
  (text-reset 1)
  (text "Steve: There was another android besides my brother?")
  (wait)
  (text-reset 1)
  (text "Cole: Yeah, and this one is on our side.")
  (wait)
  (text-reset 1)
  (text "Steve: If he's with us, why hasn't he shown himself?")
  (wait)
  (text-reset 1)
  (text "Cole: Your guess is as good as mine.")
  (wait)
  (text-reset 1)
  (text "Steve: Jill was the one who made Ghoul into what he was. I can't imagine anyone else would have the ability to make an android.")
  (wait)
  (text-reset 1)
  (text "Cole: A Jill-made android wouldn't have saved me, so... What was that flash, and those footprints, all about?")
  (wait)
  (text-reset 1)
  (text "Steve: We should head straight to Jill's place.")
  (wait)
  (text-reset 1)
  (text "Cole: But we don't even know where he is.")
  (wait)
  (text-reset 1)
  (text "Steve: Cole, read the last line in the notebook.")
  (wait)
  (text-reset 1)
  (text "...'It seems that I must make haste to the Lasnew Building.'")
  (wait)
  (text-reset 1)
  (text "Cole: The Lasnew Building?")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 1 54 38,W 0,O 1")
  (exec-mem 912 "EXIT")
  (text "Cole: So Doc was gonna go meet Jill face to face...")
  (wait)
  (text-reset 1)
  (text "Steve: Seems like it.")
  (wait)
  (text-reset 1)
  (text "Cole: What exactly is the Lasnew Building?")
  (wait)
  (text-reset 1)
  (text
   "Steve: It's a building in a dilapidated industrial zone in the third district. People know it as Bloody Fox's base, and even the cops won't go near it. Too dangerous.")
  (wait)
  (text-reset 1)
  (text "Cole: So it's Bloody Fox's hideout. I don't care where he is, I'm taking down Jill!")
  (wait)
  (text-reset 1)
  (text "Steve: I'm with you, Cole.")
  (wait)
  (text-reset 1)
  (text "Cole: But before we do that, we need to cure Sheila...")
  (wait)
  (text-reset 1)
  (text "Steve: That takes priority, yes.")
  (wait)
  (text-reset 1)
  (sound '|| 2)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB113.GPC")
  (image-mem 0 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC")
  (image-mem 1 0)
  (image-file "B:¥GPC¥DB175C.GPC")
  (image-mem 1 0)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (text "Cole: Sheila, how are you feeling?")
  (wait)
  (text-reset 1)
  (text "Sheila: Cole... I can't move my body anymore...")
  (wait)
  (text-reset 1)
  (text "Cole: It'll be okay. Once we inject you with this cure, the DNV in your body should disappear.")
  (wait)
  (text-reset 1)
  (text "Steve: Let me do it.")
  (wait)
  (text-reset 1)
  (text "Cole: Sheila, please... Hold out your arm.")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 0 54 38,W 0,O 0")
  (text "Cole: Does it hurt?")
  (wait)
  (text-reset 1)
  (text "Sheila: No... I can't feel anything...")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 1 54 38,W 0,O 1")
  (exec-mem 912 "EXIT")
  (text "Steve: I hope this heals our girl.")
  (wait)
  (text-reset 1)
  (text "Cole: ...")
  (wait)
  (text-reset 1)
  (text "Sheila: Cole, I don't like that look on your face... You look scared.")
  (wait)
  (text-reset 1)
  (text "Cole: Sheila, Steve and I are going to leave the lab for a little while.")
  (wait)
  (text-reset 1)
  (text "Sheila: Why?")
  (wait)
  (text-reset 1)
  (text "Steve: We're going to find the man who's behind all this, and we're going to end him.")
  (wait)
  (text-reset 1)
  (text "Sheila: You are...?")
  (wait)
  (text-reset 1)
  (text "Cole: So you just rest up until we get back.")
  (wait)
  (text-reset 1)
  (text "Sheila: I was afraid you were going to leave me here until I turned...")
  (wait)
  (text-reset 1)
  (text "Cole: Don't be silly...")
  (wait)
  (text-reset 1)
  (text "Sheila: It's just, you and Steve are out there risking everything, and here I am, lying in bed, worthless...")
  (wait)
  (text-reset 1)
  (text "Cole: You're not worthless. Just rest up and get well soon.")
  (wait)
  (text-reset 1)
  (text "Steve: It's about time we left, Cole.")
  (wait)
  (text-reset 1)
  (text "Cole: Roger that.")
  (wait)
  (text-reset 1)
  (text "Sheila: Cole, Steve... Don't you two die on me.")
  (wait)
  (text-reset 1)
  (text "Steve: Hahaha! There's no way we're dying. Not yet.")
  (wait)
  (text-reset 1)
  (text "Cole: There's no way someone like Jill could kill us.")
  (wait)
  (text-reset 1)
  (text "Sheila: ...")
  (wait)
  (text-reset 1)
  (text "Cole: See you later.")
  (wait)
  (text-reset 1)
  (sound '|| 2)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  ((cmd 204) 100 899)
  (mes-jump "A:¥MES¥104.MES"))
 (seg*))