; Dead of the Brain 2 (PC-98) - 103.MES
; Translated by Geometrizer
; Edited by JackDBS, commented by trentsignia
; -----Scene:-----
; Cole convenes with Steve regarding his latest findings.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB101.GPC") (image-mem 0 3)
  (image-file "B:¥GPC¥DB177.GPC") (image-mem 1 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC") (image-mem 1 0)
  (image-file "B:¥GPC¥DB178C.GPC") (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (str "Steve: What's wrong?")
  (wait)
  (text-reset 1)
  (str "Cole: This was in the bag, alongside the serum.")
  (wait)
  (text-reset 1)
  (str "Steve: A notebook?")
  (wait)
  (text-reset 1)
  (str "Cole: Yeah. Take a look inside.")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 0 54 38,W 0,O 0")
  (str "Steve: What is this!?")
  (wait)
  (text-reset 1)
  (str "Steve: Is this for real?")
  (wait)
  (text-reset 1)
  (str "Cole: Yeah, that's Doc's handwriting. The notebook contains" 'br)
  (str "detailed instructions for making the reanimation serum. I" 'br)
  (str "saw it when I was driving back... I was shocked.")
  (wait)
  (text-reset 1)
  (str "Steve: I can't believe Dr. Cooger left something like this" 'br)
  (str "behind.")
  (wait)
  (text-reset 1)
  (str "Cole: It looks like the notebook's been in there all this" 'br)
  (str "time. Nobody's touched it.")
  (wait)
  (text-reset 1)
  (str "Cole: But Jill's making reanimation serum. You'd have" 'br)
  (str "thought he would have had a copy of this notebook or" 'br)
  (str "something for reference...")
  (wait)
  (text-reset 1)
  (str "Steve: Uh oh.")
  (wait)
  (text-reset 1)
  (str "Cole: What is it?")
  (wait)
  (text-reset 1)
  (str "Steve: ...")
  (wait)
  (text-reset 1)
  (str "Cole: What's wrong?")
  (wait)
  (text-reset 1)
  (str "Steve: ...")
  (wait)
  (str "...")
  (wait)
  (text-reset 1)
  (str "Steve: Cole, I think your deduction is slightly off.")
  (wait)
  (text-reset 1)
  (str "Cole: What do you mean?")
  (wait)
  (text-reset 1)
  (str "Steve: Read the last page of the notebook.")
  (wait)
  (text-reset 1)
  (str "Cole: ...What the...")
  (wait)
  (text-reset 1)
  (str "Cole: ...Oh, shit.")
  (wait)
  (text-reset 1)
  (str "“This notebook only contains the second half of the" 'br)
  (str "  process for creating the serum. It would be almost" 'br)
  (str "  impossible to create without the first notebook.”")
  (wait)
  (text-reset 1)
  (str "Cole: You mean to tell me there are TWO notebooks!?")
  (wait)
  (text-reset 1)
  (str "Steve: Yeah, and we've only got the second one.")
  (wait)
  (text-reset 1)
  (str "“However, on Feb 22, someone stole the first half of the" 'br)
  (str "  notebook along with my research materials, but I have a" 'br)
  (str "  good idea who it was.”")
  (wait)
  (text-reset 1)
  (str "“It's likely Dr. Jill, who has a poor reputation in the" 'br)
  (str "  academic field for pilfering others' research. He's the" 'br)
  (str "  only one in my circle who'd pull that kind of stunt.”")
  (wait)
  (text-reset 1)
  (str "Cole: It's all about Jill! Doc never mentioned him to me," 'br)
  (str "though...")
  (wait)
  (text-reset 1)
  (str "Steve: Maybe Dr. Cooger predicted that you'd find and read" 'br)
  (str "the notebook...")
  (wait)
  (text-reset 1)
  (str "“If you were to make a serum using only the instructions" 'br)
  (str "  in the first half, it would create a virtually unkillable" 'br)
  (str "  zombie. We must stop that at all costs.”")
  (wait)
  (text-reset 1)
  (str "Cole: Oh, shit. That's the super-zombie I saw in the" 'br)
  (str "cemetery.")
  (wait)
  (text-reset 1)
  (str "Steve: The WHAT?")
  (wait)
  (text-reset 1)
  (str "Cole: Even though I shot it in the brain, it kept coming.")
  (wait)
  (text-reset 1)
  (str "Steve: Headshots didn't work? That's a thing now!?")
  (wait)
  (text-reset 1)
  (str "Cole: Damn... So Jill made that zombie using only the first" 'br)
  (str "half of the notebooks...")
  (wait)
  (text-reset 1)
  (str "Steve: Wait a minute. If that zombie was unkillable, how'd" 'br)
  (str "you...uh, kill it?")
  (wait)
  (text-reset 1)
  (str "Cole: I didn't kill it. Someone else saved me.")
  (wait)
  (text-reset 1)
  (str "Steve: Who saved you?")
  (wait)
  (text-reset 1)
  (str "Cole: A zombie cornered me on the edge of a cliff. I" 'br)
  (str "nearly gave up, but then I saw a red flash.")
  (wait)
  (text-reset 1)
  (str "Steve: A flash?")
  (wait)
  (text-reset 1)
  (str "Cole: Yeah... The same type of thing Ghoul did.")
  (wait)
  (text-reset 1)
  (str "Steve: !?")
  (wait)
  (text-reset 1)
  (str "Cole: And there were clearly android footprints on the" 'br)
  (str "ground.")
  (wait)
  (text-reset 1)
  (str "Steve: Damn... My brother...?")
  (wait)
  (text-reset 1)
  (str "Cole: I thought the same thing, but I swear I saw Ghoul" 'br)
  (str "blown apart right in front of me. And you have part of his" 'br)
  (str "skull, for godsakes.")
  (wait)
  (text-reset 1)
  (str "Steve: I see...")
  (wait)
  (text-reset 1)
  (str "Cole: And there's no way a killing machine like Ghoul would" 'br)
  (str "ever save me. He's proven that in the past.")
  (wait)
  (text-reset 1)
  (str "Steve: That's true...")
  (wait)
  (text-reset 1)
  (str "Cole: So I suspect it's another android, but the same type.")
  (wait)
  (text-reset 1)
  (str "Steve: There was another android besides my brother?")
  (wait)
  (text-reset 1)
  (str "Cole: Yeah, and this one is on our side.")
  (wait)
  (text-reset 1)
  (str "Steve: If he's with us, why hasn't he shown himself?")
  (wait)
  (text-reset 1)
  (str "Cole: Your guess is as good as mine.")
  (wait)
  (text-reset 1)
  (str "Steve: Jill was the one who made Ghoul into what he was. I" 'br)
  (str "can't imagine anyone else would have the ability to make an" 'br)
  (str "android.")
  (wait)
  (text-reset 1)
  (str "Cole: A Jill-made android wouldn't have saved me, so..." 'br)
  (str "What was that flash, and those footprints, all about?")
  (wait)
  (text-reset 1)
  (str "Steve: We should head straight to Jill's place.")
  (wait)
  (text-reset 1)
  (str "Cole: But we don't even know where he is.")
  (wait)
  (text-reset 1)
  (str "Steve: Cole, read the last line in the notebook.")
  (wait)
  (text-reset 1)
  (str "“It seems that I must make haste to the Lasnew Building.”")
  (wait)
  (text-reset 1)
  (str "Cole: The Lasnew Building?")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 1 54 38,W 0,O 1")
  (exec-mem 912 "EXIT")
  (str "Cole: So Doc was gonna go meet Jill face to face...")
  (wait)
  (text-reset 1)
  (str "Steve: Seems like it.")
  (wait)
  (text-reset 1)
  (str "Cole: What exactly is the Lasnew Building?")
  (wait)
  (text-reset 1)
  (str "Steve: It's a building in a dilapidated industrial zone in" 'br)
  (str "the third district. People know it as Bloody Fox's base, so" 'br)
  (str "not even cops will go near it. Too dangerous.")
  (wait)
  (text-reset 1)
  (str "Cole: So it's Bloody Fox's hideout. I don't care where he" 'br)
  (str "is, I'm taking down Jill!")
  (wait)
  (text-reset 1)
  (str "Steve: I'm with you, Cole.")
  (wait)
  (text-reset 1)
  (str "Cole: But before we do that, we need to cure Sheila...")
  (wait)
  (text-reset 1)
  (str "Steve: That takes priority, yes.")
  (wait)
  (text-reset 1)
  (sound '|| 2)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB113.GPC") (image-mem 0 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC") (image-mem 1 0)
  (image-file "B:¥GPC¥DB175C.GPC") (image-mem 1 0)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 3)
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (str "Cole: Sheila, how are you feeling?")
  (wait)
  (text-reset 1)
  (str "Sheila: Cole... I can't move my body anymore...")
  (wait)
  (text-reset 1)
  (str "Cole: It'll be okay. Once we inject you with this cure, the" 'br)
  (str "DNV in your body should disappear.")
  (wait)
  (text-reset 1)
  (str "Steve: Let me do it.")
  (wait)
  (text-reset 1)
  (str "Cole: Sheila, please... Hold out your arm.")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 0 54 38,W 0,O 0")
  (str "Cole: Does it hurt?")
  (wait)
  (text-reset 1)
  (str "Sheila: No... I can't feel anything...")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 1 54 38,W 0,O 1")
  (exec-mem 912 "EXIT")
  (str "Steve: I hope this heals our girl.")
  (wait)
  (text-reset 1)
  (str "Cole: ...")
  (wait)
  (text-reset 1)
  (str "Sheila: Cole, I don't like that look on your face... You" 'br)
  (str "look scared.")
  (wait)
  (text-reset 1)
  (str "Cole: Sheila, Steve and I are going to leave the lab for a" 'br)
  (str "little while.")
  (wait)
  (text-reset 1)
  (str "Sheila: Why?")
  (wait)
  (text-reset 1)
  (str "Steve: We're going to find the man who's behind all this," 'br)
  (str "and we're going to end him.")
  (wait)
  (text-reset 1)
  (str "Sheila: You are...?")
  (wait)
  (text-reset 1)
  (str "Cole: So you just rest up until we get back.")
  (wait)
  (text-reset 1)
  (str "Sheila: I was afraid you were going to leave me here until" 'br)
  (str "I turned...")
  (wait)
  (text-reset 1)
  (str "Cole: Don't be silly...")
  (wait)
  (text-reset 1)
  (str "Sheila: It's just, you and Steve are out there risking" 'br)
  (str "everything, and here I am, lying in bed, worthless...")
  (wait)
  (text-reset 1)
  (str "Cole: You're not worthless. Just rest up and get well soon.")
  (wait)
  (text-reset 1)
  (str "Steve: It's about time we left, Cole.")
  (wait)
  (text-reset 1)
  (str "Cole: Roger that.")
  (wait)
  (text-reset 1)
  (str "Sheila: Cole, Steve... Don't you two die on me.")
  (wait)
  (text-reset 1)
  (str "Steve: Hahaha! There's no way we're dying. Not yet.")
  (wait)
  (text-reset 1)
  (str "Cole: There's no way someone like Jill could kill us.")
  (wait)
  (text-reset 1)
  (str "Sheila: ...")
  (wait)
  (text-reset 1)
  (str "Cole: See you later.")
  (wait)
  (text-reset 1)
  (sound '|| 2)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  ((cmd 204) 100 899)
  (mes-jump "A:¥MES¥104.MES"))
 (seg*))