; Dead of the Brain 2 (PC-98) - 107.MES
; Translated by Geometrizer
; Edited by JackDBS, commented by trentsignia
; -----Scene:-----
; Confronting the last of Bloody Fox.
; --Progression:--
; Talk to the woman, then Briar.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "A:¥CLM¥DB183.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 6 5 1)			; Hotspots and buttons defined here...
  (exec-mem 3744 1 1 80 0 0 0)							; 	MOVE button
  (exec-mem 3744 1 2 80 0 0 0)							; 	SYSTEM button
  (exec-mem 3744 1 5 28 3 34 6)							; 	Briar
  (exec-mem 3744 1 6 37 4 42 7)							; 	Woman
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB183.GPC") (image-mem 0 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 40 0 40 400 1 40 0")
  (exec-mem 912 "A 1")
  (image-file "A:¥GPC¥DB_FRM2.GPC") (image-mem 1 0)
  (image-file "B:¥GPC¥DB184C.GPC") (image-mem 1 3)
  (exec-mem 912 "GET 0 54 38 23 134")
  (exec-mem 912 "A 0")
  (exec-mem 912 "GET 1 54 38 23 172")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_08.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_08.USO"))))
  (sound '|| 1)
  (if (</>
       (//
        (? (= 127 #f))								; Lead-in from previous MES file
        (str "Cole: Don't move!")
        (wait)
        (text-reset 1)
        (str "Briar: Whuh?")
        (wait)
        (text-reset 1)
        (str "Steve: This is where it ends, Briar.")
        (wait)
        (text-reset 1)
        (str "Briar: Ohhh, you two have come this far, eh?")
        (set-reg 127 #t)
        (wait)
        (text-reset 1))
       (//
        (str "Briar: Amazing you've come this far, but this is where" 'br)	; Lead-in from loading game
        (str "you're both going to die.")
        (wait)
        (text-reset 1))))
  (loop (exec-mem 3744 3 "P" 32768) (text-color 15) (text-reset 1) (seg-call)))
 (seg (? (= P 5) (= 131 #t) (= 132 #t))						; Briar (after talking to him and Woman)
   (str "Cole: Give it to me straight. Where's Jill?")
   (wait)
   (text-reset 1)
   (str "Briar: Jesus, you're fucking stupid. You think I'd tell you" 'br)
   (str "that?")
   (wait)
   (text-reset 1)
   (str "Steve: Briar, that confidence seems misplaced.")
   (wait)
   (text-reset 1)
   (str "Briar: ...Says the guy with no powers of observation.")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 0 54 38,W 0,O 0")
   (str "B.F.: Don't move!")
   (wait)
   (text-reset 1)
   (str "Cole: !?")
   (wait)
   (text-reset 1)
   (str "B.F.: Hand over the gun.")
   (wait)
   (text-reset 1)
   (str "Cole: Dammit!")
   (wait)
   (text-reset 1)
   (str "Briar: Steve, don't you get it? Bloody Fox's leader can't" 'br)
   (str "get by on muscle alone.")
   (wait)
   (text-reset 1)
   (str "Steve: So you're saying it takes a cool head and good" 'br)
   (str "judgment too? What a guy.")
   (wait)
   (text-reset 1)
   (exec-mem 912 "PUT 1 54 38,W 0,O 1")
   (exec-mem 912 "EXIT")
   (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
   (nop@)
   (set-reg 133 #t)
   (mes-jump "A:¥MES¥108.MES"))
 (seg (? (= P 5) (= 128 #f))							; Briar #1
   (str "Briar: Steve, Steve, Steve. I heard you used to be a" 'br)
   (str "detective. Is that right?")
   (wait)
   (text-reset 1)
   (str "Steve: Took you long enough to realize it.")
   (wait)
   (text-reset 1)
   (str "Briar: Well, either way, you've fucked with us one too many" 'br)
   (str "times, and it's over for you.")
   (wait)
   (text-reset 1)
   (str "Cole: What's with the misplaced confidence? That Purple Sky" 'br)
   (str "go to your brain?")
   (wait)
   (text-reset 1)
   (str "Briar: You would know, looking at what happened to your" 'br)
   (str "woman...")
   (set-reg 128 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 129 #f))							; Briar #2
   (str "Steve: Not eating? You're looking pretty scrawny these" 'br)
   (str "days, Briar. It won't take more than a single bullet to end" 'br)
   (str "you.")
   (wait)
   (text-reset 1)
   (str "Cole: I bet you're regretting becoming Daniel's lapdog.")
   (wait)
   (text-reset 1)
   (str "Briar: Hah! I was told to follow Daniel's orders. There's" 'br)
   (str "no way I would have trusted that old fart in the first" 'br)
   (str "place.")
   (wait)
   (text-reset 1)
   (str "Steve: Jill's the one pulling the strings, isn't he.")
   (set-reg 129 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 130 #f))							; Briar #3
   (str "Briar: Daniel didn't just destroy the city... He killed our" 'br)
   (str "friends, too. I was planning on settling things with him" 'br)
   (str "someday, but it looks like you already did the job.")
   (wait)
   (text-reset 1)
   (str "Steve: So in the end, you're all that remains of Bloody Fox?")
   (wait)
   (text-reset 1)
   (str "Briar: If anyone else was left, they would have ventilated" 'br)
   (str "you the second you stepped foot in here.")
   (set-reg 130 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5) (= 131 #f))							; Briar #4
   (str "Briar: Steve, when you first came into Bar Rease, one of my" 'br)
   (str "low-level guys picked a fight with you. You beat the shit" 'br)
   (str "out of them brilliantly.")
   (wait)
   (text-reset 1)
   (str "Briar: Nobody's fucked with you since then. I was planning" 'br)
   (str "on settling the score with you someday, but...")
   (wait)
   (text-reset 1)
   (str "Briar: When Cole came to the bar... You took matters into" 'br)
   (str "your own hands, and took Sheila.")
   (wait)
   (text-reset 1)
   (str "Briar: But we already injected her with the high-grade" 'br)
   (str "Purple Sky. She'll be suckin' out people's brains in a" 'br)
   (str "matter of time.")
   (wait)
   (text-reset 1)
   (str "Cole: Hopefully she'll start with yours.")
   (wait)
   (text-reset 1)
   (str "Briar: *Snort* Look at this big talker.")
   (set-reg 131 #t)
   (wait)
   (text-reset 1))
 (seg (? (= P 5))								; Briar #5 (repeat line)
   (str "Briar: Snort, Look at this big talker.")
   (wait)
   (text-reset 1))
 (seg (? (= P 6))								; Woman
   (branch-random
    (</>
     (/
      (str "Woman: Whaaa? You got something to say to me?")
      (wait)
      (text-reset 1)
      (str "Briar: Don't sweat it, these guys are gonna die anyway.")
      (wait)
      (text-reset 1))
     (/
      (str "Cole: You having fun hanging out with big man Briar over" 'br)
      (str "there?")
      (wait)
      (text-reset 1)
      (str "Woman: It's none of your business, twerp.")
      (wait)
      (text-reset 1))
     (/
      (str "Woman: Briar, would you kill these guys sooner rather than" 'br)
      (str "later?")
      (wait)
      (text-reset 1)
      (str "Briar: Mm... Let's not be too hasty.")
      (wait)
      (text-reset 1))))
   (set-reg 132 #t))
 (seg (? (= P 2))								; SYSTEM
   (text-reset 1)
   (exec-mem 6064 2 2)
   (menu1
    25 317  39 317  53 317
    (</> (/ (str "  SAVE  ")) (/ (str "  LOAD  ")) (/ (str " CANCEL "))))
   (text-reset 1)
   (if (</> (// (? (= S 255)) (nop@) (set-var S 2))))
   (branch-var S
    (</>
     (/
      (str "Select Save Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " SAVE No.1 "))
        (/ (str " SAVE No.2 "))
        (/ (str " SAVE No.3 "))
        (/ (str " SAVE No.4 "))
        (/ (str " SAVE No.5 "))
        (/ (str " SAVE No.6 "))
        (/ (str " SAVE No.7 "))
        (/ (str " SAVE No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (text #:col 15 'br)
      (text "　　　　　　　　　　　　　")
      (str "WAIT....")
      (branch-var S
       (</>
        (/ (flag-save 1))
        (/ (flag-save 2))
        (/ (flag-save 3))
        (/ (flag-save 4))
        (/ (flag-save 5))
        (/ (flag-save 6))
        (/ (flag-save 7))
        (/ (flag-save 8))
        (/ (nop@)))))
     (/
      (str "Select Load Number.")
      (menu1
       18 317  32 317  46 317  60 317
       18 337  32 337  46 337  60 337  66 298
       (</>
        (/ (str " LOAD No.1 "))
        (/ (str " LOAD No.2 "))
        (/ (str " LOAD No.3 "))
        (/ (str " LOAD No.4 "))
        (/ (str " LOAD No.5 "))
        (/ (str " LOAD No.6 "))
        (/ (str " LOAD No.7 "))
        (/ (str " LOAD No.8 "))
        (/ (str "[CANCEL]"))))
      (text-reset 1)
      (if (</> (// (? (= S 255)) (nop@) (set-var S 8))))
      (exec-mem 6064 3)
      (branch-var S
       (</>
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 1))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 2))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 3))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 4))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 5))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 6))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 7))
        (/ (exec-mem 9920 0 6 6 113 64 0) (flag-load 8))
        (/ (nop@)))))
     (/ (nop@))))
   (text-reset 1)
   (exec-mem 6064 3))
 (seg*))