(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB193.GPC")
  (image-mem 0 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 2 23 40 238 1 2 23")
  (exec-mem 912 "C 0 40 23 18 238 1 40 23")
  (exec-mem 912 "A 1")
  (image-file "B:¥GPC¥DB194L.GPC")
  (image-mem 1 0)
  (exec-mem 912 "GET 0 2 23 54 238")
  (image-file "B:¥GPC¥DB203L.GPC")
  (image-mem 1 0)
  (exec-mem 912 "GET 1 2 23 54 238")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (str "Cole: What... Where the hell is this?")
  (wait)
  (text-reset 1)
  (str "Steve: Shh! Someone's here!")
  (wait)
  (text-reset 1)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_12.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_12.USO"))))
  (sound '|| 1)
  (exec-mem 912 "PUT 0 2 23,W 0,O 0")
  (str "Man: Admirable. You two made it here intact.")
  (wait)
  (text-reset 1)
  (str "Steve: Jill!?")
  (wait)
  (text-reset 1)
  (str "Jill: I welcome you both to the laboratory of Doctor Jill.")
  (wait)
  (text-reset 1)
  (str "Cole: So YOU'RE Jill!")
  (wait)
  (text-reset 1)
  (str "Jill: Can I assume the tall one is Steve, and the...other" 'br)
  (str "one...is Cole?")
  (wait)
  (text-reset 1)
  (str "Cole: So you were the mastermind behind the incident two" 'br)
  (str "years ago.")
  (wait)
  (text-reset 1)
  (str "Jill: Such a rude demeanor, tossing that out after we just" 'br)
  (str "met.")
  (wait)
  (text-reset 1)
  (str "Steve: You stole Dr. Cooger's research and used an army of" 'br)
  (str "zombies to kill countless people. That's a helluva crime.")
  (wait)
  (text-reset 1)
  (if (</>
       (//
        (? (= 901 #t))
        (str "Cole: And we know you used Doc's notebook to make an" 'br)
        (str "incomplete reanimation serum!")
        (wait)
        (text-reset 1))))
  (exec-mem 912 "PUT 1 2 23,W 0,O 0")
  (exec-mem 912 "EXIT")
  (str "Jill: You mean this notebook? Yes, thanks to what's written" 'br)
  (str "within, I've gained powers that surpass those of even God" 'br)
  (str "himself.")
  (wait)
  (text-reset 1)
  (if (</>
       (//
        (? (= 901 #f))
        (str "Cole: The notebook...?")
        (wait)
        (text-reset 1)
        (str "Jill: Hoho, you two didn't know about the notebook?")
        (wait)
        (text-reset 1)
        (str "Steve: What are you talking about?")
        (wait)
        (text-reset 1)
        (str "Jill: This notebook clearly details everything about the" 'br)
        (str "reanimation serum. Since I took it from Cooger's house two" 'br)
        (str "years ago, I've appended my own exhaustive research.")
        (wait)
        (text-reset 1)
        (str "Cole: Are you telling us that Doc left a notebook behind?")
        (wait)
        (text-reset 1)
        (str "Jill: Heh heh... And thanks to it, I've harnessed the power" 'br)
        (str "of a god.")
        (wait)
        (text-reset 1)
        (str "Cole: So that's it... Two years ago, someone ransacked Doc's" 'br)
        (str "lab. That was you, wasn't it?")
        (wait)
        (text-reset 1)
        (str "Jill: Heh heh heh... Just putting things together now, are" 'br)
        (str "you?")
        (wait)
        (text-reset 1))))
  (str "Jill: Cooger managed to develop the serum, but he could" 'br)
  (str "never master it himself.")
  (wait)
  (text-reset 1)
  (str "Jill: That's what sets me apart. With this serum, every man," 'br)
  (str "woman, and child on Earth will kneel before me!")
  (wait)
  (text-reset 1)
  (str "Steve: Bullshit! What you want is to unleash hell on Earth!")
  (wait)
  (text-reset 1)
  (str "Cole: Stealing other people's research... How can you even" 'br)
  (str "call yourself a scientist?")
  (wait)
  (text-reset 1)
  (str "Jill: Semantics, semantics. Nobody's getting in my way" 'br)
  (str "anymore.")
  (wait)
  (text-reset 1)
  (str "Jill: Just look at my skull... Two years ago, Ghoul was my" 'br)
  (str "test subject for the serum. But one day he betrayed me and" 'br)
  (str "I received damage that would be fatal.")
  (wait)
  (text-reset 1)
  (str "Jill: And then with the last of my strength, I injected" 'br)
  (str "myself with the reanimation serum and came back to life!")
  (wait)
  (text-reset 1)
  (str "Cole: So Ghoul was lying when he told me he ended you." 'br)
  (str "Can't trust an android.")
  (wait)
  (text-reset 1)
  (str "Cole: But mark my words, you're dying by my hands, right" 'br)
  (str "now!")
  (wait)
  (text-reset 1)
  (str "Jill: Oh, such vigor, Cole! Then let the show begin. Your" 'br)
  (str "first opponent shall be a zombie revived by my newly" 'br)
  (str "completed serum.")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB193.GPC")
  (image-mem 0 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 2 23 40 238 1 2 23")
  (exec-mem 912 "C 0 40 23 18 238 1 40 23")
  (exec-mem 912 "A 1")
  (image-file "B:¥GPC¥DB195L.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 0 2 23 55 238")
  (image-file "B:¥GPC¥DB194L.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB194R.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 1 2 23 55 238")
  (image-file "B:¥GPC¥DB195R.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 2 2 23 55 238")
  (exec-mem 912 "A 0,S 0")
  ((cmd 193) 0 "B:¥GPA¥DB193A.GPA")
  ((cmd 193) 1 "B:¥GPA¥DB194L.GPA")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  ((cmd 196) 0 0)
  ((cmd 196) 0 1)
  (delay 8 0)
  ((cmd 196) 0 2)
  (delay 8 0)
  ((cmd 196) 0 3)
  (delay 10 0)
  ((cmd 196) 0 4)
  (str "Cole: !?")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 0 2 23,W 0,O 0")
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 1)
  (str "Steve: Is that you...Catherine!?")
  (wait)
  (text-reset 1)
  (str "Catherine: Cole...Steve!")
  (wait)
  (text-reset 1)
  (str "Cole: Catherine! We thought you were dead!")
  (wait)
  (text-reset 1)
  (str "Catherine: Steve... Help me!")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 1 2 23,W 0,O 0")
  (str "Steve: Catherine, you're all right now...")
  (wait)
  (text-reset 1)
  (str "Cole: We thought... We all thought you were dead...")
  (wait)
  (text-reset 1)
  ((cmd 196) 1 0)
  ((cmd 196) 1 1)
  (delay 4 0)
  ((cmd 196) 1 2)
  (str "Jill: Heh heh heh...")
  (wait)
  (text-reset 1)
  ((cmd 193) 0 "B:¥GPA¥DB196RB.GPA")
  ((cmd 193) 1 "B:¥GPA¥DB196RBB.GPA")
  ((cmd 194) 0 "ｱ..ｲ..ｳ..ｱ..ｲ..ｳ..ｱ..ｲ..ｳ..")
  (str "Cole: Wait, Steve, don't--")
  (wait)
  (text-reset 1)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_05.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_05.USO"))))
  (sound '|| 1)
  (exec-mem 912 "PUT 2 2 23,W 0,O 0")
  (exec-mem 912 "EXIT")
  ((cmd 197) 0 15)
  (str "Steve: Aaaaaaaaaaghhhhhh!")
  (wait)
  (text-reset 1)
  (str "Cole: CATHERINE!!!")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 0)
  (image-file "A:¥GPC¥COUNTER.GPC")
  (image-mem 0 0)
  (load-mem "A:¥CLM¥DB195R.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 3 2 0)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 5 34 5 40 8)
  (exec-mem 15728 0 0 0 3 0 1)
  (exec-mem 15728 1 0 0 0 0 "Z")
  (exec-mem 15728 2 1)
  (exec-mem 15456 0)
  (exec-mem 14544 2 0)
  (exec-mem 15728 3)
  (exec-mem 3744 3 "P" 32768)
  (exec-mem 15728 4)
  (image-file "A:¥GPC¥DB_FRM3.GPC")
  (image-mem 0 0)
  (if (</>
       (//
        (? (= Z 2) (= P 5))
        ((cmd 196) 1 0)
        (sound '|se | 13)
        ((cmd 196) 1 1)
        (delay 4)
        ((cmd 196) 1 2)
        (delay 4)
        ((cmd 196) 1 3)
        (delay 8)
        ((cmd 196) 1 4)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (image-file "B:¥GPC¥DB197.GPC")
        (image-mem 0 3)
        (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
        (exec-mem 912 "A 1")
        (image-file "A:¥GPC¥DB_FRM.GPC")
        (image-mem 0 3)
        (image-file "B:¥GPC¥DB197B.GPC")
        (image-mem 0 3)
        (exec-mem 912 "A 0,S 0")
        (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
        (str "Cole: Catherine...")
        (wait)
        (text-reset 1)
        (str "Catherine: ...Cole...")
        (wait)
        (text-reset 1)
        (exec-mem 23216 2 23 79 238 11 0)
        (str "Jill: Heh heh heh...")
        (wait)
        (text-reset 1)
        (str "Cole: You...you...!!!")
        (wait)
        (text-reset 1)
        (str "Jill: My goodness, no hesitation whatsoever in gunning down" 'br)
        (str "a female ally when you assume she's a zombie...")
        (wait)
        (text-reset 1)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (image-file "B:¥GPC¥DB193.GPC")
        (image-mem 0 3)
        (image-file "B:¥GPC¥DB194L.GPC")
        (image-mem 1 3)
        (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
        (exec-mem 912 "C 0 2 23 40 238 1 2 23")
        (exec-mem 912 "C 0 40 23 18 238 1 40 23")
        (exec-mem 912 "A 1")
        (exec-mem 912 "GET 0 2 23 55 238")
        (image-file "B:¥GPC¥DB198R.GPC")
        (image-mem 1 3)
        (image-file "B:¥GPC¥DB198L.GPC")
        (image-mem 1 3)
        (exec-mem 912 "GET 1 2 23 55 238")
        (exec-mem 912 "A 0,S 0")
        ((cmd 193) 0 "B:¥GPA¥DB193B.GPA")
        (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
        (str "Cole: I'll never forgive you, you reptilian shit!")
        (wait)
        (text-reset 1)
        (str "Jill: I admire that spunk of yours, but maybe you should" 'br)
        (str "worry about your friend Steve's neck injury...?")
        (wait)
        (text-reset 1)
        (str "Cole: What!?")
        (wait)
        (text-reset 1)
        (str "Jill: Soon Steve will follow suit. You haven't forgotten the" 'br)
        (str "serum acts as a virus, have you?")
        (wait)
        (text-reset 1)
        (exec-mem 912 "PUT 0 2 23,W 0,O 0")
        (str "Steve: Let me ask you, Jill... My brother... What happened" 'br)
        (str "to Ghoul's corpse at Bayside?")
        (wait)
        (text-reset 1)
        (exec-mem 912 "PUT 1 2 23,W 0,O 0")
        (str "Jill: Oh, so Ghoul was your brother! That makes things" 'br)
        (str "interesting. I resuscitated your brother's remains at" 'br)
        (str "Bayside...")
        (wait)
        (text-reset 1)
        (str "Jill: The head had been obliterated, but the brain suffered" 'br)
        (str "no damage. I simply removed the brain and brought it back" 'br)
        (str "here...")
        (wait)
        (text-reset 1)
        (str "Jill: To see the younger brother come seeking his older" 'br)
        (str "brother... Today will be an extra special day for you," 'br)
        (str "Steve.")
        (exec-mem 912 "PUT 0 2 23,W 0,O 0")
        (exec-mem 912 "EXIT")
        (wait)
        (text-reset 1)
        ((cmd 196) 0 0)
        ((cmd 196) 0 1)
        (delay 8 0)
        ((cmd 196) 0 2)
        (delay 8 0)
        ((cmd 196) 0 3)
        (delay 10 0)
        ((cmd 196) 0 4)
        (str "Cole: !?")
        (wait)
        (text-reset 1)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (mes-jump "A:¥MES¥110.MES"))
       (//
        (str "Catherine: GUAAAAAA!!!")
        (wait)
        (text-reset 1)
        (sound '|| 0)
        (sound '|se | 10)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (text "　　　　　　　　　　ＧＡＭＥ　ＯＶＥＲ")
        (menu1 32 337 48 337 (</> (/ (str "CONTINUE")) (/ (str "GAME END"))))
        (text-reset 1)
        (branch-var
         S
         (</>
          (/ (exec-mem 9920 0 6 6 113 64 0) (mes-jump "A:¥MES¥109.MES"))
          (/
           (text "　　　　　ＮＩＧＨＴＭＡＲＥ　ＣＯＬＬＥＣＴＩＯＮ" 'br)
           (text "　　　　　　ＤＥＡＤ　ＯＦ　ＴＨＥ　ＢＲＡＩＮⅡ" 'br)
           (text "　　　　　　　　　　　ＧＡＭＥ　ＥＮＤ")
           (loop (wait)))))))))
 (seg*))