(mes
 (meta (engine 'ADV) (charset "English") (extraop #t))
 (seg*
  (exec-mem 9920 0 6 6 113 64 0)
  (image-file "B:¥GPC¥DB193.GPC")
  (image-mem 0 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 2 23 40 238 1 2 23")
  (exec-mem 912 "C 0 40 23 18 238 1 40 23")
  (exec-mem 912 "A 1")
  (image-file "B:¥GPC¥DB194L.GPC")
  (image-mem 1 0)
  (exec-mem 912 "GET 0 2 23 54 238")
  (image-file "B:¥GPC¥DB203L.GPC")
  (image-mem 1 0)
  (exec-mem 912 "GET 1 2 23 54 238")
  (exec-mem 912 "A 0,S 0")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  (sound '|| 0)
  (text "Cole: What... Where the hell is this?")
  (wait)
  (text-reset 1)
  (text "Steve: Shh! Someone's here!")
  (wait)
  (text-reset 1)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_12.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_12.USO"))))
  (sound '|| 1)
  (exec-mem 912 "PUT 0 2 23,W 0,O 0")
  (text "Man: Admirable. You two made it here intact.")
  (wait)
  (text-reset 1)
  (text "Steve: Jill!?")
  (wait)
  (text-reset 1)
  (text "Jill: I welcome you both to the laboratory of Doctor Jill.")
  (wait)
  (text-reset 1)
  (text "Cole: So YOU'RE Jill!")
  (wait)
  (text-reset 1)
  (text "Jill: Can I assume the tall one is Steve, and the...other one...is Cole?")
  (wait)
  (text-reset 1)
  (text "Cole: So you were the mastermind behind the incident two years ago.")
  (wait)
  (text-reset 1)
  (text "Jill: Such a rude demeanor, tossing that out after we just met.")
  (wait)
  (text-reset 1)
  (text "Steve: You stole Dr. Cooger's research and used an army of zombies to kill countless people. That's a helluva crime.")
  (wait)
  (text-reset 1)
  (if (</>
       (//
        (? (= 901 #t))
        (text "Cole: And we know you used Doc's notebook to make an incomplete reanimation serum!")
        (wait)
        (text-reset 1))))
  (exec-mem 912 "PUT 1 2 23,W 0,O 0")
  (exec-mem 912 "EXIT")
  (text "Jill: You mean this notebook? Yes, thanks to what's written within, I've gained powers that surpass those of even God himself.")
  (wait)
  (text-reset 1)
  (if (</>
       (//
        (? (= 901 #f))
        (text "Cole: The notebook...?")
        (wait)
        (text-reset 1)
        (text "Jill: Hoho, you two didn't know about the notebook?")
        (wait)
        (text-reset 1)
        (text "Steve: What are you talking about?")
        (wait)
        (text-reset 1)
        (text
         "Jill: This notebook clearly details everything about the reanimation serum. Since I took it from Cooger's house two years ago, I've appended my own exhaustive research.")
        (wait)
        (text-reset 1)
        (text "Cole: Are you telling us that Doc left a notebook behind?")
        (wait)
        (text-reset 1)
        (text "Jill: Heh heh... And thanks to it, I've harnessed the power of a god.")
        (wait)
        (text-reset 1)
        (text "Cole: So that's it... Two years ago, someone ransacked Doc's lab. That was you, wasn't it?")
        (wait)
        (text-reset 1)
        (text "Jill: Heh heh heh... Just putting things together now, are you?")
        (wait)
        (text-reset 1))))
  (text "Jill: Cooger managed to develop the serum, but he could never master it himself.")
  (wait)
  (text-reset 1)
  (text "Jill: That's what sets me apart. With this serum, every man, woman, and child on Earth will kneel before me!")
  (wait)
  (text-reset 1)
  (text "Steve: Bullshit! What you want is to unleash hell on Earth!")
  (wait)
  (text-reset 1)
  (text "Cole: Stealing other people's research... How can you even call yourself a scientist?")
  (wait)
  (text-reset 1)
  (text "Jill: Semantics, semantics. Nobody's getting in my way anymore.")
  (wait)
  (text-reset 1)
  (text
   "Jill: Just look at my skull... Two years ago, Ghoul was my test subject for the serum. But one day he betrayed me and I received damage that would be fatal.")
  (wait)
  (text-reset 1)
  (text "Jill: And then with the last of my strength, I injected myself with the reanimation serum and came back to life!")
  (wait)
  (text-reset 1)
  (text
   "Cole: So Ghoul was lying when he told me he ended you. Can't trust an android.")
  (wait)
  (text-reset 1)
  (text "Cole: But mark my words, you're dying by my hands, right now!")
  (wait)
  (text-reset 1)
  (text "Jill: Oh, such vigor, Cole! Then let the show begin. Your first opponent shall be a zombie revived by my newly completed serum.")
  (wait)
  (text-reset 1)
  (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
  (image-file "B:¥GPC¥DB193.GPC")
  (image-mem 0 3)
  (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
  (exec-mem 912 "C 0 2 23 40 238 1 2 23")
  (exec-mem 912 "C 0 40 23 18 238 1 40 23")
  (exec-mem 912 "A 1")
  (image-file "B:¥GPC¥DB195L.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 0 2 23 55 238")
  (image-file "B:¥GPC¥DB194L.GPC")
  (image-mem 0 3)
  (image-file "B:¥GPC¥DB194R.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 1 2 23 55 238")
  (image-file "B:¥GPC¥DB195R.GPC")
  (image-mem 1 3)
  (exec-mem 912 "GET 2 2 23 55 238")
  (exec-mem 912 "A 0,S 0")
  ((cmd 193) 0 "B:¥GPA¥DB193A.GPA")
  ((cmd 193) 1 "B:¥GPA¥DB194L.GPA")
  (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
  ((cmd 196) 0 0)
  ((cmd 196) 0 1)
  (delay 8 0)
  ((cmd 196) 0 2)
  (delay 8 0)
  ((cmd 196) 0 3)
  (delay 10 0)
  ((cmd 196) 0 4)
  (text "Cole: !?")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 0 2 23,W 0,O 0")
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_07.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_07.USO"))))
  (sound '|| 1)
  (text "Steve: Is that you...Catherine!?")
  (wait)
  (text-reset 1)
  (text "Catherine: Cole...Steve!")
  (wait)
  (text-reset 1)
  (text "Cole: Catherine! We thought you were dead!")
  (wait)
  (text-reset 1)
  (text "Catherine: Steve... Help me!")
  (wait)
  (text-reset 1)
  (exec-mem 912 "PUT 1 2 23,W 0,O 0")
  (text "Steve: Catherine, you're all right now...")
  (wait)
  (text-reset 1)
  (text "Cole: We thought... We all thought you were dead...")
  (wait)
  (text-reset 1)
  ((cmd 196) 1 0)
  ((cmd 196) 1 1)
  (delay 4 0)
  ((cmd 196) 1 2)
  (text "Jill: Heh heh heh...")
  (wait)
  (text-reset 1)
  ((cmd 193) 0 "B:¥GPA¥DB196RB.GPA")
  ((cmd 193) 1 "B:¥GPA¥DB196RBB.GPA")
  ((cmd 194) 0 "ｱ..ｲ..ｳ..ｱ..ｲ..ｳ..ｱ..ｲ..ｳ..")
  (text "Cole: Wait, Steve, don't--")
  (wait)
  (text-reset 1)
  (sound '|| 0)
  (if (</>
       (// (? (= 900 #f)) (sound '|| "A:¥USO_V¥BR2_05.USO"))
       (// (sound '|| "A:¥USO_D¥BR2_05.USO"))))
  (sound '|| 1)
  (exec-mem 912 "PUT 2 2 23,W 0,O 0")
  (exec-mem 912 "EXIT")
  ((cmd 197) 0 15)
  (text "Steve: Aaaaaaaaaaghhhhhh!")
  (wait)
  (text-reset 1)
  (text "Cole: CATHERINE!!!")
  (wait)
  (text-reset 1)
  ((cmd 197) 0 0)
  (image-file "A:¥GPC¥COUNTER.GPC")
  (image-mem 0 0)
  (load-mem "A:¥CLM¥DB195R.CLM" 32768)
  (exec-mem 3744 0 #"\353\237\353\240\353\241\353\242" 3 2 0)
  (exec-mem 3744 1 1 80 0 0 0)
  (exec-mem 3744 1 5 34 5 40 8)
  (exec-mem 15728 0 0 0 3 0 1)
  (exec-mem 15728 1 0 0 0 0 "Z")
  (exec-mem 15728 2 1)
  (exec-mem 15456 0)
  (exec-mem 14544 2 0)
  (exec-mem 15728 3)
  (exec-mem 3744 3 "P" 32768)
  (exec-mem 15728 4)
  (image-file "A:¥GPC¥DB_FRM3.GPC")
  (image-mem 0 0)
  (if (</>
       (//
        (? (= Z 2) (= P 5))
        ((cmd 196) 1 0)
        (sound '|se | 13)
        ((cmd 196) 1 1)
        (delay 4)
        ((cmd 196) 1 2)
        (delay 4)
        ((cmd 196) 1 3)
        (delay 8)
        ((cmd 196) 1 4)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (image-file "B:¥GPC¥DB197.GPC")
        (image-mem 0 3)
        (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
        (exec-mem 912 "A 1")
        (image-file "A:¥GPC¥DB_FRM.GPC")
        (image-mem 0 3)
        (image-file "B:¥GPC¥DB197B.GPC")
        (image-mem 0 3)
        (exec-mem 912 "A 0,S 0")
        (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
        (text "Cole: Catherine...")
        (wait)
        (text-reset 1)
        (text "Catherine: ...Cole...")
        (wait)
        (text-reset 1)
        (exec-mem 23216 2 23 79 238 11 0)
        (text "Jill: Heh heh heh...")
        (wait)
        (text-reset 1)
        (text "Cole: You...you...!!!")
        (wait)
        (text-reset 1)
        (text "Jill: My goodness, no hesitation whatsoever in gunning down a female ally when you assume she's a zombie...")
        (wait)
        (text-reset 1)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (image-file "B:¥GPC¥DB193.GPC")
        (image-mem 0 3)
        (image-file "B:¥GPC¥DB194L.GPC")
        (image-mem 1 3)
        (exec-mem 912 "INIT,A 0,S 0,O 0,D 1")
        (exec-mem 912 "C 0 2 23 40 238 1 2 23")
        (exec-mem 912 "C 0 40 23 18 238 1 40 23")
        (exec-mem 912 "A 1")
        (exec-mem 912 "GET 0 2 23 55 238")
        (image-file "B:¥GPC¥DB198R.GPC")
        (image-mem 1 3)
        (image-file "B:¥GPC¥DB198L.GPC")
        (image-mem 1 3)
        (exec-mem 912 "GET 1 2 23 55 238")
        (exec-mem 912 "A 0,S 0")
        ((cmd 193) 0 "B:¥GPA¥DB193B.GPA")
        (exec-mem 9920 1 6 32 113 32 6 6 113 64 8 50)
        (text "Cole: I'll never forgive you, you reptilian shit!")
        (wait)
        (text-reset 1)
        (text "Jill: I admire that spunk of yours, but maybe you should worry about your friend Steve's neck injury...?")
        (wait)
        (text-reset 1)
        (text "Cole: What!?")
        (wait)
        (text-reset 1)
        (text "Jill: Soon Steve will follow suit. You haven't forgotten the serum acts as a virus, have you?")
        (wait)
        (text-reset 1)
        (exec-mem 912 "PUT 0 2 23,W 0,O 0")
        (text "Steve: Let me ask you, Jill... My brother... What happened to Ghoul's corpse at Bayside?")
        (wait)
        (text-reset 1)
        (exec-mem 912 "PUT 1 2 23,W 0,O 0")
        (text
         "Jill: Oh, so Ghoul was your brother! That makes things interesting. I resuscitated your brother's remains at Bayside...")
        (wait)
        (text-reset 1)
        (text
         "Jill: The head had been obliterated, but the brain suffered no damage. I simply removed the brain and brought it back here...")
        (wait)
        (text-reset 1)
        (text "Jill: To see the younger brother come seeking his older brother... Today will be an extra special day for you, Steve.")
        (exec-mem 912 "PUT 0 2 23,W 0,O 0")
        (exec-mem 912 "EXIT")
        (wait)
        (text-reset 1)
        ((cmd 196) 0 0)
        ((cmd 196) 0 1)
        (delay 8 0)
        ((cmd 196) 0 2)
        (delay 8 0)
        ((cmd 196) 0 3)
        (delay 10 0)
        ((cmd 196) 0 4)
        (text "Cole: !?")
        (wait)
        (text-reset 1)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (mes-jump "A:¥MES¥110.MES"))
       (//
        (text "Catherine: GUAAAAAA!!!")
        (wait)
        (text-reset 1)
        (sound '|| 0)
        (sound '|se | 10)
        (exec-mem 9920 2 6 6 113 64 6 32 113 32 0 50)
        (text "　　　　　　　　　　ＧＡＭＥ　ＯＶＥＲ")
        (menu1 32 337 48 337 (</> (/ (str "CONTINUE")) (/ (str "GAME END"))))
        (text-reset 1)
        (branch-var
         S
         (</>
          (/ (exec-mem 9920 0 6 6 113 64 0) (mes-jump "A:¥MES¥109.MES"))
          (/
           (text "　　　　　ＮＩＧＨＴＭＡＲＥ　ＣＯＬＬＥＣＴＩＯＮ" 'br)
           (text "　　　　　　ＤＥＡＤ　ＯＦ　ＴＨＥ　ＢＲＡＩＮⅡ" 'br)
           (text "　　　　　　　　　　　ＧＡＭＥ　ＥＮＤ")
           (loop (wait)))))))))
 (seg*))